### ISSUE TITLE
如何基于SPU改造PSI协议或新增PSI协议并测试？

### ISSUE THREAD

**Issue by tarantula-leo** [secretflow/spu#104]
例如想在KKRT中提取出OPRF值并进行更改，或者在ECDH协议中使用自定义的椭圆曲线。

**Comment by tarantula-leo** [comment]
感谢回答，对于第一点，使用Secretflow时，没有办法修改其中的代码，调用的是lib.so的文件，通过什么方式能修改代码并测试，或者有相关的psi测试接口吗？

**Comment by zhanglei486** [comment]
你提到的lib.so文件，应该是"install SPU via the [official PyPI package]"，可以参考[INSTALLATION.md](https://github.com/secretflow/spu/blob/main/INSTALLATION.md)中的"install From Source",
<img width="482" alt="image" src="https://user-images.githubusercontent.com/47308800/221518785-c0ed7009-36ae-4d9e-a94e-a27f9c8f2540.png">

修改代码后执行"install From Source",可以更新spu的lib.so

**Comment by tarantula-leo** [comment]
谢谢解答 这样的方式应该可以完成secretflow的调用 但如果只是想进行测试和调试 测试完成后再进行动态库的重新生成 有没有什么比较简单的方式？

**Comment by zhanglei486** [comment]
可以试一下，下面的办法
bazel build //... -c opt
在bazel-bin/spu/目录里找到lib.so，手动替换spu 安装位置的lib.so

**Comment by zhanglei486** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/47308800/222324370-f91d328b-ab38-43e8-8b59-5f8e65e53a10.png">
需要手动安装一下go

**Comment by tarantula-leo** [comment]
好的 想问下如果将yacl和以下几个依赖的代码下载 再基于例如kkrt_psi.cc和kkrt_psi.h文件写kkrt运行的代码 可以进行测试/改造吗？不太清楚其中是否会有更多的依赖要进行安装 服务器环境不太适合使用bazel
#include "absl/strings/escaping.h"
#include "openssl/crypto.h"
#include "openssl/rand.h"
#include "spdlog/spdlog.h"
#include "yacl/crypto/base/hash/hash_utils.h"
#include "yacl/crypto/primitives/ot/base_ot.h"
#include "yacl/crypto/primitives/ot/iknp_ote.h"
#include "yacl/crypto/primitives/ot/kkrt_ote.h"
#include "yacl/crypto/utils/rand.h"

**Comment by zhanglei486** [comment]
需要细看一下相关的依赖，可以先搞一版试一下编译，缺什么逐渐补充完善

**Comment by tarantula-leo** [comment]
谢谢解答

**Comment by pchyuan** [comment]
@tarantula-leo 你好，想问下可否加下隐语微信号SecretFlow01，想跟您详细深入沟通下细节
