### ISSUE TITLE
Owner of input data in P2A

### ISSUE THREAD

**Issue by DuanYuFi** [secretflow/spu#105]
Hi, In the P2A::proc of arithmetic.cc, how do I know the owner of the input for some index? Or it has assumed all the inputs are from party0? If this is the case, then I think it isn't also support for joint input?

**Comment by DuanYuFi** [comment]
According to the P2A in aby3, it seems to assume that all the inputs are from party 0.

**Comment by rivertalk** [comment]
Hi @DuanYuFi , thanks for the question

`P2A` is a kernel which convert `Public` to `Arithmetic Share`. The `P` is short for `Public` (not `Private`), it's known for all parties. So in this case, the data does not have a "owner".

PS: Currently, SPU assumes all data are either Public or Secret, we are planning to support Private semantic in the future.

**Comment by DuanYuFi** [comment]
Oops, that's make sense. Thanks for your help. :)

Best wishes
