### ISSUE TITLE
Error in compiling "psi_demo" file

### ISSUE THREAD

**Issue by magic-hya** [secretflow/spu#109]
I want to use the underlying SDK of psi and pir. At present, the compilation environment is installed in the official image. 
When compiling and executing "psi_demo", an error is reported and there is no clue.

The specific implementation process is as follows:

```
cd spu
bazel build //libspu/psi/demo:psi_demo
```

Error reporting segment：
![image](https://user-images.githubusercontent.com/85269941/222669909-dc7a2694-29a1-46ca-a292-c53fd43911b7.png)

**Comment by 6fj** [comment]
Could you please clarify the docker image and version?

**Comment by magic-hya** [comment]
secretflow/secretflow-anolis8:0.7.18b3

There is no compilation environment in this image. I have installed some related programs.

**Comment by anakinxc** [comment]
pls use secretflow/spu-ci:latest

Thx

**Comment by magic-hya** [comment]
Okay, I'll try.

Thx
