### ISSUE TITLE
Question about SPU Runtime Configuration

### ISSUE THREAD

**Issue by Sparks1Fly** [secretflow/spu#115]
Hi,
Can SPU write the time data of HLO and HAL to temp files ?  Like 'enable_processor_dump' option in SPU Runtime Configuration.

**Comment by tpppppub** [comment]
Hi @sduYGG , currently there is no such an option. If you want to write HLO/HAL info into files, you can redirect stdout to temp files.

**Comment by Sparks1Fly** [comment]
> Hi @sduYGG , currently there is no such an option. If you want to write HLO/HAL info into files, you can redirect stdout to temp files. Or you can save SPU log to files like this [example](https://github.com/secretflow/spu/blob/main/examples/python/psi/simple_psi.py#L58).

Thanks
