### ISSUE TITLE
咨询一下关于spu开启tls功能

### ISSUE THREAD

**Issue by xiaoran33** [secretflow/spu#130]
咨询一下官方的老师们，关于spu开启tls功能，有没有具体的配置示例呢？

**Comment by oeqqwq** [comment]
你好，请问是准备怎么使用spu呢，是准备直接源码集成么？

**Comment by xiaoran33** [comment]
> 你好，请问是准备怎么使用spu呢，是准备直接源码集成么？

源码集成的tls是怎么使用的呢？或者有更简单的使用方式吗？比如直接配置tls什么的

**Comment by oeqqwq** [comment]
> > > > 你好，请问是准备怎么使用spu呢，是准备直接源码集成么？
> > > 
> > > 
> > > 源码集成的tls是怎么使用的呢？或者有更简单的使用方式吗？比如直接配置tls什么的
> > 
> > 
> > 可以在创建spu的数据传输通道link时指定tls相关配置，创建link的代码可以参考：https://github.com/secretflow/spu/blob/main/examples/cpp/utils.cc#L36 link的tls相关配置可以查看： https://github.com/secretflow/yacl/blob/main/yacl/link/context.h#L92
> 
> 有点不理解，是把bool enable_ssl = false;改为true就ok了吗？证书和tls协议的版本在哪指定呢？

L92-L100都是tls相关的配置，`SSLOptions`中包含了证书等内容的指定：https://github.com/secretflow/yacl/blob/main/yacl/link/ssl_options.h

tls协议默认使用`tlsv1`, `tlsv1.1`, `tlsv1.2`，暂未开放配置
