### ISSUE TITLE
spu编译出错

### ISSUE THREAD

**Issue by hacker-jerry** [secretflow/spu#132]
在 docker 中运行bazel build //examples/cpp/pir -c opt
只有这两个文件报了 404，其他的都能下载

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/0aaa6e679847a4eeb407136e7b0bcef93ec652e6.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: Skipping '//examples/cpp/pir': no such target '//examples/cpp/pir:pir': target 'pir' not declared in package 'examples/cpp/pir' defined by /home/admin/dev/examples/cpp/pir/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//examples/cpp/pir:pir': target 'pir' not declared in package 'examples/cpp/pir' defined by /home/admin/dev/examples/cpp/pir/BUILD.bazel
INFO: Elapsed time: 218.512s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

然后就报warning了
请问如何处理？

**Comment by anakinxc** [comment]
试一下 `bazel build //examples/cpp/pir/... -c opt`

**Comment by hacker-jerry** [comment]
谢谢，运行之后产生了如下报错，似乎是版本不对？

WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository com_github_eigenteam_eigen instantiated at:
  /home/admin/dev/WORKSPACE:19:9: in <toplevel>
  /home/admin/dev/bazel/repositories.bzl:39:32: in spu_deps
  /home/admin/dev/bazel/repositories.bzl:290:10: in _com_github_eigenteam_eigen
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
WARNING: Download from https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 0c8c490764f9c2a793133491adca0cd073b73e0bde965c68cbe58d91b5ed4261 but wanted 8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72
ERROR: An error occurred during the fetch of repository 'com_github_eigenteam_eigen':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz] to /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/com_github_eigenteam_eigen/temp16545009323531812858/eigen-3.4.0.tar.gz: Checksum was 0c8c490764f9c2a793133491adca0cd073b73e0bde965c68cbe58d91b5ed4261 but wanted 8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72
ERROR: /home/admin/dev/WORKSPACE:19:9: fetching http_archive rule //external:com_github_eigenteam_eigen: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz] to /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/com_github_eigenteam_eigen/temp16545009323531812858/eigen-3.4.0.tar.gz: Checksum was 0c8c490764f9c2a793133491adca0cd073b73e0bde965c68cbe58d91b5ed4261 but wanted 8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72
INFO: Repository com_github_intel_ipp instantiated at:
  /home/admin/dev/WORKSPACE:28:10: in <toplevel>
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/yacl/bazel/repositories.bzl:32:26: in yacl_deps
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/yacl/bazel/repositories.bzl:254:10: in _com_github_intel_ipp
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
INFO: Repository com_github_gflags_gflags instantiated at:
  /home/admin/dev/WORKSPACE:28:10: in <toplevel>
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/yacl/bazel/repositories.bzl:16:30: in yacl_deps
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/yacl/bazel/repositories.bzl:68:10: in _com_github_gflags_gflags
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
INFO: Repository com_github_emptoolkit_emp_tool instantiated at:
  /home/admin/dev/WORKSPACE:28:10: in <toplevel>
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/yacl/bazel/repositories.bzl:34:36: in yacl_deps
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/yacl/bazel/repositories.bzl:296:10: in _com_github_emptoolkit_emp_tool
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
ERROR: /home/admin/dev/libspu/mpc/utils/BUILD.bazel:101:15: //libspu/mpc/utils:linalg depends on @com_github_eigenteam_eigen//:eigen3 in repository @com_github_eigenteam_eigen which failed to fetch. no such package '@com_github_eigenteam_eigen//': java.io.IOException: Error downloading [https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz] to /root/.cache/bazel/_bazel_root/eceb46742416a02f6a0f8d92bc74468c/external/com_github_eigenteam_eigen/temp16545009323531812858/eigen-3.4.0.tar.gz: Checksum was 0c8c490764f9c2a793133491adca0cd073b73e0bde965c68cbe58d91b5ed4261 but wanted 8586084f71f9bde545ee7fa6d00288b264a2b7ac3607b974e54d13e7162c1c72
ERROR: Analysis of target '//examples/cpp/pir:keyword_pir_server' failed; build aborted: 
INFO: Elapsed time: 11.056s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 1109 targets configured)
    currently loading: @org_interconnection//interconnection/link
    Fetching https://github.com/gflags/gflags/archive/v2.2.2.tar.gz
请问该如何解决呢？

**Comment by anakinxc** [comment]
```
Error in download_and_extract: java.io.IOException: Error downloading [https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz] to
```
看起来是网络的问题

**Comment by hacker-jerry** [comment]
谢谢，更换网络就可以了
