### ISSUE TITLE
static_argnames in spu

### ISSUE THREAD

**Issue by MrCapricornLiu** [secretflow/spu#147]
### Issue Type

Feature Request

### Source

binary

### Secretflow Version

latex

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
What is the use of static_argnames in SPU?
```

### Reproduction code to reproduce the issue.

```shell
...
```

**Comment by anakinxc** [comment]
Hi @MrCapricornLiu 

Please check [static_argnames in Jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html)

Best

**Comment by MrCapricornLiu** [comment]
thx.
