### ISSUE TITLE
Weird jax operations in spu

### ISSUE THREAD

**Issue by MrCapricornLiu** [secretflow/spu#148]
### Issue Type

Bug

### Source

binary

### Secretflow Version

latex

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
When running jax code in spu, the jax jit requires array boolean indices must be concrete, so I tried two methods, both failed. And I can't understand the error of method2.
```

### Reproduction code to reproduce the issue.

```shell
*****method1*****
for j in range(n_clusters):
    centroids = centroids.at[j].set(X[labels == j].mean(axis=0))

*****method2*****(The jax official documents says using where() func instead of boolean mask can avoid NonConcreteBooleanIndexError)
centroids = jnp.array([jnp.mean(X[jnp.where(labels == j)], axis=0) for j in range(n_clusters)])

*****error of method1*****
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.NonConcreteBooleanIndexError: Array boolean indices must be concrete; got ShapedArray(bool[100])

*****error of method2*****(I think this error is very weird)
The size argument of jnp.nonzero must be statically specified to use jnp.nonzero within JAX transformations.
```

**Comment by MrCapricornLiu** [comment]
But it can run correctly in plaintext, only fails in spu. I think the reason is jax-jit. Jax document says use where() can avoid the NonConcreteBooleanIndexError.

**Comment by anakinxc** [comment]
> But it can run correctly in plaintext, only fails in spu. I think the reason is jax-jit. Jax document says use where() can avoid the NonConcreteBooleanIndexError.

Can you run the same Jax code without SPU?

**Comment by MrCapricornLiu** [comment]
Sorry, what do you mean?

**Comment by anakinxc** [comment]
All the error messages you provided are all from JAX, which happens before entering into SPU. So can you make sure the Jax code is actually runable with just JAX?

**Comment by MrCapricornLiu** [comment]
Yes, if I run the code without spu, there is no bug.

**Comment by anakinxc** [comment]
> Yes, if I run the code without spu, there is no bug.

Can you provide the code?

Thanks

**Comment by anakinxc** [comment]
Or a tiny repro code snippet

**Comment by MrCapricornLiu** [comment]
```
import numpy as np
import jax.numpy as jnp
import pandas as pd
import secretflow as sf
from sklearn.datasets import load_iris
import tempfile
import os
from secretflow.data.vertical import read_csv as v_read_csv


def load_data():
    sf.shutdown()
    sf.init(['alice', 'bob', 'carol'], address='local')
    alice, bob, carol = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('carol')
    spu = sf.SPU(sf.utils.testing.cluster_def(['alice', 'bob', 'carol']))

    iris = load_iris(as_frame=True)
    df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
    temp_dir = tempfile.mkdtemp()
    v_alice, v_bob, v_carol = df.iloc[:100,
                                      :2], df.iloc[:100, 2:3], df.iloc[:100, 3:]
    v_alice_path = os.path.join(temp_dir, 'v_alice.csv')
    v_bob_path = os.path.join(temp_dir, 'v_bob.csv')
    v_carol_path = os.path.join(temp_dir, 'v_carol.csv')
    v_alice.to_csv(v_alice_path, index=False)
    v_bob.to_csv(v_bob_path, index=False)
    v_carol.to_csv(v_carol_path, index=False)

    vdf = v_read_csv(
        {alice: v_alice_path, bob: v_bob_path, carol: v_carol_path})
    x = vdf.values
    return spu, x


def _concatenate(arrays, axis: int) -> np.ndarray:
    return jnp.concatenate(arrays, axis=axis)


def fit(X: np.ndarray) -> np.ndarray:
    labels = jnp.zeros(X.shape[0])
    centroids = jnp.array(
        [jnp.mean(X[jnp.where(labels == j)], axis=0) for j in range(3)])
    return centroids

def test(mode: str) -> None:
    if mode == 'plaintext':
        iris = load_iris(as_frame=True)
        df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
        x = df.values
        fit(x)

    elif mode == 'spu':
        spu, x = load_data()
        spu_x = spu(_concatenate, static_argnames=('axis'))(
            [x.partitions[pyu].to(spu) for pyu in x.partitions], axis=1
        )
        spu(fit)(spu_x)


if __name__ == '__main__':
    test()  # Choose the mode
```

**Comment by anakinxc** [comment]
Hi @MrCapricornLiu 

Simplified the code a little bit, you have to make sure `jax.jit` succeeded before running on SPU.

```python
import numpy as np
import jax
import jax.numpy as jnp
import pandas as pd
from sklearn.datasets import load_iris


@jax.jit
def fit(X: np.ndarray) -> np.ndarray:
    labels = jnp.zeros(X.shape[0])
    centroids = jnp.array(
        [jnp.mean(X[jnp.where(labels == j)], axis=0) for j in range(3)])
    return centroids

def test() -> None:
    iris = load_iris(as_frame=True)
    df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
    x = df.values
    fit(x)



if __name__ == '__main__':
    test()  

```

**Comment by MrCapricornLiu** [comment]
The error of calculating the mean has been solved, but I have tried a lot of methods for the error of the 'if' judgment statement and I can’t solve it. The code and error message are as follows.
```
import numpy as np
import jax
import jax.numpy as jnp
from jax import random
import pandas as pd
import secretflow as sf
from sklearn.datasets import load_iris
import tempfile
import os
from secretflow.data.vertical import read_csv as v_read_csv
from jax.tree_util import tree_flatten, tree_unflatten


@jax.jit
def fit(X: np.ndarray) -> np.ndarray:
    n_clusters = 5
    tol = 1e-4
    max_iter = 10
    indice = random.choice(random.PRNGKey(
        0), X.shape[0], shape=(n_clusters,), replace=False)
    centroids = jnp.take(X, indice, axis=0)

    labels = jnp.zeros(X.shape[0])

    for i in range(max_iter):
        old_centroids = centroids.copy()

        centroids = jnp.array(
            [(jnp.sum(X * (labels == j)[:, jnp.newaxis], axis=0) - jnp.sum(X * (labels != j)[:, jnp.newaxis], axis=0)) / jnp.sum(labels == j)
             for j in range(n_clusters)])

        # This is the line that causes the error
        if jnp.all(jnp.less(jnp.max(jnp.abs(centroids - old_centroids)), tol)):
            break

    return centroids


def test() -> None:
    iris = load_iris(as_frame=True)
    df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
    x = df.values
    fit(x)


if __name__ == '__main__':
    test()
```

```
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[])>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function. 
The error occurred while tracing the function fit at forissue.py:14 for jit. This concrete value was not available in Python because it depends on the value of the argument 'X'.
```

**Comment by anakinxc** [comment]
Hi @MrCapricornLiu 

Loop in Jax jit is a really complicated story. In short, do not use Python's for/while, use jax.lax.fori_loop/jax.lax.while_loop instead.

You can use this [kmeans](https://github.com/secretflow/spu/blob/main/examples/python/ml/jax_kmeans/jax_kmeans.py) as a reference example.

Thanks

**Comment by MrCapricornLiu** [comment]
Sorry, the problem is not about the for loop, it's about the 'if' condition judgement. There is still bug even without the for loop.

**Comment by anakinxc** [comment]
> Sorry, the problem is not about the for loop, it's about the 'if' condition judgement. There is still bug even without the for loop.

The `if` statement serves as a loop termination condition here, so it's still a loop thingy.

In jitted Jax, normal Python loop needs to have a compile-time fixed length, which basically means `break` in loop body is not doable.

To achieve something similar to what you need, [jax.lax.while_loop](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.while_loop.html) with a proper `cond_fun` is what I can imagine.

**Comment by MrCapricornLiu** [comment]
But before submitting this issue, I attempted to run the `if` code without the `for` loop, it still failed. After reading your comments, I also tried using the `fori_loop`, it also failed.

**Comment by MrCapricornLiu** [comment]
I think you misunderstood me. Before I submitted this issue, I tried to use only `if` operation without a `for` loop (of course, the code after `if` is not a `break`), and the fact shows that the error is because of this `if` operation, which has nothing to do with the `for` loop.  I think the main problem is the conditional judgment code `jnp.all(jnp.less(jnp.max(jnp.abs(centroids - old_centroids)), tol))` after `if`.

**Comment by anakinxc** [comment]
> I think you misunderstood me. Before I submitted this issue, I tried to use only `if` operation without a `for` loop (of course, the code after `if` is not a `break`), and the fact shows that the error is because of this `if` operation, which has nothing to do with the `for` loop. I think the main problem is the conditional judgment code `jnp.all(jnp.less(jnp.max(jnp.abs(centroids - old_centroids)), tol))` after `if`.

The condition has it's own issue. I wrote a tiny snippet to show how to use it like a `if` condition

```python
import jax
import jax.numpy as jnp

@jax.jit
def fun(in1, in2, tol):
    return jnp.select(
        [jnp.all(jnp.less(jnp.max(jnp.abs(in1 - in2)), tol))],
        [1],
        2,
    )


print(fun(jnp.array([1, 2, 3]), jnp.array([0, 3, 1]), 10))
```
