### ISSUE TITLE
Some questions about the implementation of ABY3 and it's Truncation protocol

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/spu#150]
Hi, 
I'm reading the implementation code of ABY3 and meet some problems.
The implementation of [TruncA](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/mpc/aby3/arithmetic.cc#L623) follows the protocol introduced by ABY3, that is:
![image](https://user-images.githubusercontent.com/38127120/231638835-4e171993-95ba-45eb-b910-5b57c0bdd5b2.png)
But what I am confused about is that the right shift operation(as well as division) on the ring element  isn't homomorphic, which means (x1'+x2'+x3')/2^d may not equal to (x1'+x2')/2^d+(x3'/2^d).
I'm curious about how the SPU Team solved this problem?
Thanks~

**Comment by llCurious** [comment]
Hey @BeStrongok , this is a good question.

The problem you mentioned is discussed in the ABY3 paper already. To be specific, the truncation in ABY3, i.e. TruncA here may incur two error: 1) the 1-bit error in the MSB and 2) the 1-bit error in the LSB. 

The 1-bit MSB error happens with probability that is discussed in ABY3 paper. This shall cause significant error. Therefore we have another implementation [TruncAPr](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/mpc/aby3/arithmetic.cc#L688) to fix this problem.

We note that TruncAPr (known as probabilistic truncation) fixs (1) and does not consider (2). That said,  (x1'+x2'+x3')/2^d = (x1'+x2')/2^d+(x3'/2^d) +- 1. This error is actually negligible.

**Comment by BeStrongok** [comment]
> Hey @BeStrongok , this is a good question.
> 
> The problem you mentioned is discussed in the ABY3 paper already. To be specific, the truncation in ABY3, i.e. TruncA here may incur two error: 1) the 1-bit error in the MSB and 2) the 1-bit error in the LSB.
> 
> The 1-bit MSB error happens with probability that is discussed in ABY3 paper. This shall cause significant error. Therefore we have another implementation [TruncAPr](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/mpc/aby3/arithmetic.cc#L688) to fix this problem.
> 
> We note that TruncAPr (known as probabilistic truncation) fixs (1) and does not consider (2). That said, (x1'+x2'+x3')/2^d = (x1'+x2')/2^d+(x3'/2^d) +- 1. This error is actually negligible.

Thanks for your quickly reply. 
I'm curious about the arithmetic operations of `ring2k_t`, does it contains modulo operation?
That is, when `x1'+x2'+x3'` exceeds modulus, the result of `(x1'+x2'+x3)/2^d` is completely different with the result of `x1'+x2')/2^d+(x3'/2^d)`.

**Comment by llCurious** [comment]
> Thanks for your quickly reply. I'm curious about the arithmetic operations of `ring2k_t`, does it contains modulo operation? 

Yes. We do modulo 2^k implicitly.

> That is, when `x1'+x2'+x3'` exceeds modulus, the result of `(x1'+x2'+x3)/2^d` is completely different with the result of `x1'+x2')/2^d+(x3'/2^d)`.

You are right. This is the root cause of the 1-bit MSB error i mentioned above. To be specific, if the wrap happens, `(x1'+x2'+x3)/2^d` = `(x1'+x2')/2^d+(x3'/2^d) - 2^{k-d}`

**Comment by BeStrongok** [comment]
Thanks, the reason i mentioned this protocol is that [TruncAPr](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/mpc/aby3/arithmetic.cc#L688) needs 3 rounds which is relatively high in high latency circumstance, so i'm trying to explore a better way and meet some problem, what you told me is very helpful. :)
> Yes. We do modulo 2^k implicitly.
Could you point out the detailed implementation of `ring2k_t`? 
> You are right. This is the root cause of the 1-bit MSB error i mentioned above. To be specific, if the wrap happens, (x1'+x2'+x3)/2^d = (x1'+x2')/2^d+(x3'/2^d) - 2^{k-d}
Has `- 2^{k-d}` been already implemented in the SPU?

**Comment by llCurious** [comment]
> Could you point out the detailed implementation of `ring2k_t`?

You can refer to `type_utils.h`. [code](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/core/type_util.h) is here. It dynamically casts data type like uint32 or uint64.

> Has `- 2^{k-d}` been already implemented in the SPU?

Currently, we support TruncAPr which calculates this part (refer to [code](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/mpc/aby3/arithmetic.cc#L808)). It indeed incurs 3 rounds and you can find the original [paper](https://arxiv.org/pdf/1910.12435.pdf) for detailed description.

**Comment by BeStrongok** [comment]
> > Could you point out the detailed implementation of `ring2k_t`?
> 
> You can refer to `type_utils.h`. [code](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/core/type_util.h) is here. It dynamically casts data type like uint32 or uint64.
> 
> > Has `- 2^{k-d}` been already implemented in the SPU?
> 
> Currently, we support TruncAPr which calculates this part (refer to [code](https://github.com/secretflow/spu/blob/2b29087f6900086cf0eb1456959596c47abb6b47/libspu/mpc/aby3/arithmetic.cc#L808)). It indeed incurs 3 rounds and you can find the original [paper](https://arxiv.org/pdf/1910.12435.pdf) for detailed description.

Thanks, your reply is very helpful. I have solved my problem. 
In 3PC circumstance, do you think a more efficient truncation protocol compared to `TruncAPr` can be implemented?

**Comment by llCurious** [comment]
Yep. This is a open question indeed. If you have any idea, feel free to open a PR request :).

**Comment by BeStrongok** [comment]
> Yep. This is a open question indeed. If you have any idea, feel free to open a PR request :).

Thanks, an initial idea may works but needs more tests.  That is, a mixed truncation protocol may be useful, instead of a specific protocol.
I will see if it can help to improve the truncation performance of ABY3.
