### ISSUE TITLE
请问PIR例子中的oprf_key.bin是如何生成的？

### ISSUE THREAD

**Issue by mingo0117** [secretflow/spu#156]
### Issue Type

Documentation Bug

### Modules Involved

PIR

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

lastest

### Current Behavior?

想咨询下https://www.secretflow.org.cn/docs/spu/en/development/pir.html
中提到的oprf_key.bin是如何生成的？文档并未说明

### Standalone code to reproduce the issue

```Python
如题
```

**Comment by Chrisdehe** [comment]
hi，mingo0117！
很抱歉晚回复
测试的话可以使用dd if=/dev/urandom of=oprf_key.bin bs=32 count=1 来生成
实际的话需要设计安全生成方案

**Comment by mingo0117** [comment]
明白了，谢谢
