### ISSUE TITLE
[bazel bug] mac编译spu报错

### ISSUE THREAD

**Issue by mingo0117** [secretflow/spu#159]
```
### Issue Type

Build/Install

### Modules Involved

SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

latest

### OS Platform and Distribution

macOS 13.0

### Python Version

_No response_

### Compiler Version

_No response_

### Current Behavior?

# macOS >= 11, Xcode >=13.0

# Install Xcode
https://apps.apple.com/us/app/xcode/id497799835?mt=12

# Select Xcode toolchain version
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

# Install homebrew
https://brew.sh/

# Install dependencies
# Be aware, brew may install a newer version of bazel, when that happens bazel will give an error message during build.
# Please follow instructions in the error message to install the required version
brew install bazel cmake ninja libomp go

# For Intel mac only
brew install nasm

# Install python dependencies
pip install -r requirements.txt
pip install -r requirements-dev.txt

```

基于文档以上步骤操作后，执行bazel build //... -c opt报错：
`ERROR: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/local_config_python/BUILD:78:8: in outs attribute of genrule rule @local_config_python//:python_include: Genrules without outputs don't make sense
ERROR: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/local_config_python/BUILD:78:8: Analysis of target '@local_config_python//:python_include' failed
ERROR: Analysis of target '//spu/utils:distributed' failed; build aborted: 
INFO: Elapsed time: 0.398s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//src/tools/launcher
    Fetching @llvm_terminfo; Restarting.
`

求教，感谢

### Standalone code to reproduce the issue

```Python
如题
```

**Comment by anakinxc** [comment]
Hi @mingo0117 

麻烦提供一下 `bazel info` 的输出

**Comment by mingo0117** [comment]
> bazel info

`DEBUG: Rule 'yacl' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1680751531 +0800"
DEBUG: Repository yacl instantiated at:
  /Users/shuming/PycharmProjects/spu/WORKSPACE:19:9: in <toplevel>
  /Users/shuming/PycharmProjects/spu/bazel/repositories.bzl:45:10: in spu_deps
  /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'tf_runtime' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'llvm-raw' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_grpc_grpc' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'upb' because it already exists.
bazel-bin: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/execroot/spulib/bazel-out/darwin-fastbuild/bin
bazel-genfiles: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/execroot/spulib/bazel-out/darwin-fastbuild/bin
bazel-testlogs: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/execroot/spulib/bazel-out/darwin-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/command.log
committed-heap-size: 342MB
execution_root: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/execroot/spulib
gc-count: 35
gc-time: 658ms
install_base: /var/tmp/_bazel_shuming/install/47f1c25bb3cb1d9b4a99f26940323be5
java-home: /private/var/tmp/_bazel_shuming/install/47f1c25bb3cb1d9b4a99f26940323be5/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.6+10-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.6+10-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 4294MB
output_base: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6
output_path: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/execroot/spulib/bazel-out
package_path: %workspace%
release: release 5.4.0
repository_cache: /var/tmp/_bazel_shuming/cache/repos/v1
server_log: /private/var/tmp/_bazel_shuming/0087c1e03728cd0349dafefac9b798f6/java.log.shumingdemacbook-pro.shuming.log.java.20230418-092037.54952
server_pid: 54952
used-heap-size: 175MB
workspace: /Users/shuming/PycharmProjects/spu
`

**Comment by anakinxc** [comment]
看起来是 python 有点问题

麻烦提供一下 python 的版本，还有 `which python` 的输出

**Comment by mingo0117** [comment]
Python 3.8.2 (default, Dec 21 2020, 15:06:04)

**Comment by mingo0117** [comment]
> 看起来是 python 有点问题
> 
> 麻烦提供一下 python 的版本，还有 `which python` 的输出

<img width="478" alt="image" src="https://user-images.githubusercontent.com/29568891/232656208-31c3fd5f-61d1-4fea-a31f-10b8850d9f20.png">

**Comment by anakinxc** [comment]
> > 看起来是 python 有点问题
> > 麻烦提供一下 python 的版本，还有 `which python` 的输出
> 
> <img alt="image" width="478" src="https://user-images.githubusercontent.com/29568891/232656208-31c3fd5f-61d1-4fea-a31f-10b8850d9f20.png">

看起来这个 venv 里面的 python 缺了 dev headers
如果可以的话，可以试试用 miniconda 来管理 venv，比较靠谱 :D

**Comment by mingo0117** [comment]
> > > 看起来是 python 有点问题
> > > 麻烦提供一下 python 的版本，还有 `which python` 的输出
> > 
> > 
> > <img alt="image" width="478" src="https://user-images.githubusercontent.com/29568891/232656208-31c3fd5f-61d1-4fea-a31f-10b8850d9f20.png">
> 
> 看起来这个 venv 里面的 python 缺了 dev headers 如果可以的话，可以试试用 miniconda 来管理 venv，比较靠谱 :D

换了miniconda
<img width="510" alt="image" src="https://user-images.githubusercontent.com/29568891/232976397-8d71330a-d2d5-4d23-844b-e5c4e8f4d89c.png">

现在遇到另一个报错。重装了xcode也不行：
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/29568891/232976324-77ac56c6-293b-4721-ad8b-6d659cd55028.png">

**Comment by anakinxc** [comment]
> > > > 看起来是 python 有点问题
> > > > 麻烦提供一下 python 的版本，还有 `which python` 的输出
> > > 
> > > 
> > > <img alt="image" width="478" src="https://user-images.githubusercontent.com/29568891/232656208-31c3fd5f-61d1-4fea-a31f-10b8850d9f20.png">
> > 
> > 
> > 看起来这个 venv 里面的 python 缺了 dev headers 如果可以的话，可以试试用 miniconda 来管理 venv，比较靠谱 :D
> 
> 换了miniconda <img alt="image" width="510" src="https://user-images.githubusercontent.com/29568891/232976397-8d71330a-d2d5-4d23-844b-e5c4e8f4d89c.png">
> 
> 现在遇到另一个报错。重装了xcode也不行： <img alt="image" width="1334" src="https://user-images.githubusercontent.com/29568891/232976324-77ac56c6-293b-4721-ad8b-6d659cd55028.png">

是装的 xcode 14.3 吗

**Comment by mingo0117** [comment]
> > > > > 看起来是 python 有点问题
> > > > > 麻烦提供一下 python 的版本，还有 `which python` 的输出
> > > > 
> > > > 
> > > > <img alt="image" width="478" src="https://user-images.githubusercontent.com/29568891/232656208-31c3fd5f-61d1-4fea-a31f-10b8850d9f20.png">
> > > 
> > > 
> > > 看起来这个 venv 里面的 python 缺了 dev headers 如果可以的话，可以试试用 miniconda 来管理 venv，比较靠谱 :D
> > 
> > 
> > 换了miniconda <img alt="image" width="510" src="https://user-images.githubusercontent.com/29568891/232976397-8d71330a-d2d5-4d23-844b-e5c4e8f4d89c.png">
> > 现在遇到另一个报错。重装了xcode也不行： <img alt="image" width="1334" src="https://user-images.githubusercontent.com/29568891/232976324-77ac56c6-293b-4721-ad8b-6d659cd55028.png">
> 
> 是装的 xcode 14.3 吗

是的，app store下的最新版

**Comment by anakinxc** [comment]
> > > > > > 看起来是 python 有点问题
> > > > > > 麻烦提供一下 python 的版本，还有 `which python` 的输出
> > > > > 
> > > > > 
> > > > > <img alt="image" width="478" src="https://user-images.githubusercontent.com/29568891/232656208-31c3fd5f-61d1-4fea-a31f-10b8850d9f20.png">
> > > > 
> > > > 
> > > > 看起来这个 venv 里面的 python 缺了 dev headers 如果可以的话，可以试试用 miniconda 来管理 venv，比较靠谱 :D
> > > 
> > > 
> > > 换了miniconda <img alt="image" width="510" src="https://user-images.githubusercontent.com/29568891/232976397-8d71330a-d2d5-4d23-844b-e5c4e8f4d89c.png">
> > > 现在遇到另一个报错。重装了xcode也不行： <img alt="image" width="1334" src="https://user-images.githubusercontent.com/29568891/232976324-77ac56c6-293b-4721-ad8b-6d659cd55028.png">
> > 
> > 
> > 是装的 xcode 14.3 吗
> 
> 是的，app store下的最新版

这是一个 bazel 的 [known issue](https://github.com/bazelbuild/bazel/issues/17974)

有两个解决方式：

1. 退回 14.2 之类的低版本
2. 先用 5.4.1rc2

等 bazel 5.4.1 正式发布了我们会及时升级的
