### ISSUE TITLE
bazel build from docker error

### ISSUE THREAD

**Issue by AdijeShen** [secretflow/spu#161]
### Issue Type

Bug

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

36f25ba

### OS Platform and Distribution

windows

### Python Version

3.8

### Compiler Version

gcc 11.2

### Current Behavior?

when using docker from windows to install spu.
I run
```
docker run -d -it --name spu-gcc11-anolis-dev-$env:UserName `
     --mount type=bind,source="$(Get-Location)",target=/home/admin/dev/ `
     -w /home/admin/dev `
     --cap-add=SYS_PTRACE --security-opt seccomp=unconfined `
     --cap-add=NET_ADMIN `
     --privileged=true `
     secretflow/spu-ci:latest
```
and
```
docker exec -it -(name_of_container) bash
bazel build //... -c dbg
```

and the output is:
![image](https://user-images.githubusercontent.com/16702475/232710396-3491aae1-ff89-462d-bd46-c0c0bacd2df5.png)

the bazel version from docker image is 5.4.0

(fix): this error doesn't exist if i delete the `.bazelversion` file.

### Standalone code to reproduce the issue

```Python
![image](https://user-images.githubusercontent.com/16702475/232710396-3491aae1-ff89-462d-bd46-c0c0bacd2df5.png)
```

**Comment by anakinxc** [comment]
Hi @AdijeShen 

Can you check image sha256 of secretflow/spu-ci:latest?

**Comment by AdijeShen** [comment]
> Hi @AdijeShen
> 
> Can you check image sha256 of secretflow/spu-ci:latest?

It's `72101c026b93b2abaec890365ffea891a7d95cac4f3c31eaee062a3a03958801` and from 3 weeks ago

**Comment by anakinxc** [comment]
Hi @AdijeShen 

Just noticed you were directly calling `/usr/local/lib/bazel/bin/bazel`.

Is there any reason to do this?

**Comment by AdijeShen** [comment]
Hi @anakinxc 
just type `bazel` results the same.
I use `/usr/local/lib/bazel/bin/bazel` because the error message says "it wasn't found in `/usr/local/lib/bazel/bin`"

**Comment by 6fj** [comment]
so what's the output of 

```
 bazel --version
```
in your case?

**Comment by AdijeShen** [comment]
> so what's the output of
> 
> ```
>  bazel --version
> ```
> 
> in your case?

5.4.0

**Comment by anakinxc** [comment]
Hi @AdijeShen 

Can you provide a full repro step? 
Just tried with the docker image you specified, everything works as expected.

Thanks

**Comment by AdijeShen** [comment]
````
# enter an empty dir
mkdir C:\workspace\test
cd C:\workspace\test

# clone the spu repo
git clone https://github.com/secretflow/spu --depth=1
cd spu

# run the docker
docker run -d -it --name spu-gcc11-anolis-dev-$env:UserName-1 `
     --mount type=bind,source="$(Get-Location)",target=/home/admin/dev/ `
     -w /home/admin/dev `
     --cap-add=SYS_PTRACE --security-opt seccomp=unconfined `
     --cap-add=NET_ADMIN `
     --privileged=true `
     secretflow/spu-ci:latest

docker exec -it  spu-gcc11-anolis-dev-$env:UserName-1 bash

# just type bazel / enter to see the error msg
```
![image](https://user-images.githubusercontent.com/16702475/233028504-ca1d93bc-894c-45ca-ba08-e44699bf0609.png)

I must specify that I only test it with docker desktop in windows, are your test environment is windows?

**Comment by AdijeShen** [comment]
```
# enter an empty dir
mkdir C:\workspace\test
cd C:\workspace\test

# clone the spu repo
git clone https://github.com/secretflow/spu --depth=1
cd spu

# run the docker
docker run -d -it --name spu-gcc11-anolis-dev-$env:UserName-1 `
     --mount type=bind,source="$(Get-Location)",target=/home/admin/dev/ `
     -w /home/admin/dev `
     --cap-add=SYS_PTRACE --security-opt seccomp=unconfined `
     --cap-add=NET_ADMIN `
     --privileged=true `
     secretflow/spu-ci:latest

docker exec -it  spu-gcc11-anolis-dev-$env:UserName-1 bash

# just type bazel / enter to see the error msg
```
![image](https://user-images.githubusercontent.com/16702475/233028504-ca1d93bc-894c-45ca-ba08-e44699bf0609.png)

I must specify that I only test it with docker desktop in windows, are your test environment is windows?

**Comment by Chrisdehe** [comment]
辛苦贴下你的gcc跟cmake版本

**Comment by anakinxc** [comment]
Hi @AdijeShen 

This issue is caused by git converted LF to CRLF on Windows.

There are two solutions here:
1. do `git config --global core.autocrlf false` and clone spu again
2. run `sed $'s/\r$//' .bazelversion > .bazelversion` to convert .bazelversion back to LR

Thanks
