### ISSUE TITLE
运行bazel build //examples/cpp/pir/... -c opt命令报错

### ISSUE THREAD

**Issue by meisir5648** [secretflow/spu#163]
### Issue Type

Build/Install

### Modules Involved

PIR

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

0.3.2b12

### OS Platform and Distribution

centos7

### Python Version

3.8.0

### Compiler Version

gcc 11.2.1

### Current Behavior?

A error happened!

### Standalone code to reproduce the issue

```Python
print("ERROR: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/com_github_fmtlib_fmt/BUILD.bazel:24:20: Foreign Cc - CMake: Building fmtlib failed: (Exit 1): bash failed: error executing command /bin/bash -c bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh")
```

### Relevant log output

```Shell
FAILED: Build did NOT complete successfully
```

**Comment by 6fj** [comment]
hi @meisir5648 

请提供一下完整的log，感谢

**Comment by meisir5648** [comment]
> hi @meisir5648
> 
> 请提供一下完整的log，感谢

![image](https://user-images.githubusercontent.com/128010163/232951097-9cfa934c-e6f0-4fd9-a8f2-d9e14204474a.png)
![image](https://user-images.githubusercontent.com/128010163/232951161-32a165ba-557b-4beb-bfba-1e389a89893c.png)

**Comment by 6fj** [comment]
hi @meisir5648 

我们需要**完整的**log，并且可以用纯文本吗？

**Comment by meisir5648** [comment]
> hi @meisir5648
> 
> 我们需要**完整的**log，并且可以用纯文本吗？

DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'tf_runtime' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'llvm-raw' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_grpc_grpc' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'upb' because it already exists.
INFO: Analyzed 4 targets (1 packages loaded, 271 targets configured).
INFO: Found 4 targets...
ERROR: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/external/com_github_fmtlib_fmt/BUILD.bazel:24:20: Foreign Cc - CMake: Building fmtlib failed: (Exit 1): bash failed: error executing command /bin/bash -c bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library fmtlib

Environment:______________
TMPDIR=/tmp
LD_LIBRARY_PATH=/opt/rh/devtoolset-11/root/usr/lib64:/opt/rh/devtoolset-11/root/usr/lib:/opt/rh/devtoolset-11/root/usr/lib64/dyninst:/opt/rh/devtoolset-11/root/usr/lib/dyninst
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh
EXT_BUILD_ROOT=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib
INSTALLDIR=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib
PATH=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib:/opt/rh/devtoolset-11/root/usr/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/root/bin
BUILD_TMPDIR=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir
PWD=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib
EXT_BUILD_DEPS=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.ext_build_deps
SHLVL=3
BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/CMake.log
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh
_=/usr/bin/env
__________________________
+ cmake -DFMT_TEST=OFF -DCMAKE_TOOLCHAIN_FILE=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib -DCMAKE_PREFIX_PATH=/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/external/com_github_fmtlib_fmt
-- CMake version: 3.18.3
-- The CXX compiler identification is GNU 4.8.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/gcc
-- Check for working CXX compiler: /usr/bin/gcc - broken
CMake Error at /usr/local/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir/CMakeFiles/CMakeTmp
    
    Run Build Command(s):ninja cmTC_71fb0 && [1/2] Building CXX object CMakeFiles/cmTC_71fb0.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_71fb0.dir/testCXXCompiler.cxx.o 
    /usr/bin/gcc   -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -std=c++0x -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fdiagnostics-color=always -Wl,-z,noexecstack -fopenmp -fPIC -fstack-protector-strong -std=c++17 -o CMakeFiles/cmTC_71fb0.dir/testCXXCompiler.cxx.o -c testCXXCompiler.cxx
    gcc: error: unrecognized command line option '-std=c++17'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:66 (project)


-- Configuring incomplete, errors occurred!
See also "/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir/CMakeFiles/CMakeOutput.log".
See also "/root/.cache/bazel/_bazel_root/22360f5f82e166e664d88a3450363a29/sandbox/processwrapper-sandbox/5/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir/CMakeFiles/CMakeError.log".
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/CMake.log

INFO: Elapsed time: 6.050s, Critical Path: 2.21s
INFO: 4 processes: 3 internal, 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

是这样吗？

**Comment by 6fj** [comment]
Hi @meisir5648 

在你的log中
```
The CXX compiler identification is GNU 4.8.5
```

但是我们需要gcc 11.2才能编译。

**Comment by meisir5648** [comment]
> Hi @meisir5648
> 
> 在你的log中
> 
> ```
> The CXX compiler identification is GNU 4.8.5
> ```
> 
> 但是我们需要gcc 11.2才能编译。

[root@localhost bazel-bin]# gcc --version
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

很奇怪，我的gcc明明是11.2.1版本的。我刚刚又试着跑了一遍。log中打印的还是4.8.5版本。

**Comment by anakinxc** [comment]
> > Hi @meisir5648
> > 在你的log中
> > ```
> > The CXX compiler identification is GNU 4.8.5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是我们需要gcc 11.2才能编译。
> 
> [root@localhost bazel-bin]# gcc --version gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9) Copyright (C) 2021 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> 很奇怪，我的gcc明明是11.2.1版本的。我刚刚又试着跑了一遍。log中打印的还是4.8.5版本。

`bazel clean --expunge` 然后再跑一下看看
