### ISSUE TITLE
非法指令(吐核)

### ISSUE THREAD

**Issue by meisir5648** [secretflow/spu#167]
### Issue Type

Build/Install

### Modules Involved

PIR

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

0.3.2b12

### OS Platform and Distribution

centos7

### Python Version

3.8.0

### Compiler Version

gcc 11.2.1

### Current Behavior?

在执行PIR的service端setup的时候报了非法指令。这是因为我的机器CPU不支持这个指令集吗？
![image](https://user-images.githubusercontent.com/128010163/233020364-5db9d7ae-6dd1-4ade-80ac-4c224a6db4c3.png)

### Standalone code to reproduce the issue

```Python
print("A bug")
```

### Relevant log output

```Shell
[root@localhost spu]# python examples/python/pir/pir_setup.py --in_path B_PIR_DATA.csv --key_columns id --label_columns register_date,age --count_per_query 1 -max_label_length 18 --oprf_key_path oprf_key.bin --setup_path setup_path
非法指令(吐核)
[root@localhost spu]# cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
      1  12th Gen Intel(R) Core(TM) i7-12700
```

**Comment by Chrisdehe** [comment]
Hi，@meisir5648 
辛苦贴一下dmesg 输出。

**Comment by 6fj** [comment]
Hi @meisir5648 

1. 你是在docker里面执行的吗？
2. 按照 https://www.secretflow.org.cn/docs/spu/en/development/pir.html ，

```
bash build_wheel_entrypoint.sh
```

可以正确执行吗？

**Comment by meisir5648** [comment]
> 

Building wheels for collected packages: intervaltree, colored-traceback
  Building wheel for intervaltree (pyproject.toml) ... done
  Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26099 sha256=9fdde8722a456ae5504edf8f8f295cd66a6fcbe1109c1a996c47d2221a3b7c06
  Stored in directory: /root/.cache/pip/wheels/45/23/de/5789a92962483fd33cb06674792b9697c1b3766d7c7742830e
  Building wheel for colored-traceback (pyproject.toml) ... done
  Created wheel for colored-traceback: filename=colored_traceback-0.3.0-py3-none-any.whl size=4608 sha256=297f86adcd1a5a79b68b3ef948a117b0c89249b3b6527f3655583404287a2f8f
  Stored in directory: /root/.cache/pip/wheels/a3/d0/c4/da4834cc2d6426db3a675341a8f2eb1a60c21da050513e04e1
Successfully built intervaltree colored-traceback
Installing collected packages: unicorn, sortedcontainers, pyserial, pyelftools, urllib3, six, pysocks, pygments, pycparser, psutil, plumbum, packaging, MarkupSafe, intervaltree, idna, charset-normalizer, certifi, capstone, bcrypt, rpyc, ropgadget, requests, python-dateutil, mako, colored-traceback, cffi, pynacl, cryptography, paramiko, pwntools
Successfully installed MarkupSafe-2.1.2 bcrypt-4.0.1 capstone-5.0.0rc2 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.1.0 colored-traceback-0.3.0 cryptography-40.0.2 idna-3.4 intervaltree-3.1.0 mako-1.2.4 packaging-23.1 paramiko-3.1.0 plumbum-1.8.1 psutil-5.9.5 pwntools-4.9.0 pycparser-2.21 pyelftools-0.29 pygments-2.15.1 pynacl-1.5.0 pyserial-3.5 pysocks-1.7.1 python-dateutil-2.8.2 requests-2.28.2 ropgadget-7.3 rpyc-5.3.1 six-1.16.0 sortedcontainers-2.4.0 unicorn-2.0.1.post1 urllib3-1.26.15
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Check binary dependencies...
ldd: bazel-bin/spu/libspu.so: 没有那个文件或目录

**Comment by 6fj** [comment]
@meisir5648 

需要执行一下：

```
bazel build //examples/cpp/pir/... -c opt
```

**Comment by meisir5648** [comment]
> Hi，@meisir5648 辛苦贴一下dmesg 输出。
这个指令没用过，麻烦告知一下具体输入什么指令

**Comment by anakinxc** [comment]
apsi 用了 avx512f

![image](https://user-images.githubusercontent.com/103552181/233106653-eda693fb-7af1-451d-b442-653898b53226.png)

我们检查一下
