### ISSUE TITLE
分享一个把rpc标准设置成h2:grpc的时候遇到的问题： “remote_window_left is not enough”

### ISSUE THREAD

**Issue by chinchilla-forest** [secretflow/spu#175]
### Issue Type

Others

### Modules Involved

SPU runtime, PIR

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

master

### Current Behavior?

声明：这不是一个bug。只是我不知道如何分享日常遇到解决的问题，就先写在这里。

因为我们内部需要，需要把协议设置成grpc
`std::shared_ptr<yacl::link::Context> MakeLink() {
  yacl::link::ContextDesc lctx_desc;
  lctx_desc.brpc_channel_protocol = "h2:grpc";`
结果跑src/example/cpp/pir 的时候遇到下面问题
“send key=root:P2P-4:1->06 (chunked 1 out of 3) rpc failed: 2004, message=[E2004]remote_window_left is not enough, data_size=262235”
但是我使用跑spu默认的代码是没有问题的。我发现区别就是spu使用了baidu_std的协议，我使用了"h2:grpc"的协议，
我把协议改成默认baidu_std的协议之后就没问题了。

那使用grpc协议的错误原因是什么呢？我看到brpc的也有人遇到同样的问题https://github.com/apache/brpc/issues/715；
猜测grpc协议下面单个数据包大小应该是有限制的。
限制的值应该是在brpc/src/policy/http2_rpc_protocol.cpp 文件下面：

`DEFINE_int32(h2_client_stream_window_size, 256 * 1024,
             "Initial window size for stream-level flow control");`
下面代码限制了最大的大小为256*1024，
而yacl下单个包大小的限制应该是yacl::link::ContextDesc::http_max_payload_size,默认为1024*1024.
我把这个值改成了256*1024,还是会遇到问题，应该这个大小只是作用于数据payload的大小，没有计算protobuffer的头大小。
把这个值改成小于256*1024 之后就没问题了，比如我改成了200*1024.

结论：如果想使用“h2:grpc”协议，需要把yacl::link::ContextDesc::http_max_payload_size值改成小于256*1024.
`
std::shared_ptr<yacl::link::Context> MakeLink() {
  yacl::link::ContextDesc lctx_desc;
  lctx_desc.brpc_channel_protocol = "h2:grpc";
  lctx_desc.http_max_payload_size = 200*1024;`

### Standalone code to reproduce the issue

```Python
not a bug
```

### Relevant log output

```Shell
send key=root:P2P-4:1->06 (chunked 1 out of 3) rpc failed: 2004, message=[E2004]remote_window_left is not enough, data_size=262235 [R1][E2004]remote_window_left is not enough, data_size=262235 [R2][E2004]remote_window_left is not enough, data_size=262235 [R3][E2004]remote_window_left is not enough, data_size=262235
```

**Comment by warriorpaw** [comment]
非常感谢提供的建议，我们在后续版本中加上相应的处理，避免触发这个错误。

**Comment by fengsp** [comment]
It seems the yacl MR fix is missing on the lastet yacl master branch, so this issue is back, could anyone fix this again?
