### ISSUE TITLE
pip install spu之后import spu报错

### ISSUE THREAD

**Issue by mingo0117** [secretflow/spu#183]
### Issue Type

Bug

### Modules Involved

Documentation/Tutorial/Example

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

lastest

### Current Behavior?

pip install spu之后，
import报错如下：
![image](https://user-images.githubusercontent.com/29568891/235048970-57c1a3dc-d5f6-445e-8560-2bf0e07911cf.png)

### Standalone code to reproduce the issue

```Python
同上
```

**Comment by 6fj** [comment]
Hi @mingo0117 

由于PYTHONPATH的原因， 请不要在spu的folder下import spu，你可以换一个working dir，感谢。

**Comment by mingo0117** [comment]
ok
