### ISSUE TITLE
在具备GPU加速的Jax开发环境，基于MPC的LR不能使用GPU进行加速

### ISSUE THREAD

**Issue by Mingbo-Lee** [secretflow/spu#188]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b1 

### OS Platform and Distribution

Ubuntu 20.04 LTS

### Python version

3.8.10

### What happend and What you expected to happen.

```shell
本次issue反馈以 https://github.com/secretflow/secretflow/blob/main/docs/tutorial/lr_with_spu.ipynb 代码为例，相关运行截图以comment的形式提供，总的结论：在具备GPU加速的jax开发环境上，基于MPC的实现的LR并不能使用GPU进行加速。
```

### Reproduction code to reproduce the issue.

```shell
https://github.com/secretflow/secretflow/blob/main/docs/tutorial/lr_with_spu.ipynb
```

**Comment by Mingbo-Lee** [comment]
好的！非常感谢您的回复！ @anakinxc

**Comment by Mingbo-Lee** [comment]
Hi @anakinxc ,现在是关闭这个issue，还是让它开着？

**Comment by anakinxc** [comment]
> Hi @anakinxc ,现在是关闭这个issue，还是让它开着？

先留着吧

**Comment by anakinxc** [comment]
#371 added some foundation works for GPU acceleration.
