### ISSUE TITLE
SPU如何处理域上的负数

### ISSUE THREAD

**Issue by DuanYuFi** [secretflow/spu#190]
### Issue Type

Support

### Modules Involved

MPC protocol, SPU runtime, SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

8100491d9b9ecfdbccca8abb8b94e4e3f3ed33f0

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.9.13

### Compiler Version

11.3.0

### Current Behavior?

SPU中对于一个负数，假设是-1，那么在FM64上其实就是2^64-1。但是我现在是在域上（F_p with p = 2^61 - 1）计算，那么-1对应的数据应该是2^61-2。这种负数的转化是可以customize的吗，还是这本身就是编译器层面的转化？

### Standalone code to reproduce the issue

```Python
input=-0.7140116
```

### Relevant log output

```Shell
output=18446744073709364443=2^64+int(input * 2 ** 18)
```

**Comment by anakinxc** [comment]
Compiler 不感知数据是怎么 encode 的

这部分听起来应该是[encoding](https://github.com/secretflow/spu/blob/8100491d9b9ecfdbccca8abb8b94e4e3f3ed33f0/libspu/core/encoding.cc#L52)的处理的内容

听起来我觉得你需要一个新的 encoding method

**Comment by DuanYuFi** [comment]
了解了，感谢。
