### ISSUE TITLE
PSI 

### ISSUE THREAD

**Issue by rodinluo** [secretflow/spu#196]
### Issue Type

Bug

### Modules Involved

PSI

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

 secretflow v0.8.2b1

### OS Platform and Distribution

Ubuntu 20.04.6

### Python Version

3.8

### Compiler Version

GCC 9.4.0

### Current Behavior?

参照隐语公众号，做两方PSI，https://mp.weixin.qq.com/s?__biz=MzA5NTQ0MTI4OA==&mid=2456927592&idx=1&sn=298df759fb096df3b01dcf45174baf46&chksm=873a458fb04dcc99cbc5d5ac0ae861906d9ca95c67b8782458730c0fe3c806d202cad179e21d&cur_album_id=2497813164193972227&scene=189#wechat_redirect。
执行时出现如下错误。

配置如下，
```
cluster_def = {
'nodes': [
# <<< !!! >>> replace <192.168.0.1:12945> to alice node's local ip & free port
        {'party': 'alice', 'id': 'local:0', 'address': '10.11.0.112:7112', 'listen_address': '0.0.0.0:7112'},
# <<< !!! >>> replace <192.168.0.2:12946> to bob node's local ip & free port
        {'party': 'bob', 'id': 'local:1', 'address': '10.11.0.112:7130', 'listen_address': '0.0.0.0:7130'},
# <<< !!! >>> if you need 3pc test, please add node here, for example, add carol as rank 2
# {'party': 'carol', 'id': 'local:2', 'address': '127.0.0.1:12347'},
    ],
'runtime_config': {
'protocol': spu.spu_pb2.SEMI2K,
'field': spu.spu_pb2.FM128,
    },
}
```

### Standalone code to reproduce the issue

```Python
iicit@iicithg:~/sf-benchmark$ python test_psi.py
2023-05-12 01:38:21,218 INFO worker.py:1432 -- Connecting to existing Ray cluster at address: 10.11.0.112:9394...
2023-05-12 01:38:21,232 INFO worker.py:1625 -- Connected to Ray cluster.
(SPURuntime pid=1482) <MemoryView of 'Buffer' object>
(SPURuntime pid=1482) 2023-05-12 01:38:23.297 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=10.11.0.130:12946} (0x0x4b1a800): Connection refused [R1][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R2][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R3][E112]Not connected to 10.11.0.130:12946 yet, server_id=0
(SPURuntime pid=1482) 2023-05-12 01:38:24.298 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R1][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R2][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R3][E112]Not connected to 10.11.0.130:12946 yet, server_id=0
(SPURuntime pid=1482) 2023-05-12 01:38:25.299 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R1][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R2][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R3][E112]Not connected to 10.11.0.130:12946 yet, server_id=0
(TemporaryActor pid=1399, ip=10.11.0.130) 2023-05-12 01:38:25,493       ERROR serialization.py:387 -- Invalid serialized data!
(TemporaryActor pid=1399, ip=10.11.0.130) Traceback (most recent call last):
(TemporaryActor pid=1399, ip=10.11.0.130)   File "/home/iicit/.local/lib/python3.8/site-packages/ray/_private/serialization.py", line 385, in deserialize_objects
(TemporaryActor pid=1399, ip=10.11.0.130)     obj = self._deserialize_object(data, metadata, object_ref)
(TemporaryActor pid=1399, ip=10.11.0.130)   File "/home/iicit/.local/lib/python3.8/site-packages/ray/_private/serialization.py", line 268, in _deserialize_object
(TemporaryActor pid=1399, ip=10.11.0.130)     return self._deserialize_msgpack_data(data, metadata_fields)
(TemporaryActor pid=1399, ip=10.11.0.130)   File "/home/iicit/.local/lib/python3.8/site-packages/ray/_private/serialization.py", line 223, in _deserialize_msgpack_data
(TemporaryActor pid=1399, ip=10.11.0.130)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(TemporaryActor pid=1399, ip=10.11.0.130)   File "/home/iicit/.local/lib/python3.8/site-packages/ray/_private/serialization.py", line 213, in _deserialize_pickle5_data
(TemporaryActor pid=1399, ip=10.11.0.130)     obj = pickle.loads(in_band)
(TemporaryActor pid=1399, ip=10.11.0.130) RuntimeError: Invalid serialized data!
(TemporaryActor pid=1399, ip=10.11.0.130) 2023-05-12 01:38:25,496       ERROR worker.py:844 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=1399, ip=10.11.0.130, repr=<secretflow.device.device.spu.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7f38c5847370>)
(TemporaryActor pid=1399, ip=10.11.0.130)   At least one of the input arguments for this task could not be computed:
(TemporaryActor pid=1399, ip=10.11.0.130) ray.exceptions.RaySystemError: System error: Invalid serialized data!
(TemporaryActor pid=1399, ip=10.11.0.130) traceback: Traceback (most recent call last):
(TemporaryActor pid=1399, ip=10.11.0.130) RuntimeError: Invalid serialized data!
Traceback (most recent call last):
  File "test_psi.py", line 83, in <module>
    app.run(main)
  File "/home/iicit/.local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/iicit/.local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "test_psi.py", line 66, in main
    reports = spu.psi_csv(
  File "/home/iicit/.local/lib/python3.8/site-packages/secretflow/device/device/spu.py", line 1614, in psi_csv
    return dispatch(
  File "/home/iicit/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 111, in dispatch
    return _registrar.dispatch(self.device_type, name, self, *args, **kwargs)
  File "/home/iicit/.local/lib/python3.8/site-packages/secretflow/device/device/register.py", line 80, in dispatch
    return self._ops[device_type][name](*args, **kwargs)
  File "/home/iicit/.local/lib/python3.8/site-packages/secretflow/device/kernels/spu.py", line 300, in psi_csv
    return sfd.get(res)
  File "/home/iicit/.local/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 75, in get
    return ray.get(object_refs)
  File "/home/iicit/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/iicit/.local/lib/python3.8/site-packages/ray/_private/worker.py", line 2523, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::SPURuntime.__init__() (pid=1399, ip=10.11.0.130, repr=<secretflow.device.device.spu.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7f38c5847370>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: Invalid serialized data!
traceback: Traceback (most recent call last):
RuntimeError: Invalid serialized data!
```

**Comment by Chrisdehe** [comment]
@rodinluo ，您好，微信公众号发布的时效较长，请参考官网最新版的[psi benchmark](https://www.secretflow.org.cn/docs/secretflow/zh_CN/developer/benchmark/psi_benchmark.html)

**Comment by rodinluo** [comment]
配置IP已经修改如下，
# SPU settings
cluster_def = {
'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': '10.11.0.112:12945', 'listen_address': '0.0.0.0:12945'},
        {'party': 'bob', 'id': 'local:1', 'address': '10.11.0.130:12946', 'listen_address': '0.0.0.0:12946'},
    ],
'runtime_config': {
'protocol': spu.spu_pb2.SEMI2K,
'field': spu.spu_pb2.FM128,
    },
}

**Comment by rodinluo** [comment]
> @rodinluo ，您好，微信公众号发布的时效较长，请参考官网最新版的[psi benchmark](https://www.secretflow.org.cn/docs/secretflow/zh_CN/developer/benchmark/psi_benchmark.html)

比较了一下，变化不大。

**Comment by Chrisdehe** [comment]
SPU没链接上，请检查下SPU的IP及端口是否正确并未被占用

**Comment by rodinluo** [comment]
帮忙分析一下，查看ray状态应该是没问题的。
2023-05-12 03:26:24,826 INFO worker.py:1432 -- Connecting to existing Ray cluster at address: 10.11.0.112:9394...
2023-05-12 03:26:24,840 INFO worker.py:1625 -- Connected to Ray cluster.

**Comment by Chrisdehe** [comment]
好的 辛苦将Ray节点启动及执行代码完整的贴一下

**Comment by rodinluo** [comment]
节点1：
 ray status
======== Autoscaler status: 2023-05-12 03:42:09.960904 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_2f0cb498aa140483ea28d8ac69a8c571bd34cd7ae494850c54f74d28
 1 node_e9f99dad55b7d6bdd74de4f27541b9991c56347941e3f8654a7aeaf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/15.0 CPU
 0.0/8.0 alice
 0.0/8.0 bob
 0B/11.29GiB memory
 0B/5.07GiB object_store_memory

Demands:
 (no resource demands)
节点2：
root$ ray status
======== Autoscaler status: 2023-05-12 03:42:50.050497 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_2f0cb498aa140483ea28d8ac69a8c571bd34cd7ae494850c54f74d28
 1 node_e9f99dad55b7d6bdd74de4f27541b9991c56347941e3f8654a7aeaf9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/15.0 CPU
 0.0/8.0 alice
 0.0/8.0 bob
 0B/11.29GiB memory
 0B/5.07GiB object_store_memory

Demands:
 (no resource demands)

**Comment by rodinluo** [comment]
节点1：执行命令
RAY_DISABLE_REMOTE_CODE=true \
ray start --head --node-ip-address="10.11.0.112" --port="9394" --resources='{"alice": 8}' --include-dashboard=False
节点2：执行命令
RAY_DISABLE_REMOTE_CODE=true \
ray start --address="10.11.0.112:9394" --resources='{"bob": 8}'

**Comment by Chrisdehe** [comment]
我复现是没有问题的，辛苦贴下全部（test_psi.py）的执行代码

**Comment by rodinluo** [comment]
# SPU settings
cluster_def = {
'nodes': [
        {'party': 'alice', 'id': 'local:0', 'address': '10.11.0.112:12945', 'listen_address': '0.0.0.0:12945'},
        {'party': 'bob', 'id': 'local:1', 'address': '10.11.0.130:12946', 'listen_address': '0.0.0.0:12946'},
    ],
'runtime_config': {
'protocol': spu.spu_pb2.SEMI2K,
'field': spu.spu_pb2.FM128,
    },
}


def main(_):

    sf.init(parties=['alice', 'bob'], address='10.11.0.112:9394')

    alice = sf.PYU('alice')
    bob = sf.PYU('bob')

    input_path = {
        alice: '/home/iicit/sf-benchmark/psi_1.csv',
        bob: '/home/iicit/sf-benchmark/psi_2.csv',
    }
    output_path = {
        alice: '/home/iicit/sf-benchmark/psi_output.csv',
        bob: '/home/iicit/sf-benchmark/psi_output.csv',
    }
    select_keys = {
        alice: ['id'],
        bob: ['id'],
    }
    spu = sf.SPU(cluster_def)
# prepare data
    start = time.time()


    reports = spu.psi_csv(
        key=select_keys,
        input_path=input_path,
        output_path=output_path,
        receiver='alice',  # if `broadcast_result=False`, only receiver can get output file.
        protocol='KKRT_PSI_2PC',  # psi protocol
        precheck_input=False,  # will cost ext time if set True
        sort=False,  # will cost ext time if set True
        broadcast_result=False,  # will cost ext time if set True
    )
    print(f"psi reports: {reports}")
    logging.info(f"cost time: {time.time() - start}")

    sf.shutdown()


if __name__ == '__main__':
    app.run(main)

**Comment by rodinluo** [comment]
(SPURuntime pid=3277) 2023-05-12 05:25:01.367 [error] [context.cc:operator():132] connect to rank=1 failed with error [external/yacl/yacl/link/transport/channel_brpc.cc:368] send, rpc failed=112, message=[E111]Fail to connect Socket{id=0 addr=10.11.0.130:12946} (0x0x37eb580): Connection refused [R1][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R2][E112]Not connected to 10.11.0.130:12946 yet, server_id=0 [R3][E112]Not connected to 10.11.0.130:12946 yet, server_id=0


对ray的这个机制不太了解，
通过命令，远端bob跟alice之间建立tcp连接，10.11.0.112:9394,这个连接正常。
但是远端bob 10.11.0.130:12946基于这个端口的服务没有起来，所以出现这个问题。

**Comment by Chrisdehe** [comment]
互相telnet spu端口 看下是否能够telnet到
systemctl status firewalld 两边看看
如果主机本身没有问题，那可能就是主机所在的网络或者更底层的宿主机有问题（假如主机是虚拟机的话）

**Comment by rodinluo** [comment]
telnet 10.11.0.130:12946 肯定不通，就是服务没有起来啊。
另外，两边的防火墙没有起。

**Comment by rodinluo** [comment]
通过ray status,可以看到对端状态，可以判断10.11.0.112:9394,这个连接正常。
链接10.11.0.130:12946，链接拒绝。说明之前创建sf.SPU(cluster_def)时，没有创建起来，但也没有任何提示。

**Comment by 6fj** [comment]
@rodinluo 

看上去你是用集群仿真模式启动sf：https://www.secretflow.org.cn/docs/secretflow/zh_CN/getting_started/deployment.html#cluster-mode-for-simulation

能按照上述的文档放一下你全部的setup步骤吗？

**Comment by rodinluo** [comment]
就是两台设备alice（10.11.0.112）--bob（10.11.0.130），做PSI
1）分别在两台设备起ray，建议集群。
alice：
RAY_DISABLE_REMOTE_CODE=true \
ray start --head --node-ip-address="10.11.0.112" --port="9394" --resources='{"alice": 8}' --include-dashboard=False
bob：
ray start --address="10.11.0.112:9394" --resources='{"bob": 8}'
2）alice设备执行脚本，跑PSI。
脚本如上。

**Comment by 6fj** [comment]
sf.init(parties=['alice', 'bob'], address='10.11.0.112:9394') 这句没有问题，是需要提供parties的
