### ISSUE TITLE
spu进行函数计算，小数精度丢失异常

### ISSUE THREAD

**Issue by hy928302776** [secretflow/spu#201]
### Issue Type

Bug

### Source

binary

### Secretflow Version

0.8.2b2

### OS Platform and Distribution

Centos7 4c32g

### Python version

3.8.13

### What happend and What you expected to happen.

```shell
import json
import random
import re
import sys
import time

import secretflow as sf
import numpy as np
import pandas as pd
from dvadmin.dev_centre.sflib.item.init_data import init

def getFunAndElements(formulas: list):
    """
    将公式转为函数返回
    """
    map: dict = {}
    if formulas and len(formulas) > 0:
        for formula in formulas:
            formulaArray: list = formula.split("=")
            elements = re.findall(r'[a-zA-Z]+(?:_+[a-zA-Z]+)?\d*', formulaArray[1])
            map.update({formulaArray[0]: {"func": eval(f"(lambda {','.join(elements)}:{formulaArray[1]})"),
                                          "elements": elements}})
    return map


initdata = {
    "deviceList": [
        {
            "node_alias": "alice",
            "ip": "127.0.0.1",
            "port": "10003"
        },
        {
            "node_alias": "bob",
            "ip": "127.0.0.1",
            "port": "10004"
        }
    ],
    "address": "local",
    "selfDevice": {
        "node_alias": "alice",
        "ip": "127.0.0.1",
        "port": "10003"
    },
    "projectId": 000,
    "flowId": "flowId"
}
print(f"初始化数据：{initdata}")
spu, pyuMap, selfPyu = init(initdata)
for item in range(1, 2):
    # aa = [str(np.round(random.random()*100,2)) for i in range(1, 4)]
    # bb = [str(np.round(random.random()*100,2)) for i in range(1, 4)]
    aa=['199999.99','199999.99']
    bb=['0.00','100.01']
    df = pd.DataFrame({'A': aa, 'B': bb})
    print(f"df:{df}")
    #df.eval('C=A+B',inplace=True)
    funAndElement = getFunAndElements(['C=A+B','D=A-B'])
    funcC = funAndElement['C']["func"]
    funcD = funAndElement['D']["func"]
    data ={'A':pd.to_numeric(df['A']),'B':pd.to_numeric(df['B'])}
    spuObjC =spu(funcC)(**data)
    spuObjD =spu(funcD)(**data)

    item_result_C = sf.reveal(spuObjC).astype(str)
    item_result_D = sf.reveal(spuObjD).astype(str)

    print(f"item_result_C:{item_result_C}")
    print(f"item_result_D:{item_result_D}")
```

### Reproduction code to reproduce the issue.

```shell
df:           A       B
0  199999.99    0.00
1  199999.99  100.01

返回结果：
item_result_C:['199999.98' '200100.0']
item_result_D:['199999.98' '199899.97']

公式为：
C=A+B；  199999.99+0.00 却等于199999.98；
D=A-B， 199999.99-0.00 却等于199999.98； 199999.99-100.01却等于199899.97
```

**Comment by anakinxc** [comment]
> DEFAULT_SEMI2K_RUNTIME_CONFIG = { 'protocol': spu.spu_pb2.SEMI2K, 'field': spu.spu_pb2.FM128, 'fxp_fraction_bits': 30, } 我们的是两方计算，使用的这个协议配置，测试了下，还是不行，修改了fxp_fraction_bits的值也不行。计算： 199999.97 - 100.01 结果返回还是 199899.95

我仔细研究了一下现在大概是这样的的，用 FM64 举个例子：

199999.97 encode 到 fxp 是 52428791808
100.01 encode 到 fxp 是 26217022

52428791808 - 26217022 = 52402574786

result = 52402574786/(2^18)

这个数值在 f32 的时候是 199899.953125，所以结果出来会是 .95
如果用 f64, 这个值会是 199899.95874786376953

我们会在后续更新里尝试支持 f64 来解决这个精度问题

**Comment by hy928302776** [comment]
这个f64啥时间更新上去呢，我们着急使用发自我的 iPhone在 2023年5月18日，18:05，anakinxc ***@***.***> 写道：﻿

DEFAULT_SEMI2K_RUNTIME_CONFIG = { 'protocol': spu.spu_pb2.SEMI2K, 'field': spu.spu_pb2.FM128, 'fxp_fraction_bits': 30, } 我们的是两方计算，使用的这个协议配置，测试了下，还是不行，修改了fxp_fraction_bits的值也不行。计算： 199999.97 - 100.01 结果返回还是 199899.95

我仔细研究了一下现在大概是这样的的，用 FM64 举个例子：
199999.97 encode 到 fxp 是 52428791808
100.01 encode 到 fxp 是 26217022
52428791808 - 26217022 = 52402574786
result = 52402574786/(2^18)
这个数值在 f32 的时候是 199899.953125，所以结果出来会是 .95
如果用 f64, 这个值会是 199899.95874786376953
我们会在后续更新里尝试支持 f64 来解决这个精度问题

**Comment by anakinxc** [comment]
> 这个f64啥时间更新上去呢，我们着急使用发自我的 iPhone在 2023年5月18日，18:05，anakinxc ***@***.***> 写道：﻿ DEFAULT_SEMI2K_RUNTIME_CONFIG = { 'protocol': spu.spu_pb2.SEMI2K, 'field': spu.spu_pb2.FM128, 'fxp_fraction_bits': 30, } 我们的是两方计算，使用的这个协议配置，测试了下，还是不行，修改了fxp_fraction_bits的值也不行。计算： 199999.97 - 100.01 结果返回还是 199899.95 我仔细研究了一下现在大概是这样的的，用 FM64 举个例子： 199999.97 encode 到 fxp 是 52428791808 100.01 encode 到 fxp 是 26217022 52428791808 - 26217022 = 52402574786 result = 52402574786/(2^18) 这个数值在 f32 的时候是 199899.953125，所以结果出来会是 .95 如果用 f64, 这个值会是 199899.95874786376953 我们会在后续更新里尝试支持 f64 来解决这个精度问题 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

这个我们会尽快更新的
