### ISSUE TITLE
SPU项目编译错误

### ISSUE THREAD

**Issue by DuanYuFi** [secretflow/spu#204]
### Issue Type

Support

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

7dcab95a83c9940b05e09dee846bb07aeff5ab94

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.10.9

### Compiler Version

11.3.0

### Current Behavior?

我运行`bazel build //... -c dbg`，遇到报错：

```
CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "HEXL::hexl" configuration
  "Debug".
```

完整log见附件。
[error.log](https://github.com/secretflow/spu/files/11521905/error.log)

### Standalone code to reproduce the issue

```Python
bazel build //... -c dbg
```

**Comment by anakinxc** [comment]
will be fixed in next update

**Comment by DuanYuFi** [comment]
thanks

**Comment by anakinxc** [comment]
> So many changes. 😢

haha, majority of this pr comes from unification of SPUContext and HalContext. Should be relatively easy to follow.
