### ISSUE TITLE
关于使用spu进行计算问题

### ISSUE THREAD

**Issue by xiaoran33** [secretflow/spu#207]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

0.3.2b12

### OS Platform and Distribution

centos7

### Python Version

3.8.13

### Current Behavior?

看到spu的官方文档demo写了一个add的例子，代码如下：
```
import spu
import jax.numpy as jnp
import numpy as np

# import spu simulation module
import spu.utils.simulation as pps
# create a simulator with ABY3 x Ring64 protocol.
protocol = spu.ProtocolKind.ABY3
field = spu.FieldType.FM64
simulator = pps.Simulator.simple(3, protocol, field)

# decorate a jnp function to a simulated function
spu_add = pps.sim_jax(simulator, jnp.add)

# now we can call spu_fn like normal jnp fn.
x = np.array([[1., 2.], [3., 4.]])
y = np.array([[5., 6.], [7., 8.]])

# the function is simulated on SPU VM, which use 3 threads to simulate different parties.
# the actual progress is exactly the same as real distributed version.
z = spu_add(x, y)

print(z)
```
但是这个是使用的simulator模式初始化的，要是我是真实的三台物理节点该怎么初始化呢？求解答

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by 6fj** [comment]
Hi @xiaoran33 

spu simulator利用多线程来模拟MPC计算参与方，如果你想使用真实的物理节点，你有两个选择：
- 使用spu nodectl （https://github.com/secretflow/spu/blob/main/examples/python/utils/nodectl.py）: 这是spu做的一个toy分布式框架，我们主要用来验证spu的api。
- 使用secretflow中的spu device，请使用生产模式部署secretflow

**Comment by xiaoran33** [comment]
在不考虑secretflow的的前提下，那就只有使用spu nodectl，请问一下nodectl.py如何与上面的demo结合run起来

**Comment by anakinxc** [comment]
Hi @xiaoran33 

你可以参考一下这个[例子](https://github.com/secretflow/spu/tree/main/examples/python/ml/flax_mlp)
