### ISSUE TITLE
call kernels with KernelEvalContext

### ISSUE THREAD

**Issue by DuanYuFi** [secretflow/spu#209]
### Issue Type

Support

### Modules Involved

MPC protocol, SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

d48f0d93c3d7d3b1bf746207cc395f53c7f6f8f4

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.10.9

### Compiler Version

11.3.0

### Current Behavior?

In previous version, I can call the kernels with `call` function in Object [here](https://github.com/secretflow/spu/blob/7dcab95a83c9940b05e09dee846bb07aeff5ab94/libspu/mpc/object.h#L257). However, it was removed in version d48f0d93c3d7d3b1bf746207cc395f53c7f6f8f4, which makes my development inconvenient.

I tried to call, for example, MulAA in this way:
```
MulAA().proc(ctx, lhs, rhs);
```
but I cannot import the header file arithmetic.h in the file of my caller function because the file of caller is lower than arithmetic.h in my protocol.

Is there any solution to replace the `call` function? If not, then I will try to adjust the structure of my project. Thanks :)

### Standalone code to reproduce the issue

```Python
No
```

**Comment by rivertalk** [comment]
Hi @DuanYuFi,
Sorry for the inconvenience. 

You can use dynDispatch to do this:
https://github.com/secretflow/spu/blob/bbd4819c31f2ef1a9a8c7e0a0741da72ca7e73d8/libspu/core/context.h#LL174C22-L174C22

Here is an example
https://github.com/secretflow/spu/blob/bbd4819c31f2ef1a9a8c7e0a0741da72ca7e73d8/libspu/mpc/ab_api.cc#L182

But the dynamic dispatch method is still not stable and flexible enough, i.e. we can not support online/offline split at the moment, so the API may change in the future...

Thanks.

**Comment by rivertalk** [comment]
It should be... or I will change it for you [cry][cry]...

**Comment by DuanYuFi** [comment]
Thanks, but I was determined to refactor the codes. So I will try to fix them recently. :)

**Comment by DuanYuFi** [comment]
After deep consideration, I still think the previous way that dynamically calls to kernels is the best way (up to now) to satisfy my requirements... Now I think the best thing I could do is to wait until this part of code turns stable.

Thanks to SecretFlow, SPU team. I hope my work can merged into the main branch and I hope this day won't be so long LOL. 

![%%BYUG2OJMOH8${QA3ZTXE5](https://github.com/secretflow/spu/assets/58022886/23490940-e5dd-4fbd-94ce-99bf4e055fb3)
