### ISSUE TITLE
使用 SPU 实现主成分分析基础功能

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#213]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第一期](https://github.com/orgs/secretflow/discussions/647)任务 ISSUE，欢迎社区开发者参与共建～

## 任务介绍

- 任务名称：使用 SPU 实现主成分分析基础功能
- 技术方向：SPU/SML
- 任务难度：中等

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：实现算法的基本功能，包括：
  -  支持 fit, transform
  - 起码一种 svd 算法，如 full
  - 至少有一种设置主成分个数的方式和能查看主成分 variance
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明
-  任务难点：在密态下实现 svd 算法

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 可参考明文实现 [PCA](https://github.com/scikit-learn/scikit-learn/blob/364c77e04/sklearn/decomposition/_pca.py#L118)
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 范例：https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py

**Comment by rivertalk** [comment]
> NotImplementedError: MLIR translation rule for primitive 'eigh' not found for platform interpreter

Hi @hacker-jerry，这个看上去是因为 SPU并未支持JAX所有的算子（比如 `eigh`），请 @anakinxc 帮忙看一眼

**Comment by deadlywing** [comment]
> By the way, 用jax.jit也可以编译通过，但是还是无法使用spsim😭

能麻烦提供一下本地使用的package版本么？（主要是spu和jax）

**Comment by deadlywing** [comment]
> spu 0.3.3b0
> jax 0.4.8
> jaxlib 0.4.7

Thanks，我发现你使用ppd和spsim的方式不太一致：
在ppd中 fit 方法是明文计算的
但是在spsim中，fit部分是秘文下进行的

**Comment by deadlywing** [comment]
> 谢谢，请问spsim这里的报错是什么原因呢？应该怎样修改？

首先，我理解fit方法应该是需要能在密态下执行的，所以本质上的原因应该是SPU暂时没支持svd算子。
可能需要您自己实现一下svd算法；
1. 建议可以先实现full solver
2. randomized solver需要注意的点在于spu内对随机数的支持和明文下不太一致，建议把生成初始随机矩阵Q放在外面

**Comment by deadlywing** [comment]
> 您好，我使用jacobi的方法实现了eigh算子，重构后的代码如下：
> 
> ```python
> import jax
> import jax.numpy as jnp
> from jax import jit
> from functools import partial
> 
> 
> class PCA:
>     def __init__(self, n_components=None, tol=1e-8, max_iters=100):
>         self.n_components = n_components
>         self.tol = tol
>         self.max_iters = max_iters
>         self.components_ = None
>         self.explained_variance_ = None
>         self.mean_ = None
> 
>     def fit_transform(self, X):
>         self.mean_ = jnp.mean(X, axis=0)
>         X_centered = X - self.mean_
>         cov_matrix = jnp.cov(X_centered, rowvar=False)
>         eigenvalues, eigenvectors = jacobi_eigh(cov_matrix, self.tol, self.max_iters)
> 
>         idx = jnp.argsort(eigenvalues)[::-1]
>         eigenvalues = eigenvalues[idx]
>         eigenvectors = eigenvectors[:, idx]
> 
>         if self.n_components is None:
>             self.n_components = X.shape[1]
> 
>         self.components_ = eigenvectors[:, :self.n_components]
>         self.explained_variance_ = eigenvalues[:self.n_components]
> 
>         X_transformed = jnp.dot(X_centered, self.components_)
> 
>         return X_transformed, self.explained_variance_
> 
> 
> def jacobi_eigh(A, tol, max_iters):
>     n = A.shape[0]
>     Q = jnp.eye(n)
> 
>     def body_fn(i, vals):
>         A, Q = vals
>         p, q = jnp.unravel_index(jnp.argmax(jnp.abs(A - jnp.diag(jnp.diag(A)))), A.shape)
>         phi = 0.5 * jnp.arctan(2 * A[p, q] / (A[q, q] - A[p, p]))
>         rotation = jnp.eye(n)
>         rotation = rotation.at[[p, q], [p, q]].set(jnp.cos(phi))
>         rotation = rotation.at[q, p].set(jnp.sin(phi))
>         rotation = rotation.at[p, q].set(-jnp.sin(phi))
>         A_prime = rotation.T @ A @ rotation
>         Q_prime = Q @ rotation
> 
>         A = jax.lax.cond(jnp.abs(A[p, q]) < tol, lambda _: A, lambda _: A_prime, None)
>         Q = jax.lax.cond(jnp.abs(A[p, q]) < tol, lambda _: Q, lambda _: Q_prime, None)
>         return A, Q
> 
>     A, Q = jax.lax.fori_loop(0, max_iters, body_fn, (A, Q))
> 
>     return jnp.diag(A), Q
> ```
> 
> 该函数可以通过jit编译后调用
> 
> ```python
> pca = PCA(n_components=2)
> 
> pca_fit_transform = jit(pca.fit_transform, static_argnums=1)
> 
> # Prepare some data
> X = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
> 
> # 使用编译后的fit_transform函数进行拟合和转换
> X_transformed, explained_variance = pca_fit_transform(X)
> 
> print(explained_variance)
> 
> print(X_transformed)
> ```
> 
> 但是使用spism模拟时，再次发生报错
> 
> ```python
> import spu.utils.simulation as spsim
> import spu.spu_pb2 as spu_pb2
> import spu
> 
> sim_aby = spsim.Simulator.simple(
>     3, spu_pb2.ProtocolKind.ABY3, spu_pb2.FieldType.FM64
> )
> 
> def fit_transform(X, n_components=None):
>     pca_fit_transform = jit(PCA(n_components=n_components).fit_transform, static_argnums=1)
>     X_transformed, explained_variance = pca_fit_transform(X)
>     return X_transformed, explained_variance 
> 
> result = spsim.sim_jax(sim_aby, fit_transform,  static_argnums=(1,))(X,2)
> ```
> 
> 报错信息如下：
> 
> ```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[71], line 1
> ----> 1 result = spsim.sim_jax(sim_aby, fit_transform,  static_argnums=(1,))(X,2)
> 
> File [/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/utils/simulation.py:152](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/utils/simulation.py:152), in sim_jax..wrapper(*args, **kwargs)
>     149 def outputNameGen(out_flat):
>     150     return [f'out{idx}' for idx in range(len(out_flat))]
> --> 152 executable, output = spu_fe.compile(
>     153     spu_fe.Kind.JAX,
>     154     fun,
>     155     args,
>     156     kwargs,
>     157     in_names,
>     158     in_vis,
>     159     outputNameGen,
>     160     static_argnums=static_argnums,
>     161 )
>     163 wrapper.pphlo = executable.code.decode("utf-8")
>     165 out_flat = sim(executable, *args_flat)
> 
> File [/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py:177](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/utils/frontend.py:177), in compile(kind, fn, args, kwargs, input_names, input_vis, outputNameGen, static_argnums)
>     175     ir_type = "mhlo"
>     176     name = repr(fn)
> --> 177 mlir = spu_api.compile(ir_text, ir_type, input_vis)
>     178 executable = spu_pb2.ExecutableProto(
>     179     name=name,
>     180     input_names=input_names,
>     181     output_names=output_names,
>     182     code=mlir,
>     183 )
>     184 return executable, output
> 
> File [/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/api.py:153](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/api.py:153), in compile(ir_text, ir_type, vis)
>     150 from google.protobuf.json_format import MessageToJson
>     152 # todo: rename spu_pb2.XlaMeta to IrMeta?
> --> 153 return _spu_compilation(
>     154     ir_text, ir_type, MessageToJson(spu_pb2.XlaMeta(inputs=vis))
>     155 )
> 
> File [/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py:737](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/cachetools/__init__.py:737), in cached..decorator..wrapper(*args, **kwargs)
>     735 except KeyError:
>     736     pass  # key not found
> --> 737 v = func(*args, **kwargs)
>     738 try:
>     739     cache[k] = v
> 
> File [/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/api.py:136](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/sf/lib/python3.8/site-packages/spu/api.py:136), in _spu_compilation(ir_text, ir_type, json_meta)
>     133 @cached(cache=LRUCache(maxsize=128))
>     134 def _spu_compilation(ir_text: str, ir_type: str, json_meta: str):
>     135     pp_dir = os.getenv('SPU_IR_DUMP_DIR')
> --> 136     return libspu.compile(ir_text, ir_type, json_meta, pp_dir or "")
> 
> RuntimeError: what: 
> 	[libspu/compiler/front_end/fe.cc:64] Run front end pipeline failed
> stacktrace: 
> #0 spu::compiler::FE::doit()+0x178ad5b00
> #1 spu::compiler::compile()+0x178ac3ee4
> #2 pybind11::cpp_function::initialize<>()::{lambda()#1}::__invoke()+0x178aa778c
> #3 pybind11::cpp_function::dispatcher()+0x178a94ac4
> #4 cfunction_call_varargs+0x104f243e0
> #5 _PyObject_MakeTpCall+0x104f23af0
> #6 call_function+0x105010158
> #7 _PyEval_EvalFrameDefault+0x10500c83c
> #8 function_code_fastcall+0x104f247b4
> #9 PyVectorcall_Call+0x104f23fd8
> #10 _PyEval_EvalFrameDefault+0x10500caf0
> #11 _PyEval_EvalCodeWithName+0x1050057fc
> #12 _PyFunction_Vectorcall+0x104f24918
> #13 call_function+0x1050100c0
> #14 _PyEval_EvalFrameDefault+0x10500c8b8
> #15 function_code_fastcall+0x104f247b4
> ```
> 
> 请问是什么原因？

hello，不能跑的原因主要是eigh的实现里用到了三角函数，spu当前没有实现，所以报错了；

PLUS，你eigh的实现应该也有问题，我运行了你的eigh
```python
def test_eigh():
    X = jnp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    X_centered = X - jnp.mean(X, axis=0)
    cov_matrix = jnp.cov(X_centered, rowvar=False)

    eigenvalues, eigenvectors = jacobi_eigh(cov_matrix, 1e-8, 1000)
    # print(eigenvalues)
    # print(eigenvectors)
    print(cov_matrix @ eigenvectors)
    print(eigenvalues * eigenvectors)

    print()

    eigenvalues, eigenvectors = eigh(cov_matrix)
    # print(eigenvalues)
    # print(eigenvectors)
    print(cov_matrix @ eigenvectors)
    print(eigenvalues * eigenvectors)
```

```bash
[[2.2865321e+02 5.4445304e-06 2.5582359e+02]
 [2.2865321e+02 5.4445304e-06 2.5582359e+02]
 [2.2865321e+02 5.4445304e-06 2.5582359e+02]]
[[1.4377324e+02 1.2175019e-21 2.0135764e+02]
 [2.4747901e-06 1.2621775e-29 3.4660027e-06]
 [1.6085759e+02 9.3170446e-22 2.2528442e+02]]

[[ 4.1723251e-07 -2.9802322e-07  1.5588457e+01]
 [ 4.1723251e-07 -2.9802322e-07  1.5588457e+01]
 [ 4.1723251e-07 -2.9802322e-07  1.5588457e+01]]
[[-4.0569081e-08 -1.6165853e-06  1.5588456e+01]
 [-1.1870292e-07  1.1621918e-06  1.5588454e+01]
 [ 1.5927199e-07  4.5439356e-07  1.5588456e+01]]
```

**Comment by deadlywing** [comment]
jacobi需要计算旋转变换，当前spu无法支持；我这边提供两种思路，你可以尝试一下：
1. PCA对cov矩阵计算特征值变换，而cov是半正定的，可以用cholesky分解计算特征变换
2. 一般地，可以考虑QR分解，不需要半正定的条件

仅供参考～

**Comment by deadlywing** [comment]
> > jacobi需要计算旋转变换，当前spu无法支持；我这边提供两种思路，你可以尝试一下：
> > 
> > 1. PCA对cov矩阵计算特征值变换，而cov是半正定的，可以用cholesky分解计算特征变换
> > 2. 一般地，可以考虑QR分解，不需要半正定的条件
> > 
> > 仅供参考～
> 
> 谢谢您的建议，基于此，我重新实现了一下，代码如下：
> 
> ```python
> import jax
> import jax.numpy as jnp
> from jax import random
> 
> class PCA:
>     def __init__(self, n_components):
>         self.n_components = n_components
>         self.mean = None
>         self.components = None
>         self.variances = None
> 
>     def fit(self, X):
>         self.mean = jnp.mean(X, axis=0)
>         X = X - self.mean
> 
>         cov_matrix = jnp.cov(X, rowvar=False)
> 
>         L = jnp.linalg.cholesky(cov_matrix)
> 
>         q, r = jnp.linalg.qr(L)
> 
>         eigvals = jnp.diag(r)
> 
>         idx = jnp.argsort(eigvals)[::-1][:self.n_components]
> 
>         self.components = q[:, idx]
> 
>         self.variances = eigvals[idx]
> 
> 
>     def transform(self, X):
>         X = X - self.mean
>         return jnp.dot(X, self.components)
> 
> 
> def fit_and_transform(X, n_components):
>     pca = PCA(n_components)
>     pca.fit(X)
>     return pca.transform(X)
> 
> 
> X = random.randint(random.PRNGKey(0), (10,3), 0, 10)
> 
> fit_and_transform_jit = jit(fit_and_transform, static_argnums=1)
> 
> X_transformed = fit_and_transform_jit(X, 2)
> 
> print(X_transformed)
> ```
> 
> 您看是否符合要求？ 这次的代码通过了sispm模拟。

Sorry, 这应该是spsim的bug，实际上无论cholesky还是qr应该都无法真实的执行，执行到那两个函数的时候似乎python进程会被直接关闭，我们后续应该会修复这个bug。（所以我很好奇，您运行spsim真的能得到PCA transform后的矩阵么？）

所以，你也需要自己**手动实现**cholesky分解或qr分解。

最后，麻烦您后面提交pr的时候，用注释的方式标记一下之前的实现中，因为spu不支持算子而无法运行的实现方式，后续我们增加这些算子以后可以重新考察这些实现～

感谢！

**Comment by deadlywing** [comment]
> 的确是运行成功了， <img alt="image" width="1022" src="https://user-images.githubusercontent.com/57279550/252860618-dc1f22a3-e2ca-41f4-b9ad-a805980be4d3.png"> 您也可以测试一下，
> 
> ```python
> import spu.utils.simulation as spsim
> import spu.spu_pb2 as spu_pb2
> import spu
> 
> sim_aby = spsim.Simulator.simple(
>     3, spu_pb2.ProtocolKind.ABY3, spu_pb2.FieldType.FM64
> )
> 
> result = spsim.sim_jax(sim_aby, fit_and_transform,  static_argnums=(1,))(X,2)
> ```

Thanks, 我本地运行会一直卡住，我需要check一下原因. 另外，麻烦您运行一下下面这个代码,看是否会raise除0错误.
```python
def test_run_eigh():
    X = jnp.array(np.random.rand(6, 3))
    cov_matrix = jnp.cov(X, rowvar=False)

    sim_aby = spsim.Simulator.simple(
        3, spu_pb2.ProtocolKind.ABY3, spu_pb2.FieldType.FM64
    )

    print(cov_matrix)
    print(jnp.linalg.det(cov_matrix))
    print(jnp.linalg.cholesky(cov_matrix))
    print(spsim.sim_jax(sim_aby, jnp.linalg.cholesky)(cov_matrix))
    print(1 / 0)
```

**Comment by deadlywing** [comment]
![image](https://github.com/secretflow/spu/assets/25818621/3904e9a8-0ec7-4997-8e2c-1bf19a012944)
![image](https://github.com/secretflow/spu/assets/25818621/8373c77b-f495-4d25-90b2-13886187dec2)

我在jupyter上运行的话，也会报错...

**Comment by deadlywing** [comment]
> > ![image](https://user-images.githubusercontent.com/25818621/252868528-3904e9a8-0ec7-4997-8e2c-1bf19a012944.png) ![image](https://user-images.githubusercontent.com/25818621/252868823-8373c77b-f495-4d25-90b2-13886187dec2.png)
> > 我在jupyter上运行的话，也会报错...
> 
> 您看看spu降一下级试一下？

好的，我试试；
btw，您是用linux系统不？

**Comment by deadlywing** [comment]
> 我是用的m1 mac

我本地测试了一下，应该是jax版本问题，0.4.8是ok的，我本地是0.4.13才会报错...这个问题得 @anakinxc 看看
您可以先直接使用这两个api去实现pca吧～

建议您实现以后可以：
1. 检查是否满足特征值分解的定义
2. 检查fit后的方差等与sklearn的pca是否一致

感谢！

**Comment by tarantula-leo** [comment]
> > 我是用的m1 mac
> 
> 我本地测试了一下，应该是jax版本问题，0.4.8是ok的，我本地是0.4.13才会报错...这个问题得 @anakinxc 看看 您可以先直接使用这两个api去实现pca吧～
> 
> 建议您实现以后可以：
> 
> 1. 检查是否满足特征值分解的定义
> 2. 检查fit后的方差等与sklearn的pca是否一致
> 
> 感谢！

你好 想问下cholesky分解和qr分解是已经在SPU中支持了还是使用spsim模拟的bug？

**Comment by anakinxc** [comment]
> 我是用的m1 mac

hi，麻烦升级 spu 到最新的或者把 jax 和 jaxlib 降级到 0.4.12

**Comment by deadlywing** [comment]
那看来就是jax最新版本不太适配了，，那您就先用现在的版本先开发吧

**Comment by deadlywing** [comment]
> ok，我测试了一下，和sklearn的 PCA 效果是差不多的。请问如果要提交pr，需要在哪几个文件中进行修改？

感谢快速响应，可以先参考一下这个kmeans的PR；
https://github.com/secretflow/spu/pull/235
一般是一个文件用于实现算法逻辑(jax only)，一个文件用于spsim模拟测试，一个文件做emulation测试；

BTW：麻烦请在spsim模拟测试的那个文件中同时提交一下和明文sklearn的结果对比(可以写在不同的unittest里)

Thanks!
