### ISSUE TITLE
about PSI

### ISSUE THREAD

**Issue by SugarSugarRune** [secretflow/spu#22]
做PSI的时候，对先对本地数据做去重处理吗？

**Comment by zhanglei486** [comment]
需要先做去重处理的

**Comment by SugarSugarRune** [comment]
spu/psi/utils/csv_checker.cc是对数据做去重，还是对数据做查重呀？
在psi_1.csv里设置两条重复的数据225712978001032092，执行bazel run //examples/cpp:simple_psi -- -rank 0 -protocol 1 -in_path examples/data/psi_1.csv -field_names id -out_path /tmp/p1.out 
终端给出这样的提示如下：
RuntimeError: what:
        [Enforce fail at spu/psi/utils/csv_checker.cc:137] duplicated_size == 0. found duplicated keys: 225712978001032092

**Comment by zhanglei486** [comment]
> spu/psi/utils/csv_checker.cc是对数据做去重，还是对数据做查重呀？ 在psi_1.csv里设置两条重复的数据225712978001032092，执行bazel run //examples/cpp:simple_psi -- -rank 0 -protocol 1 -in_path examples/data/psi_1.csv -field_names id -out_path /tmp/p1.out 终端给出这样的提示如下： RuntimeError: what: [Enforce fail at spu/psi/utils/csv_checker.cc:137] duplicated_size == 0. found duplicated keys: 225712978001032092

对数据做查重
