### ISSUE TITLE
spu源码安装

### ISSUE THREAD

**Issue by yellow123Nike** [secretflow/spu#222]
### Issue Type

Build/Install

### Modules Involved

SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

0.4.0b1

### OS Platform and Distribution

linux ubuntu 20

### Python Version

3.8

### Compiler Version

GCC11

### Current Behavior?

编译spu报错
![image](https://github.com/secretflow/spu/assets/37546857/927d68fe-6f32-4f6e-ba4d-259de1f1c35a)
docker images地址404
![image](https://github.com/secretflow/spu/assets/37546857/6b2496a7-78ea-473a-9b98-7e4abd76f39a)

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by tpppppub** [comment]
应该是你的服务器网络连接 dockerhub 有问题

**Comment by anakinxc** [comment]
@yellow123Nike 试一下最新的 head
