### ISSUE TITLE
mpc协议

### ISSUE THREAD

**Issue by leileiL** [secretflow/spu#228]
### Issue Type

Others

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

No

### Installation Kind

source

### SPU Version

spu0.3.2b12

### Current Behavior?

      隐语文档给出的semi2k参考的论文是《SPDℤ_2^k：Efficient MPC mod 2^k for Dishonest Majority》，请问spu工程目录下/mpc/spdz2k对应的协议是什么呀？
     还是semi2k是简化了spdz2k的恶意安全功能？

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by da-niao-dan** [comment]
你好，semi2k的确简化了防范恶意的安全功能，以此获得更高性能。

**Comment by shangqi-zxp** [comment]
你好，/mpc/spdz2k对应的是spdz2k协议，代码仍在开发优化中，等待功能完善时会在文档和接口中透出。
/mpc/semi2k对应的是去除恶意安全功能的spdz2k协议，但也有借鉴其他文章来优化，具体细节需看代码和注释。
