### ISSUE TITLE
docker容器中构建失败

### ISSUE THREAD

**Issue by ZhouZhaoJi** [secretflow/spu#237]
错误：
![image](https://github.com/secretflow/spu/assets/36101779/20bb7d74-f7cd-4077-94c8-866d0a1c42dc)
我按照文档中写的先准备docker环境：
![image](https://github.com/secretflow/spu/assets/36101779/7029dc0b-fb33-4967-9160-f62ce14b5587)
然后在源码下运行
**bazel build //... -c dbg**
然后就出现这个错误了。
（之前还有一个错误找不到，Unknown Host：objects.githubusercontent.com，然后修改hosts文件解决了）

**Comment by 6fj** [comment]
Hi @ZhouZhaoJi 

你需要安装一下python依赖：
```
pip install -r requirements.txt
pip install -r requirements-dev.txt
```

感谢

**Comment by ZhouZhaoJi** [comment]
好的，感谢！

**Comment by ZhouZhaoJi** [comment]
closed
