### ISSUE TITLE
1千万数据做Pir查询Server启动失败

### ISSUE THREAD

**Issue by mingo0117** [secretflow/spu#239]
### Issue Type

Bug

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

binary

### SPU Version

lastest

### OS Platform and Distribution

centos8.5

### Python Version

3.8.13

### Current Behavior?

想测试下1千万数据pir的性能，在setup成功后执行server的初始化，报错如下：

E0713 06:38:49.995201 935000 external/com_github_brpc_brpc/src/brpc/server.cpp:1011] Fail to listen 10.100.82.173:9367
[2023-07-13 06:38:49.995] [warning] [channel.h:116] ChannelBase destructor is called before WaitLinkTaskFinish, try stop send thread
[ERROR] what: 
        [external/yacl/yacl/link/transport/channel_brpc.cc:137] brpc server failed start
stacktrace: 
#0 yacl::link::FactoryBrpc::CreateContext()+0x7fb39a5731d7
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fb3991f254f
#2 pybind11::cpp_function::dispatcher()+0x7fb3991ddb5c
#3 cfunction_call_varargs+0x438966

求教，谢谢

### Standalone code to reproduce the issue

```Python
代码参考pir_server.py
```

**Comment by Chrisdehe** [comment]
hi，@mingo0117 
请确定以下配置
--partyips ip0:port0,ip1:port1 --rank 0/1
指定本方是rank 0 时，必须有ip0, 端口port0没有被占用
指定本方是rank 1 时，必须有ip1, 端口port1没有被占用

**Comment by mingo0117** [comment]
已解决（ip0:port0,ip1:port1顺序反了），谢谢
