### ISSUE TITLE
编译错误：in outs attribute of genrule rule...

### ISSUE THREAD

**Issue by ZhouZhaoJi** [secretflow/spu#242]
spu版本0.4.1b1：
系统环境：ubuntu22.04
![image](https://github.com/secretflow/spu/assets/36101779/41d473fe-f822-4358-b206-77b2dd3b61bd)

**Comment by ZhouZhaoJi** [comment]
genrule(
    name = "python_include",
    outs = [

    ],
    cmd = """

   """,
)
我将这一段删掉了，应该没问题吧。

**Comment by 6fj** [comment]
Hi @ZhouZhaoJi 

请使用docker image进行编译：secretflow/release-ci:latest

具体编译指令是：https://github.com/secretflow/spu/blob/main/.circleci/release-config.yml#L117-L121

感谢

**Comment by ZhouZhaoJi** [comment]
我不想基于docker images，我用自己build的镜像，然后用linux的方法编译，可以吗？我该怎么做？

**Comment by ZhouZhaoJi** [comment]
这是secretflow大的东西，我只想编译SPU，其他都不需要。

**Comment by 6fj** [comment]
你可以参考dockerfile配置你的编译环境：

https://github.com/secretflow/devtools/blob/main/dockerfiles/release-ci.DockerFile

**Comment by anakinxc** [comment]
Hi @ZhouZhaoJi 

麻烦提供一下你运行的 command

**Comment by ZhouZhaoJi** [comment]
![image](https://github.com/secretflow/spu/assets/36101779/be4ce152-8d9b-401a-b07e-abb5065bc15a)
![image](https://github.com/secretflow/spu/assets/36101779/bd6b8910-59d3-44de-8d24-af6daac919c4)

**Comment by ZhouZhaoJi** [comment]
![image](https://github.com/secretflow/spu/assets/36101779/a78ea181-bd6e-479e-b681-3e922a6bf5cf)
![image](https://github.com/secretflow/spu/assets/36101779/72d9c6cd-b1b8-4620-a1fb-9815b06d98a1)

**Comment by ZhouZhaoJi** [comment]
这上面说的这是一个list，但是现在变成string了，这应该是bug吧。我不熟悉这种语言，但是能看懂它想做什么。

**Comment by ZhouZhaoJi** [comment]
![image](https://github.com/secretflow/spu/assets/36101779/36bad6c3-c9f6-4d33-a2bf-9f47b025fd0b)
调用的代码感觉没有问题，应该是bazel的编译器出现问题了。

**Comment by 6fj** [comment]
1. 请问你现在是在docker里面编译吗？
2. 你的编译过程能复述一下吗？

**Comment by ZhouZhaoJi** [comment]
我没有用你们的镜像，我自己弄了一个镜像，基于Ubuntu 22.04。
```
FROM ubuntu:22.04

RUN apt update
RUN apt -y install g++ gdb cgdb
RUN apt -y install autoconf automake libtool cmake pkg-config
RUN apt -y install vim tree net-tools unzip git iputils-ping gettext proxychains4
RUN apt -y install python3 python3-pip

RUN apt -y install openssl openssh-server
RUN mkdir -p /run/sshd
RUN sed -i 's/#Port 22/Port 22/g' /etc/ssh/sshd_config
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

CMD (/usr/sbin/sshd -D &) && /bin/bash

WORKDIR /root/

EXPOSE 22
``` 
然后按照你们的说明，安装依赖包：
![image](https://github.com/secretflow/spu/assets/36101779/47247215-0d16-4fe1-a26c-6fe899ad715c)
```
apt install -y software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt install -y python3.8 python3.8-distutils python3-apt ninja-build nasm apt-transport-https curl gnupg golang
curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
mv bazel-archive-keyring.gpg /usr/share/keyrings
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
apt update && apt install -y bazel-5.4.1
ln -s /usr/bin/bazel-5.4.1 /usr/bin/bazel
wget https://github.com/secretflow/spu/archive/refs/tags/0.4.1b1.tar.gz
tar zxvf 0.4.1b1.tar.gz
cd spu-0.4.1b1/
pip cache purge
python -m pip install -r requirements.txt
python -m pip install -r requirements-dev.txt
```
最后使用：
bazel build //... -c dbg
然后没有成功。

**Comment by ZhouZhaoJi** [comment]
python用的是默认的，之前按照你们的要求用了3.8，但是我发现结果差不多，然后把安装3.8的命令删掉了。

**Comment by ZhouZhaoJi** [comment]
现在搞着搞着，之前的错误没有了，不过出现另一个错误：
![image](https://github.com/secretflow/spu/assets/36101779/731b86af-87b9-4587-888f-38e27460e832)

**Comment by 6fj** [comment]
你可以用我们的docker image: secretflow/release-ci:latest，如果根据dockerfile来构建docker image：https://github.com/secretflow/devtools/blob/main/dockerfiles/release-ci.DockerFile

**Comment by ZhouZhaoJi** [comment]
我找到问题了，因为我使用代理，每一条命令输入，都会输出proxychain4的信息，然后程序里面存在捕捉标准输出的流程，它把这些信息当成命令了。
docker试过了，因为不行，所以才选择不用镜像。可能不行的原因也是这个原因。

**Comment by ZhouZhaoJi** [comment]
closed
