### ISSUE TITLE
Building Error:GET returned 404 Not Found

### ISSUE THREAD

**Issue by ZhouZhaoJi** [secretflow/spu#243]
![image](https://github.com/secretflow/spu/assets/36101779/431c152d-6a76-44c6-a3fa-e940753ec0e6)

**Comment by 6fj** [comment]
Hi @ZhouZhaoJi 

请确保你可以访问这个域名，感谢

**Comment by ZhouZhaoJi** [comment]
![image](https://github.com/secretflow/spu/assets/36101779/85a47e70-2594-4dbd-bd72-85bb9ac6fc85)

**Comment by 6fj** [comment]
请粘贴一下这个url，感谢

**Comment by ZhouZhaoJi** [comment]
https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/eda65a38acebfa4b107c42bff1d33cec712440bf.tar.gz

**Comment by 6fj** [comment]
看上去是Google mirror这边的问题，我这边也没有办法下载。

**Comment by ZhouZhaoJi** [comment]
我怀疑是这个问题，导致那个问题：https://github.com/secretflow/spu/issues/242。这个要如何解决？

**Comment by ZhouZhaoJi** [comment]
closed
