### ISSUE TITLE
libpsi_kkrt_bench.cc文件的作用是什么，没看到哪里调用了

### ISSUE THREAD

**Issue by nvxliukai** [secretflow/spu#247]
### Issue Type

Support

### Modules Involved

PSI

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

main

### Current Behavior?

libpsi_kkrt_bench.cc和kkrt_psi.cc这两种方法，为什么没有选择libpsi_kkrt_bench.cc而是选择kkrt_psi.cc

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by zhanglei486** [comment]
libpsi_kkrt_bench.cc 用来对https://github.com/osu-crypto/libPSI中的kkrt协议进行性能测试的脚本
开发kkrt过程中用来做性能对比的，在当前代码中被用到，后续我们会删掉

**Comment by nvxliukai** [comment]
那性能对比结果能分享一下吗，哪个更快呢，有必要替换成https://github.com/osu-crypto/libPSI 这个吗

**Comment by zhanglei486** [comment]
> 那性能对比结果能分享一下吗，哪个更快呢，有必要替换成https://github.com/osu-crypto/libPSI 这个吗

有些历史数据，暂时先不分享了， @nvxliukai 如果感兴趣可以对比测一下

**Comment by nvxliukai** [comment]
所以替换成https://github.com/osu-crypto/libPSI 是有必要的对吧

**Comment by zhanglei486** [comment]
隐语spu psi提供了ecdh、kkrt等多种协议的实现，大多数协议是自主开发，有些协议也引用或依赖了其它开源库
[libPSI](https://github.com/osu-crypto/libPSI)也PSI方面比较著名的开源库，spu暂时还没有计划引用或依赖libPSI
