### ISSUE TITLE
使用 SPU 实现广义线性模型

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#251]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：使用 SPU 实现广义线性模型
- 技术方向：SPU/SML
- 任务难度：进阶🌟🌟

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：实现算法的基本功能，包括：
  - 支持 fit，predict
  - 提供配置 link，dist，weight 等基本参数（sklearn 根据分布提供tweedie，poisson，gamma 回归，可参考 SecretFlow 或 statsmodels 的 API 设计）
  - 支持起码一种 fit 算法(irls, sgd, lbfgs...)
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性/准确性（最好有与明文 sklearn 结果的对比，可详见[参考 PR](https://github.com/secretflow/spu/pull/240)）
- 正确性：请确保提交的代码内容为可以直接运行的
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 可参考明文实现：
  - [sklearn tweedie](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/linear_model/_glm/glm.py#L724)
  - [secretflow glm](https://github.com/secretflow/secretflow/blob/main/secretflow/ml/linear/ss_glm/model.py#L217)
  - [statsmodels glm](https://github.com/statsmodels/statsmodels/blob/main/statsmodels/genmod/generalized_linear_model.py#L84)
-  [范例](https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py)
-  [参考 PR](https://github.com/secretflow/spu/pull/240)

## 认领说明
本任务可有多种实现方式，故支持一个任务有多位开发者进行认领，请在认领任务后，在该 issue 下 comment 你的具体设计思路。

**设计思路说明**：简单说明计划使用什么算法 or 什么优化器实现任务需求即可

> 当同一任务有多位开发者提交设计思路时：
> -  若多位开发者的设计思路均类似，则将按照 comment 的时间 assign 给第一位 comment 的开发者；
> -  若多位开发者的设计思路均不同，则该 issue 将会拆分为以不同设计思路进行实现的子 issue，并 assign 给对应开发者。

## 开发须知
以下部分代码请必须增加代码注释，对对应代码模块进行说明，包括：
-  __init__函数的超参数含义
-  fit 的具体算法实现说明

**Comment by FanGuojie** [comment]
FanGuojie Give it to me

**Comment by Candicepan** [comment]
> FanGuojie Give it to me

感谢认领～Next Step：请按照认领说明在您的回复下 再更新您计划的设计思路哈～

**Comment by FanGuojie** [comment]
设计思路：

1.	数据预处理：在开始实现算法之前，首先要对数据进行预处理，包括特征缩放、特征选择、数据标准化等。在隐私保护场景下，可以考虑使用差分隐私技术来保护原始数据隐私。

2.	SPU加密：使用SPU对输入数据进行加密，确保在计算过程中数据不会暴露。SPU是一种安全硬件处理单元，能够对数据进行安全加密和解密，可以保护数据隐私。

3.	梯度计算：根据广义线性模型的损失函数，使用不同的优化算法（如IRLS、SGD、L-BFGS等）来计算模型参数的梯度。在加密计算过程中，需要使用安全多方计算（Secure Multi-Party Computation，SMPC）或同态加密等隐私保护技术来进行梯度计算。

4.	参数更新：利用梯度下降等优化算法更新模型参数。在加密计算中，需要确保模型参数在计算过程中不会泄漏。

5.	解密输出：在模型训练结束后，使用SPU对模型输出进行解密，得到最终的预测结果。确保在计算过程中不会泄漏预测结果的隐私。

6.	收敛性和准确性验证：使用模拟器进行实验数据的验证，并与明文Sklearn实现的结果进行对比。确保算法在加密计算过程中能够达到收敛并且保持准确性。

**Comment by deadlywing** [comment]
> 设计思路：
> 
> 1. 数据预处理：在开始实现算法之前，首先要对数据进行预处理，包括特征缩放、特征选择、数据标准化等。在隐私保护场景下，可以考虑使用差分隐私技术来保护原始数据隐私。
> 2. SPU加密：使用SPU对输入数据进行加密，确保在计算过程中数据不会暴露。SPU是一种安全硬件处理单元，能够对数据进行安全加密和解密，可以保护数据隐私。
> 3. 梯度计算：根据广义线性模型的损失函数，使用不同的优化算法（如IRLS、SGD、L-BFGS等）来计算模型参数的梯度。在加密计算过程中，需要使用安全多方计算（Secure Multi-Party Computation，SMPC）或同态加密等隐私保护技术来进行梯度计算。
> 4. 参数更新：利用梯度下降等优化算法更新模型参数。在加密计算中，需要确保模型参数在计算过程中不会泄漏。
> 5. 解密输出：在模型训练结束后，使用SPU对模型输出进行解密，得到最终的预测结果。确保在计算过程中不会泄漏预测结果的隐私。
> 6. 收敛性和准确性验证：使用模拟器进行实验数据的验证，并与明文Sklearn实现的结果进行对比。确保算法在加密计算过程中能够达到收敛并且保持准确性。

Hello，感谢提供设计思路，希望能再明确一下您具体准备实现哪种（些）优化算法，以及预备支持哪种（些）分布？

**Comment by FanGuojie** [comment]
预计实现的优化算法：IRLS，SGD，L-BFGS

预备支持的分布：Tweedie分布,Poisson分布,Gamma分布

**Comment by Candicepan** [comment]
> 预计实现的优化算法：IRLS，SGD，L-BFGS
> 
> 预备支持的分布：Tweedie分布,Poisson分布,Gamma分布

LGTM 感谢您的设计方案。
PS：因目前的设计方案已基本涵盖可实现的算法与分布形式，故本 issue 不再拆分，直接 assign 给这位开发者。
