### ISSUE TITLE
使用 SPU 逻辑回归算法功能性增强

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#252]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：使用 SPU 逻辑回归算法功能性增强
- 技术方向：SPU/SML
- 任务难度：进阶🌟🌟

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：（以下 feature 可能不一定是严格正交的，比如某些优化算法若不支持特殊的正则等，必须在代码注释中明确说明）实现任一feature即可
  - 多分类支持
  - class_weight 支持
  - L1，elastic 正则支持
  -  除 sgd 外的其他优化算法
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性/准确性（最好有与明文 sklearn 结果的对比，可详见[参考 PR](https://github.com/secretflow/spu/pull/240)）
- 正确性：请确保提交的代码内容为可以直接运行的
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 可参考明文实现：[linear_model/_logistic](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/linear_model/_logistic.py#L792)
-  [范例](https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py)
-  [参考 PR](https://github.com/secretflow/spu/pull/240)

## 认领说明
本任务可有多种实现方式，故支持一个任务有多位开发者进行认领，请在认领任务后，在该 issue 下 comment 你的具体设计思路。

**设计思路说明**：简单说明计划使用什么算法 or 什么优化器实现任务需求即可

> 当同一任务有多位开发者提交设计思路时：
> -  若多位开发者的设计思路均类似，则将按照 comment 的时间 assign 给第一位 comment 的开发者；
> -  若多位开发者的设计思路均不同，则该 issue 将会拆分为以不同设计思路进行实现的子 issue，并 assign 给对应开发者。

## 开发须知
以下部分代码请必须增加代码注释，对对应代码模块进行说明，包括：
-  __init__函数的超参数含义
-  fit 的具体算法实现说明

**Comment by Heffie199** [comment]
[root@host-15-0-0-236 ap]# tar -xf secretflow-allinone-package-latest.tar.gz
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.md5ex'
[root@host-15-0-0-236 ap]# cd /ap/secretflow-allinone-package/
[root@host-15-0-0-236 secretflow-allinone-package]# ll
total 8
drwxr-xr-x 2 501 games 4096 Jul 27 13:53 images
-rwxr-xr-x 1 501 games 1399 Jul  7 11:38 install.sh
[root@host-15-0-0-236 secretflow-allinone-package]# ./install.sh
images/kuscia-0.2.0b1.tar
echo Loaded image: secretflow/kuscia:0.2.0b1
images/secretflow-lite-anolis8-1.0.0b2.tar
echo Loaded image: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.0.0b2
images/secretpad:0.1.0b0.tar
echo Loaded image: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretpad:0.1.0b0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /home/kuscia/bin/tini: exec format error
[root@host-15-0-0-236 secretflow-allinone-package]# ^C
[root@host-15-0-0-236 secretflow-allinone-package]#

**Comment by Candicepan** [comment]
> [root@host-15-0-0-236 ap]# tar -xf secretflow-allinone-package-latest.tar.gz tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.md5ex' [root@host-15-0-0-236 ap]# cd /ap/secretflow-allinone-package/ [root@host-15-0-0-236 secretflow-allinone-package]# ll total 8 drwxr-xr-x 2 501 games 4096 Jul 27 13:53 images -rwxr-xr-x 1 501 games 1399 Jul 7 11:38 install.sh [root@host-15-0-0-236 secretflow-allinone-package]# ./install.sh images/kuscia-0.2.0b1.tar echo Loaded image: secretflow/kuscia:0.2.0b1 images/secretflow-lite-anolis8-1.0.0b2.tar echo Loaded image: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.0.0b2 images/secretpad:0.1.0b0.tar echo Loaded image: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretpad:0.1.0b0 WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested exec /home/kuscia/bin/tini: exec format error [root@host-15-0-0-236 secretflow-allinone-package]# ^C [root@host-15-0-0-236 secretflow-allinone-package]#

hello～没有看懂您的问题哈 是有什么疑问吗～

**Comment by magic-hya** [comment]
magic-hya Give it to me
想挑战一下
具体思路：
1.参考sklearn logistic.py做对比验证
2.使用newton-cholesky实现
3.class_weight 支持
4.正则L2
5.实现2分类后，再看下多分类实现

**Comment by Candicepan** [comment]
> magic-hya Give it to me 想挑战一下 具体思路： 1.参考sklearn logistic.py做对比验证 2.使用newton-cholesky实现 3.class_weight 支持 4.正则L2 5.实现2分类后，再看下多分类实现

LGTM~

**Comment by magic-hya** [comment]
1.最近看了下sklearn的源码，newton-cholesky实现的逻辑比较复杂，时间也快到了，这块暂时先不做。

**Comment by deadlywing** [comment]
> 1.最近看了下sklearn的源码，newton-cholesky实现的逻辑比较复杂，时间也快到了，这块暂时先不做。 2.正则项增加L1和elastic方式，参考公式和相关资料代码，写了个demo，效果还不错，贴在下面，看下有没问题。
> 
> ```
>             w_with_zero_bias = jnp.resize(w, (num_feat, 1))
>             w_with_zero_bias = jnp.concatenate(
>                 (w_with_zero_bias, jnp.zeros((1, 1))),
>                 axis=0,
>             )
>             if self._penalty == Penalty.L2:
>                 grad = grad + w_with_zero_bias * self._l2_norm
>             elif self._penalty == Penalty.L1:
>                 grad = grad + jnp.sign(w_with_zero_bias) * self._l1_norm
>             elif self._penalty == Penalty.Elastic:
>                 grad = grad + (self._alpha * jnp.sign(w_with_zero_bias) * self._l1_norm + (1 - self._alpha) * w_with_zero_bias * self._l2_norm)
> ```
> 
> 思路公式是： L1： np.sign(w) * l1_norm Elastic: alpha * L1正则 + (1 - alpha) * L2正则 3.后面class weight 和多分类的也正在看

LGTM，您可以按照自己的思路先实现哈～

**Comment by magic-hya** [comment]
jnp.unique(y) 使用这个函数会报错，是什么原因，有什么办法能解决这个问题

**Comment by deadlywing** [comment]
> jnp.unique(y) 使用这个函数会报错，是什么原因，有什么办法能解决这个问题

密态下无法实现unique去重，请问你是什么场景需要呢？

**Comment by magic-hya** [comment]
我在做多分类，需要拿到y的label值

**Comment by deadlywing** [comment]
> 我在做多分类，需要拿到y的label值

密态下无法做数据探查，可以assume y的取值是0,1,2...这种格式的，

**Comment by magic-hya** [comment]
好的，那我作为参数传进去

**Comment by magic-hya** [comment]
现在又遇到个问题，如何判断y的值等于label的值，密态下无法拿到y的值，有什么办法能reveal

**Comment by deadlywing** [comment]
> 现在又遇到个问题，如何判断y的值等于label的值，密态下无法拿到y的值，有什么办法能reveal 我现在代码这样写的：
> 
> ```
> mask = y == pos_class
> y_bin = jnp.ones(y.shape)
> for i in range(len(y)):
>     if not mask[i]:
>         y_bin = y_bin.at[i].set(0.0)
> y = y_bin
> ```
> 
> mask需要显示

我理解，如果您是以ovr的方式实现多分类，那实际上您只需要把mask直接作为这个class下的y即可

**Comment by magic-hya** [comment]
目前遇到问题，多分类在使用roc_auc_score中，出现精度问题，而无法继续下去，我提交个pr，可以帮我看看如何解决
