### ISSUE TITLE
使用 SPU 实现高斯过程分类算法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#255]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：使用 SPU 实现高斯过程分类算法
- 技术方向：SPU/SML
- 任务难度：进阶🌟🌟

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：实现算法的基本功能，包括：
  - 支持 fit，predict
  - 支持起码一种 fit 算法
  - 起码支持一种 kernel（如 RBF）
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性/准确性（最好有与明文 sklearn 结果的对比，可详见[参考 PR](https://github.com/secretflow/spu/pull/240)）
- 正确性：请确保提交的代码内容为可以直接运行的
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 可参考明文实现：
  - [sklearn](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/gaussian_process/_gpc.py#L487)
  - [ref book](http://gaussianprocess.org/gpml/chapters/)
-  [范例](https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py)
-  [参考 PR](https://github.com/secretflow/spu/pull/240)

## 认领说明
本任务可有多种实现方式，故支持一个任务有多位开发者进行认领，请在认领任务后，在该 issue 下 comment 你的具体设计思路。

**设计思路说明**：简单说明计划使用什么算法 or 什么优化器实现任务需求即可

> 当同一任务有多位开发者提交设计思路时：
> -  若多位开发者的设计思路均类似，则将按照 comment 的时间 assign 给第一位 comment 的开发者；
> -  若多位开发者的设计思路均不同，则该 issue 将会拆分为以不同设计思路进行实现的子 issue，并 assign 给对应开发者。

## 开发须知
以下部分代码请必须增加代码注释，对对应代码模块进行说明，包括：
-  __init__函数的超参数含义
-  fit 的具体算法实现说明

**Comment by salazar1117** [comment]
salazar1117 Give it to me.
初始化：指定核函数kernal（及所需参数）
优化器：L-BFGS-B
核函数：RBF核函数（拥有超参数sigma）
fit方法：输入为训练集特征矩阵X和标签y（y至少包含两个不同的值），先用核函数得到协方差矩阵K，在主对角线元素上添加噪声方差，之后对其进行Cholesky分解得到L矩阵。将y标准化为均值为0、方差为1的形式y‘，使用标准化后的y’和L矩阵求解得到L*L^T*alpha=y’中的alpha。过程中得到模型的alpha、L、y的方差与均值，存放在类成员变量中。
predict：对测试样本x，得到其与训练矩阵X的核函数，其转置乘以(y-训练集上预测的概率)得到测试集的预测值并输出预测。

**Comment by Candicepan** [comment]
> salazar1117 Give it to me. 初始化：指定核函数kernal（及所需参数） 优化器：L-BFGS-B 核函数：RBF核函数（拥有超参数sigma） fit方法：输入为训练集特征矩阵X和标签y（y至少包含两个不同的值），先用核函数得到协方差矩阵K，在主对角线元素上添加噪声方差，之后对其进行Cholesky分解得到L矩阵。将y标准化为均值为0、方差为1的形式y‘，使用标准化后的y’和L矩阵求解得到L_L^T_alpha=y’中的alpha。过程中得到模型的alpha、L、y的方差与均值，存放在类成员变量中。 predict：对测试样本x，得到其与训练矩阵X的核函数，其转置乘以(y-训练集上预测的概率)得到测试集的预测值并输出预测。

LGTM 感谢您的设计方案。
PS：因目前的设计方案已基本涵盖可实现的算法与分布形式，故本 issue 不再拆分，直接 assign 给这位开发者。
