### ISSUE TITLE
使用 SPU 实现高斯朴素贝叶斯算法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#256]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍

- 任务名称：使用 SPU 实现高斯朴素贝叶斯算法
- 技术方向：SPU/SML
- 任务难度：进阶🌟🌟

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：实现算法的基本功能，包括：
  - 支持 fit, predict, partial_fit
  - 提供配置 smooth 参数
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性/准确性（最好有与明文 sklearn 结果的对比，可详见[参考 PR](https://github.com/secretflow/spu/pull/240)）
- 正确性：请确保提交的代码内容为可以直接运行的
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 可参考明文实现：
  - [sklearn](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/naive_bayes.py#L147)
  - [ref book](http://i.stanford.edu/pub/cstr/reports/cs/tr/79/773/CS-TR-79-773.pdf)
-  [范例](https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py)
-  [参考 PR](https://github.com/secretflow/spu/pull/240)

## 认领说明
本任务可有多种实现方式，故支持一个任务有多位开发者进行认领，请在认领任务后，在该 issue 下 comment 你的具体设计思路。

**设计思路说明**：简单说明计划使用什么算法 or 什么优化器实现任务需求即可

> 当同一任务有多位开发者提交设计思路时：
> -  若多位开发者的设计思路均类似，则将按照 comment 的时间 assign 给第一位 comment 的开发者；
> -  若多位开发者的设计思路均不同，则该 issue 将会拆分为以不同设计思路进行实现的子 issue，并 assign 给对应开发者。

## 开发须知
以下部分代码请必须增加代码注释，对对应代码模块进行说明，包括：
-  __init__函数的超参数含义
-  fit 的具体算法实现说明

**Comment by fffmath** [comment]
fffmath give it to me

**Comment by fffmath** [comment]
麻烦取消一下这个任务，我最近在家拿m1芯片的笔记本一直配不好环境，等过段时间回学校再试试，不好意思

**Comment by Candicepan** [comment]
> 麻烦取消一下这个任务，我最近在家拿m1芯片的笔记本一直配不好环境，等过段时间回学校再试试，不好意思

感谢支持哈～好的呀 欢迎之后回学校之后再次认领呀，那本任务暂时回收哈～

**Comment by nantsing** [comment]
nantsing give it to me

**Comment by nantsing** [comment]
设计思路：按照高斯朴素贝叶斯原始定义算法实现
partail_fit 记录当前的均值、方差和训练样本个数，当有新样本时更新均值和方差
fit 重复调用partial_fit实现
predict 使用正态分布函数计算当前参数下测试样本的各类别后验概率，并以此预测分类

**Comment by Candicepan** [comment]
> 设计思路：按照高斯朴素贝叶斯原始定义算法实现 partail_fit 记录当前的均值、方差和训练样本个数，当有新样本时更新均值和方差 fit 重复调用partial_fit实现 predict 使用正态分布函数计算当前参数下测试样本的各类别后验概率，并以此预测分类

LGTM 可以按照这个设计思路进行实现哈～有任何问题欢迎直接 issue 下 comment

**Comment by nantsing** [comment]
@Candicepan 我打算把partail_fit拆成两种情况来实现：用户第一次调用时需要调用first_partial_fit，后续则调用partail_fit，这样实现的原因是JAX不大支持条件分支，但处理这两种情况的方法不太一样。 请问这样实现是ok的吗

**Comment by deadlywing** [comment]
> @Candicepan 我打算把partail_fit拆成两种情况来实现：用户第一次调用时需要调用first_partial_fit，后续则调用partail_fit，这样实现的原因是JAX不大支持条件分支，但处理这两种情况的方法不太一样。 请问这样实现是ok的吗

Hi，对外的话，`partial_fit`一个api就足够了，内部确实是需要根据是否首次调用划分；

关于jax不支持条件分支，说的是不能和您的输入参数有关联，但如果只是判断是否首次fit，是可以实现的，可以参考我这个小例子：
```python
import unittest

import jax.numpy as jnp
import numpy as np

import spu.spu_pb2 as spu_pb2  # type: ignore
import spu.utils.simulation as spsim


class A:
    def __init__(self, x):
        self.x = x

        self.set_ = None

    def set(self):
        self.set_ = True

    def do(self):
        if self.set_:
            return self.x * self.x
        else:
            return self.x


class UnitTests(unittest.TestCase):
    def test_dummy(self):
        def dummy(x):
            a = A(x)
            a.set()
            return a.do()

        sim = spsim.Simulator.simple(
            3, spu_pb2.ProtocolKind.ABY3, spu_pb2.FieldType.FM64
        )

        x = jnp.arange(6).reshape(2, 3)
        result = spsim.sim_jax(sim, dummy)(x)
        print(result)


if __name__ == "__main__":
    unittest.main()
```

**Comment by nantsing** [comment]
> > @Candicepan 我打算把partail_fit拆成两种情况来实现：用户第一次调用时需要调用first_partial_fit，后续则调用partail_fit，这样实现的原因是JAX不大支持条件分支，但处理这两种情况的方法不太一样。 请问这样实现是ok的吗
> 
> Hi，对外的话，`partial_fit`一个api就足够了，内部确实是需要根据是否首次调用划分；
> 
> 关于jax不支持条件分支，说的是不能和您的输入参数有关联，但如果只是判断是否首次fit，是可以实现的，可以参考我这个小例子：
> 
> ```python
> import unittest
> 
> import jax.numpy as jnp
> import numpy as np
> 
> import spu.spu_pb2 as spu_pb2  # type: ignore
> import spu.utils.simulation as spsim
> 
> 
> class A:
>     def __init__(self, x):
>         self.x = x
> 
>         self.set_ = None
> 
>     def set(self):
>         self.set_ = True
> 
>     def do(self):
>         if self.set_:
>             return self.x * self.x
>         else:
>             return self.x
> 
> 
> class UnitTests(unittest.TestCase):
>     def test_dummy(self):
>         def dummy(x):
>             a = A(x)
>             a.set()
>             return a.do()
> 
>         sim = spsim.Simulator.simple(
>             3, spu_pb2.ProtocolKind.ABY3, spu_pb2.FieldType.FM64
>         )
> 
>         x = jnp.arange(6).reshape(2, 3)
>         result = spsim.sim_jax(sim, dummy)(x)
>         print(result)
> 
> 
> if __name__ == "__main__":
>     unittest.main()
> ```

感谢解答，这个问题暂时解决了

**Comment by nantsing** [comment]
我在测试partial_fit的时候遇到了jnp.log在SPU上运行时的精度问题，大概的例子如下

```python
import unittest

import jax.numpy as jnp
import numpy as np
from jax import jit

import spu.spu_pb2 as spu_pb2  # type: ignore
import spu.utils.simulation as spsim

def test(classes):
    c = jnp.array([0, 1, 2])
    a = jnp.zeros(3)
    for y_i in classes:
        i = c.searchsorted(y_i)
        a = a.at[i].set(a[i])
        
    return jnp.log(a)
    
class UnitTests(unittest.TestCase):
    def test_dummy(self):
        def dummy(classes):
            a = test(classes)
            return a

        sim = spsim.Simulator.simple(
            3, spu_pb2.ProtocolKind.ABY3, spu_pb2.FieldType.FM64
        )

        result = spsim.sim_jax(sim, dummy)(jnp.array([0, 1]))
        print('result:', result)


if __name__ == "__main__":
    unittest.main()
```
期待中 a= [0, 0, 0]，因此返回的对数值应该是个很小的数，但运行输出是

```
(secretflow) [jiahaozhao@wsl8 GNB]$ python test.py 
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
result: [-16.504795 -16.504787 -16.504787]
.
----------------------------------------------------------------------
Ran 1 test in 0.358s

OK
```

但如果直接返回 a 的话结果确实是[0, 0, 0]，所以我暂时还不知道是什么原因。

**Comment by nantsing** [comment]
我的困惑来源于如果我直接在SPU上求log(0)（直接输出jnp.log(0.)）它是会返回一个负的极小值（SPU上是-1.7592186e+13，在CPU上会直接得到-inf），但我这段代码得到的是-16.504795，这在后面取max的时候可能会出问题。我希望能把这个log(0)表示为一个负的很小的值，我想知道这有没有什么解决方案，感谢

**Comment by nantsing** [comment]
> > 我的困惑来源于如果我直接在SPU上求log(0)（直接输出jnp.log(0.)）它是会返回一个负的极小值（SPU上是-1.7592186e+13，在CPU上会直接得到-inf），但我这段代码得到的是-16.504795，这在后面取max的时候可能会出问题。我希望能把这个log(0)表示为一个负的很小的值，我想知道这有没有什么解决方案，感谢
> 
> SPU 本身只支持定点数，定点数不像浮点数，并不支持 +/-inf,nan。 对于如下代码
> 
> ```python
> x = np.array([0])
> def foo(x):
>   return jnp.log(x)
> ```
> 
> 在 FM64 的情况下，SPU 能表达的定点数最小值大概是 1e-6，然后拟合以后大概得值就是 -16。如果你改成 FM128，会到 1e-8 这样子，log 拟合以后会到 -22 左右。
> 
> 但是如果你运行这样代码
> 
> ```python
> def foo():
>   return jnp.log(0)
> ```
> 
> 你会得到 -1e+13 这样的值，这是因为在 compile time 编译器会直接把 jnp.log(0) fold 成 constant(-inf)。SPU 会把 -inf map 到 -FXP_MAX，所以你就得到了一个很大的值。
> 
> 对于你要的效果或许你可以试一下
> 
> ```python
> jnp.where(x == 0, jnp.inf, jnp.log(x))
> ```

明白了，问题已解决，感谢🫡
