### ISSUE TITLE
使用 SPU 实现 AdaBoost 分类器算法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#257]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍

- 任务名称：使用 SPU 实现 AdaBoost 分类器算法
- 技术方向：SPU/SML
- 任务难度：挑战🌟🌟🌟
- 任务期望完成时间：8 周

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：实现算法的基本功能，包括：
  - 支持 fit，predict
  - 提供配置学习率，分类器个数等基本参数
  - 支持起码一种弱分类器(如决策树，也可以是其他支持加权训练的分类器)
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性/准确性（最好有与明文 sklearn 结果的对比，可详见[参考 PR](https://github.com/secretflow/spu/pull/240)）
- 正确性：请确保提交的代码内容为可以直接运行的
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：
   - 为避免走弯路，请先提交你的**设计思路**，经确认后再进入开发阶段 
     - 设计思路说明：简单说明计划使用什么算法 or 什么优化器实现任务需求即可
   - 关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 可参考明文实现：[ensemble/_weight_boosting](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/ensemble/_weight_boosting.py#L341)
-  [范例](https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py)
-  [参考 PR](https://github.com/secretflow/spu/pull/240)

## 开发须知
以下部分代码请必须增加代码注释，对对应代码模块进行说明，包括：
-  __init__函数的超参数含义
-  fit 的具体算法实现说明

**Comment by FanGuojie** [comment]
申请实现

**Comment by Candicepan** [comment]
> 申请实现

感谢申请，辛苦按照格式回复哈～认领回复格式：【GitHub ID + Give it to me】

**Comment by Candicepan** [comment]
> 申请实现

感谢申请，辛苦按照格式回复哈～认领回复格式：【GitHub ID + Give it to me】

**Comment by FanGuojie** [comment]
Fanguojie Give it to me

**Comment by Candicepan** [comment]
> > 申请实现
> 
> 感谢申请，辛苦按照格式回复哈～认领回复格式：【GitHub ID + Give it to me】

感谢认领～为避免走弯路，请先提交你的**设计思路**，经确认后再进入开发阶段 
- 设计思路说明：简单说明计划使用什么算法 or 什么优化器实现任务需求即可

**Comment by FanGuojie** [comment]
基分类器：决策树、逻辑回归、SVC、KNeighborsClassifier、RandomForestClassifier、glm。adaboost本身不涉及优化器

**Comment by deadlywing** [comment]
> 基分类器：决策树、逻辑回归、SVC、KNeighborsClassifier、RandomForestClassifier、glm。adaboost本身不涉及优化器

hello，，当前sml中已经有的base model只有LR，建议您可以先把adaboost本身的功能实现，然后再考虑扩展多种base model

Thanks

**Comment by Candicepan** [comment]
> 基分类器：决策树、逻辑回归、SVC、KNeighborsClassifier、RandomForestClassifier、glm。adaboost本身不涉及优化器

因一直未提交相应 PR ，故该任务回收～

**Comment by Yeekin-GYJ** [comment]
该任务与 [spu #254](https://github.com/secretflow/spu/issues/254)、[spu #258](https://github.com/secretflow/spu/issues/258) 为「开源之夏 2024」[基于 SPU 实现 tree-based 分类算法与分位数回归算法](https://summer-ospp.ac.cn/org/prodetail/24e430452?list=org&navpage=org)的项目课题，不可单独认领。具体认领方式请遵循「开源之夏 2024」活动规则～详情查看：https://summer-ospp.ac.cn/help/student/
