### ISSUE TITLE
pip install not found

### ISSUE THREAD

**Issue by fffmath** [secretflow/spu#269]
### Issue Type

Build/Install

### Modules Involved

Documentation/Tutorial/Example

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

spu 0.3.2b12

### Current Behavior?

A bug happened!
![image](https://github.com/secretflow/spu/assets/58581109/5b9d2c32-d51e-47c1-b348-7f99b02e0982)

<img width="1099" alt="image" src="https://github.com/secretflow/spu/assets/58581109/08131986-5f8f-4353-a44f-86a4fda634c4">

找不到0.3.2b12

### Standalone code to reproduce the issue

```Python
pip install spu==0.3.2b12
```

**Comment by Chrisdehe** [comment]
hi，@fffmath 
进入到python环境后再执行pip
conda activate 环境名

**Comment by anakinxc** [comment]
Hi @fffmath 

从 error log 上来看，基本上是你的 python 版本不是 3.8

对于 3.9 3.10 3.11，spu 是从 0.3.3b0才开始提供 pip 包的

**Comment by fffmath** [comment]
是的，可以了，我conda 创建了python3.8就可以了，实际上我是报错RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.，准备降spu版本试一试，刚刚按照操作下载了spu 0.3.2b12然而还是用不了，可能要尝试换个windwos电脑了

**Comment by anakinxc** [comment]
> 是的，可以了，我conda 创建了python3.8就可以了，实际上我是报错RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.，准备降spu版本试一试，刚刚按照操作下载了spu 0.3.2b12然而还是用不了，可能要尝试换个windwos电脑了

请问您是在 Windows 的 vm 还是 wsl 里安装 spu 的呀？

**Comment by fffmath** [comment]
> > 是的，可以了，我conda 创建了python3.8就可以了，实际上我是报错RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.，准备降spu版本试一试，刚刚按照操作下载了spu 0.3.2b12然而还是用不了，可能要尝试换个windwos电脑了
> 
> 请问您是在 Windows 的 vm 还是 wsl 里安装 spu 的呀？

我目前用的是macbook，我是想用m1芯片的macbook运行的，但是总是报上面的错误解决不了

**Comment by anakinxc** [comment]
> > > 是的，可以了，我conda 创建了python3.8就可以了，实际上我是报错RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.，准备降spu版本试一试，刚刚按照操作下载了spu 0.3.2b12然而还是用不了，可能要尝试换个windwos电脑了
> > 
> > 
> > 请问您是在 Windows 的 vm 还是 wsl 里安装 spu 的呀？
> 
> 我目前用的是macbook，我是想用m1芯片的macbook运行的，但是总是报上面的错误解决不了

m1 请不要用 rosetta 运行 terminal
并且请安装 apple silicon 版本的 miniconda，不要安装 x64 的

**Comment by fffmath** [comment]
我是直接在

> > > > 是的，可以了，我conda 创建了python3.8就可以了，实际上我是报错RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.，准备降spu版本试一试，刚刚按照操作下载了spu 0.3.2b12然而还是用不了，可能要尝试换个windwos电脑了
> > > 
> > > 
> > > 请问您是在 Windows 的 vm 还是 wsl 里安装 spu 的呀？
> > 
> > 
> > 我目前用的是macbook，我是想用m1芯片的macbook运行的，但是总是报上面的错误解决不了
> 
> m1 请不要用 rosetta 运行 terminal 并且请安装 apple silicon 版本的 miniconda，不要安装 x64 的

我是直接在vscode下面的terminal运行的，我对 rosetta没有印象，可能并没有用 rosetta 运行 terminal。
我的anaconda的下载链接是https://repo.anaconda.com/archive/Anaconda3-2023.07-1-MacOSX-arm64.pkg，这样子有问题吗，十分感谢你的解答

**Comment by anakinxc** [comment]
请用python运行一下

```python
import platform
print(platform.machine())
```

如果你看到 x86_64 就说明 python 是运行在 rosetta 下面的

**Comment by fffmath** [comment]
确实是显示x86_64，那接下来我怎么做能不让python 运行在 rosetta 下面，另外我发现我单纯的import jax实际上就会报错，网上说jax/jaxlib降到0.3.22就可以了，我降版本也仍然报错，感谢。

**Comment by anakinxc** [comment]
> 确实是显示x86_64，那接下来我怎么做能不让python 运行在 rosetta 下面，另外我发现我单纯的import jax实际上就会报错，网上说jax/jaxlib降到0.3.22就可以了，我降版本也仍然报错，感谢。

如果你是在 vscode 的 terminal 里发现这个问题，请确认一下 vscode 是不是 apple silicon 版本的

**Comment by fffmath** [comment]
我过段时间还是用windows或者linux的机子试试吧，感谢回复，那我先close了
