### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by yongzhao-yan-postgraduate** [secretflow/spu#273]
想知道bazel与gcc的版本要求

**Comment by yongzhao-yan-postgraduate** [comment]
还有cmake与ninja的版本

**Comment by yongzhao-yan-postgraduate** [comment]
谢谢

**Comment by anakinxc** [comment]
> 想知道bazel与gcc的版本要求

HEAD 目前是 bazel 6.2.1+gcc11.3

别的依赖可以参考一下[这里](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux)

**Comment by yongzhao-yan-postgraduate** [comment]
gcc 11.2可以吗

**Comment by anakinxc** [comment]
> gcc 11.2可以吗

可以的

**Comment by anakinxc** [comment]
Follow-up in #275
