### ISSUE TITLE
执行第一行命令出现的问题

### ISSUE THREAD

**Issue by yongzhao-yan-postgraduate** [secretflow/spu#275]
bazel run //examples/cpp:simple_lr -- --dataset=examples/data/perfect_logit_b.csv --rank=1
INFO: Analyzed target //examples/cpp:simple_lr (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/yyz/.cache/bazel/_bazel_yyz/7e72642ecccae6d7cd965337ddc81649/external/com_github_google_leveldb/BUILD.bazel:61:11: Compiling util/logging.cc failed: undeclared inclusion(s) in rule '@com_github_google_leveldb//:leveldb':
this rule is missing dependency declarations for the following files included by 'util/logging.cc':
  '/usr/local/gcc-11.2/include/c++/11.2.0/cstdint'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/c++config.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/os_defines.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/cpu_defines.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/pstl/pstl_config.h'
  '/usr/local/gcc-11.2/lib/gcc/x86_64-linux-gnu/11.2.0/include/stdint.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cstdio'
  '/usr/local/gcc-11.2/lib/gcc/x86_64-linux-gnu/11.2.0/include/stddef.h'
  '/usr/local/gcc-11.2/lib/gcc/x86_64-linux-gnu/11.2.0/include/stdarg.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/string'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stringfwd.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/memoryfwd.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/char_traits.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_algobase.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/functexcept.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/exception_defines.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/cpp_type_traits.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/type_traits.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/numeric_traits.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_pair.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/move.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/type_traits'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_iterator_base_types.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_iterator_base_funcs.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/concept_check.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/debug/assertions.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_iterator.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/ptr_traits.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/debug/debug.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/predefined_ops.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/postypes.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cwchar'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/allocator.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/c++allocator.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/new_allocator.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/new'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/exception.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/localefwd.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/c++locale.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/clocale'
  '/usr/local/gcc-11.2/include/c++/11.2.0/iosfwd'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cctype'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/ostream_insert.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/cxxabi_forced.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_function.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/backward/binders.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/range_access.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/initializer_list'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/basic_string.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/atomicity.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/gthr.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/gthr-default.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/atomic_word.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/alloc_traits.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/alloc_traits.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_construct.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/string_view'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/functional_hash.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/hash_bytes.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/string_view.tcc'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/string_conversions.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cstdlib'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/std_abs.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cerrno'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/charconv.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/basic_string.tcc'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cassert'
  '/usr/local/gcc-11.2/include/c++/11.2.0/condition_variable'
  '/usr/local/gcc-11.2/include/c++/11.2.0/chrono'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ratio'
  '/usr/local/gcc-11.2/include/c++/11.2.0/limits'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ctime'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/parse_numbers.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/std_mutex.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/system_error'
  '/usr/local/gcc-11.2/include/c++/11.2.0/x86_64-linux-gnu/bits/error_constants.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/stdexcept'
  '/usr/local/gcc-11.2/include/c++/11.2.0/exception'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/exception_ptr.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/cxxabi_init_exception.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/typeinfo'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/nested_exception.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/unique_lock.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/shared_ptr.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/shared_ptr_base.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/allocated_ptr.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/refwrap.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/invoke.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/unique_ptr.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/utility'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_relops.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/tuple'
  '/usr/local/gcc-11.2/include/c++/11.2.0/array'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/uses_allocator.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/aligned_buffer.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/ext/concurrence.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cstddef'
  '/usr/local/gcc-11.2/include/c++/11.2.0/mutex'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cstdarg'
  '/usr/local/gcc-11.2/include/c++/11.2.0/vector'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_uninitialized.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_vector.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_bvector.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/vector.tcc'
  '/usr/local/gcc-11.2/include/c++/11.2.0/algorithm'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_algo.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/algorithmfwd.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_heap.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/stl_tempbuf.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/uniform_int_dist.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/pstl/glue_algorithm_defs.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/functional'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/std_function.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/unordered_map'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/hashtable.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/hashtable_policy.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/node_handle.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/unordered_map.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/bits/erase_if.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/pstl/execution_defs.h'
  '/usr/local/gcc-11.2/include/c++/11.2.0/cstring'
Target //examples/cpp:simple_lr failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.966s, Critical Path: 0.70s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target

**Comment by yongzhao-yan-postgraduate** [comment]
不太理解是环境出问题了吗

**Comment by anakinxc** [comment]
请问您 gcc11.2 是怎么安装的

**Comment by yongzhao-yan-postgraduate** [comment]
从官方下的安装包

**Comment by anakinxc** [comment]
> 从官方下的安装包

麻烦用包管理器安装。。

**Comment by yongzhao-yan-postgraduate** [comment]
编译过程中出现了如下错误
bazel run //examples/cpp:simple_in_memory_psi -- --rank=0
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1936bb81aafdbb3b4c9770a24fc77ba07669bd19.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/08a6b6ecfc7cce7d0c8388fe7a9c73352467091e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //examples/cpp:simple_in_memory_psi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR:/home/yyz/.cache/bazel/_bazel_yyz/7e72642ecccae6d7cd965337ddc81649/external/com_github_intel_ipp/BUILD.bazel:24:20: Foreign Cc - CMake: Building ipp failed: (Exit 1): bash failed: error executing command (from target @com_github_intel_ipp//:ipp) /bin/bash -c bazel-out/k8-fastbuild/bin/external/com_github_intel_ipp/ipp_foreign_cc/wrapper_build_script.sh

[863/8254] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_sm2_key_exchange_setup.c.o
[864/8254] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_sm2_key_exchange_get_size.c.o
[865/8254] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_sm2_key_exchange_init.c.o
[866/8254] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_sm2_message_representation.c.o
[867/8254] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_sm2_user_id_hash.c.o
[868/8254] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_sm2_stuff.c.o
[869/8254] Building C object sources/ippcp/CMakeFiles/ippcp_s_m7.dir/__/__/c_sources/m7/c_intel64/m7_sm2_key_exchange_shared_key.c.o
ninja: build stopped: subcommand failed.
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-fastbuild/bin/external/com_github_intel_ipp/ipp_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-fastbuild/bin/external/com_github_intel_ipp/ipp_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-fastbuild/bin/external/com_github_intel_ipp/ipp_foreign_cc/CMake.log

Target //examples/cpp:simple_in_memory_psi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 60.493s, Critical Path: 60.07s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target

**Comment by anakinxc** [comment]
`ninja: build stopped: subcommand failed.`

请安装 ninja build

**Comment by yongzhao-yan-postgraduate** [comment]
安装了ninja还是不能编译

**Comment by yongzhao-yan-postgraduate** [comment]
已经解决了谢谢
