### ISSUE TITLE
How to reduce the time cost of networking round in SPU

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/spu#28]
Hi,
There are several operations which need at least `log(k)` networking rounds, and is hard to be parallelized, such as `carry-out` circuit. I think there exists time cost everytime you call the networking interface to broadcast the secret shares.
I'm wondering, when dealing with big dataset, how to reduce the time cost on this? Does `bRPC` can help to resolve the problem?

**Comment by anakinxc** [comment]
> Hi, There are several operations which need at least `log(k)` networking rounds, and is hard to be parallelized, such as `carry-out` circuit. I think there exists time cost everytime you call the networking interface to broadcast the secret shares. I'm wondering, when dealing with big dataset, how to reduce the time cost on this? Does `bRPC` can help to resolve the problem?

Hi BeStrongok,

bRPC can help a little bit here through async send chunks. You can check the [code](https://github.com/secretflow/yasl/blob/dc3fbcd66ec4f417fa053fc44be0d1eaeaef05a5/yasl/link/transport/channel_brpc.cc#L342) here.

But in general, optimize operations with networking is something we would like to do in the future.

Best

**Comment by BeStrongok** [comment]
> > Hi, There are several operations which need at least `log(k)` networking rounds, and is hard to be parallelized, such as `carry-out` circuit. I think there exists time cost everytime you call the networking interface to broadcast the secret shares. I'm wondering, when dealing with big dataset, how to reduce the time cost on this? Does `bRPC` can help to resolve the problem?
> 
> Hi BeStrongok,
> 
> bRPC can help a little bit here through async send chunks. You can check the [code](https://github.com/secretflow/yasl/blob/dc3fbcd66ec4f417fa053fc44be0d1eaeaef05a5/yasl/link/transport/channel_brpc.cc#L342) here.
> 
> But in general, optimize operations with networking is something we would like to do in the future.
> 
> Best

Thanks for your helpful reply :). 
I have another question:
For example, you implement `mul` op in SPU VM, this operation needs one communication round. When dealing with element-wise multiplication on vector of length 10, are you call networking interface 10 times, or do local computation in batches and just call networking interface only once?

**Comment by anakinxc** [comment]
> > > Hi, There are several operations which need at least `log(k)` networking rounds, and is hard to be parallelized, such as `carry-out` circuit. I think there exists time cost everytime you call the networking interface to broadcast the secret shares. I'm wondering, when dealing with big dataset, how to reduce the time cost on this? Does `bRPC` can help to resolve the problem?
> > 
> > 
> > Hi BeStrongok,
> > bRPC can help a little bit here through async send chunks. You can check the [code](https://github.com/secretflow/yasl/blob/dc3fbcd66ec4f417fa053fc44be0d1eaeaef05a5/yasl/link/transport/channel_brpc.cc#L342) here.
> > But in general, optimize operations with networking is something we would like to do in the future.
> > Best
> 
> Thanks for your helpful reply :). I have another question: For example, you implement `mul` op in SPU VM, this operation needs one communication round. When dealing with element-wise multiplication on vector of length 10, are you call networking interface 10 times, or do local computation in batches and just call networking interface only once?

Hi BeStrongok,

Just once, ABY3's mul implementation is [here](https://github.com/secretflow/spu/blob/626402dcf666f4695d81cd6de20626d9727f0096/spu/mpc/aby3/arithmetic.cc#L272).

**Comment by BeStrongok** [comment]
> > > > Hi, There are several operations which need at least `log(k)` networking rounds, and is hard to be parallelized, such as `carry-out` circuit. I think there exists time cost everytime you call the networking interface to broadcast the secret shares. I'm wondering, when dealing with big dataset, how to reduce the time cost on this? Does `bRPC` can help to resolve the problem?
> > > 
> > > 
> > > Hi BeStrongok,
> > > bRPC can help a little bit here through async send chunks. You can check the [code](https://github.com/secretflow/yasl/blob/dc3fbcd66ec4f417fa053fc44be0d1eaeaef05a5/yasl/link/transport/channel_brpc.cc#L342) here.
> > > But in general, optimize operations with networking is something we would like to do in the future.
> > > Best
> > 
> > 
> > Thanks for your helpful reply :). I have another question: For example, you implement `mul` op in SPU VM, this operation needs one communication round. When dealing with element-wise multiplication on vector of length 10, are you call networking interface 10 times, or do local computation in batches and just call networking interface only once?
> 
> Hi BeStrongok,
> 
> Just once, ABY3's mul implementation is [here](https://github.com/secretflow/spu/blob/626402dcf666f4695d81cd6de20626d9727f0096/spu/mpc/aby3/arithmetic.cc#L272).

Thanks!

**Comment by anakinxc** [comment]
> > > > > Hi, There are several operations which need at least `log(k)` networking rounds, and is hard to be parallelized, such as `carry-out` circuit. I think there exists time cost everytime you call the networking interface to broadcast the secret shares. I'm wondering, when dealing with big dataset, how to reduce the time cost on this? Does `bRPC` can help to resolve the problem?
> > > > 
> > > > 
> > > > Hi BeStrongok,
> > > > bRPC can help a little bit here through async send chunks. You can check the [code](https://github.com/secretflow/yasl/blob/dc3fbcd66ec4f417fa053fc44be0d1eaeaef05a5/yasl/link/transport/channel_brpc.cc#L342) here.
> > > > But in general, optimize operations with networking is something we would like to do in the future.
> > > > Best
> > > 
> > > 
> > > Thanks for your helpful reply :). I have another question: For example, you implement `mul` op in SPU VM, this operation needs one communication round. When dealing with element-wise multiplication on vector of length 10, are you call networking interface 10 times, or do local computation in batches and just call networking interface only once?
> > 
> > 
> > Hi BeStrongok,
> > Just once, ABY3's mul implementation is [here](https://github.com/secretflow/spu/blob/626402dcf666f4695d81cd6de20626d9727f0096/spu/mpc/aby3/arithmetic.cc#L272).
> 
> Thanks! BTW, i have't found the concrete implementation of `xor_bb` operation. @anakinxc

[Here](https://github.com/secretflow/spu/blob/626402dcf666f4695d81cd6de20626d9727f0096/spu/mpc/aby3/boolean.cc#L250)

**Comment by BeStrongok** [comment]
> > > > > > Hi, There are several operations which need at least `log(k)` networking rounds, and is hard to be parallelized, such as `carry-out` circuit. I think there exists time cost everytime you call the networking interface to broadcast the secret shares. I'm wondering, when dealing with big dataset, how to reduce the time cost on this? Does `bRPC` can help to resolve the problem?
> > > > > 
> > > > > 
> > > > > Hi BeStrongok,
> > > > > bRPC can help a little bit here through async send chunks. You can check the [code](https://github.com/secretflow/yasl/blob/dc3fbcd66ec4f417fa053fc44be0d1eaeaef05a5/yasl/link/transport/channel_brpc.cc#L342) here.
> > > > > But in general, optimize operations with networking is something we would like to do in the future.
> > > > > Best
> > > > 
> > > > 
> > > > Thanks for your helpful reply :). I have another question: For example, you implement `mul` op in SPU VM, this operation needs one communication round. When dealing with element-wise multiplication on vector of length 10, are you call networking interface 10 times, or do local computation in batches and just call networking interface only once?
> > > 
> > > 
> > > Hi BeStrongok,
> > > Just once, ABY3's mul implementation is [here](https://github.com/secretflow/spu/blob/626402dcf666f4695d81cd6de20626d9727f0096/spu/mpc/aby3/arithmetic.cc#L272).
> > 
> > 
> > Thanks! BTW, i have't found the concrete implementation of `xor_bb` operation. @anakinxc
> 
> [Here](https://github.com/secretflow/spu/blob/626402dcf666f4695d81cd6de20626d9727f0096/spu/mpc/aby3/boolean.cc#L250)

Thanks a lot! :)
