### ISSUE TITLE
[OLS]使用 SPU 实现线性回归模型

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#284]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)  https://github.com/secretflow/spu/issues/249 子任务，若对该任务感兴趣，欢迎在 https://github.com/secretflow/spu/issues/249 提交你的不同设计思路。
> 也欢迎其他开发者点击[这里](https://github.com/orgs/secretflow/discussions/741)，选择其他你感兴趣的任务，热烈欢迎社区开发者参与共建～

## 设计思路
by：[Cleveland2098](https://github.com/Cleveland2098)
实施普通最小二乘法（Ordinary Least Squares, OLS）。无需迭代，只需简单的矩阵运算，就可以快速获得结果。

## 任务介绍

- 任务名称：使用 SPU 实现线性回归模型
- 技术方向：SPU/SML
- 任务难度：热身🌟

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：实现算法的基本功能，包括：
  - 支持 fit（至少一种 eg：sgd, lbfgs, svd...），predict 
  - 提供配置是否需要拟合 bias 项，是否需要正则等基本参数
  - 支持起码一种正则方式（L2, L1, elastic...）
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性/准确性（最好有与明文 sklearn 结果的对比，可详见[参考 PR](https://github.com/secretflow/spu/pull/240)）
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 可参考明文实现：
  - [linear_model/_base](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/linear_model/_base.py#L534)
  - [linear_model/_ridge](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/linear_model/_ridge.py#L915)
-  [范例](https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py)
-  [参考 PR](https://github.com/secretflow/spu/pull/240)

## 开发须知
以下部分代码请必须增加代码注释，对对应代码模块进行说明，包括：
-  __init__函数的超参数含义
-  fit 的具体算法实现说明

**Comment by Cleveland2098** [comment]
qaq好像昨天搞错了 小小更正一下 Cleveland2098 Give it to me

**Comment by Candicepan** [comment]
> qaq好像昨天搞错了 小小更正一下 Cleveland2098 Give it to me

hello～因任务认领后一直没有进展，故本任务先行回收了哈～如果对隐语社区的贡献感兴趣可以再次认领哈～感谢你的隐语社区的支持
