### ISSUE TITLE
[Perceptron-sgd]使用 SPU 实现感知机(perceptron)算法

### ISSUE THREAD

**Issue by Candicepan** [secretflow/spu#285]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741) [使用 SPU 实现感知机(perceptron)算法](https://github.com/secretflow/spu/issues/250) 子任务，若对该任务感兴趣，欢迎在 https://github.com/secretflow/spu/issues/250 提交你的不同设计思路。
> 也欢迎其他开发者点击[这里](https://github.com/orgs/secretflow/discussions/741)，选择其他你感兴趣的任务，热烈欢迎社区开发者参与共建～

## 设计思路
by：[zoeStartover](https://github.com/zoeStartover)
1. 初始化感知机模型，确定是否需要正则(L1,L2,ElasticNet,None)，是否需要拟合bias项等基本参数（参照sklearn）；输入训练集X,Y = (x_i,y_i)，优化目的是最小化-sum(y_i(w*x_i+b))，每一圈使用随机梯度下降法(SGD)更新参数w,b，w=w+η * y_i * x_i，b=b+ η * y_i，其中可选择的正则化方法包括L1,L2,ElasticNet(L1+L2)。
2. fit方法：训练感知机模型，输入训练集对X,Y = (x_i,y_i)，若某点计算为误分类点，更新参数w和b，迭代上述过程至max_iter；
3. predict方法：输入待预测样本x，输出预测结果y=sign(w*x+b)。

## 任务介绍

- 任务名称：使用 SPU 实现感知机(perceptron)算法
- 技术方向：SPU/SML
- 任务难度：热身🌟

## 详细要求
- 安全性（尽量少 reveal）
- 功能性：实现算法的基本功能，包括：
  - 支持 fit，predict
  - 提供配置是否需要拟合 bias 项，是否需要正则等基本参数
  - 支持起码一种正则方式（L2, L1, elastic...）
- 收敛性：包含 simulator 跑出的实验数据并且证明收敛性/准确性（最好有与明文 sklearn 结果的对比，可详见[参考 PR](https://github.com/secretflow/spu/pull/240)）
- 正确性：请确保提交的代码内容为可以直接运行的
- 代码规范：Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- 提交说明：关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml
- 特殊说明：若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明

## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法

## 操作说明
- 操作指引：https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- 可参考明文实现：[linear_model/_perceptron](https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/linear_model/_perceptron.py#L9)
-  [范例](https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py)
-  [参考 PR](https://github.com/secretflow/spu/pull/240)

## 认领说明
本任务可有多种实现方式，故支持一个任务有多位开发者进行认领，请在认领任务后，在该 issue 下 comment 你的具体设计思路。

## 开发须知
以下部分代码请必须增加代码注释，对对应代码模块进行说明，包括：
-  __init__函数的超参数含义
-  fit 的具体算法实现说明

**Comment by zoeStartover** [comment]
zoeStartover Give it to me

**Comment by zoeStartover** [comment]
1. 已使用jax实现perceptron的fit,predict（包含正则，是否需要拟合bias等多个参数）；
2. 使用鸢尾花数据集（100 samples）与sklearn对比准确率差1%；
3. 已使用 black+isort 进行格式化。
