### ISSUE TITLE
Is this drawing about SPU correct?

### ISSUE THREAD

**Issue by prayforwind** [secretflow/spu#286]
It is my personal view about SPU ecosystem.
Please point out any mistake, thanks!

![spu_cognition](https://github.com/secretflow/spu/assets/51848303/60f345d9-22d9-41bd-8d52-b083c07dc73e)

**Comment by rivertalk** [comment]
Hi @prayforwind,
Nice picture, you are almost correct, except

![image](https://github.com/secretflow/spu/assets/103552262/84bbc415-195d-48b0-bc3f-71886a09ef87)
mhlo to pphlo is currently done by libspu/compiler

Thanks,
Jin

**Comment by anakinxc** [comment]
Hi @prayforwind,

Thanks for drawing this graph :D

In addition to what @rivertalk pointed out,

* The code that compiles JAX to XLA is in spu/utils/frontend.py, both SPU demo & SF JAX uses it, rayfed & ppd are just distributed frameworks.
* SCQL engine, at this point, directly goes to HAL layer.
* PSI/PIR is not part of HAL technically.

Best
~Yancheng

**Comment by prayforwind** [comment]
Thanks for your corrections!

**Comment by prayforwind** [comment]
![spu-cog](https://github.com/secretflow/spu/assets/51848303/478dd027-7376-42cc-b747-17189b193fdd)

```dot
digraph SPU {
    //splines="FALSE";
    labelloc="b"
    label="\nSPU"
    pad="0.2"
    fontsize=20
    fontname="consolas"
    node[fontsize=10]
    edge[arrowsize="0.5", fontsize=8, labelfontname="consolas"]

    demopy[label="(py) demo JAX", shape="plain"]
    sfpy[label="(py) SF JAX", shape="plain"]
    xla[label="(XLA)", shape="house"]
    mhlo[label="(mhlo)", shape="box"]
    pphlo[label="(pphlo)", shape="box"]
    hal[label="(HAL)\nmpc", shape="box"]
    pir[shape="box"]
    psi[shape="box"]
    scqlsql[label="(scql.SQL)", shape="cylinder"]
    dag[label="Execution Graph", shape="cylinder"]

    demopy -> xla:nw [label="spu/utils", color=grey]
    sfpy -> xla:ne [label="secretflow + rayfed", color=green]
    xla -> mhlo [label="SPU\nspu/utils/frontend.py", color=red]
    mhlo -> pphlo:n [label="SPU\nlibspu/compiler", color=red]
    pphlo -> hal:w [label="SPU\nlibspu/kernel/hlo", color=red]
    scqlsql -> dag [label="SCDB\n...", color=blue]
    dag:w -> hal:e [label="SCQLEngine\napi/engine.proto", color=blue]
    dag -> pir [label="SCQLEngine\n...", color=blue]
    dag:e -> psi [label="SCQLEngine\n...", color=blue]

    { rank=same; scqlsql; demopy; sfpy};
    { rank=same; hal; pir; psi};
}
```
