### ISSUE TITLE
数据发送需要什么api

### ISSUE THREAD

**Issue by yongzhao-yan-postgraduate** [secretflow/spu#296]
供应方与需求方互相发送数据可以调用哪些api

**Comment by warriorpaw** [comment]
首先，SPU是一个多方共同组成的计算设备，进行密态协议计算，不负责数据的传输。你需要更上层的SF组件，文档在https://www.secretflow.org.cn/，建议先阅读文档了解隐私保护计算场景下数据提供方、计算参与方、密态设备等概念。

其次，如果你的需求只是把一份明文数据从A传输到B，不涉及隐私机器学习相关计算建模等，那么SF可能并不适用于你的场景。

**Comment by yongzhao-yan-postgraduate** [comment]
none
