### ISSUE TITLE
两方同时终端bazel run需要修改什么参数

### ISSUE THREAD

**Issue by yongzhao-yan-postgraduate** [secretflow/spu#304]
在example中同时bazel run是否需要修改ip地址、路径等参数

**Comment by 6fj** [comment]
hi @yongzhao-yan-postgraduate 

你说的是那个example？

**Comment by tpppppub** [comment]
Hi @yongzhao-yan-postgraduate ，需要修改 ip 地址，可以参考这个文档 https://github.com/secretflow/spu/tree/atc23_ae#35-configure-spu-cluster

**Comment by yongzhao-yan-postgraduate** [comment]
ok 谢谢
