### ISSUE TITLE
直接执行bazel run命令的结果，需要怎么修改

### ISSUE THREAD

**Issue by yongzhao-yan** [secretflow/spu#305]
INFO: Found 1 target...
Target //examples/cpp:simple_psi up-to-date:
  bazel-bin/examples/cpp/simple_psi
INFO: Elapsed time: 0.398s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/examples/cpp/simple_psi -rank 1 -protocol 1 -in_path examples/data/psi_2.csv -field_names id -out_path /tmp/p2.out
terminate called after throwing an instance of 'yacl::RuntimeError'
  what():  [external/yacl/yacl/link/context.cc:168] connect to mesh failed, failed to setup connection to rank=0
Aborted (core dumped)

**Comment by yongzhao-yan** [comment]
> 

需要在哪修改ip地址

**Comment by anakinxc** [comment]
> > 
> 
> 需要在哪修改ip地址

执行的时候传个[这个](https://github.com/secretflow/spu/blob/f72601927f0ce718cbc950bc12af637a5cb7f96e/examples/cpp/utils.cc#L24)参数

**Comment by yongzhao-yan-postgraduate** [comment]
ok

**Comment by yongzhao-yan-postgraduate** [comment]
ecdh_psi.cc文件中函数
void EcdhPsiContext::MaskSelf(
    const std::shared_ptr<IBatchProvider>& batch_provider) {
  size_t batch_count = 0;
  size_t item_count = 0;
  while (true) {
    // NOTE: we still need to send one batch even there is no data.
    // This dummy batch is used to notify peer the end of data stream.
    auto batch_items = batch_provider->ReadNextBatch(options_.batch_size);
    std::vector<std::string> masked_items;
    if (!batch_items.empty()) {
      masked_items = Mask(options_.ecc_cryptor,
                          HashInputs(options_.ecc_cryptor, batch_items));
    }
    // Send x^a.
    const auto tag = fmt::format("ECDHPSI:X^A:{}", batch_count);
    SendBatch(masked_items, batch_count, tag);
    if (batch_items.empty()) {
      SPDLOG_INFO("MaskSelf:{}--finished, batch_count={}, self_item_count={}",
                  options_.link_ctx->Id(), batch_count, item_count);
      if (options_.statistics) {
        options_.statistics->self_item_count = item_count;
      }
      break;
    }
    item_count += batch_items.size();
    ++batch_count;
  }
}
中的Mask函数在哪个文件中

**Comment by zhanglei486** [comment]
[libspu/psi/cryptor/ecc_cryptor.h/cc](https://github.com/secretflow/spu/blob/main/libspu/psi/cryptor/ecc_cryptor.h#L70C1-L70C1)

**Comment by yongzhao-yan-postgraduate** [comment]
ecdh_psi方法中可以传输二维数据吗，例如vector<vector<unsigned char>>数据

**Comment by zhanglei486** [comment]
> ecdh_psi方法中可以传输二维数据吗，例如vector<vector>数据

void RunEcdhPsi(const EcdhPsiOptions& options,
                const std::shared_ptr<IBatchProvider>& batch_provider,
                const std::shared_ptr<ICipherStore>& cipher_store);
RunEcdhPsi数据输入的参数是IBatchProvider，可以根据自己的数据类型重载IBatchProvider的相应的接口，来支持vector<vector>数据 类型，可以参考MemoryBatchProvider的实现。

https://github.com/secretflow/spu/blob/main/libspu/psi/core/ecdh_psi.h#L141

https://github.com/secretflow/spu/blob/main/libspu/psi/utils/batch_provider.h#L31

**Comment by yongzhao-yan-postgraduate** [comment]
PSI算法是在命令行接口传入数据并在通道中完成求交计算等操作吗

**Comment by yongzhao-yan-postgraduate** [comment]
您好，有没有yacl::link::Context link_ctx  ,  link_ctx->SendAsyncThrottled()这个函数的定义

**Comment by yongzhao-yan-postgraduate** [comment]
SendAsyncThrottled()函数可以不用batch传输吗
