### ISSUE TITLE
Does SPU Compiler supports dynamic shape?

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/spu#309]
Hi, SPU Team：
Does SPU Compiler supports dynamic shape? Which means that the code don't need to JIT compile when seeing new input shapes.

**Comment by anakinxc** [comment]
> Hi, SPU Team： Does SPU Compiler supports dynamic shape? Which means that the code don't need to JIT compile when seeing new input shapes.

Hi @BeStrongok 

We do not support dynamic shape at this point.

For our typical use cases, compilation time is far from something significant. Compare with the complexity of supporting dynamic shape, like a runtime shape inference engine, the gain is usually marginal.

Also I think jax.jit still also does not support dynamic shape (correct me if I'm wrong)

Best
~Yancheng

**Comment by BeStrongok** [comment]
> > Hi, SPU Team： Does SPU Compiler supports dynamic shape? Which means that the code don't need to JIT compile when seeing new input shapes.
> 
> Hi @BeStrongok
> 
> We do not support dynamic shape at this point.
> 
> For our typical use cases, compilation time is far from something significant. Compare with the complexity of supporting dynamic shape, like a runtime shape inference engine, the gain is usually marginal.
> 
> Also I think jax.jit still also does not support dynamic shape (correct me if I'm wrong)
> 
> Best ~Yancheng

Thank you for your answer, you're right. There are more questions i want to cimmunicate with you. :P
1) Does the static shape is required if we want to do some compilation optimization? (such as Loop unrolling, Fusion and so on）
2) Dose SPU Compiler supports these optimization currently? If supports, these optimization is really fast within the compilation time?
The reason i want to ask these questions is that i noticed that PyTorch 2.0 includes a new feature which called [TORCHDYNAMO](https://pytorch.org/docs/stable/dynamo/index.html) and i'm wondering the difference between SPU Compiler and this one.

**Comment by BeStrongok** [comment]
> > > > Hi, SPU Team： Does SPU Compiler supports dynamic shape? Which means that the code don't need to JIT compile when seeing new input shapes.
> > > 
> > > 
> > > Hi @BeStrongok
> > > We do not support dynamic shape at this point.
> > > For our typical use cases, compilation time is far from something significant. Compare with the complexity of supporting dynamic shape, like a runtime shape inference engine, the gain is usually marginal.
> > > Also I think jax.jit still also does not support dynamic shape (correct me if I'm wrong)
> > > Best ~Yancheng
> > 
> > 
> > Thank you for your answer, you're right. There are more questions i want to cimmunicate with you. :P
> > 
> > * Does the static shape is required if we want to do some compilation optimization? (such as Loop unrolling, Fusion and so on）
> > * Dose SPU Compiler supports these optimization currently? If supports, these optimization is really fast within the compilation time?
> > 
> > The reason i want to ask these questions is that i noticed that PyTorch 2.0 includes a new feature which called [TORCHDYNAMO](https://pytorch.org/docs/stable/dynamo/index.html) and i'm wondering the difference between SPU Compiler and this one.
> 
> Good questions.
> 
> Most of the loop optimizations are fine with dynamic size. For example the one you mentioned loop unrolling
> 
> ```c
> for (size_t idx = 0; idx < N; ++idx) {
>   dothings(x[idx]);
> }
> ```
> 
> Can unroll as
> 
> ```c
> size_t idx = 0;
> for (; idx < N; idx += 4) {
>   dothings(x[idx]);
>   dothings(x[idx+1]);
>   dothings(x[idx+2]);
>   dothings(x[idx+3]);
> }
> 
> // trailing
> for (; idx < N; ++idx) {
>   dothings(x[idx]);
> }
> ```
> 
> The same thing apply to fusion as well
> 
> ```c
> for (size_t idx = 0; idx < x.size(); ++idx) {
>   dothings0(x[idx]);
> }
> for (size_t idx = 0; idx < x.size(); ++idx) {
>   dothings1(x[idx]);
> }
> ```
> 
> Can fuse into
> 
> ```c
> for (size_t idx = 0; idx < x.size(); ++idx) {
>   dothings0(x[idx]);
>   dothings1(x[idx]);
> }
> ```
> 
> Although static shape may enable more fuse opportunities. Performance wise, these are typically fast enough, unless one wants to do fancy [poly](https://polly.llvm.org/) kind of optimizations.
> 
> The kind of optimizations that requires static shape are buffer reuse, consider
> 
> ```
> std::array<double, 10> x= add(..);
> ...
> // x is no longer used after this point
> std::array<double, 10> y=....;
> ```
> 
> since x is no longer alive at the point y is allocated, compiler can reuse the memory that is allocated for x, which save one allocation.
> 
> Another kind of optimization is branch pruning, consider the following code:
> 
> ```c
> if (x.size() > 100) {
>    doA(x);
> } else {
>    doB(x);
> }
> ```
> 
> With static type, one of the branch can be pruned at compile time.
> 
> SPU at this point does not do lots of loop things because it's runtime is basically a TPU, which everything is a tensor.
> 
> Normally, CPU and GPU is device working with scalar, after scalarization it's full of loops, but for SPU it's not the case.
> 
> Buffer reuse for example is kind of the optimizations we want to add in the future (has some prerequisites that need to be resolved)
> 
> For TORCHDYNAMO, you can think it as jax.jit for PyTorch. SPU can be a user-defined compiler in that graph, which digest the FXGraph and compiled it to what SPU runtime can execute.
> 
> Hope this answers your questions :D
> 
> ~Yancheng

Thanks, your answer is very helpful for me.
