### ISSUE TITLE
SPU如何添加grpc头部信息

### ISSUE THREAD

**Issue by Niclouge** [secretflow/spu#335]
SPU采用了百度的brpc通信框架，在brpc_channel_protocol中可以选择将协议换为h2:grpc选项，那么如何添加grpc的头部信息？
通过查看源码，通信过程是在yacl里面，是否存在可以调用的API来添加头部信息，还是需要进一步的修改yacl的源码？

**Comment by 6fj** [comment]
Hi @Niclouge

**Comment by Niclouge** [comment]
> Hi @Niclouge
> 
> 我们内部并没有测试过h2:grpc，如果你想要尝试使用，你可能需要自行开发和测试。如果你有后续进展，欢迎和我们分享！

好的，其实之前有尝试用h2:grpc，并且成功的使用了grpc路由。后续有进展会分享！
