### ISSUE TITLE
Custom Backend-Specific Instructions

### ISSUE THREAD

**Issue by deevashwer** [secretflow/spu#344]
Hi,

The state-of-the-art works in both [2PC](https://eprint.iacr.org/2023/1147.pdf) as well as [2PC with trusted dealer (FSS)](https://eprint.iacr.org/2023/1269.pdf) use lookup tables (LUTs) as well as varying fixed-point precision to speed up non-linear computation. 
As a result, it is hard to implement them in SPU given the limited set of operations supported by the XLA (please correct me if I'm wrong). To get around this issue, custom backend-specific implementations will be needed for some of these non-linear functions.  

How hard is it to add a custom backend-specific instruction to SPU, let's say, for GeLU?  
It'll be helpful if there's already an example of how such an instruction can be added. Since some of the authors on CipherGPT (state-of-the-art 2PC work) are from the AntGroup, I presume that there might already be some examples from the effort to integrate the CipherGPT backend with SPU.

Thanks,
Devesh

**Comment by anakinxc** [comment]
Hi @deevashwer 

In recent updates, we added [intrinsic](https://github.com/secretflow/spu/tree/main/spu/intrinsic) supports. So technically, one can use intrinsics to workaround XLA limitations.

The behavior kind of mimic implementation of [JAX custom operations](https://jax.readthedocs.io/en/latest/Custom_Operation_for_GPUs.html). But be aware, this feature is still very advance and experimental-ish.

Feel free to give it a try and feedbacks are welcome :D 

@fionser anything to add here?

Best
~Anakin

**Comment by fionser** [comment]
@deevashwer Actually, we have not implemented CipherGPT in SPU yet. 

To dispatch a customized MPC protocol, currently even for us, we need 
the `intrinsic` supports + the Python context hijack trick. 

Basically,

1. Write your back-end Cpp protocol and add a dispatch path [here](https://github.com/secretflow/spu/blob/main/libspu/device/pphlo/pphlo_intrinsic_executor.cc#L23)

```cpp
std::vector<Value> intrinsic_dispatcher(SPUContext* ctx, llvm::StringRef name,
                                        absl::Span<const Value> inputs) {
  namespace skh = spu::kernel::hal;
  if (name == "f_silu") {
    SPU_ENFORCE(inputs.size() == 1 && inputs[0].isFxp());
    return {skh::intrinsic::nn::f_silu(ctx, inputs[0])};
  }
  ....
 
}
```

The below show some possible way for implementing  a cpp back-end for SiLU

```cpp
#include "libspu/core/prelude.h"
#include "libspu/kernel/hal/constants.h"
#include "libspu/kernel/hal/fxp_approx.h"
#include "libspu/kernel/hal/prot_wrapper.h"
#include "libspu/kernel/hal/ring.h"
Value f_silu(SPUContext* ctx, const Value& x) {
  SPU_ENFORCE(x.isFxp());
  SPU_TRACE_HAL_LEAF(ctx, x);
  const auto ONE = _constant(ctx, 1, x.shape());
  const auto True = _and(ctx, ONE, ONE);
  const auto pivot0 = constant(ctx, -8.0F, x.dtype(), x.shape());
  const auto pivot1 = constant(ctx, -4.0F, x.dtype(), x.shape());
  const auto pivot2 = constant(ctx, 4.0F, x.dtype(), x.shape());

  const auto& b1 = f_less(ctx, x, pivot1);                 // x < -4
  const auto b2 = _xor(ctx, f_less(ctx, x, pivot2), ONE);  // x >= 4
  auto b3 = _xor(ctx, True, _xor(ctx, b1, b2));            // x in  [-4.0, 4)
  const auto& b0 = f_less(ctx, x, pivot0);                 // x < -8
  auto b4 = _xor(ctx, b0, b1);                             // x in [-8, -4.0)

  // seg1 = a[2] * x^2 + a[1] * x + a[0]
  // seg2 = b[6] * x^6 + b[4] * x^4 + b[2] * x^2 + b[1] * x + b[0]
  std::vector<float> a_coeffs = {-0.3067541139982155, -0.0819767021525476,
                                 -0.0055465625580307};

  std::vector<float> b_coeffs = {
      0.0085064025895951, 0.5, 0.2281430841728270, 0.0,
      -0.011113046708173, 0.0, 0.0002743776353465};

  const float scale = 1L << ctx->getFxpBits();
  auto x2 = f_square(ctx, x);
  auto x4 = f_square(ctx, x2);
  auto x6 = f_square(ctx, f_mul(ctx, x, x2));

  auto seg1_2 = _mul(ctx, x2, constant(ctx, a_coeffs[2], x.dtype(), x.shape()));
  auto seg1_1 = _mul(ctx, x, constant(ctx, a_coeffs[1], x.dtype(), x.shape()));
  auto seg1_0 = constant(ctx, a_coeffs[0] * scale, x.dtype(), x.shape());

  auto seg2_6 = _mul(ctx, x6, constant(ctx, b_coeffs[6], x.dtype(), x.shape()));
  auto seg2_4 = _mul(ctx, x4, constant(ctx, b_coeffs[4], x.dtype(), x.shape()));
  auto seg2_2 = _mul(ctx, x2, constant(ctx, b_coeffs[2], x.dtype(), x.shape()));
  auto seg2_1 = _mul(ctx, x, constant(ctx, b_coeffs[1], x.dtype(), x.shape()));
  auto seg2_0 = constant(ctx, b_coeffs[0] * scale, x.dtype(), x.shape());

  auto seg2 =
      _trunc(ctx, _add(ctx, seg2_0,
                       _add(ctx, seg2_1,
                            _add(ctx, seg2_2, _add(ctx, seg2_4, seg2_6)))))
          .setDtype(x.dtype());

  auto seg1 = _trunc(ctx, _add(ctx, seg1_2, _add(ctx, seg1_0, seg1_1)))
                  .setDtype(x.dtype());

  auto ret = _mul(ctx, b2, x);
  ret = _add(ctx, ret, _mul(ctx, b4, seg1));
  ret = _add(ctx, ret, _mul(ctx, b3, seg2));
  return ret.setDtype(x.dtype());
}
```

3. Add a python intrinsic caller using the [script](https://github.com/secretflow/spu/blob/main/spu/intrinsic/README.md)
For instance `python ./add_new_intrinsic.py f_silu` 

4. hijack your target function (e.g., gelu) following the [llama-7b example](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_llama7b/flax_llama7b.py#L86). But now we just call  the intrinsic like `return intrinsic.f_silu(x)`

**Comment by fionser** [comment]
So if you want LUT or other primitives; you might need to handle the MPC context (e.g. OT or other stateful cryptographic) by your self. Basically, we store these `stateful` information in the `State` class like [Cheetah](https://github.com/secretflow/spu/blob/main/libspu/mpc/cheetah/state.h#L38). You can access these states by first registering [them](https://github.com/secretflow/spu/blob/main/libspu/mpc/cheetah/protocol.cc#L44); then using the templaed `getState<Z2kState>()` method in the `SPUContext` to access them.

**Comment by fionser** [comment]
Also the various secret share width might be a headache ....
