### ISSUE TITLE
PSI Benchmark 测试报告疑问

### ISSUE THREAD

**Issue by guolanting** [secretflow/spu#347]
![image](https://github.com/secretflow/spu/assets/62043931/f4717316-8f0b-44a8-ba64-9555eb29b83e)
这个测试报告数据是不是有问题？ https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/developer/benchmark/psi_benchmark 。 1亿对1亿，CPU核数增加，对ecdh-psi没有影响，反而CPU最差的稍微快一点。另外根据通信量的估计，ecdh-psi下，1亿对1亿，通信量有51.2Gb. 100Mb/s光传输时间也需要500s. 目前总的时间才481s。

最后即使假设上面的测试报告数据准确，也得不出下图的结论吧：
![image](https://github.com/secretflow/spu/assets/62043931/333e6995-b90a-4e7f-ac54-b63b68126727)

**Comment by zhanglei486** [comment]
benchmark报告里面提到了目前限速是tc qdisc来设置的，可能会不是很精确，会有一些误差。
100Mbps下带宽是瓶颈，核数影响不大，
上面提到疑问的481s是8c16g LAN环境的性能

**Comment by guolanting** [comment]
ecdh-psi 三种机器配置下100Mb/s的运行时间都不到500s, 这个是因为tc qdisc 不准确导致的？
