### ISSUE TITLE
安全性自动检测问题疑惑

### ISSUE THREAD

**Issue by SZU-czw** [secretflow/spu#348]
小白提问，大佬好，请问如下问题：

有这么一个场景

编写不安全的多方安全计算应用算法逻辑，然后发起计算任务，隐语能够识别出存在安全性或者逻辑性问题，就会终止任务。

隐语目前能支持吗？能的话  有这方面的demo吗

**Comment by 6fj** [comment]
Hi @SZU-czw 

首先，隐语（secretflow）没有这种机制。在secretflow中，除非你显示地调用sf.reveal，那么密态数据将不会被转化为明文。

其次，你这种需求其实已经内嵌在SPU和SCQL等项目中。比如在SPU中，你只需要提供算法和输入的明密文标签，SPU compiler将会编译出相对应的IR；在SCQL中，你只要预先设置参与运算各column的CCL（column control list），你的query将会被解析成合理的算子来保障CCL的限制。

最后，然后你所说的逻辑性问题，这是个比较宽泛的问题，因为我们很难去定义什么是逻辑性问题。

欢迎继续讨论，感谢！
