### ISSUE TITLE
怎么修改执行的PSI算法类型

### ISSUE THREAD

**Issue by yongzhao-yan-postgraduate** [secretflow/spu#354]
修改BucketPsiConfig里的psi_type()

**Comment by Chrisdehe** [comment]
@yongzhao-yan-postgraduate 
我们支持多种psi_type协议，详情请见：
https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/psi_config#psitype

**Comment by zhanglei486** [comment]
可以参考psi 的示例代码：
https://github.com/secretflow/spu/blob/main/examples/cpp/simple_psi.cc#L71
https://github.com/secretflow/spu/blob/main/examples/python/psi/simple_psi.py#L73

**Comment by yongzhao-yan-postgraduate** [comment]
额，就是我在psi.proto中新添加了一种协议，怎么将新的协议导入BucketPsiConfig中的psi_type()，不是很懂

**Comment by zhanglei486** [comment]
> 额，就是我在psi.proto中新添加了一种协议，怎么将新的协议导入BucketPsiConfig中的psi_type()，不是很懂

psi.proto添加了一种协议，通过protobuf解析生成对应的c++代码，BucketPsiConfig已经可以支持新的psi 类型了
只是标识类型支持，对应协议实现的调用还需要在bucket_psi.h/bucket_psi.cc中添加支持代码。

**Comment by yongzhao-yan-postgraduate** [comment]
好的谢谢
