### ISSUE TITLE
[Bug]: flax_llama7b  run failed

### ISSUE THREAD

**Issue by Daihongwei1900** [secretflow/spu#365]
### Issue Type

Documentation

### Modules Involved

Documentation/Tutorial/Example

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

main 

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.8.16

### Current Behavior?

prepared:
already download llama-7b model  &&  EasyML
![image](https://github.com/secretflow/spu/assets/34463404/ff415b60-24d8-451a-9c30-512cd7336309)

when  run shell：
   python3 -m EasyLM.scripts.convert_checkpoint --load_checkpoint='params::open_llama_7b' --output_file='path-to-LLaMMA-7B.msgpack' --streaming=False

error log:
  File "/home/zchain/mpc/spu/venv/lib/python3.8/site-packages/mlxu/utils.py", line 36, in open_file
    return open(path, mode)
IsADirectoryError: [Errno 21] Is a directory: 'open_llama_7b'

### Standalone code to reproduce the issue

```Python
please give the total operation, tks
```

**Comment by anakinxc** [comment]
@Ye-D Can you take a look?

**Comment by Ye-D** [comment]
@Daihongwei1900 "--load_checkpoint" should point to the model file, not the directory.

**Comment by Daihongwei1900** [comment]
> @Daihongwei1900 "--load_checkpoint" should point to the model file, not the directory.

Dr. Dong, I am not very familiar with the llama-7b model here. According to the screenshot I downloaded from https://huggingface.co/openlm-research/open_llama_7b, there are two bin weight files here. I also got an error when I tried. Is there any tutorial missing here?
![image](https://github.com/secretflow/spu/assets/34463404/2ba50aca-6150-4584-9a7e-d18a4088037c)

Tutorial  shell command : 
 python3 -m EasyLM.scripts.convert_checkpoint --load_checkpoint='params::path-to-LLaMA-7B[Pytroch-Version]' --output_file='path-to-LLaMMA-7B.msgpack' -- streaming=False

**Comment by Ye-D** [comment]
try this link: https://huggingface.co/openlm-research/open_llama_7b_easylm/tree/main
convert the above model into msgpack.
