### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'libspu.spu_pd2'

### ISSUE THREAD

**Issue by Handikang** [secretflow/spu#370]
### Issue Type

Build/Install

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

我直接下载的github源代码的code

### OS Platform and Distribution

windows11

### Python Version

3.9.18

### Current Behavior?

![image](https://github.com/secretflow/spu/assets/42713276/d3c01f62-fc20-4f3d-b9b1-0c9c8b03180e)
我尝试运行spu论文中的例子，发现无法找到libspu.spu_pd2模块

### Standalone code to reproduce the issue

```Python
print("A bug")
```

### Relevant log output

```Shell
Traceback (most recent call last):
  File "D:\PyCode\sputest\papertest.py", line 5, in <module>
    import spu.utils.distributed as ppd
  File "D:\PyCode\sputest\spu\__init__.py", line 18, in <module>
    from .spu_pb2 import (  # type: ignore
  File "D:\PyCode\sputest\spu\spu_pb2.py", line 1, in <module>
    from libspu.spu_pd2 import *
ModuleNotFoundError: No module named 'libspu.spu_pd2'
```

**Comment by anakinxc** [comment]
Hi @Handikang 

这里有几个问题，

1. SPU 现在不支持 Windows
2. 跑这些 example 需要通过 bazel 来先 build spu，你可以参考一下[这里](https://github.com/secretflow/spu/tree/main/examples/python/ml/stax_nn)

Best

**Comment by tpppppub** [comment]
论文里的这个参考代码可以直接看这个[例子](https://github.com/secretflow/spu/blob/main/examples/python/millionaire.py#L16C11-L16C11)

**Comment by tpppppub** [comment]
复现实验可以参考这个[文档](https://github.com/secretflow/spu/tree/atc23_ae#usenix-atc-23-artifact-evaluation)
