### ISSUE TITLE
[Feature]:PSI算法的交集数据怎么输出到指定路径

### ISSUE THREAD

**Issue by yongzhao-yan-postgraduate** [secretflow/spu#373]
### Feature Request Type

Usability

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

bazel run //examples/cpp:simple_psi -- -rank 0 -protocol 1 -in_path examples/data/psi_1.csv -field_names id -out_path /tmp/p1.out 
在执行simple_psi.cc文件时怎么将交集数据输出到命令行中的路径

### Describe features you want to add to SPU

No

### Describe features you want to add to SPU

No

**Comment by 6fj** [comment]
不太理解你的问题，能否详细说明的问题。

**Comment by yongzhao-yan-postgraduate** [comment]
就是将PSI算法的输出，输出到bazel指定的路径中

**Comment by 6fj** [comment]
请使用绝对路径。

如果仍然存在问题，请给出你在terminal中执行的指令和对应的输出结果，感谢。

**Comment by yongzhao-yan-postgraduate** [comment]
bazel run //examples/cpp:simple_temp_psi -- -rank 0 -protocol 13 -in_path examples/data/A_PSI_DATA.csv -field_names id,name,gender -out_path /examples/Alice_intersection_data.txt -parties 192.168.0.112:39875,192.168.0.111:39876
输出结果为
INFO: Running command line: bazel-bin/examples/cpp/simple_temp_psi -rank 0 -protocol 13 -in_path examples/data/A_PSI_DATA.csv -field_names id,name,gender -out_path /examples/Alice_intersection_data.txt -parties 192.168.0.112:39875,192.168.0.111:39876
[2023-10-22 17:49:06.155] [error] [simple_temp_psi.cc:94] run psi failed: [Enforce fail at libspu/psi/execute.cc:70] (ec.value() == 0). failed to create output dir=/examples for path=/examples/Alice_intersection_data.txt, reason = Permission denied
Stacktrace:
#0 spu::psi::ExecutePsi::Init()+0x46903e
#1 __libc_start_main+0x7fe9c938cc87

[2023-10-22 17:49:06.156] [warning] [channel.h:113] C

**Comment by yongzhao-yan-postgraduate** [comment]
解决了谢谢
