### ISSUE TITLE
build on macOS: dependency to 'libomp' is omitted in prerequisite.

### ISSUE THREAD

**Issue by f1ed** [secretflow/spu#38]
![image](https://user-images.githubusercontent.com/40384421/202833450-a8435487-7640-4cdc-bbd9-0372c4094da6.png)

**Comment by anakinxc** [comment]
Thanks for reporting this.

This is indeed a missing dependency on macOS. We will update build inustruction soon.

Meanwhile, please install libomp with homebrew to fix this.
