### ISSUE TITLE
增加了一个psi算法，如何高效调测

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/spu#394]
### Issue Type

Build/Install

### Modules Involved

PSI

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.5

### OS Platform and Distribution

centos7

### Python Version

3.9

### Compiler Version

gcc11

### Current Behavior?

VSCode c++小白一枚，在spu框架上增加了一个新的psi算法，每次都需要bazel build、run编译，打印日志查问题。
开发IDE：vscode
当前：在IDE的terminal bazel build，bazel run
问题：出现问题，无法在IDE中单步调测，只能打印日志
期望：debug，单步调测，请教有什么方法

### Standalone code to reproduce the issue

```Python
请教单步调测的方法
```

**Comment by daydayuphere** [comment]
没有bazel的情况下，vscode 写c++代码，只要环境上有gdb，打断点都可以的。spu用bazel做build、run的这些过程，中间怎么调试，请教

**Comment by anakinxc** [comment]
bazel build 好的二进制都在 bazel-bin/ 下面
直接用 gdb 来 run 就行

**Comment by TY-cc** [comment]
我使用bazel _build好了关于目录[/spu/spu/tests/jnp_debug.py](https://github.com/secretflow/spu/blob/main/spu/tests/jnp_debug.py)的code，并且在/spu/spu/bazel-bin/spu/tests/确实有jnp_debug文件，该文件也可以正常运行，但是当我使用gdb读取jnp_debug时，提示

> not in executable format: file format not recognized
具体截图如下
![image](https://github.com/user-attachments/assets/5dc394c4-b0a5-4b90-804c-924d11632d2c)
该问题如何解决呢？感谢~
