### ISSUE TITLE
Implementation question of cheetah protocol in SPU.

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/spu#407]
### Issue Type

Currentness/Accuracy

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

No

### Have you searched existing issues?

No

### SPU Version

0.6.0b0

### OS Platform and Distribution

Linux ubuntu 18.04

### Python Version

3.8.13

### Compiler Version

9.4.0

### Current Behavior?

Hi, 
I'm reading your code of Cheetah protocol, and find a place seems to be inconsistent with the paper.
The function [DoCompute](https://github.com/secretflow/spu/blob/e0d6144353a1419c89079dc8472a52f005a50a79/libspu/mpc/cheetah/arith/matmat_prot.cc#L575) seems dicrectly calculate the dot between plain matrix M_a of Alice and encrypted matrix (M_b)_b sended by Bob.
While the matrix M_b is scret-shared by Bob and Alice also holds a shared matrix (M_b)_a, so before calculating the  inner product i think Alice first needs to add the shares of (M_b)_a and (M_b)_b.

The corresponding part of paper is:
![image](https://github.com/secretflow/spu/assets/38127120/d2848c28-75aa-47e9-8dd2-d644ed1b59db)

Thanks~

### Standalone code to reproduce the issue

```Python
no code
```

**Comment by fionser** [comment]
- For the mul of two share, (M_a + M_b) * (v_a + v_b) = M_a * v_a + **M_b * v_a + M_a * v_b** + M_b * v_b where the bold part is computed in HE.

**Comment by BeStrongok** [comment]
> * For the mul of two share, (M_a + M_b) * (v_a + v_b) = M_a * v_a + **M_b * v_a + M_a * v_b** + M_b * v_b where the bold part is computed in HE.

Thanks. Could you point out the corresponding code of `(v_a + v_b)`？
I think server needs to get the revealed value of `v` using homomorphic addition.

**Comment by fionser** [comment]
No need to perform the adding before HE. 
We can simply do HE-mul on two shares, and then add to corresponding values locally

**Comment by BeStrongok** [comment]
> No need to perform the adding before HE. We can simply do HE-mul on two shares, and then add to corresponding values locally For example, va∗wβ,α can be computed locally by the server.

Sorry, i can't understand your what you mean.
I find the corresponding code [here](https://github.com/Alibaba-Gemini-Lab/OpenCheetah/blob/1c5cd753e641661fa72cedca34acff45a59dde22/include/gemini/cheetah/hom_fc_ss.cc#L435) in OpenCheetah, but no corresponding code in SPU.
I'm trying to use your code in my own experiment and meet an problem, if the vector of bob `$$v_a$$` is secret-shared, i get wrong result.

**Comment by fionser** [comment]
I mean, some of the computation can be done **outside** the HE box.

**Comment by BeStrongok** [comment]
> I mean, some of the computation can be done **outside** the HE box.

Thank you for your patient reply. I add the code of local shares multiplication, which is added with the result of HE-mul, and then get the correct result. Thanks again. This is indeed a good optimization method in practical implementation.

**Comment by BeStrongok** [comment]
Hi, @fionser 
May i ask you another question.
What's the difference between [ModulusUpAt](https://github.com/secretflow/spu/blob/5981fdad1adc7832f8e5cfa12ab3b36a1cfefdcb/libspu/mpc/cheetah/rlwe/modswitch_helper.cc#L91) and [CenteralizeAt](https://github.com/secretflow/spu/blob/5981fdad1adc7832f8e5cfa12ab3b36a1cfefdcb/libspu/mpc/cheetah/rlwe/modswitch_helper.cc#L164C8-L164C21).
I think they are both used to do modulus down, but `CenteralizeAt` only be used in Plaintext, is there any optimization reason for this？

**Comment by fionser** [comment]
We observe that to convert the plaintext `[0, 2^k)` to the centerlized form `[-2^k/2, 2^k/2)` can introduce a less noise when doing the ciphertext-plaintext multiplication.

**Comment by BeStrongok** [comment]
> We observe that to convert the plaintext `[0, 2^k)` to the centerlized form `[-2^k/2, 2^k/2)` can introduce a less noise when doing the ciphertext-plaintext multiplication.

Thank you for your helpful reply :)
