### ISSUE TITLE
[Feature]: BumbleBee Code

### ISSUE THREAD

**Issue by deevashwer** [secretflow/spu#411]
### Feature Request Type

Performance

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

N/A

### Describe features you want to add to SPU

Hi SPU team,

The state-of-the-art Secure 2PC Inference work, titled "BumbleBee: Secure Two-party Inference Framework for Large Transformers" links to SPU for its code. However, I don't see any references to BumbleBee in this repository. Is the code release still in progress? If so, do you have an estimate on when the code will be released?

### Describe features you want to add to SPU

N/A

**Comment by anakinxc** [comment]
@fionser

**Comment by fionser** [comment]
@deevashwer 
The matrix multiplication code in the `Cheetah` back-end is already upgraded to BumbleBee's variant.
- [API entry](https://github.com/secretflow/spu/blob/main/libspu/mpc/cheetah/arith/cheetah_dot.h#L32).
- Underlying [ciphertext interleaving](https://github.com/secretflow/spu/blob/main/libspu/mpc/cheetah/rlwe/packlwes.h) for compression.

**Comment by deevashwer** [comment]
Thanks @fionser for the quick response. Is there a branch that can be used to perform end-to-end benchmarking of the BumbleBee code?

**Comment by fionser** [comment]
Just simply replace the back-end (from `ABY3` to `CHEETAH`) in the config.json file. It should work.  The SPU front-end is designed to be back-end independent.

**Comment by fionser** [comment]
@deevashwer Just a "simple" demo on how to add new features on SPU's dispatch workflow
https://github.com/secretflow/spu/pull/433
