### ISSUE TITLE
[Bug]: 关于Max和Min，现在是希望返回输入值中的一个，而不是那一个的近似值，我们该怎么解决

### ISSUE THREAD

**Issue by zhoujunxian** [secretflow/spu#423]
### Issue Type

Performance

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

No

### Have you searched existing issues?

Yes

### SPU Version

62283664bc7d558687424e235ca6d84aaa82c29f

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.9

### Compiler Version

GCC 11.2.1

### Current Behavior?

```
spu::Value *Input(spu::SPUContext* sctx, void *val, int rank, std::string name, std::string dType)
    {
        spu::device::ColocatedIo cio(sctx);
        if ((size_t)rank == cio.getRank()) {
            if (dType == "INT") {
                cio.hostSetVar(name, *(static_cast<int *>(val)), spu::Visibility::VIS_SECRET);
            } else if (dType == "FLOAT") {
                cio.hostSetVar(name, *(static_cast<float *>(val)), spu::Visibility::VIS_SECRET);
            }
        }

        cio.sync();

        auto value = cio.deviceGetVar(name);
        spu::Value *valueCp = new spu::Value();
        if (valueCp == nullptr) {
            std::cerr << "malloc calcValue->value error." << std::endl;
            exit(1);
        }
        *valueCp = value.clone();
        return valueCp;
    }

int main(int argc, char** argv) {
  ......

  float num_g = 7.06;
  float num_h = 21.76;
  auto g = Input(sctx.get(), &num_g, 0, "g", "FLOAT");
  auto h = Input(sctx.get(), &num_h, 1, "h", "FLOAT");

  res = hal::max(sctx.get(), *g, *h);
  result = hal::dump_public_as<float>(
      sctx.get(), hlo::Cast(sctx.get(), res, spu::VIS_PUBLIC, res.dtype()));
    std::cout << "max(g,h)="<< result << std::endl;

    res = hal::min(sctx.get(), *g, *h);
      result = hal::dump_public_as<float>(
      sctx.get(), hlo::Cast(sctx.get(), res, spu::VIS_PUBLIC, res.dtype()));
    std::cout << "min(g,h)="<< result << std::endl;

}
  

```

### Standalone code to reproduce the issue

```Python
max(g,h)= 21.759998
min(g,h)= 7.059998
```

**Comment by anakinxc** [comment]
Hi @zhoujunxian 

SPU 的数值操作是 encode 到定点数的，float 到 fixed point 然后计算完再返回会有一定的数值误差

**Comment by zhoujunxian** [comment]
针对这种运算，是不是编排实现要避开调用减法？还是调用完，最后返回的时候SPU有在哪里统一处理？
比如，将max编排为max(x,y)=greater than(x,y)*x+(1-greater than(x,y))*y，而不是使用select。select(pred,x,y) = y + pred*(x-y),当pred取1时，会引入x-y的精度损失

**Comment by NJIT-BP397** [comment]
Hi @anakinxc
1.spu是否保证max(x,y）的返回值与原始输入x或y一致，而非近似值？如果是，请简单解答逻辑。
2.问题1成立的话，针对max，如果采用greater(x,y)*x+(1-greater(x,y))*y，来替换spu现在逻辑：select(greater(x,y),x,y) = y + greater(x,y)*(x-y)。是否可以避免x-y引入的精度损失，返回正确结果呢？

**Comment by tpppppub** [comment]
1. x, y 浮点数进入 spu 系统时会 encoding 成定点数，这里会引入误差，与 max 实现无关。
2. 不可以，误差不是 x-y 引入的。
3. 针对你的需求，可以求 argmax、argmin，然后在明文取原始值。

**Comment by anakinxc** [comment]
Hi @NJIT-BP397 

对于问题 1，

误差完全取决于 encode 到定点数以后误差有多大，你可以手动计算一下，定点数需要多少 bits 来准确表达 0.06 这个值
同时你也可以验证一下对于 max(6.25, 7.5) 这种可以无损 encode 的值做比较会不会有误差

**Comment by NJIT-BP397** [comment]
hi @tpppppub 
我理解意思是：
2.定点数的减法是没有误差的？
3.明文取原始值怎么理解？是指进入spu系统，encode x或y时，记录原始值，最后max返回结果，再对应解码回去原始值？

**Comment by anakinxc** [comment]
> hi @tpppppub 我理解意思是： 2.定点数的减法是没有误差的？ 3.明文取原始值怎么理解？是指进入spu系统，encode x或y时，记录原始值，最后max返回结果，再对应解码回去原始值？

2 定点数本质是整数，整数的减法是没有误差的

3 本质是实现一个[argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)，纯 c++ 可能需要写点代码，python 可以直接用 jax.numpy.argmax，用 argmax 求出 max 的 index，然后明文取值
