### ISSUE TITLE
[Feature]: Discussions about the concept of SPU compiler.

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/spu#439]
### Feature Request Type

Others

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

NO.

### Describe features you want to add to SPU

Hi, SPU Team:
I'm reading your implementation code of SPU compiler. There are few questions i want to ask:
- After lowering to PPHLO, you define an execution engine yourself instead of using MLIR's ExecutionEngine, could you tell me the reason behind this?
- The output of Operation is added to `SymbolTable`, which is a `std::unordered_map`, are they `SSA` values? If a variable is only used once during the entire program running, is there an automatic recycling mechanism to prevent this variable from continuing to occupy memory?

Thank you very much!

**Comment by anakinxc** [comment]
Hi @BeStrongok 

1. mlir ExecutionEngine assumes IR can be converted into LLVM, which pphlo cannot at this point.
2. SSA is kind of meaningless out of a scope of IR, conceptually, values in SymbolTable represents a mlir::Value which is SSA. spu Value's underlying buffer uses a std::shared_ptr to do reference counting.

**Comment by BeStrongok** [comment]
> Hi @BeStrongok
> 
> 1. mlir ExecutionEngine assumes IR can be converted into LLVM, which pphlo cannot at this point.
> 2. SSA is kind of meaningless out of a scope of IR, conceptually, values in SymbolTable represents a mlir::Value which is SSA. spu Value's underlying buffer uses a std::shared_ptr to do reference counting.

Thank you very much! Your reply is very helpful!
