### ISSUE TITLE
[Feature]: SPU或者secretflow有办法直接导入密文吗？比如已经share好了的bool共享或者算数共享

### ISSUE THREAD

**Issue by WandQ** [secretflow/spu#445]
### Feature Request Type

Usability

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

我有一批已经share好了的64位bool共享数据，明文=share1^share2。是否有办法导入已有的bool共享或者算数共享到SPU中进行计算呢？
另外，SPU实现的ABY3中FM64和FM128对整数域和小数域的支持范围是多少？

我尝试用ppd.device的方式将布尔共享share1和share2以明文的方式导入，再计算share1^share2得到新的密文，但是似乎存在很多问题。我的代码：
```
def func(x, y):
    return x^y

def main():
    # CPU plaintext version
    x = np.array(10784740297487538576)
    y = np.array(5821308811732210017)
    res = func(x, y)
    logging.info(f"\nx: {x}\ny: {y}\nres: {res}")
    
    # SPU secure version
    x_spu = ppd.device("P1")(lambda x: x)(x)
    y_spu = ppd.device("P2")(lambda x: x)(y)

    res_spu = ppd.device("SPU")(func, copts=copts)(x_spu, y_spu)
    logging.info(f"\nx: {ppd.get(x_spu)}\ny: {ppd.get(y_spu)}\nres: {ppd.get(res_spu)}")

if __name__ == "__main__":
    main()
``` 
   报错：
```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_admin/7c959d265bc04eb514a0041cd10a20af/execroot/spulib/bazel-out/darwin_arm64-opt/bin/examples/python/ir_dump/ir_dump.runfiles/spulib/examples/python/ir_dump/ir_dump.py", line 82, in <module>
    main()
  File "/private/var/tmp/_bazel_admin/7c959d265bc04eb514a0041cd10a20af/execroot/spulib/bazel-out/darwin_arm64-opt/bin/examples/python/ir_dump/ir_dump.runfiles/spulib/examples/python/ir_dump/ir_dump.py", line 71, in main
    res = func(x, y)
  File "/private/var/tmp/_bazel_admin/7c959d265bc04eb514a0041cd10a20af/execroot/spulib/bazel-out/darwin_arm64-opt/bin/examples/python/ir_dump/ir_dump.runfiles/spulib/examples/python/ir_dump/ir_dump.py", line 65, in func
    return x^y
TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
``` 
我把xy改短：
    x = np.array(10784740297)
    y = np.array(58213088117)
出错：
```
x: 10784740297
y: 58213088117
res: 64677685436
INFO:root:
x: 10784740297
y: 58213088117
res: 253175996
``` 
   

### Describe features you want to add to SPU

和其他协议产生的share能互联互通

### Describe features you want to add to SPU

A clear and concise description of any alternative solutions or features you've considered.和其他协议产生的share能互联互通

**Comment by tpppppub** [comment]
1. "我有一批已经share好了的64位bool共享数据，明文=share1^share2。是否有办法导入已有的bool共享或者算数共享到SPU中进行计算呢？"
-> 你可以先在每一方明文比特分解 64 位的 bool 分享，然后以长度为 64 的 0/1 向量传入 spu，再进一步做 element-wise 的 xor 运算。

2.  “另外，SPU实现的ABY3中FM64和FM128对整数域和小数域的支持范围是多少？”
-> 这个通过 [fxp_fraction_bits](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/runtime_config) 参数可配置

**Comment by WandQ** [comment]
> 1. "我有一批已经share好了的64位bool共享数据，明文=share1^share2。是否有办法导入已有的bool共享或者算数共享到SPU中进行计算呢？"
>    -> 你可以先在每一方明文比特分解 64 位的 bool 分享，然后以长度为 64 的 0/1 向量传入 spu，再进一步做 element-wise 的 xor 运算。
> 2. “另外，SPU实现的ABY3中FM64和FM128对整数域和小数域的支持范围是多少？”
>    -> 这个通过 [fxp_fraction_bits](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/runtime_config) 参数可配置

1.感谢回复，您的意思是先将share切分为64个比特，导入spu后逐个bit进行xor运算？可是这样计算完之后，怎么把将这64个密文重新变成一个密文呢？
2.找到了，谢谢

**Comment by tpppppub** [comment]
再逐 bit 乘 2**n 累加

**Comment by WandQ** [comment]
> 再逐 bit 乘 2**n 累加

如果是最后一位*2^63会不会又溢出了呢？

**Comment by anakinxc** [comment]
除了 @tpppppub 说的方法，目前 out of box 并没有一个非常理想的 api 来导入 share，后续我们评估一下这个需求

**Comment by anakinxc** [comment]
> > 再逐 bit 乘 2**n 累加
> 
> 如果是最后一位*2^63会不会又溢出了呢？

1bit*2^63 并不会溢出呀

**Comment by WandQ** [comment]
我的配置：
```
 "runtime_config": {
                    "protocol": "ABY3",
                    "field": "FM128",
                    "fxp_fraction_bits": 0,
                    "enable_pphlo_profile": true,
                    "enable_hal_profile": true
                }
``` 
我做了一个测试：
```
def func(x, y):
    return x*y

def main():
    # CPU plaintext version
    x = np.array(2**30)
    y = np.array(1)
    res = func(x, y)
    logging.info(f"\nx: {x}\ny: {y}\nres: {res}")
    
    # SPU secure version
    x_spu = ppd.device("P1")(lambda x: x)(x)
    y_spu = ppd.device("P2")(lambda x: x)(y)

    res_spu = ppd.device("SPU")(func, copts=copts)(x_spu, y_spu)
    logging.info(f"\nx: {ppd.get(x_spu)}\ny: {ppd.get(y_spu)}\nres: {ppd.get(res_spu)}")

if __name__ == "__main__":
    main()
``` 
在我设置x=2^30时输出：
INFO:root:
x: 1073741824
y: 1
res: 1073741824
INFO:root:
x: 1073741824
y: 1
res: 1073741824

但是当我设置x=2^31时，明文输出：2147483648，密文输出-2147483648，此时还没有越界。
当我设置x=2^32时就已经越界密文输出结果为0了。
貌似FM128最多也只能容纳32位的整数。有没有办法容纳更大一点的整数呢？是不是我的配置有问题

**Comment by WandQ** [comment]
> > > 再逐 bit 乘 2**n 累加
> > 
> > 
> > 如果是最后一位*2^63会不会又溢出了呢？
> 
> 1bit*2^63 并不会溢出呀

我测试只能乘到2**32，是不是我哪里没设置好

**Comment by tpppppub** [comment]
在 import jax 之前加上 
```python
from jax import config

config.update("jax_enable_x64", True)
```
再试试

**Comment by WandQ** [comment]
感谢回复，修改后密文输出仍然为0，程序在examples/python/ir_dump/ir_dump.py的基础上测试的，这是我的完整代码:
```
import argparse
import json
import logging
import os
from jax import config
config.update("jax_enable_x64", True)

import jax.numpy as jnp
import numpy as np

import spu.spu_pb2 as spu_pb2
import spu.utils.distributed as ppd

logging.basicConfig(level=logging.INFO)

parser = argparse.ArgumentParser(description="distributed driver.")
parser.add_argument("-c", "--config", default="examples/python/conf/3pc.json")
parser.add_argument("-d", "--dir", default="ppdump")
args = parser.parse_args()

with open(args.config, "r") as file:
    conf = json.load(file)

ppd.init(conf["nodes"], conf["devices"])


# enable dump ir to custom path
dump_path = os.path.join(os.path.expanduser("~"), args.dir)
logging.info(f"Dump path: {dump_path}")
# refer to spu.proto for more detailed configuration
copts = spu_pb2.CompilerOptions()
copts.enable_pretty_print = True
copts.pretty_print_dump_dir = dump_path
copts.xla_pp_kind = 2


def func(x, y):
    return x*y

def main():
    # CPU plaintext version
    x = jnp.array(1)
    y = jnp.array(2**32)
    res = func(x, y)
    logging.info(f"\nx: {x}\ny: {y}\nres: {res}")
    
    # SPU secure version
    x_spu = ppd.device("P1")(lambda x: x)(x)
    y_spu = ppd.device("P2")(lambda x: x)(y)

    res_spu = ppd.device("SPU")(func, copts=copts)(x_spu, y_spu)
    logging.info(f"\nx: {ppd.get(x_spu)}\ny: {ppd.get(y_spu)}\nres: {ppd.get(res_spu)}")

if __name__ == "__main__":
    main()
```

**Comment by tpppppub** [comment]
在 [nodectl.py](https://github.com/secretflow/spu/blob/main/examples/python/utils/nodectl.py) 最开始加上刚那两句，然后重新运行 nodectl 再试试。不过正如 @anakinxc  说的那样，目前没有更直接优雅的解决方案，后续会进一步评估这个需求。

**Comment by WandQ** [comment]
> 在 [nodectl.py](https://github.com/secretflow/spu/blob/main/examples/python/utils/nodectl.py) 最开始加上刚那两句，然后重新运行 nodectl 再试试。不过正如 @anakinxc 说的那样，目前没有更直接优雅的解决方案，后续会进一步评估这个需求。

可以了，感谢。不过设置之后已经可以直接支持2**63的异或了👍。
