### ISSUE TITLE
semi2k方案，水平场景下多方计算方差、标准差误差较大，是否有提高精度的方法

### ISSUE THREAD

**Issue by zhouhansheng** [secretflow/spu#446]
### Issue Type

Bug

### Source

binary

### Secretflow Version

secretflow 1.3.0.dev

### OS Platform and Distribution

生产模式

### Python version

3.8.15

### What happend and What you expected to happen.

```shell
数据：两方各10000行，[1,1000]的随机浮点数
两方数据水平拼接，联合计算中位数、平均值、方差、标准差、最大值、最小值，选取FM64和FM128分别计算，发现其方差、标准差误差都较大，请问是否有提高精度的写法？
```

### Reproduction code to reproduce the issue.

```shell
使用的联合统计计算函数：
import jax.numpy as jnp
    def statistic_fn(dataset_parties_input_list):
        data_concat = dataset_parties_input_list[0]
        for i in range(num_parties-1):
            data_concat = jnp.concatenate([data_concat, dataset_parties_input_list[i+1]],axis=0)
        return jnp.array([jnp.median(data_concat), jnp.mean(data_concat), jnp.var(data_concat), jnp.std(data_concat), jnp.max(data_concat), jnp.min(data_concat)])
```

**Comment by zhouhansheng** [comment]
> > > Hi @zhouhansheng
> > > 举个例子，改成这样
> > > ```python
> > > def statistic_fn(dataset_parties_input_list):
> > >     data_concat = jnp.concatenate(dataset_parties_input_list, axis=0)
> > >     jmedian = jnp.median(data_concat)
> > >     jmean = jnp.mean(data_concat)
> > >     jmax = jnp.max(data_concat)
> > >     jmin = jnp.min(data_concat)
> > >     
> > >     jvar = 0
> > >     for a in jnp.split(data_concat, 200):
> > >         partial_diff = a - jmean
> > >         partial_sum = jnp.sum(partial_diff**2)
> > >         jvar += partial_sum / len(data_concat)
> > > 
> > >     return jnp.array(
> > >         [
> > >             jmedian, jmean, jvar, jnp.sqrt(jvar), jmax, jmin 
> > >         ]
> > >     )
> > > ```
> > 
> > 
> > 这好像只能解决溢出FM64表达范围的问题，算不准的问题还是没法解决，还有一些疑惑的地方：①FM64计算出的平均值是可能比FM128计算出来的更准一些？②由于①这个问题，按你这边代码运行也会导致方差和标准差FM64比FM128更准
> 
> fm128 也按我的代码跑精度应该是差不多的
> 
> 这里本质上的问题是mpc现在基本上都是用定点数来模拟浮点数的计算。浮点数本身encode到定点数就会有一定的误差，然后定点数计算很多非线性拟合也只能保证在一定范围内(不是非常大，也不是非常小)精度非常接近明文
> 
> 本质上要全域接近明文精度，可能需要哪天有个可用的基于浮点数的 mpc 协议了。
> 
> 在这之前，我认为比较可行的做法就是对于特别大的数据量，针对数值 range 调整一下算法提升精度

spdz中的semi2k协议应该是支持更丰富的精度设置，还可以指定小数位的精度，隐语这边目前可以实现相似设置吗？

**Comment by anakinxc** [comment]
> > > > Hi @zhouhansheng
> > > > 举个例子，改成这样
> > > > ```python
> > > > def statistic_fn(dataset_parties_input_list):
> > > >     data_concat = jnp.concatenate(dataset_parties_input_list, axis=0)
> > > >     jmedian = jnp.median(data_concat)
> > > >     jmean = jnp.mean(data_concat)
> > > >     jmax = jnp.max(data_concat)
> > > >     jmin = jnp.min(data_concat)
> > > >     
> > > >     jvar = 0
> > > >     for a in jnp.split(data_concat, 200):
> > > >         partial_diff = a - jmean
> > > >         partial_sum = jnp.sum(partial_diff**2)
> > > >         jvar += partial_sum / len(data_concat)
> > > > 
> > > >     return jnp.array(
> > > >         [
> > > >             jmedian, jmean, jvar, jnp.sqrt(jvar), jmax, jmin 
> > > >         ]
> > > >     )
> > > > ```
> > > 
> > > 
> > > 这好像只能解决溢出FM64表达范围的问题，算不准的问题还是没法解决，还有一些疑惑的地方：①FM64计算出的平均值是可能比FM128计算出来的更准一些？②由于①这个问题，按你这边代码运行也会导致方差和标准差FM64比FM128更准
> > 
> > 
> > fm128 也按我的代码跑精度应该是差不多的
> > 这里本质上的问题是mpc现在基本上都是用定点数来模拟浮点数的计算。浮点数本身encode到定点数就会有一定的误差，然后定点数计算很多非线性拟合也只能保证在一定范围内(不是非常大，也不是非常小)精度非常接近明文
> > 本质上要全域接近明文精度，可能需要哪天有个可用的基于浮点数的 mpc 协议了。
> > 在这之前，我认为比较可行的做法就是对于特别大的数据量，针对数值 range 调整一下算法提升精度
> 
> spdz中的semi2k协议应该是支持更丰富的精度设置，还可以指定小数位的精度，隐语这边目前可以实现相似设置吗？

[这里](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/runtime_config#runtimeconfig) `fxp_fraction_bits` 可以设置小数的 bits 数量，但是小数位数越多，整数的范围会变小，这里的 trade off 需要自己斟酌

**Comment by zhouhansheng** [comment]
> > > > > Hi @zhouhansheng
> > > > > 举个例子，改成这样
> > > > > ```python
> > > > > def statistic_fn(dataset_parties_input_list):
> > > > >     data_concat = jnp.concatenate(dataset_parties_input_list, axis=0)
> > > > >     jmedian = jnp.median(data_concat)
> > > > >     jmean = jnp.mean(data_concat)
> > > > >     jmax = jnp.max(data_concat)
> > > > >     jmin = jnp.min(data_concat)
> > > > >     
> > > > >     jvar = 0
> > > > >     for a in jnp.split(data_concat, 200):
> > > > >         partial_diff = a - jmean
> > > > >         partial_sum = jnp.sum(partial_diff**2)
> > > > >         jvar += partial_sum / len(data_concat)
> > > > > 
> > > > >     return jnp.array(
> > > > >         [
> > > > >             jmedian, jmean, jvar, jnp.sqrt(jvar), jmax, jmin 
> > > > >         ]
> > > > >     )
> > > > > ```
> > > > 
> > > > 
> > > > 这好像只能解决溢出FM64表达范围的问题，算不准的问题还是没法解决，还有一些疑惑的地方：①FM64计算出的平均值是可能比FM128计算出来的更准一些？②由于①这个问题，按你这边代码运行也会导致方差和标准差FM64比FM128更准
> > > 
> > > 
> > > fm128 也按我的代码跑精度应该是差不多的
> > > 这里本质上的问题是mpc现在基本上都是用定点数来模拟浮点数的计算。浮点数本身encode到定点数就会有一定的误差，然后定点数计算很多非线性拟合也只能保证在一定范围内(不是非常大，也不是非常小)精度非常接近明文
> > > 本质上要全域接近明文精度，可能需要哪天有个可用的基于浮点数的 mpc 协议了。
> > > 在这之前，我认为比较可行的做法就是对于特别大的数据量，针对数值 range 调整一下算法提升精度
> > 
> > 
> > spdz中的semi2k协议应该是支持更丰富的精度设置，还可以指定小数位的精度，隐语这边目前可以实现相似设置吗？
> 
> [这里](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/runtime_config#runtimeconfig) `fxp_fraction_bits` 可以设置小数的 bits 数量，但是小数位数越多，整数的范围会变小，这里的 trade off 需要自己斟酌

域的范围可以设置到192这种更大的值吗？

**Comment by anakinxc** [comment]
> > > > > > Hi @zhouhansheng
> > > > > > 举个例子，改成这样
> > > > > > ```python
> > > > > > def statistic_fn(dataset_parties_input_list):
> > > > > >     data_concat = jnp.concatenate(dataset_parties_input_list, axis=0)
> > > > > >     jmedian = jnp.median(data_concat)
> > > > > >     jmean = jnp.mean(data_concat)
> > > > > >     jmax = jnp.max(data_concat)
> > > > > >     jmin = jnp.min(data_concat)
> > > > > >     
> > > > > >     jvar = 0
> > > > > >     for a in jnp.split(data_concat, 200):
> > > > > >         partial_diff = a - jmean
> > > > > >         partial_sum = jnp.sum(partial_diff**2)
> > > > > >         jvar += partial_sum / len(data_concat)
> > > > > > 
> > > > > >     return jnp.array(
> > > > > >         [
> > > > > >             jmedian, jmean, jvar, jnp.sqrt(jvar), jmax, jmin 
> > > > > >         ]
> > > > > >     )
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 这好像只能解决溢出FM64表达范围的问题，算不准的问题还是没法解决，还有一些疑惑的地方：①FM64计算出的平均值是可能比FM128计算出来的更准一些？②由于①这个问题，按你这边代码运行也会导致方差和标准差FM64比FM128更准
> > > > 
> > > > 
> > > > fm128 也按我的代码跑精度应该是差不多的
> > > > 这里本质上的问题是mpc现在基本上都是用定点数来模拟浮点数的计算。浮点数本身encode到定点数就会有一定的误差，然后定点数计算很多非线性拟合也只能保证在一定范围内(不是非常大，也不是非常小)精度非常接近明文
> > > > 本质上要全域接近明文精度，可能需要哪天有个可用的基于浮点数的 mpc 协议了。
> > > > 在这之前，我认为比较可行的做法就是对于特别大的数据量，针对数值 range 调整一下算法提升精度
> > > 
> > > 
> > > spdz中的semi2k协议应该是支持更丰富的精度设置，还可以指定小数位的精度，隐语这边目前可以实现相似设置吗？
> > 
> > 
> > [这里](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/runtime_config#runtimeconfig) `fxp_fraction_bits` 可以设置小数的 bits 数量，但是小数位数越多，整数的范围会变小，这里的 trade off 需要自己斟酌
> 
> 域的范围可以设置到192这种更大的值吗？

目前不行，最大只能到 128
