### ISSUE TITLE
spu编译 zlib失败

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/spu#462]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.6

### OS Platform and Distribution

centos7

### Python Version

3.8.13

### Current Behavior?

spu编译出错
ERROR: /root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/external/zlib/BUILD.bazel:24:20: Foreign Cc - CMake: Building zlib failed: (Exit 1): bash failed: error executing command (from target @zlib//:zlib)
  (cd /root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/root/.cache/bazelisk/downloads/sha256/cdf349dc938b1f11db5a7172269d66e91ce18c0ca134b38bb3997a3e3be782b8/bin:/root/.cargo/bin:/root/miniconda3/envs/ppc/bin:/root/miniconda3/condabin:/usr/local/go/bin:/usr/local/bin:/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin \
  /bin/bash -c bazel-out/k8-opt/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh)
# Configuration: 6d4e93abf31603344a344bc500bcfd55e20ee089ef0edd06f343b68953eb12ee
# Execution platform: @local_execution_config_platform//:platform
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____
Bazel external C/C++ Rules. Building library zlib
Environment:______________
TMPDIR=/tmp
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh
EXT_BUILD_ROOT=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib
INSTALLDIR=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/bazel-out/k8-opt/bin/external/zlib/zlib
BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a
PATH=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib:/root/.cache/bazelisk/downloads/sha256/cdf349dc938b1f11db5a7172269d66e91ce18c0ca134b38bb3997a3e3be782b8/bin:/root/.cargo/bin:/root/miniconda3/envs/ppc/bin:/root/miniconda3/condabin:/usr/local/go/bin:/usr/local/bin:/root/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
BUILD_TMPDIR=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/bazel-out/k8-opt/bin/external/zlib/zlib.build_tmpdir
PWD=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib
EXT_BUILD_DEPS=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/bazel-out/k8-opt/bin/external/zlib/zlib.ext_build_deps
SHLVL=3
BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc
BUILD_LOG=bazel-out/k8-opt/bin/external/zlib/zlib_foreign_cc/CMake.log
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/zlib/zlib_foreign_cc/build_script.sh
_=/usr/bin/env
__________________________
+ cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_TOOLCHAIN_FILE=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/bazel-out/k8-opt/bin/external/zlib/zlib.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/bazel-out/k8-opt/bin/external/zlib/zlib -DCMAKE_PREFIX_PATH=/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/bazel-out/k8-opt/bin/external/zlib/zlib.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/external/zlib
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /root/miniconda3/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Renaming
--     /root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/external/zlib/zconf.h
-- to 'zconf.h.included' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
-- Configuring done (4.2s)
-- Generating done (0.0s)
-- Build files have been written to: /root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/bazel-out/k8-opt/bin/external/zlib/zlib.build_tmpdir
+ cmake --build . --config Release
[1/41] Building C object CMakeFiles/zlib.dir/compress.o
[2/41] Building C object CMakeFiles/zlib.dir/gzclose.o
[3/41] Building C object CMakeFiles/zlib.dir/adler32.o
[4/41] Building C object CMakeFiles/zlib.dir/gzlib.o
[5/41] Building C object CMakeFiles/zlib.dir/uncompr.o
[6/41] Building C object CMakeFiles/zlib.dir/crc32.o
[7/41] Building C object CMakeFiles/zlib.dir/inftrees.o
[8/41] Building C object CMakeFiles/zlib.dir/gzread.o
[9/41] Building C object CMakeFiles/zlib.dir/gzwrite.o
[10/41] Building C object CMakeFiles/zlib.dir/zutil.o
[11/41] Building C object CMakeFiles/zlib.dir/inffast.o
[12/41] Building C object CMakeFiles/zlibstatic.dir/compress.o
[13/41] Building C object CMakeFiles/zlib.dir/infback.o
[14/41] Building C object CMakeFiles/zlibstatic.dir/adler32.o
[15/41] Building C object CMakeFiles/zlibstatic.dir/gzclose.o
[16/41] Building C object CMakeFiles/zlibstatic.dir/crc32.o
[17/41] Building C object CMakeFiles/zlibstatic.dir/gzlib.o
[18/41] Building C object CMakeFiles/zlibstatic.dir/gzread.o
[19/41] Building C object CMakeFiles/zlibstatic.dir/gzwrite.o
[20/41] Building C object CMakeFiles/zlib.dir/trees.o
[21/41] Building C object CMakeFiles/zlibstatic.dir/inftrees.o
[22/41] Building C object CMakeFiles/zlibstatic.dir/uncompr.o
[23/41] Building C object CMakeFiles/zlibstatic.dir/zutil.o
[24/41] Building C object CMakeFiles/zlibstatic.dir/inffast.o
[25/41] Building C object CMakeFiles/zlib.dir/deflate.o
[26/41] Building C object CMakeFiles/minigzip.dir/test/minigzip.o
[27/41] Building C object CMakeFiles/zlibstatic.dir/infback.o
[28/41] Building C object CMakeFiles/zlib.dir/inflate.o
[29/41] Building C object CMakeFiles/example.dir/test/example.o
[30/41] Building C object CMakeFiles/example64.dir/test/example.o
[31/41] Linking C shared library libz.so.1.2.13
FAILED: libz.so.1.2.13
: && /root/miniconda3/bin/gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -D_FORTIFY_SOURCE=1 -DNDEBUG -ffunction-sections -fdata-sections -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fdiagnostics-color=always -Wl,-z,noexecstack -fopenmp -fPIC -fstack-protector-strong -mavx -DCHECK_AVX -O3 -DNDEBUG  -shared -fuse-ld=lld -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/root/miniconda3/bin -pass-exit-codes -static-libstdc++ -static-libgcc -Wl,--gc-sections -l:libstdc++.a -l:libgcc.a -fopenmp  -Wl,--version-script,"/root/.cache/bazel/_bazel_root/0363fd17116518e55293c06b124c5fd2/sandbox/processwrapper-sandbox/2602/execroot/spulib/external/zlib/zlib.map" -shared -Wl,-soname,libz.so.1 -o libz.so.1.2.13 CMakeFiles/zlib.dir/adler32.o CMakeFiles/zlib.dir/compress.o CMakeFiles/zlib.dir/crc32.o CMakeFiles/zlib.dir/deflate.o CMakeFiles/zlib.dir/gzclose.o CMakeFiles/zlib.dir/gzlib.o CMakeFiles/zlib.dir/gzread.o CMakeFiles/zlib.dir/gzwrite.o CMakeFiles/zlib.dir/inflate.o CMakeFiles/zlib.dir/infback.o CMakeFiles/zlib.dir/inftrees.o CMakeFiles/zlib.dir/inffast.o CMakeFiles/zlib.dir/trees.o CMakeFiles/zlib.dir/uncompr.o CMakeFiles/zlib.dir/zutil.o   && :
ld.lld: error: version script assignment of 'local' to symbol 'gz_intmax' failed: symbol not defined
collect2: error: ld returned 1 exit status
[32/41] Building C object CMakeFiles/minigzip64.dir/test/minigzip.o
[33/41] Building C object CMakeFiles/zlibstatic.dir/trees.o
[34/41] Building C object CMakeFiles/zlibstatic.dir/inflate.o
[35/41] Building C object CMakeFiles/zlibstatic.dir/deflate.o
ninja: build stopped: subcommand failed.
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/zlib/zlib_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/zlib/zlib_foreign_cc/CMake.log
INFO: Elapsed time: 2069.077s, Critical Path: 867.92s
INFO: 2866 processes: 260 internal, 2606 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

### Standalone code to reproduce the issue

```Python
x86服务器 8C16G
使用docker镜像secretflow/release-ci:latest，对spu源码进行编译打包
conda创建python版本3.8
python setup.py bdist_wheel
```

**Comment by anakinxc** [comment]
Hi @daydayuphere 

SPU 最新的代码应该已经修复了这个问题
