### ISSUE TITLE
[Feature]: 请教下hal/permute.cc中实现的RadixSort支持两方么

### ISSUE THREAD

**Issue by 982945902** [secretflow/spu#535]
### Feature Request Type

Build/Install

### Have you searched existing issues?

Yes

**Comment by tpppppub** [comment]
目前只有 ABY3/SEMI2K 支持，Cheetah 不支持，但 SEMI2K 需要一个可信第三方不算严格意义上的两方

**Comment by fionser** [comment]
@tpppppub 有什么原子 2PC 不支持嘛

**Comment by 982945902** [comment]
@tpppppub  SEMI2K的解决方案有发新paper么

**Comment by fionser** [comment]
那复用 Squirrel 的 PackLWEs 功能就好了。ASS - to - HE - shuffle via PackLWEs - reshare ASS

**Comment by tpppppub** [comment]
> @tpppppub SEMI2K的解决方案有发新paper么

计划中

**Comment by 982945902** [comment]
> > @tpppppub SEMI2K的解决方案有发新paper么
> 
> 计划中

@tpppppub  请教一个代码问题， semi2k中这部分代码，函数名称与其功能是否存在差异呢，PermAS 我理解是将perm apply， 但是这段代码貌似是Inverse的
![image](https://github.com/secretflow/spu/assets/49055103/c0cc7921-493c-46de-beff-e5abdaf8faf1)

**Comment by tpppppub** [comment]
PermAS 目前的“实际”作用其实是 shuffle（因为 shuffle 本质上就是将一个随机 perm apply 到一个 array 上）。PermAS 将每一方各自的一个 local perm apply 在 in，从全局上看每一方 perm 复合后的 perm 是随机的。你的理解也没问题。这里只要保证 PermAS 和 InvPermAS 两个是可逆的即可，因此不影响功能。
