### ISSUE TITLE
[Bug]: 运行weo的时候报错，libspu.so: undefined symbol

### ISSUE THREAD

**Issue by SeaCSKY** [secretflow/spu#542]
### Issue Type

Build/Install

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.8.0dev

### OS Platform and Distribution

ubuntu22.04

### Python Version

3.8

### Current Behavior?

![1707114660104](https://github.com/secretflow/spu/assets/22488192/9ca666d7-ced6-45d0-a1c4-9a66b7bfb021)

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by anakinxc** [comment]
hi @chuchaochen 

请提供一下版本号
