### ISSUE TITLE
[Question]: kernel的hal与mpc的api算子划分问题

### ISSUE THREAD

**Issue by Jerry-zhxf** [secretflow/spu#559]
### Feature Request Type

Usability

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

问题：libspu中运算的层级关系是这样的 device/pphlo->kernel/hlo->kernel/hal->mpc/ab(api)
其实hlo中提供的运算接口会比mpc/api要多，比如sub由add与negate编排而成，这是合理的。
但在mpc/api中存在一些接口，比如equal，是可以通过其他api编排来实现的，但依然在mpc/api中实现了equal_aa，这是出于什么原因考虑的呢？是做了一些性能优化工作吗？或者说libspu/mpc/api.h中的运算接口范围是以什么原则确定出来的？
![image](https://github.com/secretflow/spu/assets/36923038/5d15b4cf-c2dc-4f83-8528-94db307413e0)

### Describe features you want to add to SPU

略

### Describe features you want to add to SPU

略

**Comment by anakinxc** [comment]
> ### Feature Request Type
> Usability
> 
> ### Have you searched existing issues?
> Yes
> 
> ### Is your feature request related to a problem?
> 问题：libspu中运算的层级关系是这样的 device/pphlo->kernel/hlo->kernel/hal->mpc/ab(api) 其实hlo中提供的运算接口会比mpc/api要多，比如sub由add与negate编排而成，这是合理的。 但在mpc/api中存在一些接口，比如equal，是可以通过其他api编排来实现的，但依然在mpc/api中实现了equal_aa，这是出于什么原因考虑的呢？是做了一些性能优化工作吗？或者说libspu/mpc/api.h中的运算接口范围是以什么原则确定出来的？ ![image](https://private-user-images.githubusercontent.com/36923038/305695374-5d15b4cf-c2dc-4f83-8528-94db307413e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDQ3MjksIm5iZiI6MTcwODI0NDQyOSwicGF0aCI6Ii8zNjkyMzAzOC8zMDU2OTUzNzQtNWQxNWI0Y2YtYzJkYy00ZjgzLTg1MjgtOTRkYjMwNzQxM2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA4MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkY2FiYWM2MDE2ODNhZjgyZjhjZDIyMjI4ZmMzOTc4N2QyMjgxYmFmYWJkMTVmYjcwYzQxOTFhMzFjZjQxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTcCQVIFtORcuz0el4TC1gxQsfj6rzzsd3-Up2eLRtk)
> 
> ### Describe features you want to add to SPU
> 略
> 
> ### Describe features you want to add to SPU
> 略

有一部分 mpc 的 api 属于 optional/extension 性质的，你可以把这部分理解成类似于 SSE 这样的指令集扩展。

比如你举例的 equal，对于 aby3/semi2k 有高性能的实现，但不是所有协议都会这么个实现

这部分的 api，在 hal 先会尝试调用 equal_aa 这样的高性能实现，如果协议没有提供在 fallback 到默认的展开形式

**Comment by Jerry-zhxf** [comment]
> > ### Feature Request Type
> > Usability
> > ### Have you searched existing issues?
> > Yes
> > ### Is your feature request related to a problem?
> > 问题：libspu中运算的层级关系是这样的 device/pphlo->kernel/hlo->kernel/hal->mpc/ab(api) 其实hlo中提供的运算接口会比mpc/api要多，比如sub由add与negate编排而成，这是合理的。 但在mpc/api中存在一些接口，比如equal，是可以通过其他api编排来实现的，但依然在mpc/api中实现了equal_aa，这是出于什么原因考虑的呢？是做了一些性能优化工作吗？或者说libspu/mpc/api.h中的运算接口范围是以什么原则确定出来的？ ![image](https://private-user-images.githubusercontent.com/36923038/305695374-5d15b4cf-c2dc-4f83-8528-94db307413e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDQ3MjksIm5iZiI6MTcwODI0NDQyOSwicGF0aCI6Ii8zNjkyMzAzOC8zMDU2OTUzNzQtNWQxNWI0Y2YtYzJkYy00ZjgzLTg1MjgtOTRkYjMwNzQxM2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA4MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkY2FiYWM2MDE2ODNhZjgyZjhjZDIyMjI4ZmMzOTc4N2QyMjgxYmFmYWJkMTVmYjcwYzQxOTFhMzFjZjQxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTcCQVIFtORcuz0el4TC1gxQsfj6rzzsd3-Up2eLRtk)
> > ### Describe features you want to add to SPU
> > 略
> > ### Describe features you want to add to SPU
> > 略
> 
> 有一部分 mpc 的 api 属于 optional/extension 性质的，你可以把这部分理解成类似于 SSE 这样的指令集扩展。
> 
> 比如你举例的 equal，对于 aby3/semi2k 有高性能的实现，但不是所有协议都会这么个实现
> 
> 这部分的 api，在 hal 先会尝试调用 equal_aa 这样的高性能实现，如果协议没有提供在 fallback 到默认的展开形式

我在[cheetah](https://github.com/secretflow/spu/tree/main/libspu/mpc/cheetah)中看到了equal_aa的高性能实现，但“协议没有提供在 fallback 到默认的展开形式”这个处理逻辑没有找到在哪？

**Comment by anakinxc** [comment]
> > > ### Feature Request Type
> > > Usability
> > > ### Have you searched existing issues?
> > > Yes
> > > ### Is your feature request related to a problem?
> > > 问题：libspu中运算的层级关系是这样的 device/pphlo->kernel/hlo->kernel/hal->mpc/ab(api) 其实hlo中提供的运算接口会比mpc/api要多，比如sub由add与negate编排而成，这是合理的。 但在mpc/api中存在一些接口，比如equal，是可以通过其他api编排来实现的，但依然在mpc/api中实现了equal_aa，这是出于什么原因考虑的呢？是做了一些性能优化工作吗？或者说libspu/mpc/api.h中的运算接口范围是以什么原则确定出来的？ ![image](https://private-user-images.githubusercontent.com/36923038/305695374-5d15b4cf-c2dc-4f83-8528-94db307413e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDQ3MjksIm5iZiI6MTcwODI0NDQyOSwicGF0aCI6Ii8zNjkyMzAzOC8zMDU2OTUzNzQtNWQxNWI0Y2YtYzJkYy00ZjgzLTg1MjgtOTRkYjMwNzQxM2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA4MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkY2FiYWM2MDE2ODNhZjgyZjhjZDIyMjI4ZmMzOTc4N2QyMjgxYmFmYWJkMTVmYjcwYzQxOTFhMzFjZjQxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTcCQVIFtORcuz0el4TC1gxQsfj6rzzsd3-Up2eLRtk)
> > > ### Describe features you want to add to SPU
> > > 略
> > > ### Describe features you want to add to SPU
> > > 略
> > 
> > 
> > 有一部分 mpc 的 api 属于 optional/extension 性质的，你可以把这部分理解成类似于 SSE 这样的指令集扩展。
> > 比如你举例的 equal，对于 aby3/semi2k 有高性能的实现，但不是所有协议都会这么个实现
> > 这部分的 api，在 hal 先会尝试调用 equal_aa 这样的高性能实现，如果协议没有提供在 fallback 到默认的展开形式
> 
> 我在[cheetah](https://github.com/secretflow/spu/tree/main/libspu/mpc/cheetah)中看到了equal_aa的高性能实现，但“协议没有提供在 fallback 到默认的展开形式”这个处理逻辑没有找到在哪？

[here](https://github.com/secretflow/spu/blob/a2075ea4bbd0ace24bc1db900bceffa4ed50e3fb/libspu/kernel/hal/ring.cc#L404)
