### ISSUE TITLE
[Question]: 不同库使用同一协议的互联互通问题

### ISSUE THREAD

**Issue by Jerry-zhxf** [secretflow/spu#560]
### Feature Request Type

Usability

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

你好，请教一个问题：
隐语的SPU和[MP-SPDZ](https://github.com/data61/MP-SPDZ)都实现了SPDZ2K和Semi2k，那么如果现在有3方，两方用隐语的SPDZ2K协议，一方用MP-SPDZ的SPDZ2K协议，假设他们之间的通信链路无问题，是否能够实现计算？
现在看隐语spu中的协议实现，与自身的ctx存在依赖，是否是不同库无法联通的原因？

### Describe features you want to add to SPU

略

### Describe features you want to add to SPU

略

**Comment by tpppppub** [comment]
SPU 和 MP-SPDZ 在整体设计上差异较大，从应用层到编译器前端、运行时等各方面都没有标准化的统一接口，此外还有协议实现上的其他区别，因此不能互联互通

**Comment by Jerry-zhxf** [comment]
> SPU 和 MP-SPDZ 在整体设计上差异较大，从应用层到编译器前端、运行时等各方面都没有标准化的统一接口，此外还有协议实现上的其他区别，因此不能互联互通

嗯嗯，了解了。关键问题是在协议实现上存在一些区别？

**Comment by tpppppub** [comment]
主要还是没有标准化，协议实现只是问题之一

**Comment by Jerry-zhxf** [comment]
好的
