### ISSUE TITLE
[Feature]: SPU中的比较算子是如何实现的？

### ISSUE THREAD

**Issue by WandQ** [secretflow/spu#569]
### Feature Request Type

Others

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

我阅读了SPU的MPC的底层源码，主要的相关算子在libspu/api.h和ab_api.h中都有体现，但是我没找到比较算子（只有cheeth好像有一个比较方法，ABY3没有），只找到了msb算子，请问如果我在python层调用了比较算子中的>或者<会如何执行呢？
我猜测是先减法再msb，但是我没找到对应的代码。
期待被解答。

### Describe features you want to add to SPU

暂无

### Describe features you want to add to SPU

暂无

**Comment by tpppppub** [comment]
[here](https://github.com/secretflow/spu/blob/main/libspu/kernel/hal/ring.cc#L446)

**Comment by BeStrongok** [comment]
@WandQ 
I think the prefered practice of learning SPU code is:
- Read the corresponding [paper](https://www.usenix.org/conference/atc23/presentation/ma) which provide a detailed decription about the high level design of SPU.
- If you don't consider the compiler implementation, a good start point is the implementation of [hlo](https://github.com/secretflow/spu/blob/main/libspu/kernel/hlo/basic_binary.cc), which constains semantic implementations of commonly used operators.
- You will find that the implementation of `hlo` mainly call the kernels provided by [HAL](https://github.com/secretflow/spu/blob/main/libspu/kernel/hal/ring.cc), these kernel further dispatch the operation into MPC protocols.
- There is registration mechanism for MPC protocols who register the detailed cryptographic primitives, such as the [Cheetah](https://github.com/secretflow/spu/blob/249026eba1a9eafdaf93596196a7ed4dd5e24555/libspu/mpc/cheetah/protocol.cc#L31).
- Finally you will find the relationship between MPC protocol primitives and HAL.
Hope it's a correct way and can help you.

**Comment by WandQ** [comment]
> [here](https://github.com/secretflow/spu/blob/main/libspu/kernel/hal/ring.cc#L446)

感谢，看来和我猜测的一样！😊

**Comment by WandQ** [comment]
@BeStrongok 
Wow, this is a great learning practice! Understanding the overall architecture of SPU is exactly what I've been lacking. Currently, I have only studied the underlying cryptographic primitives of MPC. 
Thank you for your response.
