### ISSUE TITLE
[Bug]: _libpsi repo 错误

### ISSUE THREAD

**Issue by Lost-Temple** [secretflow/spu#582]
### Issue Type

Build/Install

### Modules Involved

PSI

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu main

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.9

### Compiler Version

GCC11.2.1

### Current Behavior?

[repositories.bzl](https://github.com/secretflow/spu/blob/main/bazel/repositories.bzl)
中定义的 :

```python
def _libpsi():
    maybe(
        http_archive,
        name = "psi",
        urls = [
            "https://github.com/secretflow/psi/archive/refs/tags/v0.2.0.dev240222.tar.gz",
        ],
        strip_prefix = "psi-0.2.0.dev240222",
        sha256 = "6b3aed24ae5dc4dce7acfc140093612f8753b9643a6a19177483f8462eda061f",
    )
```

这里面的链接地址是无效链接，导致这个依赖下载不了

### Standalone code to reproduce the issue

```Python
bazel build //... -c dbg

编译过程报错：提示https://github.com/secretflow/psi/archive/refs/tags/v0.2.0.dev240222.tar.gz下载失败
```

**Comment by Lost-Temple** [comment]
修改成以下内容后，重新执行编译命令成功：
```python
def _libpsi():
    maybe(
        http_archive,
        name = "psi",
        urls = [
            "https://github.com/secretflow/psi/archive/refs/tags/v0.3.0.dev240222.tar.gz",
        ],
        strip_prefix = "psi-0.3.0.dev240222",
        sha256 = "a7319040510a1581741f05ac4b31e3d887ba8ba4766154736f96d76970d00de5",
    )
```

**Comment by Chrisdehe** [comment]
看起来是一个文档错误，我们内部测试下，anyway感谢发现！

**Comment by 6fj** [comment]
> 修改成以下内容后，重新执行编译命令成功：
> 
> ```python
> def _libpsi():
>     maybe(
>         http_archive,
>         name = "psi",
>         urls = [
>             "https://github.com/secretflow/psi/archive/refs/tags/v0.3.0.dev240222.tar.gz",
>         ],
>         strip_prefix = "psi-0.3.0.dev240222",
>         sha256 = "a7319040510a1581741f05ac4b31e3d887ba8ba4766154736f96d76970d00de5",
>     )
> ```

是的，psi repo的tag发生了调整，感谢发现，我们已经修复了问题。
