### ISSUE TITLE
[Bug]: bazel: could not resolve the version 'latest' to an actual version number: unable to determine latest version ...

### ISSUE THREAD

**Issue by warpoons** [secretflow/spu#603]
### Issue Type

Usability

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.0.dev20240311

### OS Platform and Distribution

Ubuntu 18.04.6 LTS by WSL

### Python Version

3.10

### Compiler Version

GCC 11.3.0

### Current Behavior?

I have tried the example of Flax+resnet50 from the link 'https://github.com/secretflow/spu/tree/main/examples/python/ml/flax_resnet', when i run the first command, bug happened.

### Standalone code to reproduce the issue

```Python
I have searched for solutions, but the command 'echo "USE_BAZEL_VERSION=4.1.0" > .bazeliskrc' did not work for me.
```

### Relevant log output

```Shell
bazel run -c opt //examples/python/utils:nodectl -- --config `pwd`/examples/python/ml/flax_resnet/3pc.json up

2024/03/12 16:14:28 could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": dial tcp 172.217.163.42:443: i/o timeout
```

**Comment by warpoons** [comment]
> > > Hi @warpoons
> > > Couple things to notice here:
> > > 
> > > * we no longer support bazel 4.x
> > > * If you really need to change bazel version, please modify .bazelversion
> > > * `dial tcp 172.217.163.42:443: i/o timeout` please check your network
> > > 
> > > Best
> > 
> > 
> > Thanks for your reply. I have changed the SPU version to 0.8.0b0 and the bug has also changed as: ERROR: /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/external/com_github_google_cpu_features/BUILD.bazel:24:20: Foreign Cc - CMake: Building cpu_features failed: (Exit 127): bash failed: error executing command (from target @com_github_google_cpu_features//:cpu_features) /bin/bash -c bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/wrapper_build_script.sh
> > Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging rules_foreign_cc: Build failed! rules_foreign_cc: Keeping temp build directory and dependencies directory for debug. rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag. rules_foreign_cc: Printing build logs: _____ BEGIN BUILD LOGS _____
> > Bazel external C/C++ Rules. Building library cpu_features
> > Environment:______________ BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/build_script.sh EXT_BUILD_ROOT=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log PWD=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/wrapper_build_script.sh BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc TMPDIR=/tmp EXT_BUILD_DEPS=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.ext_build_deps BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a BUILD_TMPDIR=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.build_tmpdir SHLVL=2 INSTALLDIR=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features PATH=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib:/home/warpoons/.cache/bazelisk/downloads/bazelbuild/bazel-6.5.0-linux-x86_64 /bin:“/usr/local/bin:/home/warpoons/anaconda3/envs/spu_py310/bin:/home/warpoons/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/ws l/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/ PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/d/TexLive/texlive/2023/bin/windows:/mnt/d/Matlab/bin:/mnt/c/Users/78299/AppData/Local/Microsoft/WindowsApps:/mnt/d/VSCode/Microsoft VS Code/bin:/snap/bin” rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log
> > Target //examples/python/utils:nodectl failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 142.377s, Critical Path: 0.26s INFO: 129 processes: 120 internal, 9 linux-sandbox. FAILED: Build did NOT complete successfully ERROR: Build failed. Not running target
> > This example 'https://github.com/secretflow/spu/tree/main/examples/python/ml/flax_resnet' seems important and problem-solving to me. May I ask if the bazel is no longer supported，how should I run this example. Thanks for your wonderful work :)
> 
> bazel is supported, just < 6.x is no longer supported.
> 
> For your build issue, can you provide full build log at `bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log`

Thanks. I changed my Bazel to the required version of 6.5.0, the bug has reported differently:
ERROR: /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/external/com_github_openssl_openssl/BUILD.bazel:22:10: @com_github_openssl_openssl//:all_srcs: invalid label 'test/smime-eml/SignedInvalidMappingFromanyPolicyTest7.eml:OECustomProperty' in element 4383 of attribute 'srcs' in 'filegroup' rule: invalid label 'test/smime-eml/SignedInvalidMappingFromanyPolicyTest7.eml:OECustomProperty': absolute label must begin with '@' or '//'
ERROR: /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/external/com_github_brpc_brpc/BUILD.bazel:301:11: Target '@com_github_openssl_openssl//:openssl' contains an error and its package is in error and referenced by '@com_github_brpc_brpc//:butil'
ERROR: Analysis of target '//examples/python/utils:nodectl' failed; build aborted:
INFO: Elapsed time: 0.095s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: libspu/dialect/pphlo
ERROR: Build failed. Not running target

Sorry for taking your more time. Appreciate your efforts!

**Comment by anakinxc** [comment]
> > > > Hi @warpoons
> > > > Couple things to notice here:
> > > > 
> > > > * we no longer support bazel 4.x
> > > > * If you really need to change bazel version, please modify .bazelversion
> > > > * `dial tcp 172.217.163.42:443: i/o timeout` please check your network
> > > > 
> > > > Best
> > > 
> > > 
> > > Thanks for your reply. I have changed the SPU version to 0.8.0b0 and the bug has also changed as: ERROR: /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/external/com_github_google_cpu_features/BUILD.bazel:24:20: Foreign Cc - CMake: Building cpu_features failed: (Exit 127): bash failed: error executing command (from target @com_github_google_cpu_features//:cpu_features) /bin/bash -c bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/wrapper_build_script.sh
> > > Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging rules_foreign_cc: Build failed! rules_foreign_cc: Keeping temp build directory and dependencies directory for debug. rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag. rules_foreign_cc: Printing build logs: _____ BEGIN BUILD LOGS _____
> > > Bazel external C/C++ Rules. Building library cpu_features
> > > Environment:______________ BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/build_script.sh EXT_BUILD_ROOT=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log PWD=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/wrapper_build_script.sh BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc TMPDIR=/tmp EXT_BUILD_DEPS=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.ext_build_deps BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a BUILD_TMPDIR=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features.build_tmpdir SHLVL=2 INSTALLDIR=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features PATH=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/11/execroot/spulib:/home/warpoons/.cache/bazelisk/downloads/bazelbuild/bazel-6.5.0-linux-x86_64 /bin:“/usr/local/bin:/home/warpoons/anaconda3/envs/spu_py310/bin:/home/warpoons/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/ws l/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/ PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/d/TexLive/texlive/2023/bin/windows:/mnt/d/Matlab/bin:/mnt/c/Users/78299/AppData/Local/Microsoft/WindowsApps:/mnt/d/VSCode/Microsoft VS Code/bin:/snap/bin” rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log
> > > Target //examples/python/utils:nodectl failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 142.377s, Critical Path: 0.26s INFO: 129 processes: 120 internal, 9 linux-sandbox. FAILED: Build did NOT complete successfully ERROR: Build failed. Not running target
> > > This example 'https://github.com/secretflow/spu/tree/main/examples/python/ml/flax_resnet' seems important and problem-solving to me. May I ask if the bazel is no longer supported，how should I run this example. Thanks for your wonderful work :)
> > 
> > 
> > bazel is supported, just < 6.x is no longer supported.
> > For your build issue, can you provide full build log at `bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features_foreign_cc/CMake.log`
> 
> Thanks. I changed my Bazel to the required version of 6.5.0, the bug has reported differently: ERROR: /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/external/com_github_openssl_openssl/BUILD.bazel:22:10: @com_github_openssl_openssl//:all_srcs: invalid label 'test/smime-eml/SignedInvalidMappingFromanyPolicyTest7.eml:OECustomProperty' in element 4383 of attribute 'srcs' in 'filegroup' rule: invalid label 'test/smime-eml/SignedInvalidMappingFromanyPolicyTest7.eml:OECustomProperty': absolute label must begin with '@' or '//' ERROR: /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/external/com_github_brpc_brpc/BUILD.bazel:301:11: Target '@com_github_openssl_openssl//:openssl' contains an error and its package is in error and referenced by '@com_github_brpc_brpc//:butil' ERROR: Analysis of target '//examples/python/utils:nodectl' failed; build aborted: INFO: Elapsed time: 0.095s INFO: 0 processes. FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured) currently loading: libspu/dialect/pphlo ERROR: Build failed. Not running target
> 
> Sorry for taking your more time. Appreciate your efforts!

This is strange, can you try `bazel clean --expunge` and then run again

**Comment by anakinxc** [comment]
> I just realize that should I change the IP addresses in the 3pc.jasn file? the original IP is: { "id": "outsourcing.3pc", "nodes": { "node:0": "127.0.0.1:61920", "node:1": "127.0.0.1:61921", "node:2": "127.0.0.1:61922", "node:3": "127.0.0.1:61923", "node:4": "127.0.0.1:61924" }, If I really need change it, how can I determine my correct IP? thanks

Are you running with 3 machines or 3 nodes on one machine?

**Comment by warpoons** [comment]
> bazel clean --expunge
(1) By re-runing after bazel clean --expunge, bugs:
ERROR: /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/external/zlib/BUILD.bazel:24:20: Foreign Cc - CMake: Building zlib [for tool] failed: (Exit 127): bash failed: error executing command (from target @zlib//:zlib) /bin/bash -c bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library zlib

Environment:______________
BUILD_SCRIPT=bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/build_script.sh
EXT_BUILD_ROOT=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib
BUILD_LOG=bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/CMake.log
PWD=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh
TMPDIR=/tmp
EXT_BUILD_DEPS=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib/bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib.ext_build_deps
BUILD_TMPDIR=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib/bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib.build_tmpdir   
SHLVL=2
INSTALLDIR=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib/bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib
PATH=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib:“/usr/local/bin:/home/warpoons/anaconda3/envs/spu_py310/bin:/home/warpoons/an
aconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/W
indows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/d/TexLive/texlive/2023/bin/windows:/mnt/d/Matlab/bin:/mnt/c/Users/78299/AppData/Local/Microsoft/WindowsApps:/mnt/d/VSCode/Microsoft VS Code/bin:/snap/bin”
_=/usr/bin/env
__________________________
Can not copy /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib/cmake
Can not copy /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib/ninja
+ cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_TOOLCHAIN_FILE=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib/bazel-out/k8-o
pt-exec-50AE0418/bin/external/zlib/zlib.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f0
57/sandbox/linux-sandbox/2/execroot/spulib/bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib -DCMAKE_PREFIX_PATH=/home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandb
ox/linux-sandbox/2/execroot/spulib/bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib.ext_build_deps -DCMAKE_RANLIB= -GNinja -G Ninja /home/warpoons/.cache/bazel/_bazel_warpoons/7a3c07d0976ca54dbfb34add5770f057/sandbox/linux-sandbox/2/execroot/spulib/external/zlib
bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/build_script.sh: line 110: cmake: command not found
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt-exec-50AE0418/bin/external/zlib/zlib_foreign_cc/CMake.log

Target //examples/python/utils:nodectl failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 69.298s, Critical Path: 0.36s
INFO: 50 processes: 50 internal.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target


(2)
No, I am not. I had not run any extra command except for "bazel run -c opt //examples/python/utils:nodectl -- --config `pwd`/examples/python/ml/flax_resnet/3pc.json up".

**Comment by anakinxc** [comment]
Hi @warpoons 

`cmake: command not found` please make sure you have installed all prerequisites listed [here](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux)

**Comment by warpoons** [comment]
Hi @anakinxc 
Sorry for late response. I have installed cmake before starting all these tutorials and really don't understand why cmake disappears.
Anyway, I tried to re-install camke this morning, re-run the experiment and it finally works (spu version 0.8.0b0, bazel 6.5.0
 and cmake 3.29.0-rc3).
Thanks for your wise instruction.
