### ISSUE TITLE
[Bug]: spu 使用GCC 13编译时出错

### ISSUE THREAD

**Issue by Lost-Temple** [secretflow/spu#612]
### Issue Type

Build/Install

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu main

### OS Platform and Distribution

fedora38

### Python Version

3.10.12

### Compiler Version

gcc 13

### Current Behavior?

gcc 编译时 ，错误信息例子如：error: 'uint64_t' was not declared in this scope。 由于gcc版本引起，之前yacl模块中同样存在这个问题，请看 [yacl 的 #274](https://github.com/secretflow/yacl/pull/274) ，现在的spu的依赖`com_github_emptoolkit_emp_tool` 使用gcc编译会出现上述问题，需要在一些文件中添加 `#include <cstdint>`, 如：`spulib/external/com_github_emptoolkit_emp_tool/emp-tool/utils/block.h`

### Standalone code to reproduce the issue

```Python
在上述编译环境中编译，cmake 时会报错：error: 'uint64_t' was not declared in this scope
```

**Comment by anakinxc** [comment]
Hi @Lost-Temple 

Can you report this to emp-tool?

Thanks

**Comment by Chrisdehe** [comment]
timeout，先关闭了。
