### ISSUE TITLE
[Bug]: compile failed

### ISSUE THREAD

**Issue by xiansongq** [secretflow/spu#613]
### Issue Type

Build/Install

### Modules Involved

SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.8.0b0

### OS Platform and Distribution

Linux Ubuntu 16.4.0

### Python Version

3.10

### Compiler Version

GCC 9.4.0

### Current Behavior?

A bug happened!When running ```bazel build //... -c dbg``` output error info.
![bug](https://github.com/secretflow/spu/assets/63793833/8a7b5710-9968-43a9-ae14-1c7c9367cdac)

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by tpppppub** [comment]
GCC 9.4.0 is not supported. Please make sure you have installed all prerequisites listed [here](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux) . Besides, from the snapshot attached, it's a network connection problem.
