### ISSUE TITLE
SPU的编译环境

### ISSUE THREAD

**Issue by leileiL** [secretflow/spu#626]
### Issue Type

Build/Install

### Modules Involved

SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu-0.5.0b0

### OS Platform and Distribution

Linux Loongarch64

### Python Version

无

### Compiler Version

无

### Current Behavior?

你好，请问支持在龙芯3C5000上源码编译打包SPU吗？

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by anakinxc** [comment]
Hi @leileiL 

目前不支持，但是欢迎 port
