### ISSUE TITLE
[Feature]: flax_gpt2 inference using FM32 secret sharing

### ISSUE THREAD

**Issue by ccw-li** [secretflow/spu#629]
### Feature Request Type

Performance

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

Currently, flax_gpt2 inference can only use FM64 or FM128 secret sharing.
I am using NPU to accelerate MPC neural network inference. But my NPU doesn't support 64-bit integer. My NPU supports int8 and int32.
I wonder if you can support flax_gpt2 inference using FM32 secret sharing.

### Describe features you want to add to SPU

flax_gpt2 inference using FM32 secret sharing.

### Describe features you want to add to SPU

No.

**Comment by tpppppub** [comment]
Hi @ccw-li , as SPU uses fixed-point numbers to encode decimals, and using 8-bit or 32-bit rings for encoding can result in low precision that fails to meet the GPT2 requirements.

**Comment by anakinxc** [comment]
Also technically you can use multiple 32bit integers to simulate 64bit int computations

**Comment by fionser** [comment]
uint32 dynamic slice it not supporting yet, and thus the GPT2 demo is not running on u32.

**Comment by ccw-li** [comment]
> Hi @ccw-li , as SPU uses fixed-point numbers to encode decimals, and using 8-bit or 32-bit rings for encoding can result in low precision that fails to meet the GPT2 requirements.

> uint32 dynamic slice it not supporting yet, and thus the GPT2 demo is not running on u32.

That's so sad.

> Also technically you can use multiple 32bit integers to simulate 64bit int computations

Thanks for the kind suggestion. 
I understand that I can implement "64bit x 64bit -> 64bit" multiplication on a X86 CPU by using "32bit x 32bit -> 64bit" MUL instructions.
But my NPU's matmul operator doesn't support "32bit x 32bit -> 64bit" computation.
When inputs are int32, the output has to be int32 as well. So the upper 32 bits of the 64-bit multiplication result are lost.
