### ISSUE TITLE
[Bug]: Package 'examples/python/ml/my_custom_file' contains errors

### ISSUE THREAD

**Issue by warpoons** [secretflow/spu#645]
### Issue Type

Usability

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.8.0b0

### OS Platform and Distribution

Ubuntu 18.04.6 LTS by WSL

### Python Version

3.10

### Compiler Version

GCC 11.3.0

### Current Behavior?

I just tried to evaluate individual DNN layer as discussed in https://github.com/secretflow/spu/issues/634#issuecomment-2034145464. But bugs happened.

I have uploaded my test code at [here](https://github.com/warpoons/Evaluating-individual-DNN-layer-using-SPU). Download and put it in the directory `spu-0.8.0b0\examples\python\ml` and:
**1. Launch SPU backend runtime**:

> bazel run -c opt //examples/python/utils:nodectl -- --config \`pwd\`/examples/python/ml/Evaluating-individual-DNN-layer-using-SPU-master/2pc.json up

This step works. Output: 
`[2024-04-09 15:07:04,174] [Process-1] Starting grpc server at 127.0.0.1:61320`
`[2024-04-09 15:07:04,174] [Process-2] Starting grpc server at 127.0.0.1:61321` with some WARNINGs.

**2. Run custom_model_inference.py example**:

> bazel run -c opt //examples/python/ml/Evaluating-individual-DNN-layer-using-SPU-master:custom_model_inference -- --config \`pwd\`/examples/python/ml/Evaluating-individual-DNN-layer-using-SPU-master/2pc.json

Then the bugs happened.

### Standalone code to reproduce the issue

```Python
Please see above.
```

### Relevant log output

```Shell
ax_resnet_individual/2pc.json
ERROR: Traceback (most recent call last):                                                                                                                                                              
        File "/mnt/c/Users/78299/Desktop/my_spu/spu-0.8.0b0/examples/python/ml/flax_resnet_individual/BUILD.bazel", line 36, column 10, in <toplevel>
                py_binary(
        File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/external/rules_python/python/py_binary.bzl", line 36, column 20, in py_binary
                _py_binary_impl(**add_migration_tag(attrs))
Error in py_binary: py_binary rule 'custom_model_inference' in package 'examples/python/ml/flax_resnet_individual' conflicts with existing py_binary rule, defined at /mnt/c/Users/78299/Desktop/my_spu/spu-0.8.0b0/examples/python/ml/flax_resnet_individual/BUILD.bazel:24:10
ERROR: Skipping '//examples/python/ml/flax_resnet_individual:custom_model_inference': Error evaluating '//examples/python/ml/flax_resnet_individual:custom_model_inference': error loading package 'examples/python/ml/flax_resnet_individual': Package 'examples/python/ml/flax_resnet_individual' contains errors
WARNING: Target pattern parsing failed.                                                                                                                                                                
ERROR: Error evaluating '//examples/python/ml/flax_resnet_individual:custom_model_inference': error loading package 'examples/python/ml/flax_resnet_individual': Package 'examples/python/ml/flax_resnet_individual' contains errors
INFO: Elapsed time: 0.129s                                                                                                                                                                             
INFO: 0 processes.                                                                                                                                                                                     
FAILED: Build did NOT complete successfully (0 packages loaded)                                                                                                                                        
ERROR: Build failed. Not running target
```

**Comment by warpoons** [comment]
Hi @tpppppub. In the past two days, I have been trying to evaluate single DNN layer using SPU by defining an iso-architecture flax model with only single layer and feeding it to the backend of SPU. The flax model can successfully perform a inference by calling the `.apply` function. I noticed that in this [file](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_resnet/flax_resnet_inference.py) line 53, the `model_cipher` has two inputs including `inputs` and `params`. I understand that this is not a standard way of inferring a Flax model where `output =flax_model.apply(params, inputs)` should be the standard. So look into the class `FlaxResNetForImageClassification`, it can be find that calling it directly returns a `return self.module.apply(xxx)`. Therefore I have tried to rewrite the [inference function](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_resnet/flax_resnet_inference.py) (line 50):
def inference(inputs, params):
    ...
    outputs = model_cipher.apply(pixel_values=inputs, params=params)
    return outputs
but it reports bugs:
Traceback (most recent call last):
  File "/home/warpoons/anaconda3/envs/spu_py310/lib/python3.10/site-packages/jax/_src/core.py", line 789, in \_\_getattr\_\_
    attr = getattr(self.aval, name)
AttributeError: 'ShapedArray' object has no attribute 'apply'

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet_individual/custom_model_inference.runfiles/spulib/examples/python/ml/flax_resnet_individual/custom_model_inference.py", line 139, in <module>
    run_on_spu(x_in, flax_model, params)
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet_individual/custom_model_inference.runfiles/spulib/examples/python/ml/flax_resnet_individual/custom_model_inference.py", line 118, in run_on_spu
    outputs = ppd.device("SPU")(inference)(model, inputs, params)
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet_individual/custom_model_inference.runfiles/spulib/spu/utils/distributed.py", line 662, in \_\_call\_\_
    executable, args_flat, out_tree = self._compile_jax_func(
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet_individual/custom_model_inference.runfiles/spulib/spu/utils/distributed.py", line 738, in _compile_jax_func
    executable, output = spu_fe.compile(
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet_individual/custom_model_inference.runfiles/spulib/spu/utils/frontend.py", line 217, in compile
    ir_text, output = _jax_compilation(
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet_individual/custom_model_inference.runfiles/spulib/spu/utils/frontend.py", line 120, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet_individual/custom_model_inference.runfiles/spulib/examples/python/ml/flax_resnet_individual/custom_model_inference.py", line 110, in inference
    outputs = flax_model.apply(param, inputs)
AttributeError: DynamicJaxprTracer has no attribute apply

Could you please kindly give me some suggestions to fix this bug? I understand that this may be a Flax issue rather than SPU. I searched a lot of information and couldn't find a solution. Seeking help here may be an efficient way.

Sorry for taking your time. Thanks for your help.

**Comment by tpppppub** [comment]
I don't understand why you think using `model_cipher` default `__call__` is not a standard way to do inference. `FlaxResNetForImageClassification` has more encapsulations and it is not directly derived from Flax `nn.Module`.

**Comment by warpoons** [comment]
Hi @tpppppub. Sorry for late reply. Thanks for your help. I have successfully addressed the above issues and obtained the layer-wise communication/latency cost using SPU. Now I am planning to extend the NN architecture to MobileNetV2, and have implemented MobileNetV2 in flax and evaluate it in SPU. The model works well but encounter an additional issue as below:

Run on SPU
\------

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
Traceback (most recent call last):
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet18/flax_resnet_inference.runfiles/spulib/examples/python/ml/flax_resnet18/flax_resnet_inference.py", line 141, in <module>
    run_on_spu(inputs, params)
  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet18/flax_resnet_inference.runfiles/spulib/examples/python/ml/flax_resnet18/flax_resnet_inference.py", line 117, in run_on_spu
Exception: ('remote exception', Exception('Traceback (most recent call last):\n  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 325, in Run\n    ret_objs = fn(self, *args, **kwargs)\n  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 584, in builtin_spu_run\n    rt.run(spu_exec)\n  File "/home/waException: ('remote exception', Exception('Traceback (most recent call last):\n  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 325, in Run\n    ret_objs = fn(self, *args, **kwargs)\n  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 584, in builtin_spu_run\n    rt.run(spu_exec)\n  File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/api.py", line 44, in run\n    return self._vm.Run(executable.SerializeToString())\nRuntimeError: what: \n\t[Enforce fail at libspu/kernel/hlo/convolution.cc:41] kernel.shape()[2] == C. 1 vs 32.input/kernel channel mismatch\nstacktrace: \n\n\n'))

Mind you have a look at what problems are encountered here and any feasible way to solve it? Thanks.

**Comment by tpppppub** [comment]
Could you please share the snippet of your flax MobileNetV2?

**Comment by anakinxc** [comment]
> Hi @tpppppub. Sorry for late reply. Thanks for your help. I have successfully addressed the above issues and obtained the layer-wise communication/latency cost using SPU. Now I am planning to extend the NN architecture to MobileNetV2, and have implemented MobileNetV2 in flax and evaluate it in SPU. The model works well but encounter an additional issue as below:
> 
> Run on SPU ------
> 
> An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu. Traceback (most recent call last): File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet18/flax_resnet_inference.runfiles/spulib/examples/python/ml/flax_resnet18/flax_resnet_inference.py", line 141, in run_on_spu(inputs, params) File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet18/flax_resnet_inference.runfiles/spulib/examples/python/ml/flax_resnet18/flax_resnet_inference.py", line 117, in run_on_spu Exception: ('remote exception', Exception('Traceback (most recent call last):\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 325, in Run\n ret_objs = fn(self, *args, **kwargs)\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 584, in builtin_spu_run\n rt.run(spu_exec)\n File "/home/waException: ('remote exception', Exception('Traceback (most recent call last):\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 325, in Run\n ret_objs = fn(self, *args, **kwargs)\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 584, in builtin_spu_run\n rt.run(spu_exec)\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/api.py", line 44, in run\n return self._vm.Run(executable.SerializeToString())\nRuntimeError: what: \n\t[Enforce fail at libspu/kernel/hlo/convolution.cc:41] kernel.shape()[2] == C. 1 vs 32.input/kernel channel mismatch\nstacktrace: \n\n\n'))
> 
> Mind you have a look at what problems are encountered here and any feasible way to solve it?
> 
> By the way, the error info `kernel.shape()[2] == C. 1 vs 32.input/kernel channel mismatch` is independent of the scale of dataset. I have tried cifar10 (32x32) and tiny-imagenet (64x64) and the error information are the same. Thanks.

Can you try with latest SPU?

**Comment by warpoons** [comment]
> Could you please share the snippet of your flax MobileNetV2?

Sure. Here it is:

from functools import partial
from typing import Any, Callable, Tuple
import jax.numpy as jnp
from flax import linen as nn

ModuleDef = Any

class InvertedResBlock(nn.Module):
    """Inverted ResNet block."""

    expansion: int
    strides: Tuple[int, int]
    alpha: float
    filters: int
    block_id: int
    conv: ModuleDef
    norm: ModuleDef
    act: Callable
    dtype: Any = jnp.float32

    @nn.compact
    def __call__(self, inputs):
        prefix = "block_{}_".format(self.block_id)

        in_channels = inputs.shape[-1]
        pointwise_conv_filters = int(self.filters * self.alpha)
        pointwise_filters = _make_divisible(pointwise_conv_filters, 8)

        # Expand
        x = self.conv(
            features=in_channels * self.expansion,
            kernel_size=(1, 1),
            strides=(1, 1),
            padding="SAME",
            name=prefix + "expand",
        )(inputs)
        x = self.norm(name=prefix + "expand_bn")(x)
        x = self.act(x)

        # Depthwise
        dw_filters = x.shape[-1]
        x = self.conv(
            features=dw_filters,
            kernel_size=(3, 3),
            strides=self.strides,
            padding="SAME",
            feature_group_count=dw_filters,
            name=prefix + "depthwise",
        )(x)
        x = self.norm(name=prefix + "depthwise_bn")(x)
        x = self.act(x)

        # Project
        x = self.conv(
            features=pointwise_filters,
            kernel_size=(1, 1),
            strides=(1, 1),
            padding="SAME",
            name=prefix + "project",
        )(x)
        x = self.norm(name=prefix + "project_bn")(x)

        if in_channels == pointwise_filters and self.strides == (1, 1):
            x = x + inputs

        return x


def _make_divisible(v, divisor=8, min_value=None):
    """
    Reference:
        https://github.com/keras-team/keras/blob/v2.8.0/keras/applications/mobilenet_v2.py#L505
    """
    if min_value is None:
        min_value = divisor
    new_v = max(min_value, int(v + divisor / 2) // divisor * divisor)
    # Make sure that round down does not go down by more than 10%.
    if new_v < 0.9 * v:
        new_v += divisor
    return new_v


class MobileNetV2Backbone(nn.Module):
    """MobileNet V2 backbone."""

    alpha: float
    conv: ModuleDef = nn.Conv
    norm: ModuleDef = nn.BatchNorm
    act: Callable = nn.relu

    @nn.compact
    def __call__(self, x):
        inverted_res_block = partial(
            InvertedResBlock, conv=self.conv, norm=self.norm, act=self.act
        )

        first_block_filters = _make_divisible(32 * self.alpha, 8)

        x = self.conv(
            first_block_filters,
            kernel_size=(3, 3),
            strides=(2, 2),
            padding=[(3, 3), (3, 3)],
            name="conv_init",
        )(x)
        x = self.norm()(x)
        x = self.act(x)

        x = inverted_res_block(
            filters=16, alpha=self.alpha, strides=(1, 1), expansion=1, block_id=0
        )(x)
        x = inverted_res_block(
            filters=24, alpha=self.alpha, strides=(2, 2), expansion=6, block_id=1
        )(x)
        x = inverted_res_block(
            filters=24, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=2
        )(x)

        x = inverted_res_block(
            filters=32, alpha=self.alpha, strides=(2, 2), expansion=6, block_id=3
        )(x)
        x = inverted_res_block(
            filters=32, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=4
        )(x)
        x = inverted_res_block(
            filters=32, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=5
        )(x)

        x = inverted_res_block(
            filters=64, alpha=self.alpha, strides=(2, 2), expansion=6, block_id=6
        )(x)
        x = inverted_res_block(
            filters=64, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=7
        )(x)
        x = inverted_res_block(
            filters=64, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=8
        )(x)
        x = inverted_res_block(
            filters=64, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=9
        )(x)

        x = inverted_res_block(
            filters=96, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=10
        )(x)
        x = inverted_res_block(
            filters=96, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=11
        )(x)
        x = inverted_res_block(
            filters=96, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=12
        )(x)

        x = inverted_res_block(
            filters=160, alpha=self.alpha, strides=(2, 2), expansion=6, block_id=13
        )(x)
        x = inverted_res_block(
            filters=160, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=14
        )(x)
        x = inverted_res_block(
            filters=160, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=15
        )(x)

        x = inverted_res_block(
            filters=320, alpha=self.alpha, strides=(1, 1), expansion=6, block_id=16
        )(x)

        if self.alpha > 1.0:
            last_block_filters = _make_divisible(1280 * self.alpha, 8)
        else:
            last_block_filters = 1280

        x = self.conv(last_block_filters, kernel_size=(1, 1), name="conv_1")(x)
        x = self.norm(name="conv_1_bn")(x)
        x = self.act(x)

        return x


class MobileNetV2(nn.Module):
    """MobileNet V2."""

    alpha: float
    num_classes: int
    dtype: Any = jnp.float32
    act: Callable = nn.relu

    @nn.compact
    def __call__(self, x, train: bool = True):
        conv = partial(nn.Conv, use_bias=False, dtype=self.dtype)
        norm = partial(
            nn.BatchNorm,
            use_running_average=not train,
            momentum=0.9,
            epsilon=1e-5,
            dtype=self.dtype,
        )
        backbone = partial(
            MobileNetV2Backbone,
            alpha=self.alpha,
            conv=conv,
            norm=norm,
            act=self.act,
        )

        x = backbone()(x)

        x = jnp.mean(x, axis=(1, 2))
        x = nn.Dense(self.num_classes, dtype=self.dtype)(x)
        x = jnp.asarray(x, self.dtype)
        return x

and it is instantiated using `model = MobileNetV2(alpha=1.0, num_classes=num_classes)`. I currently use num_classes=100 for cifar100.

**Comment by warpoons** [comment]
> > Hi @tpppppub. Sorry for late reply. Thanks for your help. I have successfully addressed the above issues and obtained the layer-wise communication/latency cost using SPU. Now I am planning to extend the NN architecture to MobileNetV2, and have implemented MobileNetV2 in flax and evaluate it in SPU. The model works well but encounter an additional issue as below:
> > Run on SPU ------
> > An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu. Traceback (most recent call last): File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet18/flax_resnet_inference.runfiles/spulib/examples/python/ml/flax_resnet18/flax_resnet_inference.py", line 141, in run_on_spu(inputs, params) File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_resnet18/flax_resnet_inference.runfiles/spulib/examples/python/ml/flax_resnet18/flax_resnet_inference.py", line 117, in run_on_spu Exception: ('remote exception', Exception('Traceback (most recent call last):\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 325, in Run\n ret_objs = fn(self, *args, **kwargs)\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 584, in builtin_spu_run\n rt.run(spu_exec)\n File "/home/waException: ('remote exception', Exception('Traceback (most recent call last):\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 325, in Run\n ret_objs = fn(self, *args, **kwargs)\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 584, in builtin_spu_run\n rt.run(spu_exec)\n File "/home/warpoons/.cache/bazel/_bazel_warpoons/a8bffbc0d61f0a1b74b183a038eaeb46/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/api.py", line 44, in run\n return self._vm.Run(executable.SerializeToString())\nRuntimeError: what: \n\t[Enforce fail at libspu/kernel/hlo/convolution.cc:41] kernel.shape()[2] == C. 1 vs 32.input/kernel channel mismatch\nstacktrace: \n\n\n'))
> > Mind you have a look at what problems are encountered here and any feasible way to solve it?
> > By the way, the error info `kernel.shape()[2] == C. 1 vs 32.input/kernel channel mismatch` is independent of the scale of dataset. I have tried cifar10 (32x32) and tiny-imagenet (64x64) and the error information are the same. Thanks.
> 
> Can you try with latest SPU?

My current SPU version is 0.8.0b0. Should I use newer [0.9.0dev20240414] (https://github.com/secretflow/spu/releases/tag/0.9.0dev20240414) version?

**Comment by warpoons** [comment]
Hi @anakinxc @tpppppub, I tried the lastest SPU version 0.9.0dev20240414 and it works. Thanks you all !!!
