### ISSUE TITLE
[Bug]: The critical condition judgment is wrong

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#658]
### Issue Type

Usability

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

No

### Have you searched existing issues?

Yes

### SPU Version

07a5aa5890375c531bdfdb257c6e2a19dec800d7

### OS Platform and Distribution

Ubuntu 20.04

### Python Version

3.10

### Current Behavior?

In libspu/mpc/cheetah/rlwe/modswitch_helper.cc, there is a bug in the function `template <typename Scalar>
  void CenteralizeAt(NdArrayView<const Scalar> src, size_t mod_idx,
                     absl::Span<uint64_t> out) const`.
The main problem is the for cycle
```
for (size_t i = 0; i < n; ++i) {
      auto x128 = static_cast<uint128_t>(src[i]);
      if (x128 > t_half_) {
        uint64_t u = BarrettReduce(-x128 & mod_t_mask_, mod_qj);
        out[i] = negate_uint_mod(u, mod_qj);
      } else {
        out[i] = BarrettReduce(src[i], mod_qj);
      }
    }
```
When `x128 = t_half_`, it shoudl go to the first branch instead of the second branch due to the annotation `// view x \in [0, 2^k) as [-2^{k-1}, 2^{k-1})`. Note that the two branches give different results for `x128 = t_half_`.

### Standalone code to reproduce the issue

```Python
template <typename Scalar>
  void CenteralizeAt(NdArrayView<const Scalar> src, size_t mod_idx,
                     absl::Span<uint64_t> out) const {
    using namespace seal::util;
    SPU_ENFORCE_EQ(sizeof(Scalar) * 8, absl::bit_ceil(base_mod_bitlen_),
                   fmt::format("expect base_mod_bitlen={} but got {}",
                               base_mod_bitlen_, sizeof(Scalar) * 8));

    const auto &modulus = context_.key_context_data()->parms().coeff_modulus();
    SPU_ENFORCE(mod_idx < coeff_modulus_size(), "Centeralize: invalid mod_idx");
    size_t n = src.numel();
    SPU_ENFORCE(n == out.size(), "Centeralize: size mismatch");

    const auto &mod_qj = modulus[mod_idx];
    // view x \in [0, 2^k) as [-2^{k-1}, 2^{k-1})
    for (size_t i = 0; i < n; ++i) {
      auto x128 = static_cast<uint128_t>(src[i]);
      if (x128 > t_half_) {
        uint64_t u = BarrettReduce(-x128 & mod_t_mask_, mod_qj);
        out[i] = negate_uint_mod(u, mod_qj);
      } else {
        out[i] = BarrettReduce(src[i], mod_qj);
      }
    }
  }
```

**Comment by maths644311798** [comment]
@fionser , is this a bug?

**Comment by maths644311798** [comment]
One more question in packlwes.cc. The function `void NegacyclicRightShiftInplace(RLWECt &ct, size_t shift,
                                 const seal::SEALContext &context)` is just multiplying a plaintext $X^{shift}$. So it can be replaced by `seal::Evaluator:: multiply_plain`, right?

**Comment by fionser** [comment]
- Viewing $x \in [0, 2^k)$ as $[-2^{k-1}, 2^{k-1})$ or in $(-2^{k-1}, 2^{k-1}]$ should be all right for `CenteralizeAt.
- Yes, the document is mismatching the code in `CenteralizeAt` where the code is actually doing $(-2^{k-1}, 2^{k-1}]$ 
- For the `[0, gamma) -> [-gamma/2, gamma/2]` since `gamma` is an odd value. 
- `-xvec[i] mod 2^k` is fine, since that is what we what. The `mod q` part is defered to Line 365 or Line 367

**Comment by maths644311798** [comment]
(3) `xtmp[num_coeffs - 1 - i]` should be `xtmp[num_coeffs - i]` . Note that `-xvec[i]` mod $2^k$ mod q is different from `-xvec[i] mod q`. Actually, a possible case is `-xvec[i]` mod $2^k$ = $2^k$ - xvec[i]. And I do not understand the part $2^k$ mod q.

**Comment by fionser** [comment]
@maths644311798 

Nice catch.  The `Backward` encoding is pretty old and already not used by other cheetah's code. And yes that is a bug.

The sign flip here is ok. You can consider in this way. 

The Forward & Backward encodings are defined over the plaintext space which is modulo  2^k in SPU. Thus, the sign flip here should work over mod 2^k. 

In more details, `(-xvec[i] mod 2^k) mod q`  = `-(xvec[i] mod q)` when we view `xvec[i]` in the centric range `[-2^{k-1}, 2^{k-1})`  in stead of the unsigned range `[0, 2^k)`
