### ISSUE TITLE
[Question]: Are there any files building correspondence between the kernels and their dispatching functions?

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#674]
### Feature Request Type

Documentation

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

In libspu/mpc/ab_api.cc,  `Value a2p(SPUContext* ctx, const Value& x)` actually need a kernel named “a2p” to handle the data. 
(1) Where is the definition of the kernel named “a2p”?  Are there any files building correspondence between the kernels and their dispatching functions?
(2) What do “a”, “p” mean? Moreover, what do “s”, “v” mean?
I guess from api.h that “p” is public, “s” is secret, and “v” is private. But what is “a”?

### Describe features you want to add to SPU

Files building correspondence between the kernels and their dispatching functions.

### Describe features you want to add to SPU

Files building correspondence between the kernels and their dispatching functions.

**Comment by tpppppub** [comment]
1. The kernel is dispatched by name. Take ABY3 as an example, its "a2p" kernel is defined [here](https://github.com/secretflow/spu/blob/main/libspu/mpc/aby3/arithmetic.h#L27). 
2. "a" means that kernel processes arithmetic shares.

**Comment by maths644311798** [comment]
Does "a2p" mean that the arithmetic shares are open?

**Comment by tpppppub** [comment]
Yes
