### ISSUE TITLE
[Bug]: bitintl_b in ab_api.cc is wrong

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#675]
### Issue Type

Usability

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.1.dev

### OS Platform and Distribution

Ubuntu 22

### Python Version

3.10

### Compiler Version

gcc 13.2

### Current Behavior?

In the implementation of `Value bitintl_b(SPUContext* ctx, const Value& x, size_t stride)` in /mpc/ab_api.cc, if `TRY_DISPATCH` fails to  dispatch, then the following code is wrong since the `Value out` is not initialized by `x`. Actually, the implementation seems to be really independent of `x.data_`.

A similar bug appears in Value bitdeintl_b(SPUContext* ctx, const Value& x, size_t stride).

### Standalone code to reproduce the issue

```Python
Value bitintl_b(SPUContext* ctx, const Value& x, size_t stride) {
  TRY_DISPATCH(ctx, x, stride);

  // default implementation.
  // algorithm:
  //      0000000011111111
  // swap     ^^^^^^^^
  //      0000111100001111
  // swap   ^^^^    ^^^^
  //      0011001100110011
  // swap  ^^  ^^  ^^  ^^
  //      0101010101010101
  const size_t nbits = x.storage_type().as<BShare>()->nbits();
  SPU_ENFORCE(absl::has_single_bit(nbits));

  Value out;
  for (int64_t idx = Log2Ceil(nbits) - 2; idx >= static_cast<int64_t>(stride);
       idx--) {
    auto K = hack_make_p(ctx, spu::detail::kBitIntlKeepMasks[idx], x.shape());
    auto M = hack_make_p(ctx, spu::detail::kBitIntlSwapMasks[idx], x.shape());
    int64_t S = 1 << idx;
    // out = (out & K) ^ ((out >> S) & M) ^ ((out & M) << S);
    out = xor_bb(
        ctx,
        xor_bb(ctx, and_bp(ctx, out, K), and_bp(ctx, rshift_b(ctx, out, S), M)),
        lshift_b(ctx, and_bp(ctx, out, M), S));
  }
  out = setNumBits(out, numBits(x));
  return out;
}

Value bitdeintl_b(SPUContext* ctx, const Value& x, size_t stride) {
  TRY_DISPATCH(ctx, x, stride);

  // algorithm:
  //      0101010101010101
  // swap  ^^  ^^  ^^  ^^
  //      0011001100110011
  // swap   ^^^^    ^^^^
  //      0000111100001111
  // swap     ^^^^^^^^
  //      0000000011111111
  const size_t nbits = x.storage_type().as<BShare>()->nbits();
  SPU_ENFORCE(absl::has_single_bit(nbits));

  Value out;
  for (int64_t idx = stride; idx + 1 < Log2Ceil(nbits); idx++) {
    auto K = hack_make_p(ctx, spu::detail::kBitIntlKeepMasks[idx], x.shape());
    auto M = hack_make_p(ctx, spu::detail::kBitIntlSwapMasks[idx], x.shape());
    int64_t S = 1 << idx;
    // out = (out & K) ^ ((out >> S) & M) ^ ((out & M) << S);
    out = xor_bb(
        ctx,
        xor_bb(ctx, and_bp(ctx, out, K), and_bp(ctx, rshift_b(ctx, out, S), M)),
        lshift_b(ctx, and_bp(ctx, out, M), S));
  }
  out = setNumBits(out, numBits(x));
  return out;
}
```

**Comment by maths644311798** [comment]
@tpppppub , I have a question about #676. The operator= of `Value` uses the default "=". Then copying `data_` will use the NdArrayRef(const NdArrayRef& other) = default. Note that `NdArrayRef` has a pointer member `std::shared_ptr<yacl::Buffer> buf_`. So the pointer `buf_` will be copied to the new `Value`, pointing to the same buffer.

Maybe `Value clone() const` is better. Moreover, why not overload `operator=` of `Value`?

**Comment by anakinxc** [comment]
> Maybe `Value clone() const` is better. Moreover, why not overload `operator=` of `Value`?

There is no inplace modification here, so aliasing buffer is safe.

Copy buffer is an expensive operation and should only be used in ad-hoc manner.

`Value` is designed to be a `use-by-value` friendly and most of the time `SSA`-ish thingy, so shallow copy is always the preferred behavior.
