### ISSUE TITLE
[Bug]: gcc 11.2下的编译问题

### ISSUE THREAD

**Issue by YefanWu** [secretflow/spu#683]
### Issue Type

Build/Install

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.9.0b2

### OS Platform and Distribution

Ubuntu 20.04

### Python Version

3.9

### Compiler Version

GCC 11.2.0

### Current Behavior?

我已经尝试过使用gcc 13.1和gcc 11.2编译spu，但是都遇到了问题。虽然两次编译中遇到的问题不一样，但是可能对进行判断有帮助，所以我会把这两个问题都描述出来。

在gcc 13.1下，我遇到的问题和[Issue #612](https://github.com/secretflow/spu/issues/612)类似。我的设备上没有遇到bazel的构建配置问题，而是在emp-tool的相关代码里build报错。

而在将gcc版本降低到11.2，则会出现以下问题（Failed to find python3 binary）。在gcc 11.2下，已经尝试过运行bazel clean --expunge后再重新编译，但没有效果。

其他已经尝试过的排查
*在终端中， ls /usr/bin/python3* 都可以找到python3的二进制文件。
*依赖要求都已经满足

### Standalone code to reproduce the issue

```Python
bazel build //... -c dbg
```

### Relevant log output

```Shell
INFO: Repository llvm-project instantiated at:
  /home/user/.../..../spu/WORKSPACE:65:15: in <toplevel>
  /home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/xla/workspace2.bzl:113:19: in workspace
  /home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/tsl/workspace2.bzl:622:21: in workspace
  /home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/tsl/workspace2.bzl:364:15: in _tf_repositories
  /home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/tsl/third_party/llvm/setup.bzl:19:19: in llvm_setup
Repository rule llvm_configure defined at:
  /home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/llvm-raw/utils/bazel/configure.bzl:181:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/llvm-raw/utils/bazel/configure.bzl", line 150, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "/home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/llvm-raw/utils/bazel/configure.bzl", line 45, column 13, in _overlay_directories
                fail("Failed to find python3 binary")
Error in fail: Failed to find python3 binary
ERROR: /home/user/.../.../spu/WORKSPACE:65:15: fetching llvm_configure rule //external:llvm-project: Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/llvm-raw/utils/bazel/configure.bzl", line 150, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "/home/user/.cache/bazel/_bazel_user/26aac89990fa067152178e9d8e15d3b8/external/llvm-raw/utils/bazel/configure.bzl", line 45, column 13, in _overlay_directories
                fail("Failed to find python3 binary")
Error in fail: Failed to find python3 binary
ERROR: Skipping '//...': error loading package under directory '': no such package '@llvm-project//mlir': Failed to find python3 binary
WARNING: Target pattern parsing failed.
ERROR: error loading package under directory '': no such package '@llvm-project//mlir': Failed to find python3 binary
INFO: Elapsed time: 0.170s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded)
    currently loading: libspu/compiler/passes ... (3 packages)
```

**Comment by anakinxc** [comment]
According to [this](https://github.com/llvm/llvm-project/blob/99934daa9b795278b8cc168fad430e09473b4992/utils/bazel/configure.bzl#L45)

Can you check return value of `which python3`?

**Comment by YefanWu** [comment]
/home/user/.../anaconda3/bin/python3

**Comment by anakinxc** [comment]
> /home/user/.../anaconda3/bin/python3

out of curious, is there a system-wide python3?

**Comment by YefanWu** [comment]
看起来好像确实缺少了system-wide的/usr/bin/python3.9
whereis python

python: 
/usr/bin/python2.7 
/usr/lib/python2.7
/usr/local/lib/python2.7
/etc/python2.7

/usr/bin/python3.8
/usr/lib/python3.8 
/usr/local/lib/python3.8
/usr/include/python3.8
/etc/python3.8

/usr/lib/python3.9   
/usr/share/python 

/home/user/.../anaconda3/bin/python3.1
 /home/user/.../anaconda3/bin/python3.11
/home/user/.../anaconda3/bin/python3.11-config
 /home/user/.../anaconda3/bin/python

**Comment by anakinxc** [comment]
> 看起来好像确实缺少了system-wide的/usr/bin/python3.9 whereis python
> 
> python: /usr/bin/python2.7 /usr/lib/python2.7 /usr/local/lib/python2.7 /etc/python2.7
> 
> /usr/bin/python3.8 /usr/lib/python3.8 /usr/local/lib/python3.8 /usr/include/python3.8 /etc/python3.8
> 
> /usr/lib/python3.9 /usr/share/python
> 
> /home/user/.../anaconda3/bin/python3.1 /home/user/.../anaconda3/bin/python3.11 /home/user/.../anaconda3/bin/python3.11-config /home/user/.../anaconda3/bin/python

Can you add a system-wide python3 and try again?

**Comment by YefanWu** [comment]
还是不行 :q

**Comment by anakinxc** [comment]
> 还是不行 :q

确认一下 `/usr/bin/python3` 这个存在吗

**Comment by anakinxc** [comment]
> 存在，我可以运行这个二进制文件，版本是Python 3.9.5

有没有试一下 `bazel clean --expunge` 一下

**Comment by YefanWu** [comment]
尝试过了。

也许我可以试试别的安装方式，比如从docker安装，docker的安装方式支持对spu本身进行编译吗？我不太确定我需不需要修改spu本身的代码。我试图在spu的框架里引入一个新的mpc协议，这可能包含对Cheetah实现细节的修改。

**Comment by YefanWu** [comment]
当然首先需要把[puma-benchmark](https://github.com/AntCPLab/puma_benchmarks)先运行起来

**Comment by YefanWu** [comment]
@anakinxc 关掉这个issue吧。我重装了服务器的python和gcc依赖以后问题消失了。感谢你们的解答
