### ISSUE TITLE
[Question]: stub_method方法实现将函数交由server执行，请问如何调试server中函数的具体执行过程？

### ISSUE THREAD

**Issue by LXY-225** [secretflow/spu#688]
### Feature Request Type

Build/Install

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

在执行两方各提供一个数的乘法，即代码 c = ppd.device("SPU")(multi,)(a, b)时，通过pdb调试，执行到将P1的秘密数据生成shares，即make_shares函数

发现 NodeClient类的_call方法
rsp_gen = stub_method(
            distributed_pb2.RunRequest(data=split) for split in split_message(payload)
        )
将函数make_shares及参数序列化、切块、发送请求，之后服务器就完成了函数执行。

请问我可以通过单步调试来查看make_shares具体的代码执行过程吗？

**Comment by tpppppub** [comment]
make_shares 是对从 C++ pybind 的 MakeShares 函数的封装，你需要从 C++ debug。如果对 SPU C++ 部分有改动导致不能正确运行 python 侧的 examples，建议在 C++ 侧先通过单测/log/GDB 等方法测试和调试。

**Comment by LXY-225** [comment]
您好，我想请教如何在C++侧用semi2k协议测试或调试两个浮点数的乘法呢？大概涉及定点表示、定点截断的执行过程？

**Comment by tpppppub** [comment]
要了解执行细节的话至少需要对 SPU 的源码有一定了解，然后通过自己加 log 或 GDB 调试

**Comment by LXY-225** [comment]
好的好的，谢谢您
