### ISSUE TITLE
[Question]:  Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.0KiB (rounded to 3072)

### ISSUE THREAD

**Issue by LXY-225** [secretflow/spu#703]
### Feature Request Type

Build/Install

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

I'm testing the flax_gpt2 with the 2PC.json configuration, but it reports the following error. May I know how to solve it? 
![image](https://github.com/secretflow/spu/assets/49188739/cf522b60-bb45-406f-896f-e49f9ec76ad1)
![image](https://github.com/secretflow/spu/assets/49188739/12a84300-0f55-4bed-81e1-79635d45b4c4)

**Comment by anakinxc** [comment]
Hi @LXY-225 

We don't have GPU support for 2pc protocols, can you elaborate on details?

**Comment by LXY-225** [comment]
Using the **examples/python/conf/2pc.json** configuration with "protocol"="SEMI2K", run 
**bazel run -c opt //examples/python/utils:nodectl -- --config `pwd`/examples/python/ml/flax_gpt2/2pc. json up** and **bazel run -c opt //examples/python/ml/flax_gpt2 -- --config `pwd`/examples/python/ml/flax_gpt2/2pc.json**, get the following output:
![image](https://github.com/secretflow/spu/assets/49188739/d5954a82-80a8-44d7-8c4b-7c82d15ee638)
![image](https://github.com/secretflow/spu/assets/49188739/755329be-9f6d-4c13-8799-607bfaf18791)

**Comment by anakinxc** [comment]
Hi @LXY-225 

Looks like something thrown by Jax, are you using jax with gpu?

**Comment by LXY-225** [comment]
yes

**Comment by anakinxc** [comment]
> yes

would you mind try with cpu only jax?

**Comment by LXY-225** [comment]
OK, I try it.

**Comment by LXY-225** [comment]
1. The code runs when using cpu, but it is time consuming. How can I use gpu to speed up the execution?

2. Also, the SPU run result is different from the CPU version: 

Run on CPU
I enjoy walking with my cute dog, **but I'm not sure if I'll ever**

Run on SPU
I enjoy walking with my cute dog, **and I'm not sure if you're not**

Is this because of inaccurate truncation of SEMI2K protocol?

**Comment by anakinxc** [comment]
> 1. The code runs when using cpu, but it is time consuming. How can I use gpu to speed up the execution?
> 2. Also, the SPU run result is different from the CPU version:
> 
> Run on CPU I enjoy walking with my cute dog, **but I'm not sure if I'll ever**
> 
> Run on SPU I enjoy walking with my cute dog, **and I'm not sure if you're not**
> 
> Is this because of inaccurate truncation of SEMI2K protocol?

1. GPU support is only available to ABY3 as an experimental feature, and the actual performance gain is only ~10%.

2. Have you set fxp_exp_mode to 1 like `examples/python/ml/flax_gpt2/3pc.json`?

**Comment by LXY-225** [comment]
I didn't set fxp_exp_mode to 1. Thank you very much for your prompt reply!
