### ISSUE TITLE
我想请问一下bumblebee的复现配置

### ISSUE THREAD

**Issue by YefanWu** [secretflow/spu#708]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu.0.9.1

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python Version

3.10

### Compiler Version

gcc 11.2

### Current Behavior?

如题。我想请问一下bumblebee的复现配置，我意识到我的机器只有128G RAM，是否不足以复现bumblebee。(论文实验是384Gx 2-parties)

### Standalone code to reproduce the issue

```Python
如上
```

### Relevant log output

```Shell
如上
```

**Comment by anakinxc** [comment]
@fionser

**Comment by fionser** [comment]
GPT2, BERT-base 等小模型。应该可以跑起来。因为我的 MacMini 也能跑起来。主要是 Llama-7B 等大的模型要很大的内存。

**Comment by YefanWu** [comment]
我不是很理解。GPT-2和Bert-base他们的参数量大概是1.5B，而llama-7B为什么会消耗大1-2个数量级的内存？在3PC下甚至需要1T?

P.S. 您提到的MacMini是16/32G RAM?

**Comment by YefanWu** [comment]
感谢您的回复，这个可以issue关掉了
@fionser
