### ISSUE TITLE
thanks for your quick reply! !!!!!!!!!!!!!!!!!!!! i have solved the problem. sorry for reply late

### ISSUE THREAD

**Issue by zhangtiantian-coder** [secretflow/spu#711]
thanks for your quick reply! !!!!!!!!!!!!!!!!!!!! i have solved the problem. sorry for reply late

**Comment by tpppppub** [comment]
Could you please share some code snippets to reproduce your issue?

**Comment by zhangtiantian-coder** [comment]
> Could you please share some code snippets to reproduce your issue?
sorry for reply late.  The following is my code, Thanks for your qucik reply!!!!!!!!!! 

def func(inputs,params):
    config = VITConfig()
    model = FlaxViTForImageClassification(config=config)
    i = model(inputs,params)
    return i



sf.shutdown()
sf.init(['alice', 'bob', 'carol'], address='local')
alice, bob = sf.PYU('alice'), sf.PYU('bob')
conf = sf.utils.testing.cluster_def(['alice', 'bob', 'carol'])
conf['runtime_config']['fxp_exp_mode'] = 1
conf['runtime_config']['experimental_disable_mmul_split'] = True
spu = sf.SPU(conf)


def get_token_ids():
    inputs=jnp.array([...................])
    return inputs

def get_model_params():
    pretrained_model = FlaxViTForImageClassification.from_pretrained("google/vit-base-patch16-224-in21k")
    return pretrained_model.params


model_params = alice(get_model_params)()
input_token_ids = bob(get_token_ids)()
device = spu
model_params_, input_token_ids_ = model_params.to(device), input_token_ids.to(device)

output_token_ids = spu(func)(
            input_token_ids_, model_params_
        )
   

outputs_ids = sf.reveal(output_token_ids)

**Comment by fionser** [comment]
@zhangtiantian-coder I think you should put back the issues you have meet, and share how you solved it. This could be helpful for others who might meet the same problem as yours.

**Comment by zhangtiantian-coder** [comment]
> @zhangtiantian-coder I think you should put back the issues you have meet, and share how you solved it. This could be helpful for others who might meet the same problem as yours.
yeah , you are right!! when i change the fxp mode to 1, the problem solved successfully! Thanks for your teaching!
