### ISSUE TITLE
[Bug]: example/ml/flax_gpt2 文档依赖冲突

### ISSUE THREAD

**Issue by YefanWu** [secretflow/spu#712]
### Issue Type

Usability

### Modules Involved

Documentation/Tutorial/Example

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.1

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python Version

3.10

### Compiler Version

gcc 11.4

### Current Behavior?

[这里](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_gpt2/README.md)的第一步会为我安装jax, jaxlib==0.4.13，但是spu本身依赖jax>=0.4.26?

我下面的报错也也验证了这一点，因为'jax.extend.linear_util'是在jax>=0.4.24以后才有的写法
所以问题在于，正确的transformers版本是什么？

### Standalone code to reproduce the issue

```Python
pip install 'transformers[flax]'
```

### Relevant log output

```Shell
ModuleNotFoundError: No module named 'jax.extend.linear_util'
```

**Comment by fionser** [comment]
更新到最新的 jax, jaxlib试试

**Comment by YefanWu** [comment]
升级到最新的flax有用。我不太清楚为什么docker镜像拉过来安装的flax==0.7.0（好像是EasyLM的推荐版本？），升级到0.8.4以后能正常完成运算。
