### ISSUE TITLE
使用 SPU 实现 AP(average_precision_score) 函数

### ISSUE THREAD

**Issue by Yeekin-GYJ** [secretflow/spu#727]
>此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP)](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍
- **任务名称：** 使用 SPU 实现 AP(average_precision_score) 函数
- **技术方向：** SPU/SML
- **任务难度：** 热身🌟
- **任务期望时间：** 2-3 周
## 详细要求
- **安全性：** 无 reveal
- **功能性：** 实现 sklearn 中 average_precision_score 函数功能，支持至少一种 average 方式
- **收敛性：** 包含 simulator 跑出的实验数据并且证明收敛/正确性
- **代码规范：** Python 代码需要使用 black+isort 进行格式化（流水线包含代码规范检查卡点）
- **提交说明：** 关联该 isuue 并提交代码至 https://github.com/secretflow/spu/tree/main/sml （具体目录位置请与reviewer讨论）
- **特殊说明：** 若某个特性有特殊的限制，如需要 FM128，需要更多 fxp 等需要在注释文档中明确说明
## 能力要求
- 熟悉经典的机器学习算法
- 熟悉 JAX 或 NumPy，可以使用 NumPy 实现算法
## 操作说明
- **可参考：**
  ○ https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html
- **操作指引：** https://www.secretflow.org.cn/docs/spu/latest/en-US/getting_started/tutorials/develop_your_first_mpc_application
- **范例：** https://github.com/secretflow/spu/blob/main/sml/linear_model/simple_sgd.py
- **可参考隐语 MOOC 2期视频：**
  ○ https://www.bilibili.com/video/BV1ba4y1S73z/?spm_id_from=333.788
  ○ https://www.bilibili.com/video/BV1Qe411D7MG/?spm_id_from=333.788
- **贡献指引文档：** https://github.com/secretflow/spu/blob/main/sml/development.md

**Comment by z0gSh1u** [comment]
z0gSh1u Give it to me
