### ISSUE TITLE
老师们好，请问这个https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.1b0/tutorial/gpt2_with_spu在使用spu过程中，不需要劫持gelu函数和softmax的替换吗

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#729]
### Issue Type

Others

### Source

binary

### Secretflow Version

secretflow0.6.13

### OS Platform and Distribution

ubuntu18.04

### Python version

3.10.13

### What happend and What you expected to happen.

```shell
老师们好，请问这个https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.1b0/tutorial/gpt2_with_spu在使用spu过程中，不需要劫持gelu函数和softmax的替换吗
```

### Reproduction code to reproduce the issue.

```shell
老师们好，请问这个https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.1b0/tutorial/gpt2_with_spu在使用spu过程中，不需要劫持gelu函数和softmax的替换吗
```

**Comment by anakinxc** [comment]
Hi @zhangwaer 

不用，替换 gelu 和 softmax 是一个优化手段，不是必须的

**Comment by zhangwaer** [comment]
> Hi @zhangwaer
> 
> 不用，替换 gelu 和 softmax 是一个优化手段，不是必须的

也就是spu已经实现了非线性函数比如指数和倒数的替换了吗，直接使用就可以了吗

**Comment by anakinxc** [comment]
> > Hi @zhangwaer
> > 不用，替换 gelu 和 softmax 是一个优化手段，不是必须的
> 
> 也就是spu已经实现了非线性函数比如指数和倒数的替换了吗，直接使用就可以了吗

是的

**Comment by zhangwaer** [comment]
> > > Hi @zhangwaer
> > > 不用，替换 gelu 和 softmax 是一个优化手段，不是必须的
> > 
> > 
> > 也就是spu已经实现了非线性函数比如指数和倒数的替换了吗，直接使用就可以了吗
> 
> 是的

谢谢谢谢！请问指数函数的运算在哪个文件夹呢

**Comment by anakinxc** [comment]
[exp](https://github.com/secretflow/spu/blob/000eecffa8ae2c4cc8be21eeec54bb9285ce0582/libspu/kernel/hal/fxp_approx.cc#L255)

[reciprocal](https://github.com/secretflow/spu/blob/000eecffa8ae2c4cc8be21eeec54bb9285ce0582/libspu/kernel/hal/fxp_base.cc#L90)

**Comment by zhangwaer** [comment]
> [exp](https://github.com/secretflow/spu/blob/000eecffa8ae2c4cc8be21eeec54bb9285ce0582/libspu/kernel/hal/fxp_approx.cc#L255)
> 
> [reciprocal](https://github.com/secretflow/spu/blob/000eecffa8ae2c4cc8be21eeec54bb9285ce0582/libspu/kernel/hal/fxp_base.cc#L90)

谢谢谢谢！
