### ISSUE TITLE
[Bug]: when i try to use torch model in spu,it error

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#736]
### Issue Type

Build/Install

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.5.0

### OS Platform and Distribution

ubuntu18.04

### Python Version

3.10.13

### Compiler Version

GCC11.2.1

### Current Behavior?

)>' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.

### Standalone code to reproduce the issue

```Python
)>' with dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
```

**Comment by anakinxc** [comment]
Hi @zhangwaer 

Torch support is still highly experimental at latest version. Please make sure you are using latest version and follows [this](https://github.com/secretflow/spu/blob/main/examples/python/ml/torch_lr_experiment/torch_lr_experiment.py) example.

**Comment by tpppppub** [comment]
hi @zhangwaer , could you please share your code snippets to reproduce your issue?

**Comment by zhangtiantian-coder** [comment]
> hi @zhangwaer , could you please share your code snippets to reproduce your issue?

thanks for your advice! i will open a new issue

**Comment by zhangtiantian-coder** [comment]
> Hi @zhangwaer
> 
> Torch support is still highly experimental at latest version. Please make sure you are using latest version and follows [this](https://github.com/secretflow/spu/blob/main/examples/python/ml/torch_lr_experiment/torch_lr_experiment.py) example.

thanks for your advice!

**Comment by zhangwaer** [comment]
> Hi @zhangwaer
> 
> Torch support is still highly experimental at latest version. Please make sure you are using latest version and follows [this](https://github.com/secretflow/spu/blob/main/examples/python/ml/torch_lr_experiment/torch_lr_experiment.py) example.

thank you!!

**Comment by zhangwaer** [comment]
> hi @zhangwaer , could you please share your code snippets to reproduce your issue?

you are right, i will reproduce my issue, thank you!!
