### ISSUE TITLE
[Bug]: when i try to use torch_xla, i found it error. i wanna to know whether my version of python、torch、torch_xla is wrong, is there other method which can avoid install torch_xla and still use spu on torch ,thank you very muc

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#741]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.9.0b1

### OS Platform and Distribution

ubuntu18.04

### Python Version

3.10.14

### Compiler Version

7.5.0

### Current Behavior?

Dear teachers:

When download with"pip install torch~=2.3.0 torch_xla[tpu]~=2.3.0 -f https://storage.googleapis.com/libtpu-releases/index.html"
It report ERROR: Could not find a version that satisfies the requirement torch_xla~=2.3.0 (from versions: none)
ERROR: No matching distribution found for torch_xla~=2.3.0

So i use "pip install torch_xla[tpu] -f https://storage.googleapis.com/libtpu-releases/index.html"

After the install , i code "import torch_xla", 

It report "ImportError: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.30' not found (required by /miniconda3/envs/sf/lib/python3.10/site-packages/_XLAC.cpython-310-x86_64-linux-gnu.so)"

and

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "miniconda3/envs/sf/lib/python3.10/site-packages/torch_xla/__init__.py", line 7, in <module>
    import _XLAC
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

after deal with the above problems

i met the following error, i wanna to know whether my version of python、torch、torch_xla is wrong, is there other method which can avoid install torch_xla  and still use spu on torch ,thank you very much:

[  python3.10.14  torch2.3.0   torch-xla2.4.0+gitcb6549a   torch-xla-cuda-plugin     2.3.0 ]

$HOME/glibc-2.30/lib/ld-2.30.so --library-path $HOME/glibc-2.30/lib:/jty/zhangwang/miniconda3/envs/sf/lib /jty/zhangwang/miniconda3/envs/sf/bin/python -c "import torch_xla"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/miniconda3/envs/sf/lib/python3.10/site-packages/torch_xla/__init__.py", line 7, in <module>
    import _XLAC
ImportError: /miniconda3/envs/sf/lib/python3.10/site-packages/_XLAC.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c105Error4whatEv

### Standalone code to reproduce the issue

```Python
thank you very much!!!
```

**Comment by zhangwaer** [comment]
thank you very much, i have solveit!!

**Comment by tpppppub** [comment]
“importError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory”

Your can refer to [this](https://stackoverflow.com/questions/73582092/importerror-libpython3-8-so-1-0-cannot-open-shared-object-file-no-such-file-o), find your libpython local path and add it to `LD_LIBRARY_PATH ` environment variable

**Comment by zhangwaer** [comment]
> “importError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory”
> 
> Your can refer to [this](https://stackoverflow.com/questions/73582092/importerror-libpython3-8-so-1-0-cannot-open-shared-object-file-no-such-file-o), find your libpython local path and add it to `LD_LIBRARY_PATH ` environment variable

thanks you very much!!!
