### ISSUE TITLE
[Bug]:  dear teachers， after i download spu, i wanna to run "bazel run -c opt //examples/python/utils:nodectl -- up", but i can not find this folder, should i download it from github

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#744]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.8.0.dev20240202

### OS Platform and Distribution

ubuntu20.04

### Python Version

3.8.19

### Compiler Version

gcc9.4.0

### Current Behavior?

[Bug]:  dear teachers， after i download spu, i wanna to run "bazel run -c opt //examples/python/utils:nodectl -- up", but i can not find this folder, should i download the examples folder from github?

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by tpppppub** [comment]
Bazel is used for building/running from source code. git clone the code from github and refer to this [document](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#build) to prepare required environment and run this command.

**Comment by zhangwaer** [comment]
> Bazel is used for building/running from source code. git clone the code from github and refer to this [document](https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#build) to prepare required environment and run this command.

thank you very much, i install the spu through “ pip install spu” before

**Comment by zhangwaer** [comment]
> > Server terminated abruptly (error code: 14, error message: 'Connection reset by peer', log file: '/root/.cache/bazel/_bazel_root/caf5b7ace780bc9a154e315494716fe1/server/jvm.out')
> 
> feels like oom
thank you very much!!  i think you are right, when i reboot my computer, it load from 497/3725 to 849/3725, it still running more now.
I'm considering leasing a server that offers enhanced CPU performance. could you please give me some advice, i am going to test spu on gpt2_torch version

**Comment by zhangwaer** [comment]
> > Server terminated abruptly (error code: 14, error message: 'Connection reset by peer', log file: '/root/.cache/bazel/_bazel_root/caf5b7ace780bc9a154e315494716fe1/server/jvm.out')
> 
> feels like oom

dear teachers, when i change a 128G cpu computer, i enter "bazel run -c opt //examples/python/utils:nodectl -- up"
it output as follows:
[2024-06-25 10:13:37,941] [ForkServerProcess-4] Starting grpc server at 127.0.0.1:61923
[2024-06-25 10:13:37,986] [ForkServerProcess-3] Starting grpc server at 127.0.0.1:61922
[2024-06-25 10:13:37,987] [ForkServerProcess-1] Starting grpc server at 127.0.0.1:61920
[2024-06-25 10:13:38,011] [ForkServerProcess-2] Starting grpc server at 127.0.0.1:61921
[2024-06-25 10:13:38,016] [ForkServerProcess-5] Starting grpc server at 127.0.0.1:61924

but in 3pc.json, there are 8 port, the above are only 5 port, how can i use the port

3pc.json:
{
    "id": "outsourci.3pc",
    "nodes": {
        "node:0": "127.0.0.1:39439",
        "node:1": "127.0.0.1:39440",
        "node:2": "127.0.0.1:39441",
        "node:3": "127.0.0.1:39442",
        "node:4": "127.0.0.1:39443"
    },
    "devices": {
        "SPU": {
            "kind": "SPU",
            "config": {
                "node_ids": [
                    "node:0",
                    "node:1",
                    "node:2"
                ],
                "spu_internal_addrs": [
                    "127.0.0.1:39411",
                    "127.0.0.1:39412",
                    "127.0.0.1:39413"
                ],
                "experimental_data_folder": [
                    "/tmp/spu_data_0/",
                    "/tmp/spu_data_1/",
                    "/tmp/spu_data_2/"
                ],
                "runtime_config": {
                    "protocol": "ABY3",
                    "field": "FM64",
                    "enable_pphlo_profile": true,
                    "enable_hal_profile": true
                }
            }
        },
        "P1": {
            "kind": "PYU",
            "config": {
                "node_id": "node:3"
            }
        },
        "P2": {
            "kind": "PYU",
            "config": {
                "node_id": "node:4"
            }
        }
    }
}

**Comment by tpppppub** [comment]
Specify your config file explicitly like this `bazel run -c opt //examples/python/utils:nodectl -- --config /path/to/your/json up`. Five ports are used for python level nodes orchestration communication, the remaining three ports are used for C++ level MPC communications.

**Comment by zhangwaer** [comment]
> Specify your config file explicitly like this `bazel run -c opt //examples/python/utils:nodectl -- --config /path/to/your/json up`. Five ports are used for python level nodes orchestration communication, the remaining three ports are used for C++ level MPC communications.

dear teachers, i successfully started the nodes, and i try to use spu on gpt2_torch, it report errors as follows:


/usr/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1719329816.021593   14936 cpu_client.cc:405] TfrtCpuClient created.
Traceback (most recent call last):
  File "/a-tmp/aa/gg.py", line 20, in <module>
    res = ppd.device("SPU")(model)(params, inputs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 896, in __call__
    executable, args_flat, out_tree = self._compile_torch_func(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 968, in _compile_torch_func
    executable, output_tree, args_flat = spu_fe.torch_compile(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/frontend.py", line 303, in torch_compile
    args_params_flat.append(state_dict[loc.name])
                            ~~~~~~~~~~^^^^^^^^^^
KeyError: 'transformer.h.0.attn.bias'
I0000 00:00:1719329817.954742   14936 cpu_client.cc:408] TfrtCpuClient destroyed.



the code is as follows, could you please give me some suggestions, thank you very much!!


import torch
from transformers import AutoTokenizer, GPT2LMHeadModel, GPT2Config
import spu.utils.distributed as ppd
import json
import urllib
from collections import OrderedDict
from jax.tree_util import tree_map
with open("3pc.json", 'r') as file:
    conf = json.load(file)
ppd.init(conf["nodes"], conf["devices"], framework=ppd.Framework.EXP_TORCH)

model = GPT2LMHeadModel.from_pretrained("g")

tokenizer=AutoTokenizer.from_pretrained("g")
inputs = tokenizer.encode("Hello, my dog is cute", return_tensors="pt")

params = ppd.device("P1")(lambda input: tree_map(lambda x: x.detach().numpy(), input))(model.state_dict())
inputs= ppd.device("P2")(lambda x: x.detach().numpy())(inputs)

res = ppd.device("SPU")(model)(params, inputs)
logits= ppd.get(res).logits
print(logits)
