### ISSUE TITLE
[Bug]: dear teachers, i successfully started the nodes, and i try to use spu on gpt2_torch, it report errors as follows

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#745]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.9.1b0

### OS Platform and Distribution

ubuntu18.04

### Python Version

python3.11.8

### Compiler Version

GCC11.2.0

### Current Behavior?

dear teachers, i successfully started the nodes, and i try to use spu on gpt2_torch, it report errors as follows:

/usr/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1719329816.021593   14936 cpu_client.cc:405] TfrtCpuClient created.
Traceback (most recent call last):
  File "/a-tmp/aa/gg.py", line 20, in <module>
    res = ppd.device("SPU")(model)(params, inputs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 896, in __call__
    executable, args_flat, out_tree = self._compile_torch_func(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 968, in _compile_torch_func
    executable, output_tree, args_flat = spu_fe.torch_compile(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/frontend.py", line 303, in torch_compile
    args_params_flat.append(state_dict[loc.name])
                            ~~~~~~~~~~^^^^^^^^^^
KeyError: 'transformer.h.0.attn.bias'
I0000 00:00:1719329817.954742   14936 cpu_client.cc:408] TfrtCpuClient destroyed.



the code is as follows, could you please give me some suggestions, thank you very much!!


import torch
from transformers import AutoTokenizer, GPT2LMHeadModel, GPT2Config
import spu.utils.distributed as ppd
import json
import urllib
from collections import OrderedDict
from jax.tree_util import tree_map
with open("3pc.json", 'r') as file:
    conf = json.load(file)
ppd.init(conf["nodes"], conf["devices"], framework=ppd.Framework.EXP_TORCH)

model = GPT2LMHeadModel.from_pretrained("gpt2")

tokenizer=AutoTokenizer.from_pretrained("gpt2")
inputs = tokenizer.encode("Hello, my dog is cute", return_tensors="pt")

params = ppd.device("P1")(lambda input: tree_map(lambda x: x.detach().numpy(), input))(model.state_dict())
inputs= ppd.device("P2")(lambda x: x.detach().numpy())(inputs)

res = ppd.device("SPU")(model)(params, inputs)
logits= ppd.get(res).logits
print(logits)


### Standalone code to reproduce the issue

```Python
print("A bug")
```


### Relevant log output

_No response_

**Comment by tpppppub** [comment]
try replace params with
```python
    from collections import OrderedDict

    params_buffers = OrderedDict()
    for k, v in model.named_parameters():
        params_buffers[k] = v
    for k, v in model.named_buffers():
        params_buffers[k] = v
    params = ppd.device("P1")(
        lambda input: tree_map(lambda x: x.detach().numpy(), input)
    )(params_buffers)
```

**Comment by zhangwaer** [comment]
> try replace params with
> 
> ```python
>     from collections import OrderedDict
> 
>     params_buffers = OrderedDict()
>     for k, v in model.named_parameters():
>         params_buffers[k] = v
>     for k, v in model.named_buffers():
>         params_buffers[k] = v
>     params = ppd.device("P1")(
>         lambda input: tree_map(lambda x: x.detach().numpy(), input)
>     )(params_buffers)
> ```

thanks for your advice, but when change the params, it still report the same error:
Traceback (most recent call last):
  File "/hy-tmp/aa/gg.py", line 29, in <module>
    res = ppd.device("SPU")(model)(params, inputs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 896, in __call__
    executable, args_flat, out_tree = self._compile_torch_func(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 968, in _compile_torch_func
    executable, output_tree, args_flat = spu_fe.torch_compile(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/frontend.py", line 303, in torch_compile
    args_params_flat.append(state_dict[loc.name])
                            ~~~~~~~~~~^^^^^^^^^^
KeyError: 'lm_head.weight'
I0000 00:00:1719369178.827899   14330 cpu_client.cc:408] TfrtCpuClient destroyed.

**Comment by zhangwaer** [comment]
> > try replace params with
> > ```python
> >     from collections import OrderedDict
> > 
> >     params_buffers = OrderedDict()
> >     for k, v in model.named_parameters():
> >         params_buffers[k] = v
> >     for k, v in model.named_buffers():
> >         params_buffers[k] = v
> >     params = ppd.device("P1")(
> >         lambda input: tree_map(lambda x: x.detach().numpy(), input)
> >     )(params_buffers)
> > ```
> 
> thanks for your teaching, but when change the params, it still report the same error: Traceback (most recent call last): File "/a-tmp/aa/gg.py", line 29, in res = ppd.device("SPU")(model)(params, inputs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 896, in **call** executable, args_flat, out_tree = self._compile_torch_func( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 968, in _compile_torch_func executable, output_tree, args_flat = spu_fe.torch_compile( ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/spu/utils/frontend.py", line 303, in torch_compile args_params_flat.append(state_dict[loc.name]) ~~~~~~~~~~^^^^^^^^^^ KeyError: 'lm_head.weight' I0000 00:00:1719369178.827899 14330 cpu_client.cc:408] TfrtCpuClient destroyed.

**Comment by tpppppub** [comment]
try this
```python
    params_buffers = OrderedDict()
    for k, v in model.named_parameters():
        params_buffers[k] = v
    for k, v in model.named_buffers():
        params_buffers[k] = v
    for k, v in model.state_dict().items():
        params_buffers[k] = v
```

**Comment by zhangwaer** [comment]
> try this
> 
> ```python
>     params_buffers = OrderedDict()
>     for k, v in model.named_parameters():
>         params_buffers[k] = v
>     for k, v in model.named_buffers():
>         params_buffers[k] = v
>     for k, v in model.state_dict().items():
>         params_buffers[k] = v
> ```

thanks for your teaching!! when change the params ,the error changed as follows:



You are using PyTorch as frontend framework, which is experimental.
/usr/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1719369527.633534   16989 cpu_client.cc:405] TfrtCpuClient created.
Traceback (most recent call last):
  File "/a-tmp/aa/gg.py", line 32, in <module>
    res = ppd.device("SPU")(model)(params, inputs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 916, in __call__
    results = [future.result() for future in futures]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 916, in <listcomp>
    results = [future.result() for future in futures]
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 247, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/spu/utils/distributed_impl.py", line 240, in _call
    raise Exception("remote exception", result)
Exception: ('remote exception', Exception('Traceback (most recent call last):\n  File "/root/.cache/bazel/_bazel_root/caf5b7ace780bc9a154e315494716fe1/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed_impl.py", line 326, in Run\n    ret_objs = fn(self, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/root/.cache/bazel/_bazel_root/caf5b7ace780bc9a154e315494716fe1/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed_impl.py", line 589, in builtin_spu_run\n    rt.run(spu_exec)\n  File "/root/.cache/bazel/_bazel_root/caf5b7ace780bc9a154e315494716fe1/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/api.py", line 44, in run\n    return self._vm.Run(executable.SerializeToString())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nRuntimeError: what: \n\t[libspu/device/pphlo/pphlo_intrinsic_executor.cc:150] Unhandled intrinsic call pphlo.gather\nstacktrace: \n#0 spu::device::pphlo::dispatchOp<>()+0x146be5826bfd\n#1 spu::device::pphlo::dispatchOp<>()+0x146be5829401\n#2 spu::device::pphlo::dispatchOp<>()+0x146be5829ca3\n#3 spu::device::pphlo::dispatchOp<>()+0x146be582ba2f\n#4 spu::device::pphlo::dispatchOp<>()+0x146be582dca4\n#5 spu::device::runBlock()+0x146be59a3f75\n#6 spu::device::runRegion()+0x146be59a5f83\n#7 spu::device::executeImpl()+0x146be52fdf71\n#8 spu::RuntimeWrapper::Run()+0x146be4603579\n#9 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x146be45d6615\n#10 pybind11::cpp_function::dispatcher()+0x146be45cb9a6\n#11 (unknown)+0x5ed889\n\n\n'))
I0000 00:00:1719369542.711288   16989 cpu_client.cc:408] TfrtCpuClient destroyed.

**Comment by tpppppub** [comment]
Thanks for reporting. This is a bug and will be fixed soon. Currently you can try with commit before 389327a1d94786dd94ff0aa12a963efdea6f531d.

**Comment by zhangwaer** [comment]
> Thanks for reporting. This is a bug and will be fixed soon. Currently you can try with commit before [389327a](https://github.com/secretflow/spu/commit/389327a1d94786dd94ff0aa12a963efdea6f531d).

thanks for your teaching!!, so i could try replace the file in spu with the previous version to solve the bug? For example, replace "pphlo_intrinsic_executor.cc" with the previous version in https://github.com/secretflow/spu/commit/389327a1d94786dd94ff0aa12a963efdea6f531d

**Comment by zhangwaer** [comment]
> Just replace the single file may be not enough. I recommend to use previous versions.

thanks very much!!, i will try to use spu0.6.0b0

**Comment by zhangwaer** [comment]
> > Just replace the single file may be not enough. I recommend to use previous versions.
> 
> thanks very much!!, i wanna try to use spu0.6.0b0.

**Comment by tpppppub** [comment]
You can just git checkout to the last commit before [389327a](https://github.com/secretflow/spu/commit/389327a1d94786dd94ff0aa12a963efdea6f531d) and run the same steps as you did before.

**Comment by zhangwaer** [comment]
> You can just git checkout to the last commit before [389327a](https://github.com/secretflow/spu/commit/389327a1d94786dd94ff0aa12a963efdea6f531d) and run the same steps as you did before.

thank you very much, i install the spu From Pypi rather than From Source, after the install, i find there is no "examples/python/utils/nodectl", then i download the spu folder from github. Maybe this is the reason for the error above?

**Comment by tpppppub** [comment]
Please follow the readme to run nodes and examples both with bazel from source code. If you run nodes with bazel and examples with pypi package, the SPU frondend/backend are mismatched and may encounter unexpected behavior.

**Comment by zhangwaer** [comment]
> Please follow the readme to run nodes and examples both with bazel from source code. If you run nodes with bazel and examples with pypi package, the SPU frondend/backend are mismatched and may encounter unexpected behavior.

thank you very much, when i run nodes and examples both with bazel from source code, it worked successfully. but i found there is no spu.log without secretflow,  could you please give me some teaching on how to open the spulog to record the communication rounds

**Comment by tpppppub** [comment]
enable profiling options in config json like [this](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_gpt2/3pc.json#L27)

**Comment by zhangwaer** [comment]
> enable profiling options in config json like [this](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_gpt2/3pc.json#L27)

thank you very much, i do it as the config, but i cannot find spu.log, i used the following command:
sudo find / -type f -name "spu.log"

**Comment by anakinxc** [comment]
> > enable profiling options in config json like [this](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_gpt2/3pc.json#L27)
> 
> thank you very much, i do it as the config, but i cannot find spu.log, i used the following command: sudo find / -type f -name "spu.log"

all spu logs are printed to console. If you want to save it to a file, you need to manually pipe logs to files.

**Comment by zhangwaer** [comment]
> > > enable profiling options in config json like [this](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_gpt2/3pc.json#L27)
> > 
> > 
> > thank you very much, i do it as the config, but i cannot find spu.log, i used the following command: sudo find / -type f -name "spu.log"
> 
> all spu logs are printed to console. If you want to save it to a file, you need to manually pipe logs to files.

thank you very much!!, i understand it
