### ISSUE TITLE
Security check in malicious security protocol

### ISSUE THREAD

**Issue by DuanYuFi** [secretflow/spu#75]
Hi, I'm now trying to implement *SpdzWiseField* protocol into spu and I am now analysing the feasibility and designing the code. I noticed that there isn't malicious security protocol in spu yet, so here is a problem that where to do the security check is good and efficient. Putting them into the end of kernels like `MulAA` is proper? Or setting a batch size to check them in batches? Thanks!

**Comment by rivertalk** [comment]
Hi @DuanYuFi , thanks for the question

> Putting them into the end of kernels like MulAA is proper? Or setting a batch size to check them in batches? 

I think it depends.

The `MulAA` operator only responsible for multiply two arithmetic shares, it `does not` have any security related semantic, the security semantic is guaranteed by the protocol itself.

My suggestion is, first ignore the perf problem, implement a correct malicious `MulAA` first, then when tuning performance, the protocol can decide to record some batch information as a `State` and use it do multi-batch verification.

**Comment by DuanYuFi** [comment]
I see, you mean now I first focus on the semi-honest operations and later decide where to verify?

**Comment by rivertalk** [comment]
Yes, and of course you can also do verification at each `MulAA`. :P

**Comment by DuanYuFi** [comment]
I think verifying at each `MulAA` will increase the communication costs. I'll just store the multiplication triples in `State` and verify in somewhere else. Thanks for your help :)

**Comment by kkonevets** [comment]
@DuanYuFi Hey, did you integrate any malicious protocol into SPU? Do you have any link to your results? I need to use malicious protocol too, any help is appreciated

**Comment by DuanYuFi** [comment]
@kkonevets Hi, 
I tried to add the SpdzWise Field protocol (https://eprint.iacr.org/2018/570) based on a very old version of SPU, and this is not finished yet ([code](https://github.com/DuanYuFi/spu/tree/feat-spdzwise), the code may be hard to read). But it cannot work in the latest version of SPU.
By the way, SPU now supports Spdz2K (https://eprint.iacr.org/2018/482) protocol based on a trusted third party to provide beaver triples. However, if you want to add a new protocol, you can refer to [this](https://www.secretflow.org.cn/docs/spu/latest/en-US/development/add_protocols) document. And if you want to achieve malicious security, you can refer to the Spdz2K protocol in SPU, especially how to deal with I/O, communicator, randomness, etc. 
Other contributors in the community are also very nice. You can ask them for help. Good luck! :)

**Comment by kkonevets** [comment]
Thanks for your reply. 
As [this](https://www.secretflow.org.cn/docs/spu/latest/en-US/reference/mpc_status#supported-mpc-protocol) doc states they support semi-honest Semi2k-SPDZ protocol, not a malicious. Any ideas why? According to the [paper](https://eprint.iacr.org/2018/482) SPDZ2k is a malicious protocol (also MP-SPDZ states it is). 
Also tanks for the links you provided.

**Comment by tpppppub** [comment]
1. The main reason behind this is due to performance considerations.

**Comment by kkonevets** [comment]
Thanks. I will read [this](https://www.secretflow.org.cn/docs/spu/latest/en-US/development/add_protocols) doc first and will try to create a merge request if things go well.
