### ISSUE TITLE
源码安装出现错误

### ISSUE THREAD

**Issue by muou55555** [secretflow/spu#76]
我想用源码安装secureflow，在执行python setup.py bdist_wheel时，出现以下错误：
![image](https://user-images.githubusercontent.com/5515510/212868494-bd0d3f4d-bf44-4dce-b026-70563d946251.png)

我的机器环境  centos 7.9, 已安装bazel 5.11、devtoolset-11、cmake 4.2.1

**Comment by anakinxc** [comment]
duplicate https://github.com/secretflow/secretflow/issues/272
