### ISSUE TITLE
[Question]: Does SPU support bigdata or parallel computing

### ISSUE THREAD

**Issue by xyz-scorpio** [secretflow/spu#761]
### Feature Request Type

Performance

### Have you searched existing issues?

Yes

### Describe features you want to add to SPU

Just want to know if SPU supports bigdata / parallel computing, and if yes, in what way did it support such a think. TY.

**Comment by tpppppub** [comment]
There are various granularities of parallelism and vectorization within the SPU. It's not clear what your specific requirements are. How much data do you need to process and what granularity of parallelism do you need?

**Comment by xyz-scorpio** [comment]
> There are various granularities of parallelism and vectorization within the SPU. It's not clear what your specific requirements are. How much data do you need to process and what granularity of parallelism do you need?

Let us take the SPU [workflow](https://cdn.nlark.com/yuque/0/2022/png/29690418/1658470423867-a5e4fe16-9ac8-4c63-b872-61139a02881e.png) as an example. My question is: 
i) What is the upper bound of data scale that SPU could handle? If I write some code to train a model with tensorflow, on very large datasets (e.g. ~TB) from different parties, how does SPU handle that? Will it do data parallel automaticly?
ii) How many resources can a SPU VM take advantage of? Say, if I have 4 AWS EC2s, can one SPU VM take advantage of all 4 EC2s, or just one EC2 instance? And what is the parallel model of SPU VM?

**Comment by anakinxc** [comment]
> > There are various granularities of parallelism and vectorization within the SPU. It's not clear what your specific requirements are. How much data do you need to process and what granularity of parallelism do you need?
> 
> ![image](https://private-user-images.githubusercontent.com/23226534/347341184-bd1c20af-b8b8-4ab2-8dc4-3bd7de3a8c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTE0MzMsIm5iZiI6MTcyMTM5MTEzMywicGF0aCI6Ii8yMzIyNjUzNC8zNDczNDExODQtYmQxYzIwYWYtYjhiOC00YWIyLThkYzQtM2JkN2RlM2E4YzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEyMTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NDllMDBiMDdiMTY4YjMxMTc1MzZkODViN2NhZjExZTQxNmNjMDFlYzkxODAxYzFmOTM5NGVkYmI5MWIzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y-uGAtICbFl9gMvDN5S6K4vdsf9yVnUnpvcIiVrBCTk)
> 
> Let us take the SPU workflow as an example. My question is: i) What is the upper bound of data scale that SPU could handle? If I write some code to train a model with tensorflow, on very large datasets (e.g. ~TB) from different parties, how does SPU handle that? Will it do data parallel automaticly? ii) How many resources can a SPU VM take advantage of? Say, if I have 4 AWS EC2s, can one SPU VM take advantage of all 4 EC2s, or just one EC2 instance? And what is the parallel model of SPU VM?

1. We do not have a hard limit on data size. It is up to frameworks like `Tensorflow` to properly handles such large data through batching or some other techniques.
2. At this point, `SPU` can only take one machine. Right now, `SPU` only supports DLP and ILP on one machine.
