### ISSUE TITLE
[Question]: Is `msb_s` good to use or buggy?

### ISSUE THREAD

**Issue by linzzzzzz** [secretflow/spu#769]
### Feature Request Type

Usability

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

Two questions:
1. Is `msb_s` good to use or still buggy?
2. I saw two functions `msb_s` and `msb_v`. What is the difference between secret and private? any good doc on the difference?

https://github.com/secretflow/spu/blob/fcef2ff4ae58d15e4e2df48369b4cd8577a01552/libspu/mpc/api.cc#L301

### Describe features you want to add to SPU

--

### Describe features you want to add to SPU

--

**Comment by anakinxc** [comment]
> ### Feature Request Type
> Usability
> 
> ### Have you searched existing issues?
> Yes
> 
> ### Is your feature request related to a problem?
> Two questions:
> 
> 1. Is `msb_s` good to use or still buggy?
> 2. I saw two functions `msb_s` and `msb_v`. What is the difference between secret and private? any good doc on the difference?
> 
> https://github.com/secretflow/spu/blob/fcef2ff4ae58d15e4e2df48369b4cd8577a01552/libspu/mpc/api.cc#L301
> 
> ### Describe features you want to add to SPU
> --
> 
> ### Describe features you want to add to SPU
> --

1. Yes, still good to use.
2. Private is still an experimental feature, so not well documented at this point. 

In general, `private` is a special `secret`, you can think it as a pre-shared `secret` where the owner has the plaintext data and others just meta info. 

It may reduce some `public x secret` and `secret x secret` computations into cheaper `private` computations
