### ISSUE TITLE
[Question]: protocol for secure bit-wise comparison in Cheetah

### ISSUE THREAD

**Issue by linzzzzzz** [secretflow/spu#784]
### Feature Request Type

Documentation

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

1. Which specific protocol for secure bit-wise comparison is Cheetah using? Some paper links or documentation would be helpful.

2. In order to privately compute the argmax in Cheetah, are you **reconstructing** the output of the secure bit-wise comparison protocol for every pair of comparison (I know tree-reduction is applied to reduce the number of comparisons), and then directly comparing the reconstructed result in plaintext to get the argmax?

3. Could you please point us to where in your codebase you implement the MPC protocol for secure bit-wise comparison?

### Describe features you want to add to SPU

--

### Describe features you want to add to SPU

--

**Comment by anakinxc** [comment]
Hi @fionser, can you take a look? thanks

**Comment by fionser** [comment]
- The argmax is basically a maximum with an extra selection operation on the index. See the [lax code](https://github.com/google/jax/blob/ca70ebbb868dc76ebf895122e8bcd0dd5c62d962/jax/_src/lax/lax.py#L4125). 
- I am not sure what you call `bit-wise` comparison, does it different with the comparison between two secret shares ?

**Comment by fionser** [comment]
1. `(x-y)` is in binary representation ...  ==> we can just view it as  `x - y mod 2^k \in [0, 2^k)` (i.e,. unsigned modulus subtraction) 
3. There is a typo but the correct formula is `msb(x) = msb(x0) ^ msb(x1) ^ 1(x0 mod 2^{k-1} + x1 mod 2^{k-1} >= 2^{k-1})`. That is the carry bit is to see whether the sum the lowest `k-1` bits of the two share `x0 , x1` overflow to the highest bit (k-th bit) or not.

**Comment by fionser** [comment]
* SS-XGB is extremely **inefficient** for the Cheetah's backend。 Make sure you what you want, the training database is vertical split for horizontally split ?
* The secure argmax should give you the secret share of one index (i.e., index of bin) of the maximum score.
