### ISSUE TITLE
[Bug]: squirrel experiment

### ISSUE THREAD

**Issue by yuan1995** [secretflow/spu#785]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

63cce33618b9b3d76761126453851f72d56fbf8b

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.10

### Compiler Version

GCC 11.2

### Current Behavior?

Running directly results in the following bug：
![image](https://github.com/user-attachments/assets/912ec586-da43-4733-ba19-014d7c9f1677)
specifying the num_tree parameter value allows it to run normally.
![image-1](https://github.com/user-attachments/assets/c14f4b25-ed68-4f51-aac6-2d0fc271787c)

### Standalone code to reproduce the issue

```Python
./squirrel_demo_main --rank0_nfeatures=7 --rank1_nfeatures=8 --standalone --train=breast_cancer_b.csv --test=breast_cancer_b-test.csv --standalone=true --rank=1 --has_label=1 --lr=1.0 --subsample=0.8

./squirrel_demo_main --rank0_nfeatures=7 --rank1_nfeatures=8 --standalone --train=breast_cancer_b.csv --test=breast_cancer_b-test.csv --standalone=true --rank=1 --has_label=1 --lr=1.0 --subsample=0.8 --num_tree=10
```

**Comment by anakinxc** [comment]
@fionser your's :P
