### ISSUE TITLE
[Question]: how are signed integers represented as fixed point binary values in SPU?

### ISSUE THREAD

**Issue by linzzzzzz** [secretflow/spu#789]
### Feature Request Type

Documentation

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

Is SPU always using Two's complement encoding to represent signed integers?

### Describe features you want to add to SPU

--

### Describe features you want to add to SPU

--

**Comment by fionser** [comment]
what other option is possible ?

**Comment by anakinxc** [comment]
Hi @linzzzzzz 

integers are still integers, has nothing to do with fixed-point.

For SPU, all data are just bit stream, encoding is a protocol specific thingy. As of today, all implemented protocols follow two's complement for signed integers (also fixed-point).

Consider hardwares today are all using two's complement, it's highly unlikely that protocol designers will pick things like one's complement or signed magnitude.
