### ISSUE TITLE
[Bug]: when i use spu, it errors as follows "keyboardInterrrupt", but i did not use ctrl+c to end it

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#790]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.9.1b0

### OS Platform and Distribution

linux18.04

### Python Version

3.10.14

### Compiler Version

GCC11.2.1

### Current Behavior?

OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 64: Resource temporarily unavailable                                                   
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 64: Resource temporarily unavailable                                                   
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 64: Resource temporarily unavailable                                                   
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 64: Resource temporarily unavailable                                                   
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 64: Resource temporarily unavailable                                                   
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 64: Resource temporarily unavailable                                                  
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 64: Resource temporarily unavailable                                                  
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 64: Resource temporarily unavailable                                                  
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 64: Resource temporarily unavailable                                                  
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 64: Resource temporarily unavailable                                                  
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max                                                                                    
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max
OpenBLAS blas_thread_init: pthread_create failed for thread 16 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max
OpenBLAS blas_thread_init: pthread_create failed for thread 17 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2061029 current, 2061029 max
Traceback (most recent call last):                                                                                                                      
  File "/z.py", line 2, in <module>                                                                  
    from transformers import AutoTokenizer, FlaxGPT2LMHeadModel, GPT2Config
  File "sfnew/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "sfnew/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "sfnew/lib/python3.10/site-packages/transformers/utils/__init__.py", line 34, in <module>
    from .generic import (
  File "sfnew/lib/python3.10/site-packages/transformers/utils/generic.py", line 29, in <module>
    import numpy as np
  File "sfnew/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "sfnew/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "sfnew/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "sfnew/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by aokaokd** [comment]
能复现吗，问题背景辛苦描述下

**Comment by zhangwaer** [comment]
> 能复现吗，问题背景辛苦描述下
Thanks very much, when i use the following code, it errors above. But i can use it yesterday


import sys
from transformers import AutoTokenizer, FlaxGPT2LMHeadModel, GPT2Config
def text_generation(input_ids, params):
    config = GPT2Config()
    model = FlaxGPT2LMHeadModel(config=config)

    for _ in range(10):
        outputs = model(input_ids=input_ids, params=params)
        next_token_logits = outputs[0][0, -1, :]
        next_token = jnp.argmax(next_token_logits)
        input_ids = jnp.concatenate([input_ids, jnp.array([[next_token]])], axis=1)
    return input_ids
import secretflow as sf

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob', 'carol'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
conf = sf.utils.testing.cluster_def(['alice', 'bob', 'carol'])
conf['runtime_config']['fxp_exp_mode'] = 1
conf['runtime_config']['experimental_disable_mmul_split'] = True
spu = sf.SPU(conf)

def get_model_params():
    pretrained_model = FlaxGPT2LMHeadModel.from_pretrained("gpt2")
    return pretrained_model.params


def get_token_ids():
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    return tokenizer.encode('I enjoy walking with my cute dog', return_tensors='jax')


model_params = alice(get_model_params)()
input_token_ids = bob(get_token_ids)()

device = spu
model_params_, input_token_ids_ = model_params.to(device), input_token_ids.to(device)

output_token_ids = spu(text_generation)(input_token_ids_, model_params_)
outputs_ids = sf.reveal(output_token_ids)
print('-' * 65 + '\nRun on SPU:\n' + '-' * 65)

print(tokenizer.decode(outputs_ids[0], skip_special_tokens=True))
print('-' * 65)

**Comment by zhangwaer** [comment]
when i use the following code, it errors above. But i can use it yesterday


import sys
from transformers import AutoTokenizer, FlaxGPT2LMHeadModel, GPT2Config
def text_generation(input_ids, params):
    config = GPT2Config()
    model = FlaxGPT2LMHeadModel(config=config)

    for _ in range(10):
        outputs = model(input_ids=input_ids, params=params)
        next_token_logits = outputs[0][0, -1, :]
        next_token = jnp.argmax(next_token_logits)
        input_ids = jnp.concatenate([input_ids, jnp.array([[next_token]])], axis=1)
    return input_ids
import secretflow as sf

# In case you have a running secretflow runtime already.
sf.shutdown()

sf.init(['alice', 'bob', 'carol'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
conf = sf.utils.testing.cluster_def(['alice', 'bob', 'carol'])
conf['runtime_config']['fxp_exp_mode'] = 1
conf['runtime_config']['experimental_disable_mmul_split'] = True
spu = sf.SPU(conf)

def get_model_params():
    pretrained_model = FlaxGPT2LMHeadModel.from_pretrained("gpt2")
    return pretrained_model.params


def get_token_ids():
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    return tokenizer.encode('I enjoy walking with my cute dog', return_tensors='jax')


model_params = alice(get_model_params)()
input_token_ids = bob(get_token_ids)()

device = spu
model_params_, input_token_ids_ = model_params.to(device), input_token_ids.to(device)

output_token_ids = spu(text_generation)(input_token_ids_, model_params_)
outputs_ids = sf.reveal(output_token_ids)
print('-' * 65 + '\nRun on SPU:\n' + '-' * 65)

print(tokenizer.decode(outputs_ids[0], skip_special_tokens=True))
print('-' * 65)

**Comment by anakinxc** [comment]
Hi @zhangwaer 

`RLIMIT_NPROC 2061029 current, 2061029 max` seems like you reached nproc limit

**Comment by zhangwaer** [comment]
> Hi @zhangwaer
> 
> `RLIMIT_NPROC 2061029 current, 2061029 max` seems like you reached nproc limit

Thanks very much, the error may caused by my comupter, because it report error as follows when i use " nvidia-smi"：nvidia-smi
-bash: fork: retry: 资源暂时不可用
-bash: fork: retry: 资源暂时不可用
-bash: fork: retry: 资源暂时不可用

**Comment by anakinxc** [comment]
> > Hi @zhangwaer
> > `RLIMIT_NPROC 2061029 current, 2061029 max` seems like you reached nproc limit
> 
> Thanks very much, the error may caused by my comupter, because it report error as follows when i use " nvidia-smi"：nvidia-smi -bash: fork: retry: resource unavailable temporarily -bash: fork: retry: resource unavailable temporarily -bash: fork: retry: resource unavailable temporarily

yup, either a reboot or increase limit should resolve this

**Comment by zhangwaer** [comment]
> > Hi @zhangwaer
> > `RLIMIT_NPROC 2061029 current, 2061029 max` seems like you reached nproc limit
> 
> Thanks very much, the error may caused by my comupter, because it report error as follows when i use " nvidia-smi"：nvidia-smi -bash: fork: retry: resource unavailable temporarily -bash: fork: retry: resource unavailable temporarily -bash: fork: retry: resource unavailable temporarily

thanks very much!!!
