### ISSUE TITLE
[Bug]: when i install secretflow using " pip install -U secretflow", it report errors as follows

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#791]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0

### OS Platform and Distribution

linux18.04

### Python Version

3.11

### Compiler Version

GCC9.4.0

### Current Behavior?

Downloading https://mirrors.aliyun.com/pypi/packages/a2/23/81eac041ea4901cc1c190ebb62f0e0396714649095f61a0a78f1729434cc/secretflow-1.5.0.dev20240304-cp311-cp311-manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 899.9 kB/s eta 0:00:00
  Downloading https://mirrors.aliyun.com/pypi/packages/3c/d6/90e65201b1dbcf357de5ce233117da0cde9ed1612c0a5e05148de84467cd/secretflow-0.7.7b0.tar.gz (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 743.8 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-y0u3_8si/secretflow_13de546bba8d47a7970e2871f150527a/setup.py", line 100, in <module>
          install_requires=read_requirements(),
                           ^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-y0u3_8si/secretflow_13de546bba8d47a7970e2871f150527a/setup.py", line 17, in read_requirements
          with open('./requirements.txt') as file:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by dz12123** [comment]
你好 可以和你讨论一下ditto代码实现的问题吗
