### ISSUE TITLE
[Bug]: hello, could you please tell me some advice on the code location of "Ditto: Quantization-aware Secure Inference of Transformers upon MPC"

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#799]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.5.0

### OS Platform and Distribution

linux18.04

### Python Version

3.11

### Compiler Version

GCC9.4.0

### Current Behavior?

Since iam curious about the encrypted computation, so I read the paper "Ditto: Quantization-aware Secure Inference of Transformers upon MPC". It showed the code is available at spu. Could you please tell me some advice on the code location. Thanks very much !!!

### Standalone code to reproduce the issue

```Python
a
```

**Comment by anakinxc** [comment]
Hi @zhangwaer 

Ditto's source code is available [here](https://github.com/secretflow/spu/tree/ditto_icml24)

**Comment by anakinxc** [comment]
Hi @llCurious 

Feel free to comment on things to notice :D

**Comment by llCurious** [comment]
@zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp)
and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).

You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.

**Comment by zhangwaer** [comment]
> Hi @llCurious
> 
> Feel free to comment on things to notice :D

Thanks very much!!!

**Comment by zhangwaer** [comment]
> @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> 
> You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.

Thanks very much!!!

**Comment by zhangwaer** [comment]
> @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> 
> You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.

thanks very much, the code is so excellent, i hava two questions hoping to get some teaching. The first is that i know the spu support datatype conversion, i wanna know whether the secretflow support it. The second is that i know that "jnp.float16 and jnp.float32 for low-, and high-precision, which correspond to 32-bit ring and 64-bit ring". what about the 128-bit ring. Thanks very much!!!

**Comment by anakinxc** [comment]
> > > > @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> > > > You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.
> > > 
> > > 
> > > thanks very much, the code is so excellent, i hava two questions hoping to get some teaching. The first is that i know the spu support datatype conversion, i wanna know whether the secretflow support it. The second is that i know that "jnp.float16 and jnp.float32 for low-, and high-precision, which correspond to 32-bit ring and 64-bit ring". what about the 128-bit ring. Thanks very much!!!
> > 
> > 
> > Mapping float16 and float32 to different rings is an experimental feature only available in `Ditto`'s work.
> > For secretflow or normal SPU, datatype conversion will not actually increase or decrease ring size.
> 
> Thanks very much!!! so the spu in "https://github.com/secretflow/spu/tree/ditto_icml24" is not the new version that support datatype conversion? And the the data conversion is not support to other models such as resnet and only support for ditto?

SPU supports datatype conversion since day 1. 

In normal SPU, the conversion is not optimal, `Ditto` introduced a more plaintext-like and optimal datatype conversion.

**Comment by zhangwaer** [comment]
> > > > > > @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> > > > > > You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.
> > > > > 
> > > > > 
> > > > > thanks very much, the code is so excellent, i hava two questions hoping to get some teaching. The first is that i know the spu support datatype conversion, i wanna know whether the secretflow support it. The second is that i know that "jnp.float16 and jnp.float32 for low-, and high-precision, which correspond to 32-bit ring and 64-bit ring". what about the 128-bit ring. Thanks very much!!!
> > > > 
> > > > 
> > > > Mapping float16 and float32 to different rings is an experimental feature only available in `Ditto`'s work.
> > > > For secretflow or normal SPU, datatype conversion will not actually increase or decrease ring size.
> > > 
> > > 
> > > Thanks very much!!! so the spu in "https://github.com/secretflow/spu/tree/ditto_icml24" is not the new version that support datatype conversion? And the the data conversion is not support to other models such as resnet and only support for ditto?
> > 
> > 
> > SPU supports datatype conversion since day 1.
> > In normal SPU, the conversion is not optimal, `Ditto` introduced a more plaintext-like and optimal datatype conversion.
> 
> Thanks very much!!! So can i understand it as ditto improve the normal spu greatly, the new spu is optimal datatype conversion. and the new spu is shown in "https://github.com/secretflow/spu/tree/ditto_icml24".

When i use the code "https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.8.0b0/tutorial/gpt2_with_puma" and change the code "self.low_dtype = jnp.float16
self.blocks = [
    FlaxGPT2Block(self.config, name=str(i), dtype=self.low_dtype)
    for i in range(self.config.num_hidden_layers)
]
"
it report errors as follows:
	[Enforce fail at libspu/kernel/hal/type_cast.cc:102] (to_type == DT_F32 || to_type == DT_F64). expect to_type FXP, got F16

**Comment by zhangwaer** [comment]
when i install dittospu as "https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp", 
when i prepared "Install gcc>=11.2, cmake>=3.18, ninja, nasm>=2.15, python==3.8, bazel==6.2.1, golang"  
and go to the step "python setup.py bdist_wheel" 
it report the following answers, hope to get your advice, thanks!!!!!
ERROR: Skipping '//spu:init': error loading package 'spu': at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/defs.bzl:17:6: at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/py_binary.bzl:17:6: Unable to find package for @rules_python_internal//:rules_python_config.bzl: The repository '@rules_python_internal' could not be resolved: Repository '@rules_python_internal' is not defined.
ERROR: error loading package 'spu': at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/defs.bzl:17:6: at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/py_binary.bzl:17:6: Unable to find package for @rules_python_internal//:rules_python_config.bzl: The repository '@rules_python_internal' could not be resolved: Repository '@rules_python_internal' is not defined.
INFO: Elapsed time: 2.117s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: spu/utils ... (2 packages)
    Fetching repository @rules_cc; Restarting.
Traceback (most recent call last):
  File "setup.py", line 242, in <module>
    setuptools.setup(
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 216, in run
    return pip_run(self)
  File "setup.py", line 193, in pip_run
    build(True, True)
  File "setup.py", line 159, in build
    return bazel_invoke(
  File "setup.py", line 120, in bazel_invoke
    result = invoker(['bazel'] + cmdline, *args, **kwargs)
  File "/usr/local/miniconda3/envs/sfz/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '-c', 'opt', '--config=linux-release', '--config=avx', '--', '//spu:init', '//spu/utils:distributed', '//spu:api']' returned non-zero exit status 1.

**Comment by anakinxc** [comment]
> > > > > > > @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> > > > > > > You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.
> > > > > > 
> > > > > > 
> > > > > > thanks very much, the code is so excellent, i hava two questions hoping to get some teaching. The first is that i know the spu support datatype conversion, i wanna know whether the secretflow support it. The second is that i know that "jnp.float16 and jnp.float32 for low-, and high-precision, which correspond to 32-bit ring and 64-bit ring". what about the 128-bit ring. Thanks very much!!!
> > > > > 
> > > > > 
> > > > > Mapping float16 and float32 to different rings is an experimental feature only available in `Ditto`'s work.
> > > > > For secretflow or normal SPU, datatype conversion will not actually increase or decrease ring size.
> > > > 
> > > > 
> > > > Thanks very much!!! so the spu in "https://github.com/secretflow/spu/tree/ditto_icml24" is not the new version that support datatype conversion? And the the data conversion is not support to other models such as resnet and only support for ditto?
> > > 
> > > 
> > > SPU supports datatype conversion since day 1.
> > > In normal SPU, the conversion is not optimal, `Ditto` introduced a more plaintext-like and optimal datatype conversion.
> > 
> > 
> > Thanks very much!!! So can i understand it as ditto improve the normal spu greatly, the new spu is optimal datatype conversion. and the new spu is shown in "https://github.com/secretflow/spu/tree/ditto_icml24".
> 
> When i use the code "https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.8.0b0/tutorial/gpt2_with_puma" and change the code "self.low_dtype = jnp.float16 self.blocks = [ FlaxGPT2Block(self.config, name=str(i), dtype=self.low_dtype) for i in range(self.config.num_hidden_layers) ] " it report errors as follows: [Enforce fail at libspu/kernel/hal/type_cast.cc:102] (to_type == DT_F32 || to_type == DT_F64). expect to_type FXP, got F16

This line of enforce does not exist on ditto branch, please make sure you are using the right version to do experiments.

**Comment by zhangwaer** [comment]
> > > > > > > > @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> > > > > > > > You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.
> > > > > > > 
> > > > > > > 
> > > > > > > thanks very much, the code is so excellent, i hava two questions hoping to get some teaching. The first is that i know the spu support datatype conversion, i wanna know whether the secretflow support it. The second is that i know that "jnp.float16 and jnp.float32 for low-, and high-precision, which correspond to 32-bit ring and 64-bit ring". what about the 128-bit ring. Thanks very much!!!
> > > > > > 
> > > > > > 
> > > > > > Mapping float16 and float32 to different rings is an experimental feature only available in `Ditto`'s work.
> > > > > > For secretflow or normal SPU, datatype conversion will not actually increase or decrease ring size.
> > > > > 
> > > > > 
> > > > > Thanks very much!!! so the spu in "https://github.com/secretflow/spu/tree/ditto_icml24" is not the new version that support datatype conversion? And the the data conversion is not support to other models such as resnet and only support for ditto?
> > > > 
> > > > 
> > > > SPU supports datatype conversion since day 1.
> > > > In normal SPU, the conversion is not optimal, `Ditto` introduced a more plaintext-like and optimal datatype conversion.
> > > 
> > > 
> > > Thanks very much!!! So can i understand it as ditto improve the normal spu greatly, the new spu is optimal datatype conversion. and the new spu is shown in "https://github.com/secretflow/spu/tree/ditto_icml24".
> > 
> > 
> > When i use the code "https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.8.0b0/tutorial/gpt2_with_puma" and change the code "self.low_dtype = jnp.float16 self.blocks = [ FlaxGPT2Block(self.config, name=str(i), dtype=self.low_dtype) for i in range(self.config.num_hidden_layers) ] " it report errors as follows: [Enforce fail at libspu/kernel/hal/type_cast.cc:102] (to_type == DT_F32 || to_type == DT_F64). expect to_type FXP, got F16
> 
> This line of enforce does not exist on ditto branch, please make sure you are using the right version to do experiments.

Thanks very much, but when i install dittospu as "https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp",
when i prepared "Install gcc>=11.2, cmake>=3.18, ninja, nasm>=2.15, python==3.8, bazel==6.2.1, golang"
and go to the step "python setup.py bdist_wheel"
it report the following answers, hope to get your advice, thanks!!!!!
ERROR: Skipping '//spu:init': error loading package 'spu': at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/defs.bzl:17:6: at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/py_binary.bzl:17:6: Unable to find package for @rules_python_internal//:rules_python_config.bzl: The repository '@rules_python_internal' could not be resolved: Repository '@rules_python_internal' is not defined.
ERROR: error loading package 'spu': at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/defs.bzl:17:6: at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/py_binary.bzl:17:6: Unable to find package for @rules_python_internal//:rules_python_config.bzl: The repository '@rules_python_internal' could not be resolved: Repository '@rules_python_internal' is not defined.
INFO: Elapsed time: 2.117s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
currently loading: spu/utils ... (2 packages)
Fetching repository @rules_cc; Restarting.
Traceback (most recent call last):
File "setup.py", line 242, in
setuptools.setup(
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/init.py", line 104, in setup
return distutils.core.setup(**attrs)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
return run_commands(dist)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
dist.run_commands()
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
self.run_command(cmd)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
super().run_command(command)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
self.run_command("build")
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
self.distribution.run_command(command)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
super().run_command(command)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
self.run_command(cmd_name)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
self.distribution.run_command(command)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
super().run_command(command)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "setup.py", line 216, in run
return pip_run(self)
File "setup.py", line 193, in pip_run
build(True, True)
File "setup.py", line 159, in build
return bazel_invoke(
File "setup.py", line 120, in bazel_invoke
result = invoker(['bazel'] + cmdline, *args, **kwargs)
File "/usr/local/miniconda3/envs/sfz/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '-c', 'opt', '--config=linux-release', '--config=avx', '--', '//spu:init', '//spu/utils:distributed', '//spu:api']' returned non-zero exit status 1.

**Comment by anakinxc** [comment]
> > > > > > > > > @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> > > > > > > > > You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > thanks very much, the code is so excellent, i hava two questions hoping to get some teaching. The first is that i know the spu support datatype conversion, i wanna know whether the secretflow support it. The second is that i know that "jnp.float16 and jnp.float32 for low-, and high-precision, which correspond to 32-bit ring and 64-bit ring". what about the 128-bit ring. Thanks very much!!!
> > > > > > > 
> > > > > > > 
> > > > > > > Mapping float16 and float32 to different rings is an experimental feature only available in `Ditto`'s work.
> > > > > > > For secretflow or normal SPU, datatype conversion will not actually increase or decrease ring size.
> > > > > > 
> > > > > > 
> > > > > > Thanks very much!!! so the spu in "https://github.com/secretflow/spu/tree/ditto_icml24" is not the new version that support datatype conversion? And the the data conversion is not support to other models such as resnet and only support for ditto?
> > > > > 
> > > > > 
> > > > > SPU supports datatype conversion since day 1.
> > > > > In normal SPU, the conversion is not optimal, `Ditto` introduced a more plaintext-like and optimal datatype conversion.
> > > > 
> > > > 
> > > > Thanks very much!!! So can i understand it as ditto improve the normal spu greatly, the new spu is optimal datatype conversion. and the new spu is shown in "https://github.com/secretflow/spu/tree/ditto_icml24".
> > > 
> > > 
> > > When i use the code "https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.8.0b0/tutorial/gpt2_with_puma" and change the code "self.low_dtype = jnp.float16 self.blocks = [ FlaxGPT2Block(self.config, name=str(i), dtype=self.low_dtype) for i in range(self.config.num_hidden_layers) ] " it report errors as follows: [Enforce fail at libspu/kernel/hal/type_cast.cc:102] (to_type == DT_F32 || to_type == DT_F64). expect to_type FXP, got F16
> > 
> > 
> > This line of enforce does not exist on ditto branch, please make sure you are using the right version to do experiments.
> 
> Thanks very much, but when i install dittospu as "https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp", when i prepared "Install gcc>=11.2, cmake>=3.18, ninja, nasm>=2.15, python==3.8, bazel==6.2.1, golang" and go to the step "python setup.py bdist_wheel" it report the following answers, hope to get your advice, thanks!!!!! ERROR: Skipping '//spu:init': error loading package 'spu': at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/defs.bzl:17:6: at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/py_binary.bzl:17:6: Unable to find package for @rules_python_internal//:rules_python_config.bzl: The repository '@rules_python_internal' could not be resolved: Repository '@rules_python_internal' is not defined. ERROR: error loading package 'spu': at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/defs.bzl:17:6: at /root/.cache/bazel/_bazel_root/5fb069ff7e8788e0e7d803c89624f2bc/external/rules_python/python/py_binary.bzl:17:6: Unable to find package for @rules_python_internal//:rules_python_config.bzl: The repository '@rules_python_internal' could not be resolved: Repository '@rules_python_internal' is not defined. INFO: Elapsed time: 2.117s INFO: 0 processes. FAILED: Build did NOT complete successfully (0 packages loaded) currently loading: spu/utils ... (2 packages) Fetching repository @rules_cc; Restarting. Traceback (most recent call last): File "setup.py", line 242, in setuptools.setup( File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/init.py", line 104, in setup return distutils.core.setup(**attrs) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup return run_commands(dist) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands dist.run_commands() File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command super().run_command(command) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run self.run_command("build") File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command self.distribution.run_command(command) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command super().run_command(command) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run self.run_command(cmd_name) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command self.distribution.run_command(command) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command super().run_command(command) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "setup.py", line 216, in run return pip_run(self) File "setup.py", line 193, in pip_run build(True, True) File "setup.py", line 159, in build return bazel_invoke( File "setup.py", line 120, in bazel_invoke result = invoker(['bazel'] + cmdline, *args, **kwargs) File "/usr/local/miniconda3/envs/sfz/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '-c', 'opt', '--config=linux-release', '--config=avx', '--', '//spu:init', '//spu/utils:distributed', '//spu:api']' returned non-zero exit status 1.

Hi @zhangwaer 

There were some code syncing issues, just pushed a fix. Please try build again.

**Comment by zhangwaer** [comment]
> > > > > @zhangwaer The related codes are: [experimental_mp](https://github.com/secretflow/spu/tree/ditto_icml24/examples/python/ml/experimental_mp) and [backend impl](https://github.com/secretflow/spu/blob/ditto_icml24/libspu/mpc/aby3/conversion.cc#L629).
> > > > > You can also run the [test script](https://github.com/secretflow/spu/blob/ditto_icml24/spu/tests/jnp_dynamic_ring_test.py) to have a try on dynamic ring computations.
> > > > 
> > > > 
> > > > thanks very much, the code is so excellent, i hava two questions hoping to get some teaching. The first is that i know the spu support datatype conversion, i wanna know whether the secretflow support it. The second is that i know that "jnp.float16 and jnp.float32 for low-, and high-precision, which correspond to 32-bit ring and 64-bit ring". what about the 128-bit ring. Thanks very much!!!
> > > 
> > > 
> > > Mapping float16 and float32 to different rings is an experimental feature only available in `Ditto`'s work.
> > > For secretflow or normal SPU, datatype conversion will not actually increase or decrease ring size.
> > 
> > 
> > Thanks very much!!! so the spu in "https://github.com/secretflow/spu/tree/ditto_icml24" is not the new version that support datatype conversion? And the the data conversion is not support to other models such as resnet and only support for ditto?
> 
> SPU supports datatype conversion since day 1.
> 
> In normal SPU, the conversion is not optimal, `Ditto` introduced a more plaintext-like and optimal datatype conversion.

Thanks very much!!! When i use the following code and change the FlaxGPT2Block to float16" ", it output "I enjoy walking with my cute dog cement Facility Users LankaPHOTOS henceitial periodsGener observations". This is different with the right answer.


 
import sys
from transformers import AutoTokenizer, FlaxGPT2LMHeadModel, GPT2Config
tokenizer = AutoTokenizer.from_pretrained("gpt2")

def text_generation(input_ids, params):
    config = GPT2Config()
    model = FlaxGPT2LMHeadModel(config=config)

    for _ in range(10):
        outputs = model(input_ids=input_ids, params=params)
        next_token_logits = outputs[0][0, -1, :]
        next_token = jnp.argmax(next_token_logits)
        input_ids = jnp.concatenate([input_ids, jnp.array([[next_token]])], axis=1)
    return input_ids
import secretflow as sf
from typing import Any, Callable, Dict, Optional, Tuple, Union
import jax.nn as jnn
import flax.linen as nn
from flax.linen.linear import Array
import jax
import argparse
import spu.utils.distributed as ppd
import spu.intrinsic as intrinsic
import spu.spu_pb2 as spu_pb2
from contextlib import contextmanager
import jax.numpy as jnp

copts = spu_pb2.CompilerOptions()
copts.enable_pretty_print = False
copts.xla_pp_kind = 2
# enable x / broadcast(y) -> x * broadcast(1/y)
copts.enable_optimize_denominator_with_broadcast = True
Array = Any

# In case you have a running secretflow runtime already.
sf.shutdown()
def hack_softmax(
    x: Array,
    axis: Optional[Union[int, Tuple[int, ...]]] = -1,
    where: Optional[Array] = None,
    initial: Optional[Array] = None,
) -> Array:
    x_max = jnp.max(x, axis, where=where, initial=initial, keepdims=True)
    x = x - x_max

    # exp on large negative is clipped to zero
    b = x > -14
    nexp = jnp.exp(x)

    divisor = jnp.sum(nexp, axis, where=where, keepdims=True)

    return b * (nexp / divisor)


@contextmanager
def hack_softmax_context(msg: str, enabled: bool = False):
    if not enabled:
        yield
        return
    # hijack some target functions
    raw_softmax = jnn.softmax
    jnn.softmax = hack_softmax
    yield
    # recover back
    jnn.softmax = raw_softmax
def hack_gelu(
    x: Array,
    axis: Optional[Union[int, Tuple[int, ...]]] = -1,
    where: Optional[Array] = None,
    initial: Optional[Array] = None,
) -> Array:
    b0 = x < -4.0
    b1 = x < -1.95
    b2 = x > 3.0
    b3 = b1 ^ b2 ^ True  # x in [-1.95, 3.0]
    b4 = b0 ^ b1  # x in [-4, -1.95]

    # seg1 = a[3] * x^3 + a[2] * x^2 + a[1] * x + a[0]
    # seg2 = b[6] * x^6 + b[4] * x^4 + b[2] * x^2 + b[1] * x + b[0]
    a_coeffs = jnp.array(
        [
            -0.5054031199708174,
            -0.42226581151983866,
            -0.11807612951181953,
            -0.011034134030615728,
        ]
    )
    b_coeffs = jnp.array(
        [
            0.008526321541038084,
            0.5,
            0.3603292692789629,
            0.0,
            -0.037688200365904236,
            0.0,
            0.0018067462606141187,
        ]
    )
    x2 = jnp.square(x)
    x3 = jnp.multiply(x, x2)
    x4 = jnp.square(x2)
    x6 = jnp.square(x3)

    seg1 = a_coeffs[3] * x3 + a_coeffs[2] * x2 + a_coeffs[1] * x + a_coeffs[0]
    seg2 = (
        b_coeffs[6] * x6
        + b_coeffs[4] * x4
        + b_coeffs[2] * x2
        + b_coeffs[1] * x
        + b_coeffs[0]
    )

    ret = b2 * x + b4 * seg1 + b3 * seg2

    return ret


@contextmanager
def hack_gelu_context(msg: str, enabled: bool = False):
    if not enabled:
        yield
        return
    # hijack some target functions
    raw_gelu = jnn.gelu
    jnn.gelu = hack_gelu
    yield
    # recover back
    jnn.gelu = raw_gelu
sf.init(['alice', 'bob', 'carol'], address='local')

alice, bob = sf.PYU('alice'), sf.PYU('bob')
conf = sf.utils.testing.cluster_def(['alice', 'bob', 'carol'])
conf['runtime_config']['protocol'] = 'ABY3'
conf['runtime_config']['field'] = 'FM64'
conf['runtime_config']['fxp_exp_mode'] = 0
conf['runtime_config']['fxp_exp_iters'] = 5

spu = sf.SPU(conf)


def get_model_params():
    pretrained_model = FlaxGPT2LMHeadModel.from_pretrained("gpt2")
    return pretrained_model.params


def get_token_ids():
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    return tokenizer.encode('I enjoy walking with my cute dog', return_tensors='jax')


model_params = alice(get_model_params)()
input_token_ids = bob(get_token_ids)()

device = spu
model_params_, input_token_ids_ = model_params.to(device), input_token_ids.to(device)

with hack_softmax_context("hijack jax softmax", enabled=True), hack_gelu_context(
    "hack jax gelu", enabled=True
):
    output_token_ids = spu(text_generation, copts=copts)(
        input_token_ids_, model_params_
    )
outputs_ids = sf.reveal(output_token_ids)
print('-' * 65 + '\nRun on SPU:\n' + '-' * 65)
print(tokenizer.decode(outputs_ids[0], skip_special_tokens=True))
print('-' * 65)
