### ISSUE TITLE
[Bug]: ERROR: Build failed. Not running target

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#805]
### Issue Type

Others

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.5.0.dev20240805

### OS Platform and Distribution

ubuntu20.04

### Python Version

3.8.19

### Compiler Version

GCC11.2.0

### Current Behavior?

dear teachers, i successfully run "bazel run -c opt //examples/python/utils:nodectl -- --config `pwd`/examples/python/ml/experimental_mp/3pc_nExp.json up"

but when i us "bazel run -c opt //examples/python/ml/experimental_mp:{gpt2_bench, bert_bench} -- --gelu quad --config examples/python/ml/experimental_mp/3pc_nExp.json"

it report the errors as follows, hope to get your advice, thanks very much!!!:

ERROR: Skipping '//examples/python/ml/experimental_mp:{gpt2_bench,': no such target '//examples/python/ml/experimental_mp:{gpt2_bench,': target '{gpt2_bench,' not declared in package 'examples/python/ml/experimental_mp' defined by /hy-tmp/spu/examples/python/ml/experimental_mp/BUILD.bazel (did you mean 'gpt2_bench'? Tip: use `query "//examples/python/ml/experimental_mp:*"` to see all the targets in that package)
WARNING: Target pattern parsing failed.
ERROR: no such target '//examples/python/ml/experimental_mp:{gpt2_bench,': target '{gpt2_bench,' not declared in package 'examples/python/ml/experimental_mp' defined by /hy-tmp/spu/examples/python/ml/experimental_mp/BUILD.bazel (did you mean 'gpt2_bench'? Tip: use `query "//examples/python/ml/experimental_mp:*"` to see all the targets in that package)
INFO: Elapsed time: 0.503s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by anakinxc** [comment]
`{gpt2_bench, bert_bench}` means pick `gpt2_bench` or `bert_bench`

**Comment by zhangwaer** [comment]
> `{gpt2_bench, bert_bench}` means pick `gpt2_bench` or `bert_bench`

Thanks very much!!!
