### ISSUE TITLE
[Bug]: dear teachers, i wanna to test the time proportion of softmax、gelu in gpt2， could you please give me some advice

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#807]
### Issue Type

Others

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.5.0.dev20240805

### OS Platform and Distribution

ubuntu20.04

### Python Version

3.8.19

### Compiler Version

GCC11.2.0

### Current Behavior?

dear teachers, i wanna to test the time proportion of softmax、gelu in gpt2， could you please give me some advice

### Standalone code to reproduce the issue

```Python
dear teachers, i wanna to test the time proportion of softmax、gelu in gpt2， could you please give me some advice
```

**Comment by anakinxc** [comment]
Hi @zhangwaer 

Please check answers here https://github.com/secretflow/spu/issues/634
