### ISSUE TITLE
[Bug]: dear teachers, how to test the runtime using secretflow in lan and wan environment, could you please give me some advice on setting the lan and wan

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#808]
### Issue Type

Performance

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.5.0

### OS Platform and Distribution

ubuntu20.04

### Python Version

3.8.19

### Compiler Version

GCC11.2.0

### Current Behavior?

dear teachers, how to test the runtime using secretflow in lan and wan environment, could you please give me some advice on setting the lan and wan

### Standalone code to reproduce the issue

```Python
dear teachers, how to test the runtime using secretflow in lan and wan environment, could you please give me some advice on setting the lan and wan
```

**Comment by tpppppub** [comment]
see the *network setting* section in https://github.com/secretflow/spu/blob/ditto_icml24/examples/python/ml/experimental_mp/README.md#2-parameter-configuration

**Comment by fionser** [comment]
单独开个 Q&A 吧；这几个常规问题整天都来。

**Comment by zhangwaer** [comment]
> see the _network setting_ section in https://github.com/secretflow/spu/blob/ditto_icml24/examples/python/ml/experimental_mp/README.md#2-parameter-configuration

Thanks very much!!!

**Comment by zhangwaer** [comment]
> 单独开个 Q&A 吧；这几个常规问题整天都来。

Thanks very much!!!
