### ISSUE TITLE
[Bug]: types do not equal

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#817]
### Issue Type

Usability

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

No

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.3.dev

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.10

### Compiler Version

gcc 13.2

### Current Behavior?

(1) In libspu/mpc/utils/ring_ops.cc,
`#define PFOR_GRAIN_SIZE 4096` seems useless.

(2) In libspu/mpc/common/pv2k.cc, 
```
class EqualVP : public BinaryKernel {
 public:
  static constexpr char kBindName[] = "equal_vp";

  ce::CExpr latency() const override { return ce::Const(0); }
  ce::CExpr comm() const override { return ce::Const(0); }

  NdArrayRef proc(KernelEvalContext* ctx, const NdArrayRef& x,
                  const NdArrayRef& y) const override {
    SPU_ENFORCE_EQ(x.eltype(), y.eltype());

    if (isOwner(ctx, x.eltype())) {
      return ring_equal(x, y).as(x.eltype());
    } else {
      return x;
    }
  }
};
```
The enforce sentence ` SPU_ENFORCE_EQ(x.eltype(), y.eltype());
` is confusing. The name ` EqualVP ` implies that `x` is private and `y` is public. How can their types equal?

### Standalone code to reproduce the issue

```Python
class EqualVP : public BinaryKernel {
 public:
  static constexpr char kBindName[] = "equal_vp";

  ce::CExpr latency() const override { return ce::Const(0); }
  ce::CExpr comm() const override { return ce::Const(0); }

  NdArrayRef proc(KernelEvalContext* ctx, const NdArrayRef& x,
                  const NdArrayRef& y) const override {
    SPU_ENFORCE_EQ(x.eltype(), y.eltype());

    if (isOwner(ctx, x.eltype())) {
      return ring_equal(x, y).as(x.eltype());
    } else {
      return x;
    }
  }
};
```

**Comment by anakinxc** [comment]
Hi @maths644311798 

Nice catch.

For 1, yes, it's no longer used by anything in that file.
For 2, looks like a copy paste mistake, that enforce should be removed.

Feel free to draft a pr :D

Thanks
