### ISSUE TITLE
[Feature]: mark data as private (not secret sharing) in python script

### ISSUE THREAD

**Issue by ccw-li** [secretflow/spu#829]
### Feature Request Type

Others

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

No.

### Describe features you want to add to SPU

Hi, I want to mark data as private in python script, so that during computation only 1 party has the cleartext of this data. The other parties don't have the cleartext nor secret sharing of this data.

**Comment by anakinxc** [comment]
For now, SPU treats private as a special secret.

There are two prerequisites to make private work:
1. enable `experimental_enable_colocated_optimization`.
2. Mark SPU device has the same node_id as corresponding PYU device.

Please use [this config](https://github.com/secretflow/spu/blob/main/examples/python/conf/3pc_colocated.json) as an example.

**Comment by ccw-li** [comment]
Thank you. I can use this feature now.
