### ISSUE TITLE
[Bug]: The least significant bit of compact OT data is not valid

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#831]
### Issue Type

Usability

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

No

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.3.dev

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.10

### Compiler Version

gcc 13.2

### Current Behavior?

(1) In /libspu/mpc/cheetah/ot/basic_ot_proc.cc, `#include "ot_util.h"` and `#include "libspu/mpc/cheetah/ot/ot_util.h"` refer to the same header file. So `#include "ot_util.h"` can be deleted.
(2) The least significant bit of compact OT data is not valid (see yacl/kernel/algorithms/ferret_ote.h from the repository yacl). In /libspu/mpc/cheetah/ot/basic_ot_proc.cc, the function `std::array<NdArrayRef, 3> BasicOTProtocols::AndTriple(FieldType field,
const Shape &shape, size_t nbits_each)` uses `(b[j] & 1)`, which is the least significant bit. So I think this has a problem.

### Standalone code to reproduce the issue

```Python
std::array<NdArrayRef, 3> BasicOTProtocols::AndTriple(FieldType field,
                                                      const Shape &shape,
                                                      size_t nbits_each) {
  int64_t numel = shape.numel();
  SPU_ENFORCE(numel > 0);
  SPU_ENFORCE(nbits_each >= 1 && nbits_each <= SizeOf(field) * 8,
              "invalid packing load {} for one AND", nbits_each);

  // NOTE(juhou): we use uint8_t to store 1-bit ROT
  constexpr size_t ot_msg_width = 1;
  std::vector<uint8_t> a(numel * nbits_each);
  std::vector<uint8_t> b(numel * nbits_each);
  std::vector<uint8_t> v(numel * nbits_each);
  std::vector<uint8_t> u(numel * nbits_each);
  if (0 == Rank()) {
    ferret_receiver_->RecvRMRC(absl::MakeSpan(a), absl::MakeSpan(u),
                               ot_msg_width);
    ferret_sender_->SendRMRC(absl::MakeSpan(v), absl::MakeSpan(b),
                             ot_msg_width);
    ferret_sender_->Flush();
  } else {
    ferret_sender_->SendRMRC(absl::MakeSpan(v), absl::MakeSpan(b),
                             ot_msg_width);
    ferret_sender_->Flush();
    ferret_receiver_->RecvRMRC(absl::MakeSpan(a), absl::MakeSpan(u),
                               ot_msg_width);
  }

  std::vector<uint8_t> c(numel * nbits_each);
  pforeach(0, c.size(), [&](int64_t i) {
    b[i] = b[i] ^ v[i];
    c[i] = (a[i] & b[i]) ^ u[i] ^ v[i];
  });

  // init as zero
  auto AND_a = ring_zeros(field, shape);
  auto AND_b = ring_zeros(field, shape);
  auto AND_c = ring_zeros(field, shape);

  DISPATCH_ALL_FIELDS(field, [&]() {
    auto AND_xa = NdArrayView<ring2k_t>(AND_a);
    auto AND_xb = NdArrayView<ring2k_t>(AND_b);
    auto AND_xc = NdArrayView<ring2k_t>(AND_c);
    pforeach(0, numel, [&](int64_t i) {
      int64_t bgn = i * nbits_each;
      int64_t end = bgn + nbits_each;
      for (int64_t j = bgn; j < end; ++j) {
        AND_xa[i] = (AND_xa[i] << 1) | (a[j] & 1);
        AND_xb[i] = (AND_xb[i] << 1) | (b[j] & 1);
        AND_xc[i] = (AND_xc[i] << 1) | (c[j] & 1);
      }
    });
  });

  return {AND_a, AND_b, AND_c};
}
```

**Comment by fionser** [comment]
Please point out in Yacl where the last bit is invalid .

**Comment by maths644311798** [comment]
[compact ot store type](https://github.com/secretflow/yacl/blob/ddf34696d9fe61431ceccab7fa9854a8d3bf9bcd/yacl/kernel/type/ot_store.h#L117).

>   // Compact mode for COT (Receiver):
  //
  // Blocks Buffer: |-----block[0]----*|---.......--|-----block[n]----*|
  //                                  |                               |
  //                              choice[0]                        choice[n]

Ferret OTe in YACL is designed to used compact OtStoreType. So the valid data should be in the higher 127 bits.

However, in spu/libspu/mpc/cheetah/ot/yacl/ferret.cc, the function `ParaCrHashInplace_128` seems to make the data valid in all bits.

**Comment by fionser** [comment]
Indeed for the base Ferret OTe, sender sends two messages $m_0, m_1$, and the receiver obtains $(m_c, c)$  where $c$ is the last-bit of $m_c$. Also, $m_1 = m_0 + \Delta$ for a fixed Delta.

**Comment by maths644311798** [comment]
Yes. If the receiver knows both the last bits of $m_0$ and $m_1$, then the last bit should be invalid due to security consideration.

**Comment by fionser** [comment]
I still not get your point. In what case the receiver can know both last bits of m0 and m1

**Comment by maths644311798** [comment]
`spu::mpc::cheetah::BasicOTProtocols::AndTriple` uses `yacl::crypto::FerretOtExtRecv_cheetah` to generate OT data. The corresponding messages output by `FerretOtExtSend_cheetah` are $m_0$ and $m_1$ such that the least bit of $m_0$ is $0$, and the least bit of $m_1$ is $1$. 

However, spu uses `ParaCrHashInplace_128` to handle the OT data. Then the least bits seem random, right?

**Comment by fionser** [comment]
Why not to view 'yacl' and 'ParaCrHashInplace' as a whole functionality, which is exactly how a Random OT is defined.

**Comment by maths644311798** [comment]
I understand it now. The problem (1) can be fixed in the next update.
