### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'spu.libspu'; 'spu' is not a package

### ISSUE THREAD

**Issue by guanglaiguo** [secretflow/spu#836]
### Issue Type

Build/Install

### Modules Involved

SPU runtime, SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu.0.9.1b0

### OS Platform and Distribution

Linux Red Hat 4.8.5-44

### Python Version

3.10

### Compiler Version

GCC 4.8.5

### Current Behavior?

A bug happened! 

SPU module has been installed at path: /usr/local/lib/python3.10/site-packages of python interpreter.

### Standalone code to reproduce the issue

```Python
import secretflow as sf
import spu

# In case you have a running SecretFlow runtime already.
sf.shutdown()
sf.init(['carol', 'dave'], address='local')

cheetah_config = sf.utils.testing.cluster_def(
    parties=['carol', 'dave'],
    runtime_config={
        'protocol': spu.spu_pb2.CHEETAH,
        'field': spu.spu_pb2.FM64,
    },
)

spu_device = sf.SPU(cheetah_config)

def get_carol_assets(): 
    return 1000000

def get_dave_assets():
    return 1000002

carol, dave = sf.PYU('carol'), sf.PYU('dave')

carol_assets = carol(get_carol_assets)()
dave_assets = dave(get_dave_assets)()

def get_winner(carol, dave):
    return carol > dave 

winner = spu_device(get_winner)(carol_assets, dave_assets)
sf.reveal(winner)
```

### Relevant log output

```Shell
ModuleNotFoundError: No module named 'spu.libspu'; 'spu' is not a package
```

**Comment by tpppppub** [comment]
renaming your own `spu.py` to something else
