### ISSUE TITLE
目前spu有长时间监听一个rpc端口服务的example吗

### ISSUE THREAD

**Issue by linjunmian** [secretflow/spu#84]
从目前提供的例子（psi）来看，都是临时监听本地端口，然后去连接远程rpc端口。代码里好像都是这么写的。CreateContext的时候会去监听本地端口。
  yacl::link::FactoryBrpc factory;
  link_ctx = factory.CreateContext(lctx_desc, self_rank);
  link_ctx->ConnectToMesh();

实际使用过程中是要考虑并行多任务的例子，所以应该需要一个全局保持监听的服务，目前有如何使用yacl的例子吗？

**Comment by anakinxc** [comment]
就目前的设计上来说，这个全局监听一般是交给上层拉起 SPU 的框架来完成的

yacl 的 link 是用于 spu instances 之前的通信

@warriorpaw @rivertalk 你们补充一下？

**Comment by warriorpaw** [comment]
@linjunmian  如果需要多个PSI 任务并发执行的话，需要修改配置中的端口，保证多个任务的端口不冲突。

目前无法在多个任务之间复用同一组端口进行通讯。

隐语之后会开源调度框架和可视化平台，不需要手动管理端口，并且框架中会提供getaway统一管理跨节点通讯，提供端口复用。

**Comment by linjunmian** [comment]
@warriorpaw  好的谢谢。目前我们只打算集成spu，而且我们得环境也不能开很多端口。我看了一下spu和yacl的代码，主要是yacl的transport_proto 这个传输的协议没有一个可以区分不同任务的值。我打算自己改一下yacl的代码，把里面的receiver变成全局的模式应该就可以了。好像spu不需要改动。

**Comment by Chrisdehe** [comment]
> @linjunmian 如果需要多个PSI 任务并发执行的话，需要修改配置中的端口，保证多个任务的端口不冲突。
> 
> 目前无法在多个任务之间复用同一组端口进行通讯。
> 
> 隐语之后会开源调度框架和可视化平台，不需要手动管理端口，并且框架中会提供getaway统一管理跨节点通讯，提供端口复用。

done
