### ISSUE TITLE
[Bug]: Is the formula correct?

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#846]
### Issue Type

Usability

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

No

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.3.dev

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.10

### Compiler Version

gcc 13.2

### Current Behavior?

In cheetah/arithmetic.cc, the annotation
```
// Math:
//  msb(x0 + x1 mod 2^k) = msb(x0) ^ msb(x1) ^ 1{(x0 + x1) > 2^{k-1} - 1}
```
before the function `NdArrayRef MsbA2B::proc(KernelEvalContext* ctx, const NdArrayRef& x) const ` is confusing. Assume $k = 4$, $x_0 = (1000)_2$ and $x_1 = (0000)_2$ where $x_0$ and $x_1$ are written in binary form. That is, $x_0 = 8$ and $x_1 = 0$ in the decimal form. Then $msb(x_0 + x_1 \mod 2^k) = 1$. But
$$msb(x_0) \oplus  msb(x_1) \oplus 1 \lbrace (x_0 + x_1) > 2^{k-1} - 1 \rbrace = 0.$$
Is the formula correct?

### Standalone code to reproduce the issue

```Python
// Math:
//  msb(x0 + x1 mod 2^k) = msb(x0) ^ msb(x1) ^ 1{(x0 + x1) > 2^{k-1} - 1}
//  The carry bit
//     1{(x0 + x1) > 2^{k - 1} - 1} = 1{x0 > 2^{k - 1} - 1 - x1}
//  is computed using a Millionare protocol.
NdArrayRef MsbA2B::proc(KernelEvalContext* ctx, const NdArrayRef& x) const {
  const int64_t numel = x.numel();
  const auto field = ctx->getState<Z2kState>()->getDefaultField();
  const size_t nbits = nbits_ == 0 ? SizeOf(field) * 8 : nbits_;
  const size_t shft = nbits - 1;
  SPU_ENFORCE(nbits <= 8 * SizeOf(field));

  NdArrayRef out(x.eltype(), x.shape());
  if (numel == 0) {
    return out.as(makeType<BShrTy>(field, 1));
  }

  const int rank = ctx->getState<Communicator>()->getRank();

  return DISPATCH_ALL_FIELDS(field, [&]() {
    using u2k = std::make_unsigned<ring2k_t>::type;
    const u2k mask = (static_cast<u2k>(1) << shft) - 1;
    NdArrayRef adjusted = ring_zeros(field, x.shape());
    auto xinp = NdArrayView<const u2k>(x);
    auto xadj = NdArrayView<u2k>(adjusted);

    if (rank == 0) {
      // x0
      pforeach(0, numel, [&](int64_t i) { xadj[i] = xinp[i] & mask; });
    } else {
      // 2^{k - 1} - 1 - x1
      pforeach(0, numel, [&](int64_t i) { xadj[i] = (mask - xinp[i]) & mask; });
    }

    auto carry_bit = TiledDispatchOTFunc(
                         ctx, adjusted,
                         [&](const NdArrayRef& input,
                             const std::shared_ptr<BasicOTProtocols>& base_ot) {
                           CompareProtocol prot(base_ot);
                           return prot.Compute(input, /*greater*/ true);
                         })
                         .as(x.eltype());
    // [msb(x)]_B <- [1{x0 + x1 > 2^{k- 1} - 1]_B ^ msb(x0)
    NdArrayView<u2k> _carry_bit(carry_bit);
    pforeach(0, numel, [&](int64_t i) { _carry_bit[i] ^= (xinp[i] >> shft); });

    return carry_bit.as(makeType<BShrTy>(field, 1));
  });
}
```

**Comment by maths644311798** [comment]
@fionser, what is wrong in the problem?

**Comment by maths644311798** [comment]
The input `x` should be represented with sign at the most significant bit. The addition in `1{(x0 + x1) > 2^{k-1} - 1}` means adding the lower bits.

**Comment by deadlywing** [comment]
May be `msb(x0 + x1 mod 2^k) = msb(x0) ^ msb(x1) ^ 1{(x0 + x1) > 2^{k-1} - 1}` should be change to `msb(x0 + x1 mod 2^k) = msb(x0) ^ msb(x1) ^ 1{( (x0 & msk) + (x1 & msk) ) > msk}`, where `msk = 2^{k-1} - 1`, which means the msb of x is just influenced by msb of x0 , msb of x1 and the wrap bit.
