### ISSUE TITLE
[Bug]: 执行python setup.py bdist_wheel时报错，无法下载lib25519

### ISSUE THREAD

**Issue by TY-cc** [secretflow/spu#847]
### Issue Type

Build/Install

### Modules Involved

SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu-main

### OS Platform and Distribution

linux ubuntu 22.04

### Python Version

Python 3.10.4

### Compiler Version

GCC 11.2

### Current Behavior?

执行python setup.py bdist_wheel时报上述错误，看着是无法下载lib25519造成的，我尝试了切换网络，但是无法解决该问题。然后我自己下载了lib25519安装包，但是不知道放在哪可以让脚本识别到。希望能指点

### Standalone code to reproduce the issue

```Python
WARNING: Download from https://lib25519.cr.yp.to/lib25519-20240321.tar.gz failed: class javax.net.ssl.SSLException Connection reset
ERROR: An error occurred during the fetch of repository 'lib25519':
   Traceback (most recent call last):
	File "/home/cc/.cache/bazel/_bazel_cc/4b0eecd3fe3f4b0d73b122c19241297c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://lib25519.cr.yp.to/lib25519-20240321.tar.gz] to /home/cc/.cache/bazel/_bazel_cc/4b0eecd3fe3f4b0d73b122c19241297c/external/lib25519/temp3008020813848306487/lib25519-20240321.tar.gz: Connection reset
```

**Comment by maths644311798** [comment]
Note the sentence `file:///repository/lib25519-20240321.tar.gz` in the following code
```
def _lib25519():
    maybe(
        http_archive,
        name = "lib25519",
        strip_prefix = "lib25519-20240321",
        sha256 = "d010baea719153fe3f012789b5a1de27d91fbbcfc65559e7eee5d802bf91eadd",
        type = "tar.gz",
        build_file = "@yacl//bazel:lib25519.BUILD",
        urls = [
		"file:///repository/lib25519-20240321.tar.gz",
            "https://lib25519.cr.yp.to/lib25519-20240321.tar.gz",
        ],
    )
```
in bazel/repositories.bzl. `file:///repository/lib25519-20240321.tar.gz` points to the path `/repository/lib25519-20240321.tar.gz`.

**Comment by TY-cc** [comment]
![image](https://github.com/user-attachments/assets/a3fb9788-e81c-4266-967c-93bc9868087e)
I checked the `def _lib25519()` but didn't found this code in bazel/repositories.bzl. Weather is other file?

**Comment by maths644311798** [comment]
In yacl/bazel/repositories.bzl. You can add sentences like "file:///repository/lib25519-20240321.tar.gz" to urls.

**Comment by TY-cc** [comment]
Thanks. I have solve this problem.
But there are some similar problems, such as boost library, etc. 
![image](https://github.com/user-attachments/assets/4ab8409f-f3d4-45b3-8c14-193b232e3332)
How do we confirm the library belong to who? This is helpful to find `bazel/repositories.bzl`

**Comment by anakinxc** [comment]
> Thanks. I have solve this problem. But there are some similar problems, such as boost library, etc. ![image](https://private-user-images.githubusercontent.com/86347316/365494452-4ab8409f-f3d4-45b3-8c14-193b232e3332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDk0ODIsIm5iZiI6MTcyNTg0OTE4MiwicGF0aCI6Ii84NjM0NzMxNi8zNjU0OTQ0NTItNGFiODQwOWYtZjNkNC00NWIzLThjMTQtMTkzYjIzMmUzMzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTQ2MzRiYjI4YzRlZjA3OGYzMjE0ODY3ODlhNTQ0NTQ5Y2RhZGI1MWY2ZjBkMDEwZGU1NzBjNDY1OGI4ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9yJP0_l1zkyeNM4e3S3IniCwgKlIb1bCaOOLlsarn8) How do we confirm the library belong to who? This is helpful to find `bazel/repositories.bzl`

Just fix network issues, replace download link for everything is not a feasible solution.

**Comment by TY-cc** [comment]
> > Thanks. I have solve this problem. But there are some similar problems, such as boost library, etc. ![image](https://private-user-images.githubusercontent.com/86347316/365494452-4ab8409f-f3d4-45b3-8c14-193b232e3332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDk0ODIsIm5iZiI6MTcyNTg0OTE4MiwicGF0aCI6Ii84NjM0NzMxNi8zNjU0OTQ0NTItNGFiODQwOWYtZjNkNC00NWIzLThjMTQtMTkzYjIzMmUzMzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTQ2MzRiYjI4YzRlZjA3OGYzMjE0ODY3ODlhNTQ0NTQ5Y2RhZGI1MWY2ZjBkMDEwZGU1NzBjNDY1OGI4ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9yJP0_l1zkyeNM4e3S3IniCwgKlIb1bCaOOLlsarn8) How do we confirm the library belong to who? This is helpful to find `bazel/repositories.bzl`
> 
> Just fix network issues, replace download link for everything is not a feasible solution.

yeah，i know.  I want to download this library by manual. But i don't find it belong to which the `bazel/repositories.bzl`

**Comment by anakinxc** [comment]
> > > Thanks. I have solve this problem. But there are some similar problems, such as boost library, etc. ![image](https://private-user-images.githubusercontent.com/86347316/365494452-4ab8409f-f3d4-45b3-8c14-193b232e3332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDk0ODIsIm5iZiI6MTcyNTg0OTE4MiwicGF0aCI6Ii84NjM0NzMxNi8zNjU0OTQ0NTItNGFiODQwOWYtZjNkNC00NWIzLThjMTQtMTkzYjIzMmUzMzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTQ2MzRiYjI4YzRlZjA3OGYzMjE0ODY3ODlhNTQ0NTQ5Y2RhZGI1MWY2ZjBkMDEwZGU1NzBjNDY1OGI4ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R9yJP0_l1zkyeNM4e3S3IniCwgKlIb1bCaOOLlsarn8) How do we confirm the library belong to who? This is helpful to find `bazel/repositories.bzl`
> > 
> > 
> > Just fix network issues, replace download link for everything is not a feasible solution.
> 
> yeah，i know. I want to download this library by manual. But i don't find it belong to which the `bazel/repositories.bzl`

If you are trying to do offline build, use [this](https://bazel.build/reference/command-line-reference#flag--repository_cache) instead.

**Comment by anakinxc** [comment]
> Thankes. I have solved these problems about the fetching library. But there are new problem when comiling library. ![image](https://private-user-images.githubusercontent.com/86347316/365584269-ac0b927c-dab8-429f-8b17-0495ac3a003c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDgwMTMsIm5iZiI6MTcyNTk0NzcxMywicGF0aCI6Ii84NjM0NzMxNi8zNjU1ODQyNjktYWMwYjkyN2MtZGFiOC00MjlmLThiMTctMDQ5NWFjM2EwMDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA1NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwODJmZTcxOTZmZDRlYzAzMGQyNDg5ZDg0Mzc4YjNmZTQyZGMyN2RmOTMxODMwOTFiNzcxYmQ2Y2Y2NjJkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36LP8pnuXbRz_n_y8XpLSXvrHgNrcwzcZfWMrE5DkoM) It seem the libpsi comiling failed. And i can't find similar problem in before issue. How to fix this comiling failed?

Can you provide the build log? Should be under `bazel-out/k8-opt/bin/external/com_github_intel_ipp/ipp_foreign_cc/CMake.log`

**Comment by TY-cc** [comment]
I have solved. This is due to the low version of nasm.

**Comment by TY-cc** [comment]
Thanks for your help. I will close this issue
