### ISSUE TITLE
[Question]: Does SPDZ2k support multiparty computation?

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#848]
### Feature Request Type

Usability

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

(1) In the function
```
std::tuple<AuthBit, AuthBit, AuthBit, AuthBit> GaOT(
    const std::shared_ptr<Communicator>& comm,
    const std::shared_ptr<yacl::crypto::OtSendStore>& send_opts,
    const std::shared_ptr<yacl::crypto::OtRecvStore>& recv_opts, size_t size,
    uint128_t tinyot_key)
```
in spdz2k/ot/tiny_ot.cc, the vectors in the returned value ` {e, chi0, chi1, z} ` will have larger sizes than ` size `. They have sizes ` total_num = expand_factor * size ` now. Maybe we can resize the vectors in `{e, chi0, chi1, z}` and then uses `std::vector:: shrink_to_fit()`.

(2) In the function
```
inline AuthBit AuthBitSender(
    const std::shared_ptr<Communicator>& comm,
    const std::shared_ptr<yacl::crypto::OtSendStore>& base_ot, size_t size,
uint128_t tinyot_key)
```
in spdz2k/ot/tiny_ot.cc, the function ` KosOtExtRecv` requires the number of parties to be 2. SPDZ2k is a multiparty protocol for any positive number of parties, does the implementation in SPU or in ` tiny_ot.cc ` requires the number of parties to be 2?

### Describe features you want to add to SPU

How to use tiny_ot in SPDZ2k to support multiparty?

**Comment by anakinxc** [comment]
Hi @maths644311798 

spdz2k is still an incomplete protocol in SPU.
