### ISSUE TITLE
[Bug]: SPU report error when i execute “SPU Quickstart” code

### ISSUE THREAD

**Issue by TY-cc** [secretflow/spu#849]
### Issue Type

Usability

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.9.3

### OS Platform and Distribution

linux ubuntu 22.04

### Python Version

Python 3.10.4

### Compiler Version

GCC 11.4

### Current Behavior?

I try to run the code of [SPU_quick_start](https://secret-flow.antgroup.com/docs/spu/en/getting_started/quick_start.html).
It can be normal run when i put `**Program with JAX**` and `Program with SPU` codes in a python file.
But it report error when i put `Program with JAX` and `Program with SPU` codes in different py files. 

### Standalone code to reproduce the issue

```Python
Program with JAX code as follow(file name is jax_test.py)
import numpy as np
import jax.numpy as jnp

def make_rand():
    np.random.seed()
    return np.random.randint(100, size=(1, ))

def greater(x, y):
    return jnp.greater(x, y)

x = make_rand()
y = make_rand()
ans = greater(x, y)

print(f"x = {x}")
print(f"y = {y}")
print(f"x>y = {ans}")

Program with SPU code as follow(file name is spu_utils_test.py)
import spu.utils.distributed as ppd
import jax_test

# initialized the distributed environment.
ppd.init(ppd.SAMPLE_NODES_DEF, ppd.SAMPLE_DEVICES_DEF)

print(ppd.current().nodes_def)

print(ppd.current().devices)

print(ppd.device('SPU').details())

# run make_rand on P1, the value is visible for P1 only.
x = ppd.device("P1")(jax_test.make_rand)()

# run make_rand on P2, the value is visible for P2 only.
y = ppd.device("P2")(jax_test.make_rand)()

# run greater on SPU, it automatically fetches x/y from P1/P2 (as ciphertext), and compute the result securely.
ans = ppd.device("SPU")(jax_test.greater)(x, y)
```

### Relevant log output

```Shell
Traceback (most recent call last):
  File "/home/cc/Code/spu_test/spu_utils_test.py", line 33, in <module>
    x = ppd.device("P1")(jax_test.make_rand)()
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 505, in __call__
    self.device.node_client.run(server_fn, *args, **kwargs),
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 247, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 236, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 214, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 214, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 236, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: No module named 'jax_test'"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-09-11T10:20:46.694060398+08:00", grpc_status:2, grpc_message:"Exception iterating responses: No module named \'jax_test\'"}
```

**Comment by anakinxc** [comment]
`No module named 'jax_test'`

Seems you have `import jax_test` somewhere?

**Comment by TY-cc** [comment]
i put Program with JAX and Program with SPU codes in different py files
![image](https://github.com/user-attachments/assets/111731a3-877b-4bbd-9604-c057acc2ceb4)
**jax_test.py**
`import numpy as np
import jax.numpy as jnp

def make_rand():
    np.random.seed()
    return np.random.randint(100, size=(1, ))

def greater(x, y):
    return jnp.greater(x, y)

x = make_rand()
y = make_rand()
ans = greater(x, y)

print(f"x = {x}")
print(f"y = {y}")
print(f"x>y = {ans}")`

**spu_utils_test.py**
`import spu.utils.distributed as ppd
import jax_test

# initialized the distributed environment.
ppd.init(ppd.SAMPLE_NODES_DEF, ppd.SAMPLE_DEVICES_DEF)

print(ppd.current().nodes_def)

print(ppd.current().devices)

print(ppd.device('SPU').details())

# run make_rand on P1, the value is visible for P1 only.
x = ppd.device("P1")(jax_test.make_rand)()

# run make_rand on P2, the value is visible for P2 only.
y = ppd.device("P2")(jax_test.make_rand)()

# run greater on SPU, it automatically fetches x/y from P1/P2 (as ciphertext), and compute the result securely.
ans = ppd.device("SPU")(jax_test.greater)(x, y)`

**Comment by TY-cc** [comment]
i put Program with JAX and Program with SPU codes in different py files
![image](https://github.com/user-attachments/assets/ce5c5d24-896d-4c41-b8a7-03643d61bbde)

> jax_test.py
`import numpy as np
import jax.numpy as jnp

def make_rand():
    np.random.seed()
    return np.random.randint(100, size=(1, ))

def greater(x, y):
    return jnp.greater(x, y)

x = make_rand()
y = make_rand()
ans = greater(x, y)

print(f"x = {x}")
print(f"y = {y}")
print(f"x>y = {ans}")
`

> spu_utils_test.py
`import spu.utils.distributed as ppd
import jax_test

# initialized the distributed environment.
ppd.init(ppd.SAMPLE_NODES_DEF, ppd.SAMPLE_DEVICES_DEF)

print(ppd.current().nodes_def)

print(ppd.current().devices)

print(ppd.device('SPU').details())

# run make_rand on P1, the value is visible for P1 only.
x = ppd.device("P1")(jax_test.make_rand)()

# run make_rand on P2, the value is visible for P2 only.
y = ppd.device("P2")(jax_test.make_rand)()

# run greater on SPU, it automatically fetches x/y from P1/P2 (as ciphertext), and compute the result securely.
ans = ppd.device("SPU")(jax_test.greater)(x, y)`

**Comment by anakinxc** [comment]
Try to add __init__.py at current folder.

**Comment by TY-cc** [comment]
sorry,i can't understand. What should i write in init.py?

**Comment by anakinxc** [comment]
> sorry,i can't understand. What should i write in init.py?

Nothing, just an empty `__init__.py` file

**Comment by TY-cc** [comment]
It didn't help，and reports a same error

**Comment by anakinxc** [comment]
> It didn't help，and reports a same error

And change `import jax_test`
to
`from .jax_test import (whatever you need)`

**Comment by TY-cc** [comment]
i tried the change 
`import jax_test`
to
`from .jax_test import make_rand,greater`
Report error as:
```
Traceback (most recent call last):
  File "/home/cc/Code/spu_test/spu_utils_test.py", line 4, in <module>
    from .jax_test import make_rand,greater
ImportError: attempted relative import with no known parent package
```

i tried the change 
`import jax_test`
to
`from jax_test import make_rand,greater`
Report error as before:
`grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: No module named 'jax_test'"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-09-11T11:08:51.808819609+08:00", grpc_status:2, grpc_message:"Exception iterating responses: No module named \'jax_test\'"}"`

**Comment by anakinxc** [comment]
> i tried the change `import jax_test` to `from .jax_test import make_rand,greater` Report error as:
> 
> ```
> Traceback (most recent call last):
>   File "/home/cc/Code/spu_test/spu_utils_test.py", line 4, in <module>
>     from .jax_test import make_rand,greater
> ImportError: attempted relative import with no known parent package
> ```
> 
> i tried the change `import jax_test` to `from jax_test import make_rand,greater` Report error as before: `grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with: status = StatusCode.UNKNOWN details = "Exception iterating responses: No module named 'jax_test'" debug_error_string = "UNKNOWN:Error received from peer {created_time:"2024-09-11T11:08:51.808819609+08:00", grpc_status:2, grpc_message:"Exception iterating responses: No module named \'jax_test\'"}"`

Interesting, this is a Python import issue, you may need to ask some python experts.

**Comment by TY-cc** [comment]
SPU may have some problems.
In my spu_utils_test.py
i change import jax_test
to
from jax_test import make_rand,greater
```
import spu.utils.distributed as ppd
from jax_test import make_rand,greater

x = make_rand()
y = make_rand()
ans = greater(x, y)

print(f"x = {x}")
print(f"y = {y}")
print(f"x>y = {ans}")
'''

ppd.init(ppd.SAMPLE_NODES_DEF, ppd.SAMPLE_DEVICES_DEF)

print(ppd.current().nodes_def)

print(ppd.current().devices)

print(ppd.device('SPU').details())

x = make_rand()
y = make_rand()
ans = greater(x, y)
print(f"x = {x}")
print(f"y = {y}")
print(f"x>y = {ans}")

x = ppd.device("P1")(make_rand)()
y = ppd.device("P2")(make_rand)()
ans = ppd.device("SPU")(greater)(x, y)
```
It can normal run such as  `x = make_rand()`, it occur error at `x = ppd.device("P1")(make_rand)()`
```
x = [64]
y = [91]
x>y = [False]
Traceback (most recent call last):
  File "/home/cc/Code/spu_test/spu_utils_test.py", line 40, in <module>
    x = ppd.device("P1")(make_rand)()
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 505, in __call__
    self.device.node_client.run(server_fn, *args, **kwargs),
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 247, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 236, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 214, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 214, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 236, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: No module named 'jax_test'"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception iterating responses: No module named \'jax_test\'", grpc_status:2, created_time:"2024-09-11T11:16:31.634342886+08:00"}"
```

**Comment by TY-cc** [comment]
Thank you for your reply. At present, i can only put the code into one python file.

**Comment by anakinxc** [comment]
> SPU may have some problems. In my spu_utils_test.py i change import jax_test to from jax_test import make_rand,greater
> 
> ```
> import spu.utils.distributed as ppd
> from jax_test import make_rand,greater
> 
> x = make_rand()
> y = make_rand()
> ans = greater(x, y)
> 
> print(f"x = {x}")
> print(f"y = {y}")
> print(f"x>y = {ans}")
> '''
> 
> ppd.init(ppd.SAMPLE_NODES_DEF, ppd.SAMPLE_DEVICES_DEF)
> 
> print(ppd.current().nodes_def)
> 
> print(ppd.current().devices)
> 
> print(ppd.device('SPU').details())
> 
> x = make_rand()
> y = make_rand()
> ans = greater(x, y)
> print(f"x = {x}")
> print(f"y = {y}")
> print(f"x>y = {ans}")
> 
> x = ppd.device("P1")(make_rand)()
> y = ppd.device("P2")(make_rand)()
> ans = ppd.device("SPU")(greater)(x, y)
> ```
> 
> It can normal run such as `x = make_rand()`, it occur error at `x = ppd.device("P1")(make_rand)()`
> 
> ```
> x = [64]
> y = [91]
> x>y = [False]
> Traceback (most recent call last):
>   File "/home/cc/Code/spu_test/spu_utils_test.py", line 40, in <module>
>     x = ppd.device("P1")(make_rand)()
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 505, in __call__
>     self.device.node_client.run(server_fn, *args, **kwargs),
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 247, in run
>     return self._call(self._stub.Run, fn, *args, **kwargs)
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 236, in _call
>     rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 214, in rebuild_messages
>     return b''.join([msg for msg in msgs])
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 214, in <listcomp>
>     return b''.join([msg for msg in msgs])
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/spu/utils/distributed_impl.py", line 236, in <genexpr>
>     rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/grpc/_channel.py", line 543, in __next__
>     return self._next()
>   File "/home/cc/anaconda3/envs/sf_code/lib/python3.10/site-packages/grpc/_channel.py", line 969, in _next
>     raise self
> grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
>         status = StatusCode.UNKNOWN
>         details = "Exception iterating responses: No module named 'jax_test'"
>         debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception iterating responses: No module named \'jax_test\'", grpc_status:2, created_time:"2024-09-11T11:16:31.634342886+08:00"}"
> ```

This is not an SPU issue.

Once you pass a function to SPU, pickle needs to be able to serialize and deserialize this function.

You can manually try to pickle a function from `jax_test`, you should observe the same error message.
