### ISSUE TITLE
[Feature]: 指定参与方生成共同随机数

### ISSUE THREAD

**Issue by c-doubley** [secretflow/spu#863]
### Feature Request Type

Build/Install

### Have you searched existing issues?

Yes

### Describe features you want to add to SPU

我想在SPU中构造新的协议，目前遇到一个问题，我希望可以在指定参与方之间生成共同的随机数，例如有4个参与方，我想要Pi,Pi+1,Pi+3之间都生成同一个随机数，目前没有在PrgState类中找到这个实现。我知道fillPrssPair可以给所有参与方生成随机数，但是我希望的是指定的某几个参与方生成共同的随机数。如果没有这样的函数可以给我一些提示吗，需要如何实现这样的函数？
我知道一些直接的实现，但是我希望避免：
1. 由可信第三方分发随机数
2. 由其中一方生成随机数后发送给其他需要共同拥有该随机数的参与方

**Comment by anakinxc** [comment]
Hi @c-doubley 

感觉你可以考虑所有参与方都生成随机数，然后不需要的 party 把这个数直接 discard 掉

**Comment by c-doubley** [comment]
> 你好@c-doubley
> 
> 你感觉可以考虑所有参与方都生成随机数，然后不需要的一方把这个数直接丢弃掉
这个数不可以被不需要的这一方知道，比如有4个参与方，P0 P1 P2都得到随机数r P3不允许知道这个随机数而不仅仅是不需要使用

**Comment by tpppppub** [comment]
你只需要让 P0, P1, P2 三方同步 seed 然后产生随机数即可

**Comment by c-doubley** [comment]
> 你只需要让 P0, P1, P2 三方同步 seed 然后产生随机数即可

好的，这个我大概知道，如果我要在PrgState类中添加这个新的函数有需要注意的地方吗，我可能需要多次调用这个函数，直至每个Pi,Pi+1,Pi+2类似的组合都拥有共同的随机数，每次生成都三方同步seed?

**Comment by tpppppub** [comment]
可以参考现有的实现，在初始化时同步即可

**Comment by c-doubley** [comment]
> 可以参考现有的实现，在初始化时同步即可

好的，谢谢，我尝试一下，可以暂时不关闭问题后续在这里进行提问吗

**Comment by anakinxc** [comment]
> > 可以参考现有的实现，在初始化时同步即可
> 
> 好的，谢谢，我尝试一下，可以暂时不关闭问题后续在这里进行提问吗

可以

**Comment by c-doubley** [comment]
你好，目前我通过同步随机种子实现了这个生成随机数的函数，想问一下spu中有已经实现好的哈希函数吗，在哪里可以查看呢？

**Comment by tpppppub** [comment]
可以用 yacl 里的 hash 算法，https://github.com/secretflow/yacl/blob/main/yacl/crypto/hash/hash_interface.h

**Comment by c-doubley** [comment]
> 可以用 yacl 里的 hash 算法，https://github.com/secretflow/yacl/blob/main/yacl/crypto/hash/hash_interface.h

好的，谢谢

**Comment by c-doubley** [comment]
目前我写了一个随机数生成函数，只要输入参与方的rank就可以生成这些之间共同的的随机数，但是我还遇到了一些问题想要请教一下。比如一个三方的协议，ranks={0,1}, genCommonRandom(ranks)可以生成一个P0和P1之间共同拥有的随机数。现在我需要下面的功能：设定当前参与方的rank为i，我希望每个参与方i能生成（i,i+1）和（i,i+2）之间的随机数。也就是说
P0调用r0=genCommonRandom({0,1})，r1=genCommonRandom({0,2})
P1调用r0=genCommonRandom({1,2})，r1=genCommonRandom({1,0})
P2调用r0=genCommonRandom({2,0})，r1=genCommonRandom({2,1})
也就是说每个人拥有的r0,r1并不一定相同，但是这样做出现了一些通信问题
unknown file: Failure
C++ exception with description "[external/yacl/yacl/link/transport/channel_mem.cc:53] Get data timeout, key=sim.4:P2P-33:1->0" thrown in the test body.
出现这些问题的原因是什么呢？下面附上genCommonRandom的代码
```
// all parties in ranks get a common random number
NdArrayRef PrgState::genCommonRandom(FieldType field, const std::vector<size_t>& ranks, 
                           const Shape& shape, const std::shared_ptr<yacl::link::Context>& lctx,
                           const std::string& commTag) {
  //constexpr char kCommTag[] = "Random:CommonSeed";

  // generate local random seed 
  uint128_t self_seed = yacl::crypto::SecureRandSeed();

  // send self_seed to other parties
  for (size_t rank : ranks) {
      if (rank != lctx->Rank()) { // not send to self
          lctx->SendAsync(rank, yacl::SerializeUint128(self_seed), commTag);
      }
  }

  // receive other parties' seed
  std::vector<uint128_t> seeds;
  for (size_t rank : ranks) {
      if (rank != lctx->Rank()) { // not receive self seed
          uint128_t seed = yacl::DeserializeUint128(lctx->Recv(rank, commTag));
          seeds.push_back(seed);
      }
  }
  seeds.push_back(self_seed); // add self seed

  // generate common seed
  uint128_t commonSeed = std::accumulate(seeds.begin(), seeds.end(), uint128_t(0));

  
  NdArrayRef res(makeType<RingTy>(field), shape); 

  // generate random number by common seed 
  priv_counter_ = yacl::crypto::FillPRand(kAesType, commonSeed, 0, priv_counter_,
                                            absl::MakeSpan(res.data<char>(), res.buf()->size()));

  return res;
}
```

**Comment by tpppppub** [comment]
P0 调 r0=genCommonRandom({0,1})，block 了在从 recv from P1，同理 P1 block 了在 recv from P2，P2 block 了在 recv from P0，这不就死锁了吗？

**Comment by c-doubley** [comment]
> P0 调 r0=genCommonRandom({0,1})，block 了在从 recv from P1，同理 P1 block 了在 recv from P2，P2 block 了在 recv from P0，这不就死锁了吗？
好的，谢谢您，之前没有发现这个问题，似乎无法做到我想要的生成方式，我换了一种方法，不过也遇到了一些问题。
我直接采用了下面的方式来生成随机数
if(rank !=2){
  r01=genCommonRandom({0,1});
 }
yacl::link::Barrier(comm->lctx(), "sync_r01");
if(rank !=1){
  r02=genCommonRandom({0,2});
 }
yacl::link::Barrier(comm->lctx(), "sync_r02");
if(rank !=0){
  r12=genCommonRandom({1,2});
 }
但是我在检查的时候发现P0 P1生成的 r01是相同的，但P1和P2生成的r12不相同，P0和P1生成的r01也不相同，出现这种问题的原因可能是什么呢？我在test中测试过genCommonRandom是可以成功生成指定参与方之间的随机数的。

**Comment by tpppppub** [comment]
检查下 seed 和 counter 是否符合预期

**Comment by c-doubley** [comment]
> 检查下 seed 和 counter 是否符合预期

好的非常感谢，我发现是下面这步的counter没有同步，我这样生成的随机似乎比较难界定属于public给是private，不过为了能实现我想要的功能，我选择了使用public_counter来生成随机数，但更新private_counter，就是逻辑有点怪
```
  priv_counter_ = yacl::crypto::FillPRand(kAesType, commonSeed, 0, pub_counter_,
                                            absl::MakeSpan(res.data<char>(), res.buf()->size()));
```

**Comment by c-doubley** [comment]
pforeach是一个并行处理，现在我有个需求是检查两个哈希值是否相等，但是貌似比较次数有点多
```
      pforeach(0, lhs.numel(), [&](int64_t idx) {
        if(hash_diff_z6[idx] == z8_[idx]){
          std::cout << "p3 z6 == z8" << std::endl;
        }
      });
```
我这里我希望当检查到第一个不相等的值时后续线程都不再需要比较了，需要怎么做呢？因为我发现在测试中有七百多个这样的检查，导致时间上有些慢
