### ISSUE TITLE
Howto Help: examples/python/millionare.py under production scenario

### ISSUE THREAD

**Issue by prayforwind** [secretflow/spu#87]
I have 3 hosts: 192.168.1.180/181/182 with firewalld stopped.

I starts 3 ray cluster on the hosts:
```bash
ray start --head --node-ip-address="192.168.1.180" --port="46379" --include-dashboard=False --disable-usage-stats
ray start --head --node-ip-address="192.168.1.181" --port="46379" --include-dashboard=False --disable-usage-stats
ray start --head --node-ip-address="192.168.1.182" --port="46379" --include-dashboard=False --disable-usage-stats
```

```python
cluster_config = {
    'parties': {
        'alice': {
            'address': '192.168.1.181:40000'
        },
        'bob': {
            'address': '192.168.1.182:40000'
        },
        'charlie': {
            'address': '192.168.1.180:40000'
        }
    }
}
```
[bob.txt](https://github.com/secretflow/spu/files/10762644/bob.txt)
[charlie.txt](https://github.com/secretflow/spu/files/10762645/charlie.txt)
[alice.txt](https://github.com/secretflow/spu/files/10762646/alice.txt)

I rewrite the 'examples/python/millionare.py' and try to 
1. just run python code in charlie.txt - hang: not work
2. run alice.txt and bob.txt python code first, then run charlie.txt - hang: not work

```Bash
(venv) [secretflow@H0 pressure]$ python charlie.py 
2023-02-17 10:09:58,043 INFO worker.py:1352 -- Connecting to existing Ray cluster at address: 192.168.1.180:46379...
2023-02-17 10:09:58,058 INFO worker.py:1538 -- Connected to Ray cluster.
2023-02-17 10:09:59 INFO fed.barriers [charlie] --  RecverProxy was successfully created.
(RecverProxyActor pid=26351) INFO:fed.barriers:Successfully start Grpc service without credentials.
2023-02-17 10:10:00 INFO fed.barriers [charlie] --  SendProxy was successfully created.
z(<class 'secretflow.device.device.spu.SPUObject'> is a device object ref, we can not access it directly.
^CTraceback (most recent call last):
  File "charlie.py", line 72, in <module>
    print(f"z = {sf.reveal(z)}")
  File "/home/secretflow/venv/lib/python3.8/site-packages/secretflow/device/driver.py", line 151, in reveal
    all_object = sfd.get(all_object_refs)
  File "/home/secretflow/venv/lib/python3.8/site-packages/secretflow/distributed/primitive.py", line 47, in get
    return fed.get(object_refs)
  File "/home/secretflow/venv/lib/python3.8/site-packages/fed/api.py", line 361, in get
    values = ray.get(ray_refs)
  File "/home/secretflow/venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/secretflow/venv/lib/python3.8/site-packages/ray/_private/worker.py", line 2303, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/secretflow/venv/lib/python3.8/site-packages/ray/_private/worker.py", line 668, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 1554, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 195, in ray._raylet.check_status
KeyboardInterrupt
```

So, what's wrong with my code, config, operation or scenario?

**Comment by rivertalk** [comment]
Hi @prayforwind, thanks for the detailed description.

Are you running this example:
https://github.com/secretflow/spu/blob/main/examples/python/millionaire.py

If yes, it's does not require ray/secretflow to setup, and the examples will not try to connect to a ray cluster. you can follow instructions inside the source code:
![image](https://user-images.githubusercontent.com/103552262/219537308-dc529f4f-5710-4d16-97ee-565b3665e1ab.png)

FYI: spu has a simple handcrafted distributed system to launch multiple parties, it's small and light-weighted and it's built for play and research purpose.
But for production, it's recommended to use secretflow, and you have to switch to secretflow's examples.

**Comment by prayforwind** [comment]
My motivation is to test SPU under production environment.
My prerequisition is each party owns a ray cluster.
Like this https://www.secretflow.org.cn/docs/secretflow/en/getting_started/deployment.html#production.

I choose a millionaire scenario to make the first step.
So it has nothing to do with SPU's simple handcrafted distributed system.

An overview of my intention as python code can be found in attachment file: charlie.txt.

**Comment by ian-huu** [comment]
> My motivation is to test SPU under production environment. My prerequisition is each party owns a ray cluster. Like this https://www.secretflow.org.cn/docs/secretflow/en/getting_started/deployment.html#production.
> 
> I choose a millionaire scenario to make the first step. So it has nothing to do with SPU's simple handcrafted distributed system.
> 
> An overview of my intention as python code can be found in attachment file: charlie.txt.

In this case, alice/bob/charlie need exactly the same code (except for the setup code). You can refer to this document for more details: https://www.secretflow.org.cn/docs/secretflow/en/developer/design/programming_in_secretflow.html#multi-controller-execution

**Comment by prayforwind** [comment]
I works!
Thanks for the guidance.

Can I say "Multi-controller" deployment is necessary and sufficient conditions for production, and
"Single-controller" is only for play and research purpose?

**Comment by ian-huu** [comment]
> Can I say "Multi-controller" deployment is necessary and sufficient conditions for production, and "Single-controller" is only for play and research purpose?

In short: yes.

Just to explain a bit more: 
We call "Single-controller" the "simulation mode", and it is used for play, research and dev purpose.
"Multi-controller" or "production mode" is aims to be a production-ready deployment mode and is under active development with more features to come in future releases.

**Comment by prayforwind** [comment]
Clearly understood.
