### ISSUE TITLE
[Feature]: ttp_server镜像编译

### ISSUE THREAD

**Issue by reacher1130** [secretflow/spu#876]
### Feature Request Type

Others

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

在执行bfia任务时，需要向ttp beaver服务器建立通信，从secretflow官方镜像源pull的ttp-server镜像无法使用，想自己编译libspu/mpc/semi2k/beaver/beaver_impl/ttp_server:beaver_server_main，并构建dockerfile

### Describe features you want to add to SPU

希望在libspu/mpc/semi2k/beaver/beaver_impl/ttp_server:beaver_server_main文件夹下补充如何构建，或者补充到https://github.com/secretflow/interconnection-impl/tree/main

**Comment by tpppppub** [comment]
[这里](https://github.com/secretflow/interconnection-impl/tree/main?tab=readme-ov-file#%E5%90%AF%E5%8A%A8-beaver-%E6%9C%8D%E5%8A%A1) 第一步就是编译
```bash
bazel build -c opt libspu/mpc/semi2k/beaver/beaver_impl/ttp_server:beaver_server_main
```
