### ISSUE TITLE
[Feature]: 您好，请问关于SPU详细的使用方法，有官方指导文档么？

### ISSUE THREAD

**Issue by TY-cc** [secretflow/spu#878]
### Feature Request Type

Documentation

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

您好，最近一直在摸索spu的使用方法，浏览了官网的资料与例子，对issue中他人的例子进行了试运行，也在B站上学习了你们提供关于spu的指导视频。
现阶段问题是，对于SPU的架构与理论上的流程已经了解了，但是对于其spu的使用方法还比较模糊。
1、例如包括节点开启，spu创建，数据的传入，算子(函数)的自定义，算子(函数)的导入，spu内部的算子执行，密文结果导出，明文结果展示等等，这些功能有比较详细的指导文档么？
2、如果要对spu内部功能进行修改，这方面是否有详细的介绍文档？
期待您的回复，感谢~

### Describe features you want to add to SPU

希望增加spu的使用指导文档

### Describe features you want to add to SPU

如上所述

**Comment by tpppppub** [comment]
目前的主要参考资料：
1. SPU [论文](https://www.usenix.org/conference/atc23/presentation/ma);
2. 官网文档，里面有设计文档，API 文档，示例程序；
3. @fionser 同学提供的二次开发[指南](https://github.com/secretflow/spu/blob/main/docs/SPU_gudience.pdf);
4.  如果要对内部功能进行修改，需要阅读源码，熟悉 C++ 和 python
