### ISSUE TITLE
[Bug]: when i installed spu, it output warning

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#890]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.9.3.dev20241013

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python Version

3.9.20

### Compiler Version

GCC11.2.0

### Current Behavior?

dear teachers, when i installed spu by guideline and run example gpt2, it output warning as follow. will this affect the runtime? could you please give me some advice. Thank you!!
[2024-10-18 10:20:59.247] [warning] [openssl_factory.cc:83] Yacl has been configured to use Yacl's entropy source, but unable to find one. Fallback to use openssl's default entropy srouce

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by zhangwaer** [comment]
> ### Issue Type
> Build/Install
> 
> ### Modules Involved
> Others
> 
> ### Have you reproduced the bug with SPU HEAD?
> Yes
> 
> ### Have you searched existing issues?
> Yes
> 
> ### SPU Version
> 0.9.3.dev20241013
> 
> ### OS Platform and Distribution
> Ubuntu 18.04.6 LTS
> 
> ### Python Version
> 3.9.20
> 
> ### Compiler Version
> GCC11.2.0
> 
> ### Current Behavior?
> dear teachers, when i installed spu by guideline and run example gpt2, it output warning as follow.  
[2024-10-18 10:20:59.247] [warning] [openssl_factory.cc:83] Yacl has been configured to use Yacl's entropy source, but unable to find one. Fallback to use openssl's default entropy srouce

There is a observatiion: i did not install yacl, but i can still run example gpt2 successfully. A question is : In many files, yacl is imported, but the example still run successfully.

So i am curious about when the yacl didnot install successfully, the system will use openssl and overlook yacl? 
And i wanna know how the example run when yacl didnot be installed?

could you please give me some advice. Thanks very much!!

> 
> ### Standalone code to reproduce the issue
> ```python
> print("A bug")
> ```
> 
> ### Relevant log output
> _No response_

**Comment by tpppppub** [comment]
I don't get your point. YACL is a C++ crypto lib used by SPU, not a Python package.

**Comment by zhangwaer** [comment]
> I don't get your point. YACL is a C++ crypto lib used by SPU, not a Python package.

thanks very much!!  since i didnot install lib yacl, spu output "Yacl has been configured to use Yacl's entropy source, but unable to find one. Fallback to use openssl's default entropy srouce". 

Though warning above, the spu example still run successfully. But in spu, many python code include yacl. 
For example, in protocol.h:
#pragma once
#include "yacl/link/link.h"
#include "libspu/core/context.h"

So I'm a little confused, because the spu recognizes that yacl is not installed, so the python program's yacl function has been replaced with an openssl implementation?

Thanks very much!!!
