### ISSUE TITLE
[Bug]: dear teachers, if the spu recognizes that yacl is not installed successfully, the yacl will be replaced with an openssl implementation?

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#891]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.9.3

### OS Platform and Distribution

ubuntu18.04

### Python Version

3.9

### Compiler Version

gcc11.2

### Current Behavior?

 dear teachers, if the spu recognizes that yacl is not installed successfully, the yacl will be replaced with an openssl implementation?

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by tpppppub** [comment]
YACL is a C++ dependency of SPU. There is no such a situation that YACL is so-called "not installed".

**Comment by zhangwaer** [comment]
> YACL is a C++ dependency of SPU. There is no such a situation that YACL is so-called "not installed".

thanks very much!!!!, i understand the dependency. 

Before spu, i didnot install yacl solely, and i only installed spu with guideline, but when "bazel run -c opt //examples/python/utils:nodectl -- --config `pwd`//examples/flax_gpt2/3pc.json up"

 it output "[warning] [openssl_factory.cc:83] Yacl has been configured to use Yacl's entropy source, but unable to find one. Fallback to use openssl's default entropy srouce"

And in /.cache/bazel/as312dsd23sa34/external/yacl/yacl, there are yacl lib installed by bazel of spu.

So simply entropy source cannot be used, and the cryptographic code in yacl will be used when performing secure inference?

thanks very much!!!!!!
/mnt/zhangwang/.cache/bazel/_bazel_zhangwang/a726b1a9c1370b22b7ac8039af1c1cf4/external/yacl/yacl

**Comment by tpppppub** [comment]
The warning message comes from YACL, not SPU. Maybe you should create an issue in YACL's repo.

**Comment by zhangwaer** [comment]
> The warning message comes from YACL, not SPU. Maybe you should create an issue in YACL's repo.

yeah, thanks very much!!!
