### ISSUE TITLE
[Bug]: dear teachers, i hope to know the meaning of WrapValue, thanks very much!!!

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#901]
### Issue Type

Build/Install

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.9.3.dev20241013

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python Version

3.9.20

### Compiler Version

GCC11.2.0

### Current Behavior?

A bug happened!

### Standalone code to reproduce the issue

```Python
dear teachers, i hope to know the meaning of WrapValue, thanks very much!!!
```

**Comment by tpppppub** [comment]
the name is self-explained, it's a wrapper of value

**Comment by zhangwaer** [comment]
> the name is self-explained, it's a wrapper of value

thanks very much！！！！
