### ISSUE TITLE
[Bug]: anolis os编译spu出错

### ISSUE THREAD

**Issue by reacher1130** [secretflow/spu#905]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.2b0

### OS Platform and Distribution

anolis os 23.1

### Python Version

3.10

### Compiler Version

gcc 版本 12.3.0 20230508 (Anolis OS 12.3.0-5) (GCC)

### Current Behavior?

ERROR: /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_fmtlib_fmt/BUILD.bazel:24:20: Foreign Cc - CMake: Building fmtlib failed: (Exit 127): bash failed: error executing command (from target @com_github_fmtlib_fmt//:fmtlib) 
  (cd /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
  /bin/bash -c bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh)
# Configuration: b31970f7587b61226d79424fd913eb94a75d0bc8399da15b61f8ffd8970f060f
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library fmtlib

Environment:______________
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh
EXT_BUILD_ROOT=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib
BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/CMake.log
PWD=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh
BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc
TMPDIR=/tmp
EXT_BUILD_DEPS=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.ext_build_deps
BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a
BUILD_TMPDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir
SHLVL=2
INSTALLDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib
PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib:/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
_=/usr/bin/env
__________________________
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/cmake
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/ninja
+ cmake -DFMT_TEST=OFF -DCMAKE_TOOLCHAIN_FILE=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib -DCMAKE_PREFIX_PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/external/com_github_fmtlib_fmt
bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh: line 112: cmake: command not found
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/CMake.log

ERROR: /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_msgpack_msgpack/BUILD.bazel:24:20: Foreign Cc - CMake: Building msgpack failed: (Exit 127): bash failed: error executing command (from target @com_github_msgpack_msgpack//:msgpack) 
  (cd /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
  /bin/bash -c bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/wrapper_build_script.sh)
# Configuration: b31970f7587b61226d79424fd913eb94a75d0bc8399da15b61f8ffd8970f060f
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library msgpack

Environment:______________
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/build_script.sh
EXT_BUILD_ROOT=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib
BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/CMake.log
PWD=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/wrapper_build_script.sh
BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc
TMPDIR=/tmp
EXT_BUILD_DEPS=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.ext_build_deps
BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a
BUILD_TMPDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.build_tmpdir
SHLVL=2
INSTALLDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack
PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib:/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
_=/usr/bin/env
__________________________
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/cmake
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/ninja
+ cmake -DMSGPACK_CXX17=ON -DMSGPACK_USE_BOOST=OFF -DMSGPACK_BUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DMSGPACK_BUILD_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack -DCMAKE_PREFIX_PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/external/com_github_msgpack_msgpack
bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/build_script.sh: line 112: cmake: command not found
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/CMake.log

ERROR: /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_herumi_mcl/BUILD.bazel:61:20: Foreign Cc - CMake: Building mcl-cmake failed: (Exit 127): bash failed: error executing command (from target @com_github_herumi_mcl//:mcl-cmake) 
  (cd /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/146/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
  /bin/bash -c bazel-out/k8-opt/bin/external/com_github_herumi_mcl/mcl-cmake_foreign_cc/wrapper_build_script.sh)
# Configuration: b31970f7587b61226d79424fd913eb94a75d0bc8399da15b61f8ffd8970f060f
# Execution platform: @local_execution_config_platform//:platform

### Standalone code to reproduce the issue

```Python
ERROR: /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_fmtlib_fmt/BUILD.bazel:24:20: Foreign Cc - CMake: Building fmtlib failed: (Exit 127): bash failed: error executing command (from target @com_github_fmtlib_fmt//:fmtlib) 
  (cd /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
  /bin/bash -c bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh)
# Configuration: b31970f7587b61226d79424fd913eb94a75d0bc8399da15b61f8ffd8970f060f
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library fmtlib

Environment:______________
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh
EXT_BUILD_ROOT=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib
BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/CMake.log
PWD=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh
BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc
TMPDIR=/tmp
EXT_BUILD_DEPS=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.ext_build_deps
BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a
BUILD_TMPDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir
SHLVL=2
INSTALLDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib
PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib:/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
_=/usr/bin/env
__________________________
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/cmake
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/ninja
+ cmake -DFMT_TEST=OFF -DCMAKE_TOOLCHAIN_FILE=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib -DCMAKE_PREFIX_PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/129/execroot/spulib/external/com_github_fmtlib_fmt
bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh: line 112: cmake: command not found
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib_foreign_cc/CMake.log

ERROR: /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_msgpack_msgpack/BUILD.bazel:24:20: Foreign Cc - CMake: Building msgpack failed: (Exit 127): bash failed: error executing command (from target @com_github_msgpack_msgpack//:msgpack) 
  (cd /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
  /bin/bash -c bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/wrapper_build_script.sh)
# Configuration: b31970f7587b61226d79424fd913eb94a75d0bc8399da15b61f8ffd8970f060f
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____

Bazel external C/C++ Rules. Building library msgpack

Environment:______________
BUILD_SCRIPT=bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/build_script.sh
EXT_BUILD_ROOT=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib
BUILD_LOG=bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/CMake.log
PWD=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib
BUILD_WRAPPER_SCRIPT=bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/wrapper_build_script.sh
BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc
TMPDIR=/tmp
EXT_BUILD_DEPS=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.ext_build_deps
BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a
BUILD_TMPDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.build_tmpdir
SHLVL=2
INSTALLDIR=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack
PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib:/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
_=/usr/bin/env
__________________________
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/cmake
Can not copy /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/ninja
+ cmake -DMSGPACK_CXX17=ON -DMSGPACK_USE_BOOST=OFF -DMSGPACK_BUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DMSGPACK_BUILD_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.build_tmpdir/crosstool_bazel.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack -DCMAKE_PREFIX_PATH=/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack.ext_build_deps -DCMAKE_RANLIB= -DCMAKE_MAKE_PROGRAM=ninja -G Ninja /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/145/execroot/spulib/external/com_github_msgpack_msgpack
bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/build_script.sh: line 112: cmake: command not found
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/wrapper_build_script.sh
rules_foreign_cc: Build script location: bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/build_script.sh
rules_foreign_cc: Build log location: bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack_foreign_cc/CMake.log

ERROR: /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_herumi_mcl/BUILD.bazel:61:20: Foreign Cc - CMake: Building mcl-cmake failed: (Exit 127): bash failed: error executing command (from target @com_github_herumi_mcl//:mcl-cmake) 
  (cd /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/146/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
  /bin/bash -c bazel-out/k8-opt/bin/external/com_github_herumi_mcl/mcl-cmake_foreign_cc/wrapper_build_script.sh)
# Configuration: b31970f7587b61226d79424fd913eb94a75d0bc8399da15b61f8ffd8970f060f
# Execution platform: @local_execution_config_platform//:platform
```

**Comment by w-gc** [comment]
能否使用`--sandbox_debug`编译，提供下更为详细的错误日志？

**Comment by tpppppub** [comment]
看起来没装 cmake 请确认下环境是否符合要求 https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux

**Comment by reacher1130** [comment]
cmake 等工具已经安装完成:
(base) [root@anolis ~]# cmake --version
cmake version 3.26.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

还是会出现类似问题：
[output.log](https://github.com/user-attachments/files/17644894/output.log)

ERROR: /root/spu/libspu/dialect/pphlo/IR/BUILD.bazel:150:15: Compiling libspu/dialect/pphlo/IR/type_inference.cc failed: (Exit 1): gcc failed: error executing command (from target //libspu/dialect/pphlo/IR:dialect) 
  (cd /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/sandbox/linux-sandbox/9124/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/usr/local/cmake-3.26.3/bin:/root/.cargo/bin:/root/miniconda3/envs/secretflow/bin:/root/miniconda3/condabin:/root/.local/bin:/root/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++14' -MD -MF bazel-out/k8-opt/bin/libspu/dialect/pphlo/IR/_objs/dialect/type_inference.pic.d '-frandom-seed=bazel-out/k8-opt/bin/libspu/dialect/pphlo/IR/_objs/dialect/type_inference.pic.o' -fPIC -DFMT_HEADER_ONLY -DSPDLOG_FMT_EXTERNAL -DSPDLOG_NO_TLS '-DLLVM_ON_UNIX=1' '-DHAVE_BACKTRACE=1' '-DBACKTRACE_HEADER=<execinfo.h>' '-DLTDL_SHLIB_EXT=".so"' '-DLLVM_PLUGIN_EXT=".so"' '-DLLVM_ENABLE_THREADS=1' '-DHAVE_DEREGISTER_FRAME=1' '-DHAVE_LIBPTHREAD=1' '-DHAVE_PTHREAD_GETNAME_NP=1' '-DHAVE_PTHREAD_H=1' '-DHAVE_PTHREAD_SETNAME_NP=1' '-DHAVE_REGISTER_FRAME=1' '-DHAVE_SETENV_R=1' '-DHAVE_STRERROR_R=1' '-DHAVE_SYSEXITS_H=1' '-DHAVE_UNISTD_H=1' -D_GNU_SOURCE '-DHAVE_LINK_H=1' '-DHAVE_MALLINFO=1' '-DHAVE_SBRK=1' '-DHAVE_STRUCT_STAT_ST_MTIM_TV_NSEC=1' -DHAVE_BUILTIN_THREAD_POINTER '-DLLVM_NATIVE_ARCH="X86"' '-DLLVM_NATIVE_ASMPARSER=LLVMInitializeX86AsmParser' '

**Comment by tpppppub** [comment]
用 gcc 11.2~11.4 版本再试一下
