### ISSUE TITLE
[Bug]: dear teachers, how can i know the input after spu, thanks very much!!!

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#908]
### Issue Type

Build/Install

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.9.3.dev20241013

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python Version

3.9.20

### Compiler Version

GCC11.2.0

### Current Behavior?

For example, how can i know the model_params and input_token_ids, thanks very much!!!

def get_model_params():
    pretrained_model = FlaxGPT2LMHeadModel.from_pretrained("gpt2")
    return pretrained_model.params

def get_token_ids():
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    return tokenizer.encode('I enjoy walking with my cute dog', return_tensors='jax')

model_params = alice(get_model_params)()
input_token_ids = bob(get_token_ids)()

device = spu
model_params_, input_token_ids_ = model_params.to(device), input_token_ids.to(device)

output_token_ids = spu(text_generation)(input_token_ids_, model_params_)

### Standalone code to reproduce the issue

```Python
print("A bug")
```

**Comment by zhangwaer** [comment]
> I think secretflow's [documentation](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/source/secretflow#secretflow.reveal) is clear

thanks very much!!

**Comment by zhangwaer** [comment]
> I think secretflow's [documentation](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/source/secretflow#secretflow.reveal) is clear

reveal can get the plain input, but how i can i get the secret shares. could you please give me some advice, thanks very much!!

**Comment by tpppppub** [comment]
https://www.secretflow.org.cn/en/docs/secretflow/v1.10.0b1/tutorial/spu_basics#SPUObject

**Comment by zhangwaer** [comment]
> https://www.secretflow.org.cn/en/docs/secretflow/v1.10.0b1/tutorial/spu_basics#SPUObject

thanks very much!!
