### ISSUE TITLE
[Feature]: SPU跨协议调用

### ISSUE THREAD

**Issue by c-doubley** [secretflow/spu#911]
### Feature Request Type

Build/Install

### Have you searched existing issues?

Yes

### Describe features you want to add to SPU

我想要设计一个新协议，设计过程可能会需要调用SPU中spdz2k协议和semi2k协议的乘法子协议，请问这样的跨协议调用是可以的吗，需要注意哪些内容？

**Comment by tpppppub** [comment]
如果你的协议是基于这两个协议的，可以在这二者的基础上新增 kernel。如果使用的完全不同的 secret share schema，底层的类型和状态不同，不能直接调用。

**Comment by c-doubley** [comment]
虽然使用的是完全不同的secret share scheme，但是我可以编写底层的类型转换，完成符合其他协议的输入，如果是这样的话能否跨协议调用呢？

**Comment by tpppppub** [comment]
可以尝试一下，你需要完成 type 的转换，还有 semi2k state 和 kernel 的注册，整个过程不如在你的协议中重新实现乘法更方便

**Comment by c-doubley** [comment]
好，重新实现乘法是一个备用的选择，因为我需要使用spdz2k中的验证，如果可以调用的话方便一些，否则还要重新实现mac的逻辑，成本有点高

**Comment by c-doubley** [comment]
您好，我在进行协议设计的时候遇到一个奇怪的问题，需要向您请教一下。
我使用下面的代码在两个参与方之间发送和接收消息：
```
// P1
comm->sendAsync(0, z2, kBindName);


// P0
const auto z3 = comm->recv(1, x3.eltype(), kBindName);
```
我在发送之前已经确认了z2.shape()是20x30
但是我在检查z3.shape()时却发现变成了600
我不太理解出现这种错误可能的原因是什么，x3.eltype(): Ring<FM32>

**Comment by tpppppub** [comment]
recv 的结果是 flatten 的，需要自己 reshape 回去

**Comment by c-doubley** [comment]
另外还想请问在spdz2k协议中是否实现了“中止”功能，中止如何体现以及反馈到上层应用呢？我尝试搜索“abort”没有在项目中搜索到相关内容
