### ISSUE TITLE
[Bug]: Hello!!! Why is gpt2 tested many times on spu, but the send bytes and recv bytes consumed by communication are different? Is it because of the influence of random numbers. could you please give me some advice, thanks!!

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#924]
### Issue Type

Performance

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.8.0b0

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python Version

3.9.20

### Compiler Version

GCC11.2.0

### Current Behavior?

Hello!!! Why is gpt2 tested many times on spu, but the send bytes and recv bytes consumed by communication are different? Is it because of the influence of random numbers. could you please give me some advice, thanks!!

### Standalone code to reproduce the issue

```Python
Hello!!! Why is gpt2 tested many times on spu, but the send bytes and recv bytes consumed by communication are different? Is it because of the influence of random numbers. could you please give me some advice, thanks!!
```

**Comment by deadlywing** [comment]
Some kernels may have dynamic costs, which means different party may have different rounds and comm.
But in average，it's cost should be similar.

**Comment by zhangwaer** [comment]
> It is exactly the stat from one Party, not the total counts.

Thank you very much. Does spu only show one party communication per run? Why is every test different? could you please give me some advice, thanks!!!

**Comment by zhangwaer** [comment]
> > It is exactly the stat from one Party, not the total counts.
> 
> Thank you very much. Does spu only show one party communication per run? Why is every test different? could you please give me some advice, thanks!!!

Some kernels may have dynamic costs, I don't quite understandthis, does this kernels refer to the mpc protocol kernel, such as RandKernel and shiftkernel. 
It is exactly the stat from one Party, not the total counts.

Thank you very much. Does spu only show one party communication per run? Why is every test different? could you please give me some advice, thanks!!!

**Comment by deadlywing** [comment]
1. Yes
2. Refer to mpc kernels, some protocol are asymmetric, so are thier costs. You can see the implementation of kernels in MPC layer (The costs of these kernels will be marked as Dynamic)

**Comment by zhangwaer** [comment]
> 1. Yes
> 2. Refer to mpc kernels, some protocol are asymmetric, so are thier costs. You can see the implementation of kernels in MPC layer (The costs of these kernels will be marked as Dynamic)

Thank you very much. 
Is it due to network reasons, communication retransmission and random number generation. could you please give me some advice, thanks!!!

**Comment by deadlywing** [comment]
Nope, exactly because of the asymmetrical of the algorithm. You should read the codes if you are really interested at this.

**Comment by zhangwaer** [comment]
> Nope, exactly because of the asymmetrical of the algorithm. You should read the codes if you are really interested at this.

Thank you very much!!! I seem to understand that because gpt2 involves a huge amount of computation and many times of computation, the amount of tasks executed by different participants in each computation is different, resulting in the final amount of computation performed is different. 

However, the amount of computation performed in each computation is similar, and the amount of computation performed by each participant is similar. 

For example, when multiplication truncation is performed, such as when bit mapping is performed, the choice of sender and receiver can lead to a difference in traffic. 

The selection of the sender is random, but in the whole calculation process, the selection of the sender is in line with an average distribution, resulting in the final traffic of each calculation is similar. 

could you please give me some advice, thanks!!!

**Comment by deadlywing** [comment]
Yes, u r right.
