### ISSUE TITLE
[Bug]: bazel运行millionaire示例报No module named 'jax'（pip包含jax库）

### ISSUE THREAD

**Issue by dtera** [secretflow/spu#925]
### Issue Type

Usability

### Modules Involved

Documentation/Tutorial/Example

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

main

### OS Platform and Distribution

macosx-arm64

### Python Version

3.10.14

### Compiler Version

clang 16.0.0

### Current Behavior?

`bazel run -c opt //examples/python:millionaire`

![image](https://github.com/user-attachments/assets/2b198aca-73f1-49d8-8ee1-ff5a56708969)

### Standalone code to reproduce the issue

```Python
bazel run -c opt //examples/python:millionaire
```

**Comment by w-gc** [comment]
please install Python dependency packages first: https://github.com/secretflow/spu/blob/main/requirements.txt

**Comment by dtera** [comment]
> please install Python dependency packages first: https://github.com/secretflow/spu/blob/main/requirements.txt
都安装了的，所以我不明白安装了为啥还会报上面的错误，请看下面（我上面的图也标了已经安装了）
![image](https://github.com/user-attachments/assets/0912f7ab-a4fd-4309-8885-7d40404a73b6)

**Comment by tpppppub** [comment]
bazel clean 然后再重跑下

**Comment by dtera** [comment]
> bazel clean 然后再重跑下

clean后运行会报另一个error，如下图

![image](https://github.com/user-attachments/assets/aaa6eade-42cb-4e30-a61a-5b0e3e35c6f6)

**Comment by tpppppub** [comment]
请确保你的 nodes 已经启动在运行

**Comment by dtera** [comment]
> 请确保你的 nodes 已经启动在运行
按照readme运行的，具体要启动什么呢，ray？

**Comment by dtera** [comment]
> 请确保你的 nodes 已经启动在运行

ok了，感谢~
