### ISSUE TITLE
[Bug]: hello!! hal::trunc, mpc::truncpr, aby3::truncpr I have learned the relationship between the three.  could you please give me some advice, thanks!!

### ISSUE THREAD

**Issue by zhangwaer** [secretflow/spu#927]
### Issue Type

Build/Install

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.8.0b0

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python Version

3.9.20

### Compiler Version

GCC11.2.0

### Current Behavior?

hello!! hal::trunc, mpc::truncpr, aby3::truncpr I have learned the relationship between the three. 

If I want to modify the implementation of aby3::truncpr, do I only need to modify the trunc function of the arithmetic file of aby3 protocol? Do I need to modify mpc::truncpr ?  And i am curious about the implement of hal::trunc

Is the truc of ab_api.cc corresponding to mpc::truncpr or hal::trunc?
Given that the truc for ab_api.cc looks like this, what is the connection between this implementation being affected by the mpc::truncpr modification? Is trunc_a the mpc layer and TILED_DISPATCH the hal layer. could you please give me some advice, thanks!!      

Value trunc_a(SPUContext* ctx, const Value& x, size_t nbits, SignType sign) {
TILED_DISPATCH(ctx, x, nbits, sign);
}

### Standalone code to reproduce the issue

```Python
hello!! 
```

**Comment by zhangwaer** [comment]
Another question is, why do pphlo and hal layers also have data interaction, and why do they also have send and recv. could you please give me some advice, thanks!!

**Comment by w-gc** [comment]
PPHLO ops call HAL ops, and then HAL ops call MPC ops, more details in the picture below:
<img width="1119" alt="image" src="https://github.com/user-attachments/assets/c73c3c7a-617a-4c88-b55a-b40038c8bc3a">

If you want to replace the aby3 trunc op with your special trunc op, you should register it into kernel container and remove the default trunc op in line 71-75:
<img width="722" alt="image" src="https://github.com/user-attachments/assets/a74f9690-71c9-4015-81ab-4e49f6f5b3fe">

**Comment by zhangwaer** [comment]
> PPHLO ops call HAL ops, and then HAL ops call MPC ops, more details in the picture below: <img alt="image" width="1119" 

thanks very much!!

**Comment by zhangwaer** [comment]
> PPHLO ops call HAL ops, and then HAL ops call MPC ops, more details in the picture below: <img alt="image" width="1119" 


i am curious about why do pphlo and hal layers also have data interaction, and why do they also have send and recv. could you please give me some advice, thanks!!
