### ISSUE TITLE
[Bug]: Could you update the configuration process for LLAMA-7B? EasyLM seems to be updated and the old configuration is not correct anymore.

### ISSUE THREAD

**Issue by Tianshi-Xu** [secretflow/spu#929]
### Issue Type

Build/Install

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

latest

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.10

### Compiler Version

GCC 11.3

### Current Behavior?

The EasyLM has been updated and the steps in README.md in examples/python/ml/flax_llama7b are incorrect.

### Standalone code to reproduce the issue

```Python
Lots of errors
```

**Comment by Tianshi-Xu** [comment]
Main errors come from 
```
python convert_hf_to_easylm.py  \
   --hf_model     /home/code/models/Llama-7b    \
   --output_file flax-llama7b-EasyLM.msgpack  \
   --streaming false
```

**Comment by tpppppub** [comment]
It seems to be a duplicate of #704

**Comment by Tianshi-Xu** [comment]
> It seems to be a duplicate of #704

Yes, it can work with some tedious modifications, but I recommend updating the readme or giving some hits to prevent future users from these errors.  After all, LLAMA is an important model in PPDL.
Thanks a lot!
