### ISSUE TITLE
spu运行打印的通信信息

### ISSUE THREAD

**Issue by zhou-pz** [secretflow/spu#949]
### Issue Type

Others

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu

### OS Platform and Distribution

Ubuntu

### Python Version

3.9

### Current Behavior?

`Link details: total send bytes 29106000, recv bytes 21344400, send actions 1100, recv actions 900`
请问打印信息中的通信信息是指每隔参与方的通信量和轮数还是所有参与方总通信量和轮数？
我的运行命令是bazel run -c opt  --jobs 2 //sml/emulations:my_program

### Standalone code to reproduce the issue

```Python
no
```

**Comment by tpppppub** [comment]
单方的

**Comment by zhou-pz** [comment]
好的，感谢~~

**Comment by yNotAVAILABLEa** [comment]
spu可以得到模型训练时前向传播和反向传播的通信开销吗

**Comment by yNotAVAILABLEa** [comment]
请问spu可以得到模型训练时前向传播和反向传播的通信开销吗

**Comment by zhou-pz** [comment]
emulator.run会打印单独的信息，前向传播和反向传播分别用两次emulator.run跑应该可以吧

> 请问spu可以得到模型训练时前向传播和反向传播的通信开销吗
